### PR TITLE
Add containers_events_dropped_total metric

### PR DESCRIPTION
**Pull request by surik**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

To expose the amount of dropped events for PLEG.
The event may be dropped when the feature is enabled and there are no subscribers to consume the events from the full event channel(buffer is 1000).

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
Add containers_events_dropped_total metric
```

### CODE REVIEW

**Comment by surik** [comment]
ping @mrunalp @klihub @sohankunkerkar

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Pull request merged**
