### PR TITLE
Update Kubernetes to v1.18.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update vendored Kubernetes to v1.18.0.

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
The latest beta of k8s drops support for go 1.12, opened up a discussion here: https://github.com/kubernetes/kubernetes/pull/88465#issuecomment-597515848

**Comment by saschagrunert** [comment]
I have to rebuild the nix image (still using go 1.12) which takes a couple of hours on my machine. :)

**Comment by saschagrunert** [comment]
Had to drop the musl libc version of the static build, since go 1.14 does not build right now. This makes things easier I guess since we still have the glibc variant which is partly cached by upstream nix.

**Comment by saschagrunert** [comment]
@chavafg I think we have to update golang to 1.13 in kata to let the tests pass. Do you have something like this already on your agenda? Otherwise I could take care of it.

**Comment by chavafg** [comment]
hi @saschagrunert, 
Please open a PR to update it on:
https://github.com/kata-containers/runtime/blob/master/versions.yaml#L303

thanks.

**Comment by chavafg** [comment]
@saschagrunert thanks for your PR in kata, it is already merged and now kata should be fine with your change. 😃

**Comment by saschagrunert** [comment]
> @saschagrunert thanks for your PR in kata, it is already merged and now kata should be fine with your change.

Awesome, thank you!

**Comment by saschagrunert** [comment]
Needs https://github.com/cri-o/cri-o/pull/3463

**Comment by saschagrunert** [comment]
Ready for review. PTAL @haircommander

**Pull request merged**
