### PR TITLE
Do not rebuild binaries when installing

### PR DESCRIPTION
**Pull request by saschagrunert**
Closes to #2978

### CODE REVIEW

**Comment by mythi** [comment]
@saschagrunert I think we should understand why make thinks binaries are not built. `make --trace install` gives good info

**Comment by saschagrunert** [comment]
> @saschagrunert I think we should understand why make thinks binaries are not built. `make --trace install` gives good info

May I ask you what you mean with "it thinks that binaries are not built"? I have the feeling that I miss some point here.

**Comment by mythi** [comment]
> May I ask you what you mean with "it thinks that binaries are not built"? 

`binaries` target is already completed during `make` but something makes `make install` think that it needs updating.

**Comment by rhatdan** [comment]
I think the issue is, if you do a
make
followed by a 
make install

The make install builds the images a second time. IE it is not smart enough to know that the executables are up2date.

**Comment by umohnani8** [comment]
LGTM

**Comment by mythi** [comment]
FWIW, make always rebuilds: subsequent `make` commands trigger a new build so c6ab92c is not the right fix.

**Comment by saschagrunert** [comment]
/hold

I’ll rework this after the kubecon.

**Comment by yihuaf** [comment]
Not sure if it will help, but on ToT, if you run `make bin/crio` for example, the binary will always get rebuild. It's if command delete `bin/crio` binary right before the build command. Output for `make -d bin/crio`:
```
Updating goal targets....
Considering target file 'bin/crio'.
 File 'bin/crio' does not exist.
  Considering target file 'git-vars'.
   File 'git-vars' does not exist.
   Finished prerequisites of target file 'git-vars'.
  Must remake target 'git-vars'.
  Successfully remade target file 'git-vars'.
  Considering target file '.gopathok'.
   Finished prerequisites of target file '.gopathok'.
  No need to remake target '.gopathok'; using VPATH name '/home/yihuaf/private/go/.gopathok'.
 Finished prerequisites of target file 'bin/crio'.
Must remake target 'bin/crio'.
GO111MODULE=on go build -mod=vendor -ldflags '-s -w -X main.gitCommit="7e44ac76cc16a64edba4830527beef0865359f76" -X main.buildInfo=1575924051' -tags "containers_image_ostree_stub  exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove  seccomp selinux" -o bin/crio github.com/cri-o/cri-o/cmd/crio
```

**Comment by saschagrunert** [comment]
Closing in favor of https://github.com/cri-o/cri-o/pull/3027

**Pull request closed without merging**
