### PR TITLE
Add Nestybox to the CRI-O adopters list.

### PR DESCRIPTION
**Pull request by ctalledo**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Adds Nestybox to the list of CRI-O adopters list.

#### Which issue(s) this PR fixes:

None.

#### Does this PR introduce a user-facing change?

No.

### Release note:

```release-note
None
```

Signed-off-by: Cesar Talledo <ctalledo@nestybox.com>

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve

LGTM, thanks @ctalledo ! 

@cri-o/cri-o-maintainers @TomSweeneyRedHat PTAL

**Comment by haircommander** [comment]
/ok-to-test
/approve

LGTM, thanks @ctalledo ! 

@cri-o/cri-o-maintainers @TomSweeneyRedHat PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
Thanks @ctalledo !

**Pull request merged**
