### PR TITLE
Move metrics into singleton helpers

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

We now provide an `Instance()` singleton for metrics as well as
modification helper functions to be able to enable/disable them in
further patches.

#### Which issue(s) this PR fixes:

Part of https://github.com/cri-o/cri-o/issues/4982

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve

LGTM

**Comment by saschagrunert** [comment]
@haircommander PTAL

**Pull request merged**
