### PR TITLE
Bump kube and cri-tools to 1.26

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind dependency-change
#### What this PR does / why we need it:
somehow this got missed in the 1.26 cut process
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — CHANGES_REQUESTED** [review]
Looks like we have to change the GitHub actions `critest` and `critest-conmonrs` tests as well, since they do seem to fail / do nothing:

- https://github.com/cri-o/cri-o/actions/runs/3849540739/jobs/6600434675
- https://github.com/cri-o/cri-o/actions/runs/3849540739/jobs/6600434183

```
++ bats --jobs 1 --tap critest.bats
1..1
critest version: 1.26.0
Running Suite: CRI validation - /home/runner/work/cri-o/cri-o/test
==================================================================
Random Seed: 1672[9](https://github.com/cri-o/cri-o/actions/runs/3849540739/jobs/6600434675#step:8:10)45053

Will run 0 of 88 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Ran 0 of 88 Specs in 0.001 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 88 Skipped
PASS
ok 1 run the critest suite
```

**Comment by haircommander** [comment]
I find it weird critest-conmonrs and critest are behaving differently...

**Comment by haircommander** [comment]
I didn't get a chance to debug this today. Could you possibly take a look tomorrow @saschagrunert

**Comment by saschagrunert** [comment]
> I didn't get a chance to debug this today. Could you possibly take a look tomorrow @saschagrunert

Done, the empty vars introduced a behavioral CLI change, but I guess we don't need them in any case because we fixed all the tests in conmon-rs. 

- https://github.com/cri-o/cri-o/actions/runs/3881639261/jobs/6620867774
- https://github.com/cri-o/cri-o/actions/runs/3881639261/jobs/6620868062

**Pull request merged**
