### PR TITLE
Use CRIU version check go-criu; not from Podman

### PR DESCRIPTION
**Pull request by adrianreber**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Use CRIU version check go-criu; not from Podman

See #7866

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
@adrianreber, we might need a quick rebase.

**Comment by adrianreber** [comment]
> @adrianreber, we might need a quick rebase.

Rebased. Now even more code is removed.

**Pull request merged**
