### PR TITLE
[1.16] Make config package public

### PR DESCRIPTION
**Pull request by haircommander**
As there were libraries that relied on it, as well as it's a useful struct for public use.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
happy tests @saschagrunert @umohnani8 @mrunalp @rhatdan PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by haircommander** [comment]
@umohnani8 @rhatdan needs approve

**Comment by runcom** [comment]
tested in MCO, works good

/approve

**Pull request merged**
