### PR TITLE
[1.20] test: pin and bump cri tools version

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind ci
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
/hold

It may be required to switch to v1.21.0 because the test images in v1.20.0 are not available any more.

**Comment by mrunalp** [comment]
Fixed by #5271

**Pull request closed without merging**
