### PR TITLE
Close the done channel in runtimeOCI#ReopenContainerLog

### PR DESCRIPTION
**Pull request by tedyu**
####  What type of PR is this?

/kind bug

#### What this PR does / why we need it:
In runtimeOCI#ReopenContainerLog, if the goroutine receives watcher error, we would execute the following (around line 1059):
```
	case err := <-errorCh:
```
where the done channel is not closed.

This PR moves the closing of done channel to the main goroutine so that done channel is always closed.

#### Which issue(s) this PR fixes:

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by tedyu** [comment]
@TomSweeneyRedHat 
Can you give /lgtm ?

Thanks

**Pull request merged**
