### PR TITLE
Bump Kubernetes to v1.27.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Update Kubernetes to the latest minor version.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
/test ci-fedora-critest

@cri-o/cri-o-maintainers PTAL

**Comment by haircommander** [comment]
```
  [FAIL] [sig-cli] Kubectl client Simple pod [It] should support inline execution and attach
```
is back in conmon-rs :\ 

since it's releasewee, naturally fedora-critest decides to start failing too...

/retest

**Pull request merged**
