### PR TITLE
Build failure following install.md instructions with latest changes

### LINKED ISSUE #5192: Build failure following install.md instructions with latest changes
**Description**

Having a build-from-source error when following the install.md instructions.

**Steps to reproduce the issue:**
1. Follow instructions at https://github.com/cri-o/cri-o/blob/master/install.md#get-source-code
2. Follow instructions directly below that:  https://github.com/cri-o/cri-o/blob/master/install.md#build

**Describe the results you received:**
Error message:
make
go build -trimpath  -ldflags '-s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate='2021-08-11T19:22:20Z' -X github.com/cri-o/cri-o/internal/version.gitCommit=78f06f200a544ec3be594d58a37d247f822c1946 -X github.com/cri-o/cri-o/internal/version.gitTreeState=clean ' -tags "containers_image_ostree_stub  exclude_graphdriver_btrfs btrfs_noversion    seccomp selinux" -o bin/crio github.com/cri-o/cri-o/cmd/crio
vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/metrics.go:21:2: cannot find package "." in:
        /home/drewhome/cri-o/vendor/io/fs
make: *** [Makefile:171: bin/crio] Error 1

**Describe the results you expected:**
Clean build.

**Additional information you deem important (e.g. issue happens only occasionally):**
I tested this with source code from the latest stable release and this problem did not occur.  Precisely, code pulled with
```
wget https://github.com/cri-o/cri-o/archive/refs/tags/v1.21.2.tar.gz
tar xzf v1.21.2.tar.gz
```
Then, I got code with
```
git checkout a07f02ffd6bc39cb8ad35500f83f864b7189756d
```
Which is the second most recent commit to master, because I remember building successfully earlier this week.  Building this code also worked for me.
The most recent commit to master likely contains the culpable change.

**Output of `crio --version`:**
N/A, this issue doesn't have to do with crio at runtime

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 33

### PR DESCRIPTION
**Pull request by ajwock**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Documentation update informs users and contributors that go 1.16 or later is required to build from source.

#### Which issue(s) this PR fixes:

Fixes #5192 

#### Does this PR introduce a user-facing change?

Yes
```release-note
Documentation update informs users and contributors that go 1.16 or later is required to build from source.
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve

thanks @ajwock LGTM

**Comment by fidencio** [comment]
LGTM, thanks @ajwock!

**Comment by ajwock** [comment]
I fetched the upstream to my fork's master which added a merge commit to this PR.  I guess I shouldn't have been using master as my branch for a PR in the fork.  I've undone that change now so the state of this PR should be the same as before.

**Comment by ajwock** [comment]
Would this pr be ready to merge?

**Comment by ajwock** [comment]
Edit- actually, it looks like the doc has already been updated and we need go 1.17.   Closing this PR.

**Pull request closed without merging**
