### PR TITLE
Use the official nix package for building static binaries

### PR DESCRIPTION
**Pull request by saschagrunert**
Since we now have [an official nix package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/cri-o/default.nix), we can remove our internal
derivation and override needed attributes directly from the
defaults.nix. The build image has been updated and is now used in a
versioned way in travis and CircleCI to ensure backwards compatibility.

It would be awesome if we can get this change in before releasing v1.15.0 :innocent:

### CODE REVIEW

**Comment by haircommander** [comment]
@saschagrunert i've been using the release-1.15 tag to mark things I'd like in before the release. Feel free to also use it :)

**Comment by haircommander** [comment]
LGTM

**Comment by saschagrunert** [comment]
> @saschagrunert i've been using the release-1.15 tag to mark things I'd like in before the release. Feel free to also use it :)

I have not enough power to add the tag :(

**Comment by haircommander** [comment]
Odd... well ping me if you want anything else in :)

**Comment by mrunalp** [comment]
@saschagrunert Try adding labels again. I have changed your permissions. Let me know if it doesn't work :)

**Comment by saschagrunert** [comment]
> @saschagrunert Try adding labels again. I have changed your permissions. Let me know if it doesn't work :)

Thank you very much, it works! 🙏

**Pull request merged**
