### PR TITLE
ci: update system-packages.yml to install gpgme-devel on fedora

### PR DESCRIPTION
**Pull request by haircommander**
as well as reorder for readability

Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

#### What type of PR is this?

/kind ci
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
@littlejawa @fidencio what's the state of the kata tests?

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the tests are hip

**Comment by haircommander** [comment]
This is needed for https://github.com/openshift/release/pull/34784 to pass, and all of the expected tests pass, so I am merging

**Comment by littlejawa** [comment]
> @littlejawa @fidencio what's the state of the kata tests?

Sorry, I'm late on this.
I don't understand what happened - apparently the CI job was not able to checkout this pull request:

```
18:44:06 Cloning into '/tmp/jenkins/workspace/kata-containers-2-crio-PR/go/src/github.com/cri-o/cri-o'...
18:44:16 fatal: couldn't find remote ref pull/6445/head
```

Subsequent jobs have run without issue, not sure what happened with this one.

**Pull request merged**
