### PR TITLE
config: merge runtime and workload allowed annotations

### PR DESCRIPTION
**Pull request by haircommander**
to allow for a more smooth transition between workloads and runtime class level allowed annotations

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
Allow for both runtime class and workload level allowed annotations. Now, if a container or pod has both specified, the list will be merged.
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests.

**Comment by wgahnagl** [comment]
Do you think the cgorupv2 test failure is telated to the PR?

**Pull request merged**
