### PR TITLE
[1.19] server: cleanup container in runtime after failed creation

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
partial cherry-pick of https://github.com/cri-o/cri-o/pull/4198

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where a container creation failure caused that container to leak in the runtime
```

### CODE REVIEW

**Comment by haircommander** [comment]
weird failure on integration_fedora:
```

not ok 11 config dir should fail with invalid option
# (in test file ./config.bats, line 38)
#   `RES=$(cat "$CRIO_LOG")' failed
# cat: /tmp/tmp.MPXCSj4ECK/crio.log: No such file or directory
```

[ref](https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/4201/test_pull_request_crio_integration_rhel/21009/artifacts/testout.txt)

**Review by mrunalp — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by sferich888** [comment]
Relates to https://bugzilla.redhat.com/show_bug.cgi?id=1882501 for tracking purposes.

**Pull request merged**
