### PR TITLE
Update compatibility matrix to mention v1.20

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
This also removes the mentioning of v1.17 as well as sorting the table
in the way that the most recent entry is on top.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by fidencio** [comment]
LGTM, thanks @saschagrunert!
/retest

**Pull request merged**
