### PR TITLE
Fix install.md links

### LINKED ISSUE #5357: Wrong link in Install.md
**Description**

Install.md has two wrong link.

**Steps to reproduce the issue:**
1. Click to "openSUSE's OBS" link

2. Click to "open an issue" link.

**Describe the results you received:**

1. Go to "https://github.com/cri-o/cri-o/blob/main/build.opensuse.org"
Error 404

2. Go to https://github.com/cri-o/cri-o/blob/main/github.com/cri-o/cri-o/issues/new
Error 404

**Describe the results you expected:**

1. Go to https://build.opensuse.org (I think).
2. Go to https://github.com/cri-o/cri-o/issues/new

### PR DESCRIPTION
**Pull request by EGuesnet**
Signed-off-by: Étienne Guesnet <etienne.guesnet@atos.net>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Correct two wrong link in install.md.

#### Which issue(s) this PR fixes:

Fixes #5357

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve
LGTM
@cri-o/cri-o-maintainers PTAL

**Comment by fgiudici** [comment]
/lgtm
thanks!

**Pull request merged**
