### PR TITLE
Use a common cert-reloader for metrics and streaming endpoints

### PR DESCRIPTION
**Pull request by bitoku**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR is required to fix / https://github.com/cri-o/cri-o/issues/7513 .

Currently streaming server and metrics server has similar cert reload system, but implemented differently.
This PR splits out the current cert reloader for metrics server to a new package, and has streaming server use it.
This also enables streaming server to detect the cert change immediately and change the cert.

#### Which issue(s) this PR fixes:

https://github.com/cri-o/cri-o/issues/7513 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by bitoku** [comment]
@cri-o/cri-o-maintainers Can you PTAL?

**Comment by haircommander** [comment]
/approve

LGTM, thanks!

**Comment by kwilczynski** [comment]
This is nice, however it does not entirely fix the linked issue. But, it's an improvement nonetheless.

**Comment by kwilczynski** [comment]
/hold

So I can make a review.

**Comment by bitoku** [comment]
@cri-o/cri-o-maintainers Can anyone give review?

**Review by saschagrunert — APPROVED** [review]
Great work, thank you!

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
