### PR TITLE
version: bump to 1.25.4

### PR DESCRIPTION
**Pull request by sohankunkerkar**
#### Which issue(s) this PR fixes:
https://github.com/cri-o/cri-o/issues/6805#issuecomment-1655644811

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
I was wondering if we could get https://github.com/cri-o/cri-o/pull/7132 in before merging this PR

**Comment by sohankunkerkar** [comment]
And https://github.com/cri-o/cri-o/pull/7156 as well

**Comment by haircommander** [comment]
let's wait on https://github.com/cri-o/cri-o/pull/7156 but get https://github.com/cri-o/cri-o/pull/7132

**Comment by haircommander** [comment]
@sohankunkerkar is this ready?

**Comment by sohankunkerkar** [comment]
> let's wait on #7156 but get #7132

sure thing!

**Comment by sohankunkerkar** [comment]
> @sohankunkerkar is this ready?

Yes, it is

**Comment by atirek89** [comment]
Is this version released or any ETA on this.

**Comment by haircommander** [comment]
https://github.com/cri-o/cri-o/releases/tag/v1.25.4 is released! we'll work on getting packaged this week as well

**Comment by agoyald** [comment]
Thank you very much

**Pull request merged**
