### PR TITLE
crio wipe: do not wipe images by default

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where images were wiped by default on upgrades (the default should be false).
```

### CODE REVIEW

**Comment by haircommander** [comment]
fixes https://github.com/cri-o/cri-o/issues/5352

**Comment by haircommander** [comment]
related to https://github.com/openshift/machine-config-operator/pull/2776

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests which are ever so close.

**Review by QiWang19 — COMMENTED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
```
level=error msg="Tag `version_file_persist` with expected value `\"\"` not found in `docs/crio.conf.5.md`"
```
From the CI

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by haircommander** [comment]
solved in https://github.com/cri-o/cri-o/pull/6022/

**Pull request closed without merging**
