### PR TITLE
Test for master tag if release branch contains none

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
If the release branch tag contains none then we have to check for the
master branch before giving up. This fixes to have the right version
when creating release branches which contain no actual tag.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
Relates to https://github.com/cri-o/cri-o/pull/3503
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander let's do a fast-forward with the script to verify that this change can be merged on top. I can do it as well if you want to :innocent:

**Comment by haircommander** [comment]
> @haircommander let's do a fast-forward with the script to verify that this change can be merged on top. I can do it as well if you want to innocent

I did it and it worked perfectly!

**Comment by saschagrunert** [comment]
Cool, I'll propose the automation in my WIP PR :+1:

**Pull request merged**
