### PR TITLE
test/network_ping.bats: simplify

### PR DESCRIPTION
**Pull request by kolyshkin**
_This used to be a part of #4127, which I am splitting into smaller PRs._

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Simplify the code and fix shellcheck warnings; similar to #4245

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by kolyshkin** [comment]
I've seen this before:

```
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/ingressclass.go:46
Oct  6 22:43:16.720: Unexpected error:
    <*errors.StatusError | 0xc002ca40a0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "ingressclasses.networking.k8s.io \"ingressclass1\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "ingressclass1",
                Group: "networking.k8s.io",
                Kind: "ingressclasses",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
    ingressclasses.networking.k8s.io "ingressclass1" already exists
occurred
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/ingressclass.go:48
```

Looks very much like a race between two tests that try to create "ingressclass1", or a failure to remove it after the test is finished.

**Comment by mrunalp** [comment]
We should open an upstream issue for the imagestream flake.

**Pull request merged**
