### PR TITLE
[1.25] Vendor in stable containers/storage instead of stray commit

### PR DESCRIPTION
**Pull request by akalenyu**
We may or may not be seeing an issue related to this in kubevirt on OpenShift,
regardless, it doesn't seem like a bad idea to vendor in a stable release instead of a stray commit.
We also vendor this exact version in 1.26 at the point of writing this.
Diff:
https://github.com/containers/storage/compare/a747b27...v1.45.3

The issue we are (rarely) observing is
```bash
sh-4.4# cat /proc/1/mountinf | grep 'ddd0718f846fa69a311121696360a9d6f2e2d9258ffc40'
sh-4.4# cd /var/lib/containers/storage/overlay/ddd0718f846fa69a311121696360a9d6f2e2d9258ffc407cee3fd9b992122ebb
sh-4.4#
```
Meaning, the overlay path exists, but there is no such mount.
The mount was succeeded at one point according to the journal, so it's weird to me that it's not in /proc/1/mountinfo,
as if it was unmounted when it should not have.

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test

we generally attempt to avoid bumping the storage library in release branches, and favor cherry-picking fixes. have you seen this version being helpful? 

cc @nalind @giuseppe @mtrmac

**Comment by akalenyu** [comment]
> /ok-to-test
> 
> we generally attempt to avoid bumping the storage library in release branches, and favor cherry-picking fixes. have you seen this version being helpful?
> 
> cc @nalind @giuseppe @mtrmac

I am still looking for the exact culprit, but we seem to only hit it in the 1.25 pipelines (1.26 is fine),
and only since we brought in a cri-o bump that included these:
```bash
$ git log --oneline 3c4e50c..0a083f9 | grep Merge
0a083f9f9 Merge pull request #6524 from openshift-cherrypick-robot/cherry-pick-6450-to-release-1.25
f9b577337 Merge pull request #6646 from haircommander/runtime-tools-1.25
1a6bb9c9b Merge pull request #6613 from haircommander/bump-storage-1.25
5352a27c5 Merge pull request #6529 from openshift-cherrypick-robot/cherry-pick-6403-to-release-1.25
```

I noticed one of these changes (https://github.com/cri-o/cri-o/pull/6613) was pinning the version of containers/storage to a stray commit, so I thought it may be a good start.

I totally understand the preference to cherry-pick a change, I can try bringing https://github.com/cri-o/cri-o/pull/6634
which also brought this bump to 1.26.

**Comment by haircommander** [comment]
if you'd like, you can message me on slack and I can help you put the binary this creates onto a node to see if it helps your issue

**Comment by akalenyu** [comment]
> if you'd like, you can message me on slack and I can help you put the binary this creates onto a node to see if it helps your issue

that would be awesome. thank you!

**Comment by haircommander** [comment]
we chatted offline and this did not fix the problem. @akalenyu were you still hoping for this PR

**Comment by akalenyu** [comment]
> we chatted offline and this did not fix the problem. @akalenyu were you still hoping for this PR

feel free to close

**Pull request closed without merging**
