### PR TITLE
Remove unnecessary _posts dir

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
After the merge of https://github.com/cri-o/cri-o/pull/3548 we do not
have a need for the `_posts` dir any more. Updated the README to link to
the new dependencies report.
#### Which issue(s) this PR fixes:

Requires https://github.com/cri-o/cri-o/pull/3548
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by giuseppe** [comment]
needs rebase

**Comment by saschagrunert** [comment]
Thanks for the hint, let's wait for #3548 before I rebase :)

**Comment by saschagrunert** [comment]
Rebased, every master merge will trigger a merge conflict with this PR so I suggest in merging this one fast. :)

**Pull request merged**
