### PR TITLE
add installation steps for CentOS

### PR DESCRIPTION
**Pull request by lsm5**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Adds installation steps for CentOS

#### Which issue(s) this PR fixes:
None (that I know of)

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/lgtm

(I'm not so sure how many people will go digging in the release branches for these docs,

**Comment by lsm5** [comment]
> /lgtm

@haircommander I guess you edited part of the comment :D . But ya, I anticipate many issues will be filed, in which case just tag me there and move on :) . Sorry about the constant repo re-org.

**Comment by haircommander** [comment]
no problem at all. I edited because i sent it before it was a completed thought, then I dropped the thought. thanks for the PRs and your work, as always!

**Pull request merged**
