### PR TITLE
Bump version to 1.18.4

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Bump the version for the next 1.18 release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
dang, we haven't even packaged 1.18.3 yet :laughing:

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by haircommander** [comment]
did you do this with https://github.com/cri-o/cri-o/pull/4017

**Comment by saschagrunert** [comment]
> did you do this with #4017

Yes, I'll close this for now since the issue is not as urgent any more on our side. :)

**Pull request closed without merging**
