### PR TITLE
oci: fix panic on double close

### PR DESCRIPTION
**Pull request by haircommander**
and listen to a comment saying explicitly not to close that channel there :facepalm:

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
Fix potential panic when reopening a container's log
```

### CODE REVIEW

**Comment by haircommander** [comment]
listen to yourself Peter https://github.com/cri-o/cri-o/blob/master/internal/oci/runtime_oci.go#L1099

**Review by mrunalp — APPROVED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
