### PR TITLE
Update OCI CNI to v0.4.2

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Update the dependency to the latest version.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
@saschagrunert, we might need a quick rebase.

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL

**Pull request merged**
