### PR TITLE
[1.12] Backport empty CircleCI config

### PR DESCRIPTION
**Pull request by saschagrunert**
We now add a stub that CircleCi does not complain any more.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Porting back to 1.12 should be enough, right? :eyes:

**Comment by haircommander** [comment]
@saschagrunert can you do one for 1.11 just to be sure? I think everything before that has broken CI anyway...

**Comment by haircommander** [comment]
@mrunalp @rhatdan needs approval

**Pull request merged**
