### PR TITLE
contrib/test: Use the main branch of runc

### PR DESCRIPTION
**Pull request by sohankunkerkar**
Now https://github.com/opencontainers/runc/pull/4053 has fixed, Let's use the main branch of runc

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
cc @kolyshkin

**Review by mrunalp — COMMENTED** [review]
Let's retain the logic to set git version and set it to main

**Review by kolyshkin — APPROVED** [review]
SGTM

**Comment by kolyshkin** [comment]
@sohankunkerkar seems this one needs to be rebased; too many failures not related to runc

**Review by saschagrunert — CHANGES_REQUESTED** [review]
We need to fix the `verify-dependencies` CI run for this.

**Pull request merged**
