### PR TITLE
[1.11] port forward: drain the stream on error

### PR DESCRIPTION
**Pull request by haircommander**
Before, we never drained the stream when we failed before calling pools.Copy(). A failure like this could happen if socat is not installed, or there is an invalid id found.

The problem is: if we never drain the streams, they stay open, and will cause kubelet to hang when trying to allocate one of its streams. If we don't drain on error, we can leak

fix this by draining the streams on error, until we actually want to copy data out of it

fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1798193

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
(this is currently untested)

**Comment by rhatdan** [comment]
LGTM
@haircommander Is this the one that Kata does not work for?

**Comment by haircommander** [comment]
> LGTM
> @haircommander Is this the one that Kata does not work for?

no, you're thinking of https://github.com/cri-o/cri-o/pull/3045

kata isn't working here probably because 1.11 is wicked old. I'm also not super inclined to get it to work because 1.11 is out of support in the upstream, and this PR is mostly for openshift 3.11 support

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
