### PR TITLE
Bump cri-tools to v1.24.2

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Update cri-tools to the latest release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated cri-tools to v1.24.2.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Updated to match cri-tools v1.24.1.

**Comment by saschagrunert** [comment]
Alright, this now requres a new release as containing https://github.com/kubernetes-sigs/cri-tools/pull/940
/hold

**Comment by saschagrunert** [comment]
/unhold
/retest

@haircommander PTAL

**Comment by saschagrunert** [comment]
@fidencio @fgiudici I think we have to bump cri-tools in kata to v1.24.2 as well. Can you hint me to the location where I should update the version? :)

**Comment by saschagrunert** [comment]
> @fidencio @fgiudici I think we have to bump cri-tools in kata to v1.24.2 as well. Can you hint me to the location where I should update the version? :)

Probably this one should be enough: https://github.com/kata-containers/kata-containers/pull/4340

**Comment by haircommander** [comment]
/hold 

ci issues

**Pull request merged**
