### PR TITLE
version change from 0.7.4 to 0.8.1 released on June 6

### PR DESCRIPTION
**Pull request by 979156**
Signed-off-by: Yeongju Kang <979156@gmail.com>

**- What I did**
document changes 

**- How I did it**
I checked out 0.8.1 instead of using 0.7.4 and built it on fedora 30 container and debian 9 container.

**- How to verify it**
doing same with markdown

**- Description for the changelog**
document update using CNI plugin 0.8.1

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hey @979156 :wave:, thanks for the PR!

/ok-to-test

**Comment by haircommander** [comment]
LGTM @979156 though you have whitespace errors in your commit message
https://circleci.com/gh/cri-o/cri-o/3362?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by 979156** [comment]
@haircommander thanks Peter, I will update that when I am availiable

**Comment by saschagrunert** [comment]
Hey @979156, can you squash your commits together to fix the git-validation step?

**Comment by 979156** [comment]
@saschagrunert @haircommander thanks for the reviews, very solid process. learned a lot from yours!

**Pull request merged**
