### PR TITLE
server status: add cgroup manager

### PR DESCRIPTION
**Pull request by vrothberg**
Fixes: #2414
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
According to the API, only the runtime and network status are required and all other statuses are optional, so we can add any kind of data.

I think that other config options could be valuable as well and that we can generalize #2414 a bit more. But before jumping into that: WDYT @umohnani8 @saschagrunert @haircommander @mrunalp ?

**Comment by saschagrunert** [comment]
> According to the API, only the runtime and network status are required and all other statuses are optional, so we can add any kind of data.

Sure, this looks good to me too.

> I think that other config options could be valuable as well and that we can generalize #2414 a bit more. 

Is there any reason why to not use the `/info` HTTP endpoint which already includes this information?

**Comment by vrothberg** [comment]
> Is there any reason why to not use the /info HTTP endpoint which already includes this information?

Do you know if any cli-client is using that?

**Comment by saschagrunert** [comment]
> > Is there any reason why to not use the /info HTTP endpoint which already includes this information?
> 
> Do you know if any cli-client is using that?

I don't think so, but we could trigger it with any HTTP client:

```
> sudo curl -s --unix-socket /var/run/crio/crio.sock http://localhost/info | jq
{
  "storage_driver": "btrfs",
  "storage_root": "/var/lib/containers/storage",
  "cgroup_driver": "cgroupfs",
  "default_id_mappings": {
    "uids": [
      {
        "container_id": 0,
        "host_id": 0,
        "size": 4294967295
      }
    ],
    "gids": [
      {
        "container_id": 0,
        "host_id": 0,
        "size": 4294967295
      }
    ]
  }
}
```

I guess we have to add documentation about that... :thinking:

**Comment by vrothberg** [comment]
> I guess we have to add documentation about that...

Very good idea. I'll close the PR in favor of the http request :+1:

**Pull request closed without merging**
