### PR TITLE
server: reduce object creation in List{Containers,PodSandboxes}

### PR DESCRIPTION
**Pull request by haircommander**
by only creating a new sandbox or container object when they change

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
related to https://github.com/cri-o/cri-o/pull/5606 and https://github.com/cri-o/cri-o/pull/5409

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by haircommander** [comment]
@saschagrunert PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Oops the linter/build is not happy.

**Comment by haircommander** [comment]
(sorry, compile error, PTAL again :heart: )

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
/hold

ci issues

**Comment by haircommander** [comment]
actually wait

/hold

thought of another possible problem here

**Comment by haircommander** [comment]
nevermind we're good
/unhold

**Pull request merged**
