### PR TITLE
bump to v1.19.0

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind documentation 

> /kind failing-test
> /kind feature
> /kind flake

#### What this PR does / why we need it:
as title says!
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by saschagrunert** [comment]
This commit basically broke the build of the release-notes tool: 15aa81b6bf6b0fc3a8982f099cb3d8ae1582f697

Working on a fix.

**Pull request merged**
