### PR TITLE
Update k/release to 0.3.2

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
This allows us to automatically add dependency changes to generated
release-notes (feature is enabled by default).
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

[Demo - v1.19.0-dev.md.txt](https://github.com/cri-o/cri-o/files/4730099/v1.19.0-dev.md.txt)

#### Does this PR introduce a user-facing change?

```release-note
- Added dependency report to generated release notes
```

### CODE REVIEW

**Comment by haircommander** [comment]
nice
LGTM

**Comment by saschagrunert** [comment]
Had to rebase to resolve the merge conflict.

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons

**Pull request merged**
