### PR TITLE
test: reduce flakes

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:
deflake stats test by making the two containers different
deflake all tests by ignoring ENOENT on the shm unmount (as we're allowed to attempt to UnmountShm() multiple times)
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
/cherry-pick release-1.19

[this](https://prow.ci.openshift.org/view/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/4141/test_pull_request_crio_e2e_crun_fedora/12326/) run seems to be hit negatively by a bug fixed by https://github.com/cri-o/cri-o/pull/4146

/retest

**Comment by fidencio** [comment]
LGTM

**Pull request merged**
