### PR TITLE
fix ci test shellcheck shfmt err

### PR DESCRIPTION
**Pull request by lance5890**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
I have seen the verify / shfmt ci error in all recently PR, such as https://github.com/cri-o/cri-o/actions/runs/7510297349/job/20448541353?pr=7687

I think this was caused  by this commit  https://github.com/cri-o/cri-o/commit/5faee5d82556a6bf4dd1144d2a86e70d097ab200
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lance5890** [comment]
@haircommander fix a ci test error f ths commit https://github.com/cri-o/cri-o/commit/5faee5d82556a6bf4dd1144d2a86e70d097ab200

**Review by sohankunkerkar — APPROVED** [review]
/approve
/lgtm

**Comment by sohankunkerkar** [comment]
https://github.com/cri-o/cri-o/actions/runs/7510393471/job/20448765988?pr=7688

I think you need to address this issue as well.

**Comment by sohankunkerkar** [comment]
It looks like @haircommander already put up a PR for this: https://github.com/cri-o/cri-o/pull/7674

**Comment by lance5890** [comment]
> It looks like @haircommander already put up a PR for this: #7674

I have proposed a new PR， maybe it‘s better to encapsulate a function  @haircommander what do u think ?

**Comment by haircommander** [comment]
interesting idea, though I don't personally see a reason to copy the file if we're not editing it

**Pull request closed without merging**
