### PR TITLE
add version_bump.go script to automate the release pipeline

### LINKED ISSUE #7169: Bump versions using go script
This is a child issue to the parent issue https://github.com/cri-o/cri-o/issues/4003

### Description:
Currently, the version of ```cri-o``` needs to be manually modified in the ```internal/version/version.go``` file.

This needs to be automated using a go-script which can be used in the CI environments to bump that version automatically.

### Additional Context:
In the future, the modified version would need to be pushed to the main branch using GitHub action workflow automatically.

### PR DESCRIPTION
**Pull request by anshgoyalevil**
#### What type of PR is this?
This PR adds the ```version_bump.go``` script to automatically bump the version in internal/version/version.go file.
/kind feature

#### What this PR does / why we need it:
We needed this feature to automate the version bumping using GitHub actions. This script has little use as of now, but as per issue https://github.com/cri-o/cri-o/issues/4003 this script would be used in the CI environment of GitHub actions to change the version and create pull requests.

#### Which issue(s) this PR fixes:
fixes #7169 

#### Special notes for your reviewer:
This script is designed to work as below:

- run the command ```go run scripts/version_bump.go```
- The version inside the internal/version/version.go would be changed. For example: 1.2.3 to 1.2.4

It also supports additional arguments like:
- ```go run scripts/version_bump.go patch``` for patch bump. Example: 1.2.3 to 1.2.4
- ```go run scripts/version_bump.go minor``` for minor bump. Example: 1.2.3 to 1.3.0
- ```go run scripts/version_bump.go major``` for major bump. Example: 1.2.3 to 2.0.0

#### Does this PR introduce a user-facing change?
No

```release-note
add version bump automation script
```

### CODE REVIEW

**Comment by anshgoyalevil** [comment]
//cc @haircommander @saschagrunert 
Made the required changes. Please review.
Thanks

**Comment by anshgoyalevil** [comment]
@saschagrunert is it ready to merge?

**Review by saschagrunert — APPROVED** [review]

**Comment by anshgoyalevil** [comment]
@saschagrunert 
2 tests are still failing. Is that an expected behavior? 🤔

**Pull request merged**
