### PR TITLE
OCPBUGS-13980: runtime handler hooks: run default hooks on graceful container exit

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
previously, some containers were missing the default hooks, as they didn't run on container exit.

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where the PostStop runtime handler hooks weren't being called when a container exited gracefully
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by haircommander** [comment]
@cri-o/cri-o-maintainers PTAL

**Pull request merged**
