### PR TITLE
Add Reddit to ADOPTERS.md

### PR DESCRIPTION
**Pull request by eaceaser**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Adds Reddit to ADOPTERS.md

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by mrunalp** [comment]
@eaceaser Thanks! Could you add signoff the commit?

**Comment by eaceaser** [comment]
@mrunalp should be good now

**Review by saschagrunert — APPROVED** [review]
Thank you so much!
/lgtm

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Pull request merged**
