### PR TITLE
Remove device mapper storage driver support

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind deprecation

#### What this PR does / why we need it:

Device mapper storage driver is hard to set up, slow, and obsoleted by overlayfs.
My best guess is nobody is using it nowadays.

Let's remove it.

#### Which issue(s) this PR fixes:

Fixes: #7002

#### Does this PR introduce a user-facing change?

```release-note
Remove device mapper storage driver.
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
OK, this is blocked by buildah which can't be built without libdevmapper.

Moving to draft until we have buildah release with https://github.com/containers/buildah/pull/4832 included

**Comment by fidencio** [comment]
@kolyshkin, devmapper can be used with Kata Containers and in the Confidential Containers front it'll be heavily used.

We're using devmapper as TEE capable kernels do not support virtio-fs, virtio-9p is not supported by several distros (and also by several hypervisors), leaving us with the only option to use devmapper as the way to share the container rootfs between host and guest via a block device.

I know, Red Hat OpenShift is not using it, AFAIU, but other users of CRi-O could.

This is not a show stopper for this PR, but I'd love to have it taken into consideration.

/cc @littlejawa @bpradipt

**Comment by sohankunkerkar** [comment]
>Moving to draft until we have buildah release with https://github.com/containers/buildah/pull/4832 included

This fix has been included in https://github.com/containers/buildah/releases/tag/v1.31.0

**Comment by kolyshkin** [comment]
Resurrected as #8019

**Pull request closed without merging**
