### PR TITLE
Revert "Revert "server: use IsAlive() more""

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind ci
/kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:
This reverts commit 1c6849c5bbfbbefa9942c0801735084febd15c4d.

Hopefully we can fix the test failures that caused the revert

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
built on top of https://github.com/cri-o/cri-o/pull/5740 now

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Pull request closed without merging**
