### PR TITLE
add ignore rules to muse config for infer tool

### PR DESCRIPTION
**Pull request by arcolife**
Signed-off-by: arcolife <archit.py@gmail.com>

#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

muse report generated has false postitives. This PR aims to initiate a muse config that could be enhanced as needed.

#### Special notes for your reviewer:

bugbash reports from muse

references:
- https://docs.muse.dev/docs/repository-configuration/

#### Does this PR introduce a user-facing change?

None

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve
LGTM, thanks @arcolife

**Comment by arcolife** [comment]
I saw the details before the last `/retest` and it seems some of those include a lot many timeouts. 
Post-retest, there are even more # of total failures without a change.

Is there a non-deterministic creep ?

**Comment by arcolife** [comment]
btw the latest commit worked and it picked up the `RESOURCE LEAK` ignored in muse conf as `FIXED` 

https://console.muse.dev/result/cri-o/cri-o/01F4WTCSQTZ08M4VJ81ACJB0NX?t=Infer%7CRESOURCE_LEAK&tab=results

**Review by saschagrunert — APPROVED** [review]

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
