### PR TITLE
[1.28] Add registries.conf to CRI-O bundle

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
To make the build in OBS work with the latest spec.

#### Which issue(s) this PR fixes:

Refers to https://github.com/cri-o/cri-o/issues/7280 and https://github.com/kubernetes/release/issues/3214
 
#### Special notes for your reviewer:
Inherited from https://github.com/cri-o/cri-o/pull/7243 and https://github.com/cri-o/cri-o/pull/7232
#### Does this PR introduce a user-facing change?

```release-note
Added registries.conf to CRI-O bundle
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander can I tag a v1.28.2 after this has been merged?

**Comment by haircommander** [comment]
Since we're still using our libcontainers OBS for 1.28, would you be open to using a dummy tag for it for testing until we have more work to warrant a 1.28.2? I am open but hesitant of the patch version growing a lot bc of other now hidden gaps

**Comment by saschagrunert** [comment]
@haircommander sounds good to me!

**Pull request merged**
