### PR TITLE
Fixups for moving to github.com/cri-o/cri-o

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@caniszczyk CLA isn't working. Are there any steps we need to follow?

**Comment by caniszczyk** [comment]
@mrunalp you can drop the CLA requirement and just use ALv2 + DCO (this is what almost all CNCF projects do outside of k8s)

**Comment by mrunalp** [comment]
@caniszczyk okay, thanks!

**Comment by mrunalp** [comment]
@caniszczyk I am not sure what is making the cla/linuxfoundation check show up here. I don't have a webhook for it.

**Comment by vrothberg** [comment]
Looks like the CI is still referring to the old repo:
```
[...] /go/src/github.com/kubernetes-sigs/cri-o/contrib/test/integration/build/cri-o.yml: [...]
```

Same for the "[stat the expected cri-o directory]" task which clearly has been updated in the commit.

**Comment by mrunalp** [comment]
okay the tests are in good shape. I am going to open another PR for integration_rhel issue.

**Pull request merged**
