### PR TITLE
vendor: fix CI due to incosistent vendoring

### PR DESCRIPTION
**Pull request by sohankunkerkar**
`make check-vendor` and `make release-notes` started failing on the main branch. I think this PR should fix those jobs.

#### What type of PR is this?

/kind bug
/kind ci

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by saschagrunert — APPROVED** [review]
Awesome! So much code gone.

**Pull request merged**
