### PR TITLE
Add CircleCI badge

### PR DESCRIPTION
**Pull request by saschagrunert**
This PR adds the CircleCI badge to our README.md

I guess we would be ready to succeed travis with CircleCI after the 1.15 release. WDYT?

### CODE REVIEW

**Comment by vrothberg** [comment]
LGTM but I'd prefer adding the badge after the migration to CircleCI.

**Comment by saschagrunert** [comment]
> LGTM but I'd prefer adding the badge after the migration to CircleCI.

Would be fine to me too. We're already running it on the master branch.

**Comment by vrothberg** [comment]
> > LGTM but I'd prefer adding the badge after the migration to CircleCI.
> 
> Would be fine to me too. We're already running it on the master branch.

Scratch what I said before, I am cool to merge (LGTM). I had a look at the list of running checks and circli did not yet show up, so I assumed it's not yet on master.

**Comment by saschagrunert** [comment]
> > > LGTM but I'd prefer adding the badge after the migration to CircleCI.
> > 
> > 
> > Would be fine to me too. We're already running it on the master branch.
> 
> Scratch what I said before, I am cool to merge (LGTM). I had a look at the list of running checks and circli did not yet show up, so I assumed it's not yet on master.

It only builds on the openSUSE fork, because I enabled it manually for it. It reports the results only if the PR is already open during the test run, which means that there are sometimes no/incomplete results reported if I'm too slow.

BTW everyone can integrate CircleCI into their fork currently, but this would be obsolete when we toggle the switch for "building PRs" as well.

**Pull request merged**
