### PR TITLE
Move CNI plugin into NetworkConfig

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
The network configuration validation seems to be the right place to init
the CNI plugin, because after that we have all necessary information for
it.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Looks like we have a crun compilation issue:
```json
{
  "changed": false,
  "cmd": "/usr/bin/gmake",
  "msg": "/bin/sh: m: command not found\ngmake[2]: [Makefile:2263: src/libcrun/signals.c] Error 127 (ignored)\n/usr/bin/ld: src/crun-kill.o: in function `crun_command_kill':\n/go/src/github.com/containers/crun/src/kill.c:104: undefined reference to `str2sig'\ncollect2: error: ld returned 1 exit status\ngmake[2]: *** [Makefile:1039: crun] Error 1\ngmake[1]: *** [Makefile:1551: all-recursive] Error 1\ngmake: *** [Makefile:769: all] Error 2",
  "rc": 2,
  "stderr": "/bin/sh: m: command not found\ngmake[2]: [Makefile:2263: src/libcrun/signals.c] Error 127 (ignored)\n/usr/bin/ld: src/crun-kill.o: in function `crun_command_kill':\n/go/src/github.com/containers/crun/src/kill.c:104: undefined reference to `str2sig'\ncollect2: error: ld returned 1 exit status\ngmake[2]: *** [Makefile:1039: crun] Error 1\ngmake[1]: *** [Makefile:1551: all-recursive] Error 1\ngmake: *** [Makefile:769: all] Error 2\n",
  "stderr_lines": [
    "/bin/sh: m: command not found",
    "gmake[2]: [Makefile:2263: src/libcrun/signals.c] Error 127 (ignored)",
    "/usr/bin/ld: src/crun-kill.o: in function `crun_command_kill':",
    "/go/src/github.com/containers/crun/src/kill.c:104: undefined reference to `str2sig'",
    "collect2: error: ld returned 1 exit status",
    "gmake[2]: *** [Makefile:1039: crun] Error 1",
    "gmake[1]: *** [Makefile:1551: all-recursive] Error 1",
    "gmake: *** [Makefile:769: all] Error 2"
  ],
  "stdout": "  GEN      .version\n/usr/bin/gmake  all-recursive\ngmake[1]: Entering directory '/go/src/github.com/containers/crun'\nMaking all in libocispec\ngmake[2]: Entering directory '/go/src/github.com/containers/crun/libocispec'\n/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=. --out=./src ./runtime-spec/schema ./image-spec/schema\n/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=./tests/test-spec --out=./src ./tests/test-spec/imageManifestItems\n/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=. --out=./src ./runtime-spec/schema ./image-spec/schema\n/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=./tests/test-spec --out=./src ./tests/test-spec/imageManifestItems\n/usr/bin/gmake  all-am\ngmake[3]: Entering directory '/go/src/github.com/containers/crun/libocispec'\n  CC       src/validate.o\n  CC       src/json_common.lo\n/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=. --out=./src ./runtime-spec/schema ./image-spec/schema\n/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=./tests/test-spec --out=./src ./tests/test-spec/imageManifestItems\n  CC       src/image_spec_schema_config_schema.lo\n  CC       src/image_spec_schema_content_descriptor.lo\n  CC       src/image_spec_schema_defs.lo\n  CC       src/image_spec_schema_defs_descriptor.lo\n  CC       src/image_spec_schema_image_index_schema.lo\n  CC       src/image_spec_schema_image_layout_schema.lo\n  CC       src/image_spec_schema_image_manifest_schema.lo\n  CC       src/runtime_spec_schema_config_linux.lo\n  CC       src/runtime_spec_schema_config_schema.lo\n  CC       src/runtime_spec_schema_config_solaris.lo\n  CC       src/runtime_spec_schema_config_vm.lo\n  CC       src/runtime_spec_schema_config_windows.lo\n  CC       src/runtime_spec_schema_defs.lo\n  CC       src/runtime_spec_schema_defs_linux.lo\n  CC       src/runtime_spec_schema_defs_vm.lo\n  CC       src/runtime_spec_schema_defs_windows.lo\n  CC       src/runtime_spec_schema_state_schema.lo\n  CC       src/image_manifest_items_image_manifest_items_schema.lo\n  CC       src/read-file.lo\n  CCLD     libocispec.la\ncopying selected object files to avoid basename conflicts...\n  CCLD     src/validate\n  CC       tests/test-1.o\n  CCLD     tests/test-1\n  CC       tests/test-2.o\n  CCLD     tests/test-2\n  CC       tests/test-3.o\n  CCLD     tests/test-3\n  CC       tests/test-4.o\n  CCLD     tests/test-4\n  CC       tests/test-5.o\n  CCLD     tests/test-5\n  CC       tests/test-6.o\n  CCLD     tests/test-6\n  CC       tests/test-7.o\n  CCLD     tests/test-7\n  CC       tests/test-8.o\n  CCLD     tests/test-8\n/bin/sh ./libtool --mode=link  libocispec.la -o libocispec.a\nlibtool: link: ar cru libocispec.a \nlibtool: link: ranlib libocispec.a\ngmake[3]: Leaving directory '/go/src/github.com/containers/crun/libocispec'\ngmake[2]: Leaving directory '/go/src/github.com/containers/crun/libocispec'\ngmake[2]: Entering directory '/go/src/github.com/containers/crun'\n  CC       src/crun-crun.o\n  CC       src/crun-run.o\n  CC       src/crun-delete.o\n  CC       src/crun-kill.o\n  CC       src/crun-pause.o\n  CC       src/crun-unpause.o\n  CC       src/crun-spec.o\n  CC       src/crun-exec.o\n  CC       src/crun-list.o\n  CC       src/crun-create.o\n  CC       src/crun-start.o\n  CC       src/crun-state.o\n  CC       src/crun-update.o\n  CC       src/crun-ps.o\n  CC       src/crun-checkpoint.o\n  CC       src/crun-restore.o\n  CC       src/libcrun/libcrun_la-utils.lo\n  CC       src/libcrun/libcrun_la-cloned_binary.lo\n  CC       src/libcrun/libcrun_la-container.lo\n  CC       src/libcrun/libcrun_la-cgroup.lo\n  CC       src/libcrun/libcrun_la-criu.lo\n  CC       src/libcrun/libcrun_la-linux.lo\n  CC       src/libcrun/libcrun_la-seccomp.lo\n  CC       src/libcrun/libcrun_la-ebpf.lo\n  CC       src/libcrun/libcrun_la-error.lo\n  CC       src/libcrun/libcrun_la-status.lo\n  CC       src/libcrun/libcrun_la-terminal.lo\n  CC       src/libcrun/libcrun_la-chroot_realpath.lo\nm 100 --null-strings --pic -tCEG -S1 src/libcrun/signals.perf > src/libcrun/signals.c\n  CC       src/libcrun/libcrun_la-signals.lo\n  CCLD     libcrun.la\n  CCLD     crun\ngmake[2]: Leaving directory '/go/src/github.com/containers/crun'\ngmake[1]: Leaving directory '/go/src/github.com/containers/crun'\n",
  "stdout_lines": [
    "  GEN      .version",
    "/usr/bin/gmake  all-recursive",
    "gmake[1]: Entering directory '/go/src/github.com/containers/crun'",
    "Making all in libocispec",
    "gmake[2]: Entering directory '/go/src/github.com/containers/crun/libocispec'",
    "/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=. --out=./src ./runtime-spec/schema ./image-spec/schema",
    "/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=./tests/test-spec --out=./src ./tests/test-spec/imageManifestItems",
    "/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=. --out=./src ./runtime-spec/schema ./image-spec/schema",
    "/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=./tests/test-spec --out=./src ./tests/test-spec/imageManifestItems",
    "/usr/bin/gmake  all-am",
    "gmake[3]: Entering directory '/go/src/github.com/containers/crun/libocispec'",
    "  CC       src/validate.o",
    "  CC       src/json_common.lo",
    "/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=. --out=./src ./runtime-spec/schema ./image-spec/schema",
    "/usr/bin/python3 ./src/generate.py --gen-common --gen-ref --root=./tests/test-spec --out=./src ./tests/test-spec/imageManifestItems",
    "  CC       src/image_spec_schema_config_schema.lo",
    "  CC       src/image_spec_schema_content_descriptor.lo",
    "  CC       src/image_spec_schema_defs.lo",
    "  CC       src/image_spec_schema_defs_descriptor.lo",
    "  CC       src/image_spec_schema_image_index_schema.lo",
    "  CC       src/image_spec_schema_image_layout_schema.lo",
    "  CC       src/image_spec_schema_image_manifest_schema.lo",
    "  CC       src/runtime_spec_schema_config_linux.lo",
    "  CC       src/runtime_spec_schema_config_schema.lo",
    "  CC       src/runtime_spec_schema_config_solaris.lo",
    "  CC       src/runtime_spec_schema_config_vm.lo",
    "  CC       src/runtime_spec_schema_config_windows.lo",
    "  CC       src/runtime_spec_schema_defs.lo",
    "  CC       src/runtime_spec_schema_defs_linux.lo",
    "  CC       src/runtime_spec_schema_defs_vm.lo",
    "  CC       src/runtime_spec_schema_defs_windows.lo",
    "  CC       src/runtime_spec_schema_state_schema.lo",
    "  CC       src/image_manifest_items_image_manifest_items_schema.lo",
    "  CC       src/read-file.lo",
    "  CCLD     libocispec.la",
    "copying selected object files to avoid basename conflicts...",
    "  CCLD     src/validate",
    "  CC       tests/test-1.o",
    "  CCLD     tests/test-1",
    "  CC       tests/test-2.o",
    "  CCLD     tests/test-2",
    "  CC       tests/test-3.o",
    "  CCLD     tests/test-3",
    "  CC       tests/test-4.o",
    "  CCLD     tests/test-4",
    "  CC       tests/test-5.o",
    "  CCLD     tests/test-5",
    "  CC       tests/test-6.o",
    "  CCLD     tests/test-6",
    "  CC       tests/test-7.o",
    "  CCLD     tests/test-7",
    "  CC       tests/test-8.o",
    "  CCLD     tests/test-8",
    "/bin/sh ./libtool --mode=link  libocispec.la -o libocispec.a",
    "libtool: link: ar cru libocispec.a ",
    "libtool: link: ranlib libocispec.a",
    "gmake[3]: Leaving directory '/go/src/github.com/containers/crun/libocispec'",
    "gmake[2]: Leaving directory '/go/src/github.com/containers/crun/libocispec'",
    "gmake[2]: Entering directory '/go/src/github.com/containers/crun'",
    "  CC       src/crun-crun.o",
    "  CC       src/crun-run.o",
    "  CC       src/crun-delete.o",
    "  CC       src/crun-kill.o",
    "  CC       src/crun-pause.o",
    "  CC       src/crun-unpause.o",
    "  CC       src/crun-spec.o",
    "  CC       src/crun-exec.o",
    "  CC       src/crun-list.o",
    "  CC       src/crun-create.o",
    "  CC       src/crun-start.o",
    "  CC       src/crun-state.o",
    "  CC       src/crun-update.o",
    "  CC       src/crun-ps.o",
    "  CC       src/crun-checkpoint.o",
    "  CC       src/crun-restore.o",
    "  CC       src/libcrun/libcrun_la-utils.lo",
    "  CC       src/libcrun/libcrun_la-cloned_binary.lo",
    "  CC       src/libcrun/libcrun_la-container.lo",
    "  CC       src/libcrun/libcrun_la-cgroup.lo",
    "  CC       src/libcrun/libcrun_la-criu.lo",
    "  CC       src/libcrun/libcrun_la-linux.lo",
    "  CC       src/libcrun/libcrun_la-seccomp.lo",
    "  CC       src/libcrun/libcrun_la-ebpf.lo",
    "  CC       src/libcrun/libcrun_la-error.lo",
    "  CC       src/libcrun/libcrun_la-status.lo",
    "  CC       src/libcrun/libcrun_la-terminal.lo",
    "  CC       src/libcrun/libcrun_la-chroot_realpath.lo",
    "m 100 --null-strings --pic -tCEG -S1 src/libcrun/signals.perf > src/libcrun/signals.c",
    "  CC       src/libcrun/libcrun_la-signals.lo",
    "  CCLD     libcrun.la",
    "  CCLD     crun",
    "gmake[2]: Leaving directory '/go/src/github.com/containers/crun'",
    "gmake[1]: Leaving directory '/go/src/github.com/containers/crun'"
  ]
}
```

cc @giuseppe

**Comment by dougsland** [comment]
LGTM

**Comment by saschagrunert** [comment]
@haircommander I think this might be ready to be merged.

**Pull request merged**
