### PR TITLE
Add gocritic paramTypeCombine linter and fixes

### PR DESCRIPTION
**Pull request by saschagrunert**
This commit fixes issues related to the `paramTypeCombine` linter,
which detects if function parameters could be combined by type and
suggest the way to do it.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by haircommander** [comment]
you added so many linters they keep conflicting @saschagrunert ;) i'll lgtm once it goes green, just to be safe :)

**Comment by saschagrunert** [comment]
> you added so many linters they keep conflicting @saschagrunert ;) i'll lgtm once it goes green, just to be safe :)

Yeah I expected that somehow, but there are not many linters left to enable. :grin:

**Pull request merged**
