### PR TITLE
vendor github.com/containers/image@v3.0.0

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Argh ... we need to update buildah first

**Comment by vrothberg** [comment]
@mrunalp PTAL

**Comment by haircommander** [comment]
LGTM

**Comment by mrunalp** [comment]
@vrothberg Thanks! We need this for 1.13 - 1.15 as well.

**Comment by vrothberg** [comment]
We should wait for https://github.com/containers/image/pull/675 to be merged and ultimately for (v3.0.1).

**Comment by rhatdan** [comment]
@vrothberg I just merged it.

**Comment by vrothberg** [comment]
Closing in favour of https://github.com/cri-o/cri-o/pull/2689

**Pull request closed without merging**
