### PR TITLE
[1.16] Set process label to privileged when host network is true

### PR DESCRIPTION
**Pull request by mrunalp**
This is a regression from 1.14.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
What is the reason for this.  SELinux should not be interfering between two containers on the same network, or on the host network.

**Pull request merged**
