### PR TITLE
[1.22] ci: use kubernetes 1.22 and cri-tools 1.22

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

Use kubernetes 1.22 and cri-tools 1.22 in CI, since this is 1.22 branch.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
seems like we need https://github.com/cri-o/cri-o/pull/5662/commits/a5d7076b9b0fed4cfdf8624ad25bd3bd6aa961e9 here too

**Comment by saschagrunert** [comment]
A friendly reminder that this PR had no activity for 30 days.

**Comment by haircommander** [comment]
/lgtm cancel

actually @kolyshkin can you rebase first?

**Pull request merged**
