### PR TITLE
[1.16] Fix server restore to not remove podman containers

### PR DESCRIPTION
**Pull request by haircommander**
The previous behavior was that CRI-O forcely tried to remove running
podman containers on startup, which only succeeded for the container
storage but not the running process. The result was was a running
container process in podman, which got broken because its storage got
removed.

This is now fixed by excluding podman containers on restore, discovered
by the new podman annotation.

A dedicated unit test has been added as well.

Signed-off-by: Sascha Grunert <sgrunert@suse.com>

taking over https://github.com/cri-o/cri-o/pull/2883

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM
/approve

**Comment by haircommander** [comment]
merge me when e2e_fedora passes

**Comment by haircommander** [comment]
@umohnani8 @mrunalp merge me?

**Pull request merged**
