### PR TITLE
[1.19] crio: force garbage collection with SIGUSR2

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
add option to trigger a golang memory garbage collection by sending CRI-O SIGUSR2
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by fgiudici** [comment]
LGTM
/retest

**Comment by fgiudici** [comment]
Please, let's /override kata-containers ci job here! I would do, but I'm missing the super-powers... ;-)

**Comment by fidencio** [comment]
> /override ci/kata-jenkins

Third time's a charm! :-)

**Comment by haircommander** [comment]
I thnk we can do without this one

**Pull request closed without merging**
