### PR TITLE
Update Kubernetes to v1.16.0

### PR DESCRIPTION
**Pull request by saschagrunert**
Bump Kubernetes to the final v1.16.0 release. We also had to pin
`github.com/prometheus/client_golang` to a lower version to be
compatible.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by saschagrunert** [comment]
> /cherry-pick release-1.16
If we wait for https://github.com/cri-o/cri-o/pull/2841, then it should be possible

**Comment by haircommander** [comment]
ah lol good point

**Pull request merged**
