### PR TITLE
Bump `go.opentelemetry.io/*` dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Bumping the OTEL dependencies as well as removing the pinned `google.golang.org/genproto` version.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
cc @fidencio for verification that this does not break kata containers
/hold
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Rebased and test are green, PTAL @fidencio

**Comment by fidencio** [comment]
@saschagrunert, CI would catch if the change would cause some breakage.

LGTM!

**Comment by saschagrunert** [comment]
@haircommander PTAL

**Comment by saschagrunert** [comment]
@fidencio can you please /lgtm again? I saw we can bum another containerd patch here :)

**Comment by fidencio** [comment]
> @fidencio can you please /lgtm again? I saw we can bum another containerd patch here :)

/lgtm :-)

**Pull request merged**
