### PR TITLE
Rename separate_pull_cgroup to image_pull_cgroup

### PR DESCRIPTION
**Pull request by mrunalp**
The current name is more suitable as a boolean whereas we are really expecting a value so renaming
it to image pull cgroup.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Rename the option so it is clearer 

#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?

```release-note
Rename separate_pull_cgroup option to image_pull_cgroup
```

### CODE REVIEW

**Comment by haircommander** [comment]
since this option exists in 1.20, we'll need to mark it as deprecated and support it for a release before dropping it

**Comment by giuseppe** [comment]
> since this option exists in 1.20, we'll need to mark it as deprecated and support it for a release before dropping it

Do we still need to go through the deprecation step considering the feature is marked as EXPERIMENTAL?

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
I like the idea of this PR but it's been long enough with the old name that I think we should leave it as is. If we really want to change the flag name, we should go through the configuration deprecation process

**Pull request closed without merging**
