### PR TITLE
Update the crictl tutorial and simplify a few steps

### PR DESCRIPTION
**Pull request by markusthoemmes**
Signed-off-by: Markus Thömmes <markusthoemmes@me.com>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

1. Update command outputs with actual outputs of a more recent version.
2. Simplify the Redis health check by obtaining the Pod's IP automatically and explicitly calling out where to get it from.
3. Further simplifying the Redis health check by using `ncat` instead of `telnet` to just get a simple command rather than having to deal with an interactive shell.
4. Explicitly state what happens when stopping and removing containers and pods and group the respective check commands with the resource that's being removed.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve

LGTM, thanks @markusthoemmes

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM
but tests aren't happy still, it's always the straight forward "easy" changes that cause the most CI upset it seems.

**Review by kolyshkin — APPROVED** [review]
/lgtm

**Pull request merged**
