### PR TITLE
Make config package public

### PR DESCRIPTION
**Pull request by haircommander**
As there were libraries that relied on it, as well as it's a useful struct for public use.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

**- Description for the changelog**
CRI-O now exposes pkg/config for configuration management

### CODE REVIEW

**Comment by haircommander** [comment]
/cc @runcom 

@mrunalp @umohnani8 @saschagrunert PTAL

**Comment by runcom** [comment]
👍

**Comment by saschagrunert** [comment]
I think after this change we should cherry pick https://github.com/cri-o/cri-o/pull/2875 into the master.

**Pull request merged**
