### PR TITLE
node: log if we are using cgroupv2

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
CRI-O now logs when it is using cgroupv2
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests.

**Review by saschagrunert — APPROVED** [review]
LGTM
/retest

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
