### PR TITLE
[1.19] vendor: bump containers/storage to v1.23.8

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

_(this is a backport of #4334 to 1.19 release branch)_

This is mostly to have containers/storage#757
which should fix occasional CI failures (and probably real failures, too).

#### Which issue(s) this PR fixes:

> time="2020-11-02T19:00:03Z" level=fatal msg="creating container: rpc error: code = Unknown desc = error creating an ID-mapped copy of layer "01d6f430ddfdf1203b505fbb03c6479802a3366609d5e0231a30f85f412f873d": exit status 1: error during chown: storage-chown-by-maps: chown("lib/apk/db/scripts.tar"): lchown lib/apk/db/scripts.tar: interrupted system call"

periodically caught by CI

#### Special notes for your reviewer:

_(this is a backport of #4334 to 1.19 release branch)_

#### Does this PR introduce a user-facing change?

```release-note
Fix occasional "chown: interrupted system call" error on container creation.
```

### CODE REVIEW

**Comment by haircommander** [comment]
I think for 1.19 we should stick to the closest stable branch: https://github.com/containers/storage/tree/v1.20-stable

**Comment by kolyshkin** [comment]
Ah OK; we need a release for that first (1.20.5 or so).

**Comment by kolyshkin** [comment]
Re-implemented with 1.20.5

**Comment by kolyshkin** [comment]
Ahhh, can't reopen this one :)

**Pull request closed without merging**
