### PR TITLE
server: remove exit file in exit monitor

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
Otherwise, the file will leak and fill up `/run`. also, while we're here, cleanup the exit monitor function a bit to be less deep
#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where exit files were never cleaned up from `/run/crio/exits`
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by saschagrunert** [comment]
A friendly reminder that this PR had no activity for 30 days.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
/hold

I hope this version passes openshift e2e, but past ones have yet to

**Comment by haircommander** [comment]
huzzah!

/hold cancel

**Comment by haircommander** [comment]
Failing because we need a go bump
/override ci-integration
/override cI-e2e

**Comment by haircommander** [comment]
/hold

fine I'll fix it for real

**Comment by mrunalp** [comment]
I think we can drop the first commit, otherwise this looks fine.

**Comment by haircommander** [comment]
> I think we can drop the first commit, otherwise this looks fine.

I think I'd prefer to keep it, though I reordered the commits so it makes clear when there's behavior change

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
