### PR TITLE
Removed UpdateContainerStatus function

### LINKED ISSUE #6465: Remove the `UpdateContainerStatus` call when `evented pleg` is enabled
I am still pretty anxious about adding this call. this means for every single pod event there's a corresponding call to `runc state` and all the overhead of managing a new process. We really shouldn't need this call, and if we do, we're not reacting to a container exit correctly, or are sending the event too early

_Originally posted by @haircommander in https://github.com/cri-o/cri-o/pull/6404#discussion_r1049969804_

### PR DESCRIPTION
**Pull request by Omkar0114**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Checking evented_pleg feature's functionality.

#### Which issue(s) this PR fixes:
Fixes #6465

#### Special notes for your reviewer:

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
[evented-pleg failed once](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/7240/pull-ci-cri-o-cri-o-main-ci-e2e-evented-pleg/1694349302530314240)

**Comment by Omkar0114** [comment]
Hi @haircommander, 4 test cases are failing, right? 
1. lint
2. integration
3. space-at-eol
4. e2e-evented-pleg

Can you point me out what approach should I follow to pass these tests?

**Comment by haircommander** [comment]
> lint

`make lint` in the repo should fix or tell you what's wrong
>  integration

`not ok 188 metrics container oom` is a flake, you can ignore it

>  space-at-eol

fixed by lint

> e2e-evented-pleg

this is one we need to worry about. we should retry them and if they continue to fail, we could assume this change is the issue and we need to fix this PR to fix that test

**Comment by Omkar0114** [comment]
Hi @haircommander fixes lint issues, lets try failed test now

**Comment by Omkar0114** [comment]
Hi @haircommander @sohankunkerkar 
What's update on this PR? How can I go ahead with this ? I fixes link issues but e2e event pleg is failing!

**Comment by haircommander** [comment]
it sounds like this is the crux of the issue. We need to debug this failing test and figure out if we can fix it without UpdateContainerStatus :) ideally, we find the situation it's failing and make an integration test to prevent regression. 

@harche @sairameshv do y'all have any cycles to quickly look at the e2e test output and give a synopsis of what's going wrong?

**Comment by harche** [comment]
IIRC, during the development of the evented pleg we had discovered that CRIO wasn't sending the correct status to the kubelet where it generates the kube [pod status from the received events](https://github.com/kubernetes/kubernetes/blob/dbbce2aaba2501d2409e1829be1637a976990e3b/pkg/kubelet/pleg/evented.go#L224). We found that, we if trigger update status in crio before an event is sent, this issue went away, indicating that somewhere the container status wasn't correctly getting updated in crio. 

Simply removing this code block will make those node e2e fail again (they fail, not flake). We need to dig deeper into why the container statuses aren't upto date by the time crio is ready to send the event, until then this was put in as a stop gap solution for evented pleg to make progress.

**Pull request closed without merging**
