### PR TITLE
Add 32bit (386) build to CI pipeline

### PR DESCRIPTION
**Pull request by saschagrunert**
This streamlines our test-image build process by adding a new test
target `make test-images`. The target utilizes a new image build script
on top of buildah to have a unique container image for every
configuration.

We now build three images:

- A standard image with the latest go version for amd64
- An image containing the latest go version for 386 (32bit)
- A legacy image containing go1.10 and amd64

We're now free to add any logic and test to the script as we want for
any future architecture or go version.

Needs to be merged after: https://github.com/cri-o/cri-o/pull/2436

### CODE REVIEW

**Comment by saschagrunert** [comment]
ready for review. @haircommander @mrunalp @rhatdan PTAL.

**Comment by rhatdan** [comment]
LGTM

**Comment by haircommander** [comment]
this is amazing, LGTM

**Comment by haircommander** [comment]
@saschagrunert were you able to push to quay.io/crio ? I think moving images there makes sense to me

**Comment by saschagrunert** [comment]
> @saschagrunert were you able to push to quay.io/crio ? I think moving images there makes sense to me

Yes, it seems that I have no permissions. Can you add my account somehow: https://quay.io/user/saschagrunert ? :innocent:

**Comment by haircommander** [comment]
@saschagrunert you should have gotten an invite!

**Comment by saschagrunert** [comment]
> @saschagrunert you should have gotten an invite!

Thanks! I'll update the Makefile and CircleCI config regarding that.

**Comment by saschagrunert** [comment]
Had to rebase on top of the latest master, PTAL

**Comment by saschagrunert** [comment]
Vendoring fails on the master branch, this PR fixes it as well.

**Comment by saschagrunert** [comment]
G/test integration_rhel

**Comment by saschagrunert** [comment]
:green_heart: tests, PTAL. After that we have to update the toolchain to the latest versions of golang etc.

**Comment by saschagrunert** [comment]
@haircommander just a friendly ping, do you think we can get this in? :)

**Pull request merged**
