### PR TITLE
test: update to new runc behavior

### PR DESCRIPTION
**Pull request by haircommander**
of failing if there are no containers on `runc list`

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Which issue(s) this PR fixes:

/kind ci
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
this is a guess I haven't dug into the code to see what's up, but [here](https://github.com/cri-o/cri-o/pull/5708) it's only failing on runc tests on this line

**Comment by TomSweeneyRedHat** [comment]
1 unhappy test left to make this a really good guess!
LGTM

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
