### PR TITLE
update containers/{image,storage} dependencies

### PR DESCRIPTION
**Pull request by vrothberg**
Pull in the latest version of the c/image and c/storage libraries to
benefit from performance improvements as well as bug fixes.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@vrothberg travis is failing on lint

**Comment by vrothberg** [comment]
@umohnani8 thanks for the ping, will look into it now.

**Comment by rhatdan** [comment]
Needs a rebase.
LGTM

**Comment by vrothberg** [comment]
> Needs a rebase.

Ewww...thanks for ping. Rebased and pushed.

**Comment by vrothberg** [comment]
@mrunalp, do we still need this?

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
