### PR TITLE
Added Gitpod config

### PR DESCRIPTION
**Pull request by JanKoehnlein**
Hi cri-o team! 👋

here is a PR that fully-automates the dev setup of cri-o with Gitpod, providing anyone with a pre-built, browser-based development environment in one click:

[Open in Gitpod](https://gitpod.io/#https://github.com/cri-o/cri-o)

Screen Shot 2021-05-04 at 18 01 53

### What it does

* Comes with all cri-o lifecycle dependencies pre-installed (Go, Docker...)
* Runs `make` ahead-of-time so you don't need to wait
* Gives anyone immediate access to the pre-compiled cri-o, and allows to easily edit & rebuild the code

I hope this can make life easier for contributors, and for maintainers who need to review many PRs (hint: you can already open this PR in Gitpod to easily review & test it without messing up your local checkout).

I'm looking forward to your feedback on this PR! 🚀

```release-note
none
```

### CODE REVIEW

**Comment by JanKoehnlein** [comment]
I don't see how my changes could be related to the failing tests. Could anybody help me?

**Comment by haircommander** [comment]
thanks for the PR btw @JanKoehnlein !

**Comment by haircommander** [comment]
/lgtm

thanks @JanKoehnlein

**Comment by JanKoehnlein** [comment]
It looks like I am cooking your CI.It sends me an email ever hour. I have no idea how to mitigate this.

**Pull request merged**
