### PR TITLE
Workaround on new CA from Ubuntu. Also minor documentation improvemen…

### PR DESCRIPTION
**Pull request by thanos1983**
…t on how to deploy metrics without the need to download the repo.

Signed-off-by: Athanasios Garyfalos <athanasios.garyfalos@maersk.com>

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by thanos1983** [comment]
@haircommander  follow up?

**Comment by haircommander** [comment]
sorry @thanos1983 we can't merge it with all of the merge commits in therre. have you tried using `git rebase` to remove/squash them?

**Pull request closed without merging**
