### PR TITLE
Add a .snyk file to configure the Snyk security scanner

### PR DESCRIPTION
**Pull request by kwilczynski**
#### What type of PR is this?

/kind other
/assign kwilczynski

#### What this PR does / why we need it:

Add a .snyk file to configure the Snyk security scanner.

Why? At the very least, we want to exclude vendored files and tests from being scanned. As for these paths, many false positives are being reported, most of which we can't and won't be fixing.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve

LGTM

**Review by saschagrunert — APPROVED** [review]
/retest

**Pull request merged**
