### PR TITLE
Pin gocapability to v0.0.0-20180916011248-d98352740cb2

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
One day this problem will be fixed
#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where CRI-O can't work with runc 1.0.0-rc93 because of an incorrectly specified list of capabilities
```

### CODE REVIEW

**Comment by haircommander** [comment]
fix https://github.com/cri-o/cri-o/issues/4658#issuecomment-823515468

/cherry-pick release-1.21

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
