### PR TITLE
Exclude failing conntrack e2e test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
This is a workaround until we moved our testing to true multi-node tests
in test-infra (see https://github.com/kubernetes/test-infra/issues/16589).

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
if we decide to get this in to unblock master, let's create an issue to track. I have a feeling it's a legit failure on our part

**Comment by saschagrunert** [comment]
> if we decide to get this in to unblock master, let's create an issue to track. I have a feeling it's a legit failure on our part

Yeah, I think we should move forward to bring the e2e CRI-O tests in test-infra up and running to be able to remove them from here. I started working on this in https://github.com/kubernetes/kubernetes/pull/91209 now.

**Comment by haircommander** [comment]
/lgtm

to unblock master

**Pull request merged**
