### PR TITLE
[1.18] Test for master tag if release branch contains none

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
If the release branch tag contains none then we have to check for the
master branch before giving up. This fixes to have the right version
when creating release branches which contain no actual tag.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
Relates to https://github.com/cri-o/cri-o/pull/3502
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
wait,
/hold
aren't we looking to have the branch-forward-script do this?

**Comment by saschagrunert** [comment]
Yes. Let’s do it via the script.

**Pull request closed without merging**
