### PR TITLE
test: add irqbalance dependency to CI

### PR DESCRIPTION
**Pull request by sohankunkerkar**
#### What type of PR is this?

/kind failing-test
#### Which issue(s) this PR fixes:

fixes issues like https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6750/pull-ci-cri-o-cri-o-main-ci-cgroupv2-integration/1638178252549787648/artifacts/cgroupv2-integration/cri-o-gather/artifacts/testout.txt
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
I wouldn't expect the integration tests to pass yet. the vm rebuild job needs to run after this merges

**Comment by sohankunkerkar** [comment]
> I wouldn't expect the integration tests to pass yet. the vm rebuild job needs to run after this merges

ok, let's get this PR in.

**Pull request merged**
