### PR TITLE
Backport irqbalance handling onto 1.20

### PR DESCRIPTION
**Pull request by jianzzha**
#### What type of PR is this?

> /kind api-change
/kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:

This PR is to backport https://github.com/cri-o/cri-o/pull/4441 to 1.20
 
#### Which issue(s) this PR fixes:

This would manipulate irqbalance service if it's already running on the system to exclude assigned pod CPUs from IRQ balancing.

#### Does this PR introduce a user-facing change?

```release-note
When using high performance hooks, CRI-O now restarts the irqbalance service after updating the irqbalance config file. rather than calling `irqbalance --oneshot`. A new config value `irqbalance_config_file` has been introduced to configure the file to update with `IRQBALANCE_BANNED_CPUS` settings. The default of this config value is `/etc/sysconfig/irqbalance`, but must be set to `/etc/default/irqbalance` for Ubuntu-like distributions.
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/ok-to-test
LGTM

**Comment by saschagrunert** [comment]
@jianzzha thank you for the backport! :pray: Can you please copy/paste the release notes from the original PR, too?

**Comment by jianzzha** [comment]
@saschagrunert: release note pasted.

**Comment by haircommander** [comment]
/lgtm

thanks @jianzzha !

**Pull request merged**
