### PR TITLE
Disable infra container drop on node e2e tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### Which issue(s) this PR fixes:

Refers to https://github.com/cri-o/cri-o/issues/5202
#### Special notes for your reviewer:
It's suspicious that the drop of the infra container corresponds to
fails/flakes of the Kubernetes node e2e tests. With this path we disable
the option for now while bumping the used CRI-O version.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@harche can we manually test if this bump works?

**Comment by haircommander** [comment]
I found that making sure the node was runnning cgroupv1 caused the tests to pass, even when dropping infra. I haven't figured out the cgroupv2 errors though.

**Comment by saschagrunert** [comment]
Rebased the PR to contain runc v1.0.1.

**Comment by saschagrunert** [comment]
As discussed, closing.

**Pull request closed without merging**
