### PR TITLE
Isolate ContainerServer from Server package

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
To be able to refactor further we need to split the ContainerServer from
the Server implementation. This allows us to use the ContainerServer in
the new interface without having the need to rely on the *Server.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
/cc @rhafer 
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
hmhmhm I'm not stoked about the global variable (but sync.Once symantics won't quite work with needing libconfig everytime we call ContainerServer() ). What do you need to call the container server from the sandbox package for?

**Comment by saschagrunert** [comment]
I know, global mutable state is bad. :-/ The Server package calls to the Container Server during sandbox and container creation (and deletion etc.) multiple times. This was fine, since the server had the container server as direct member. The only way to bring an interface in between both is from my perspective the need to decouple them. This seems needed because the new interfaces should never import anything from the server package. 😶

**Comment by saschagrunert** [comment]
Closing for now.

**Pull request closed without merging**
