### PR TITLE
Pin conmon-rs to v0.6.2

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:

Pin the conmon-rs lib to the latest release. This also bumps other dependencies.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kannon92** [comment]
I've been babysitting this for weeks now. https://github.com/cri-o/cri-o/pull/7852

I'm happy to close this one and have you carry the torch. We are sorta stuck due to the crun CI issues we are seeing with updates. I am not sure how to solve these right now though.

**Comment by haircommander** [comment]
/hold 

for 1.31 bump

**Comment by saschagrunert** [comment]
```
# github.com/containers/storage/drivers/overlay
vendor/github.com/containers/storage/drivers/overlay/composefs_notsupported.go:14:6: generateComposeFsBlob redeclared in this block
	vendor/github.com/containers/storage/drivers/overlay/composefs.go:39:6: other declaration of generateComposeFsBlob
vendor/github.com/containers/storage/drivers/overlay/composefs_notsupported.go:18:6: mountComposefsBlob redeclared in this block
	vendor/github.com/containers/storage/drivers/overlay/composefs.go:128:6: other declaration of mountComposefsBlob
```

**Comment by saschagrunert** [comment]
Part of https://github.com/cri-o/cri-o/pull/8144

**Pull request closed without merging**
