### PR TITLE
Remove `crio-status` binary

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind deprecation

#### What this PR does / why we need it:
We deprecated the subcommand in v1.28 and now can remove it.
#### Which issue(s) this PR fixes:

Follow-up on https://github.com/cri-o/cri-o/pull/6557

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Removed `crio-status` binary in favor of the `crio status` subcommand.
```

### CODE REVIEW

**Review by sohankunkerkar — APPROVED** [review]

**Comment by haircommander** [comment]
failures are legit--we need to update the script that builds CRI-O from source cc @sohankunkerkar

**Comment by saschagrunert** [comment]
> failures are legit--we need to update the script that builds CRI-O from source cc @sohankunkerkar

Found them in the cri-o.spec.

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL again

**Pull request merged**
