### PR TITLE
remove dead code

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind ci
/kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### Special notes for your reviewer:
I fell down a rabbit hole...

found using staticcheck:
`staticcheck -tags=test --unused.whole-program=true   -- ./...`
(an old version though `go get honnef.co/go/tools/cmd/staticcheck@v0.0.1-2020.1.4`)

I did not remove all the dead code. some code we've adapted from other repos, and don't use some fields. I think it's worth keeping them. I have also left some functions that are not used in the code base, but are useful in tests (container_server HasSandbox is an example)
 
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM 
assuming happy tests.

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by mrunalp — APPROVED** [review]

**Comment by haircommander** [comment]
/override ci/prow/e2e-agnostic
(passed on gcp)

**Pull request merged**
