### PR TITLE
test/c*: cleanups

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Various cleanups to
 - simplify code;
 - make it pass shellcheck.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
Look ma, green CI :man_dancing:

**Review by saschagrunert — APPROVED** [review]
I'll take it while it's still hot!
/lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM
but me thinks you spoke too soon on the green status...

**Pull request merged**
