### PR TITLE
[1.16] Bump image 5.4.4 1.16

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

 /kind dependency-change

#### What this PR does / why we need it:
bumps to c/image 5.4.4 to get platform matching fixes
#### Special notes for your reviewer:
currently carrying https://github.com/cri-o/cri-o/pull/3795
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM
unit-tests is complaining about tree being dirty

**Comment by saschagrunert** [comment]
@haircommander can you try to run `make vendor` with the go version specified in the release-1.16 branch's go.mod?

**Comment by haircommander** [comment]
the issue was the mockgen task was using go 1.13, and the vendor task was using 1.12. I have updated both to 1.13, because it's a simpler fix :slightly_smiling_face:

**Comment by haircommander** [comment]
happy tests PTAL @umohnani8 @mrunalp @saschagrunert

**Pull request merged**
