### PR TITLE
OWNERS: add sohankunkerkar to cri-o-reviewers

### PR DESCRIPTION
**Pull request by sohankunkerkar**
I'm nominating myself for the cri-o-reviewers after discussing it with @haircommander 

#### What type of PR is this?

/kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve

Thanks for all of your work, +1 from me!

**Review by saschagrunert — APPROVED** [review]
/retest

**Pull request merged**
