### PR TITLE
systemd: use on-failure as restart policy

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the last unhappy test is fixed up.

**Comment by haircommander** [comment]
I think we should not go this route actually

**Pull request closed without merging**
