### PR TITLE
[1.14] Add username and homedir to generated password

### PR DESCRIPTION
**Pull request by mrunalp**
When generating a an entry in the /etc/passwd file, we
need to also add username and homedir, so that the user
can properly login.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

Port of #2325

### CODE REVIEW

**Comment by saschagrunert** [comment]
It looks like we have to make some lint and code adaptions to let the CI pass.

**Comment by cgwalters** [comment]
Hm, so this logic to change `/etc/passwd` only exists in crio and not podman?

**Comment by mrunalp** [comment]
@mheon Can you look into making sure that podman has this logic as well?

**Comment by haircommander** [comment]
everything but codecov is green, manually merging

**Comment by mrunalp** [comment]
Pushed the tag :+1:

**Comment by rhatdan** [comment]
@cgwalters Podman should have this functionality as well.

**Pull request merged**
