### PR TITLE
[1.18] storage: disable fdatasync() for atomic writes and bump c/storage to v1.19.2

### PR DESCRIPTION
**Pull request by giuseppe**
#### What type of PR is this?

> /kind api-change
/kind bug
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### What this PR does / why we need it:

drop unuseful fdatasync calls

#### Which issue(s) this PR fixes:

fewer writes to the disk

#### Special notes for your reviewer:

I am vendoring a custom containers/storage branch (github.com/giuseppe/storage no-sync).

PR for containers/storage: containers/storage#620

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by giuseppe** [comment]
@umohnani8 @haircommander @mrunalp ready to ship :-)

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
