### PR TITLE
[1.21] Fix podman name in README

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

#### What type of PR is this?

/kind cleanup

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by mrunalp** [comment]
Opened to check e2e status

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
LOL (e2es passed,fwiw)
/lgtm

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
