### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

#### What type of PR is this?

> /kind feature

#### Does this PR introduce a user-facing change?

```release-note
Update nix pin with `make nixpkgs`
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
