### PR TITLE
Update golang dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Update all golang dependencies to their latest version.
#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
containers/common cannot be upgraded right now due to compatibility issues with buildah (should be resolved with the next buildah release)

**Comment by saschagrunert** [comment]
Quay is down :shrug:

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by saschagrunert** [comment]
Let me just rebase again, I'd like to debug our CI issues.

**Comment by saschagrunert** [comment]
Okay so coredns does not become healthy... *sigh*

**Comment by saschagrunert** [comment]
Looks like we're encountering a new failure: 
```
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:549
May 28 10:49:51.120: Expected
    <string>: 
to contain substring
    <string>: stdin closed
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:573
```

**Pull request merged**
