### PR TITLE
[1.21] bump to 1.21.4

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind documentation

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
we apparently needed https://github.com/cri-o/cri-o/pull/5384, hopefully that does it

**Comment by haircommander** [comment]
okay it's fixed for real this time
@cri-o/cri-o-maintainers PTAL

**Review by QiWang19 — COMMENTED** [review]
/lgtm

**Pull request merged**
