### PR TITLE
[1.15] bump to containers storage 1.13.6

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by haircommander** [comment]
this one is bumping two sub-minor versions (1.13.4->1.13.6), but 1.14 was on 1.13.5, so we must have missed getting that into 1.15. updating here.

**Comment by rhatdan** [comment]
@haircommander Do we still want/need this?

**Comment by haircommander** [comment]
1.15 is on 1.13.7 now

**Pull request closed without merging**
