### PR TITLE
Add missing config template values

### PR DESCRIPTION
**Pull request by saschagrunert**
Add missing `insecure_registries` and `bind_mount_prefix` to config template.

### CODE REVIEW

**Comment by rhatdan** [comment]
The only thing with this, is we should tell the user that we would prefer that they make registries changes in registries.conf rather then in crio.conf.  That way the other tools, skopeo, Podman, Buildah will follow the rules. If you change just crio.conf the other tools have no idea.

**Comment by saschagrunert** [comment]
> The only thing with this, is we should tell the user that we would prefer that they make registries changes in registries.conf rather then in crio.conf. That way the other tools, skopeo, Podman, Buildah will follow the rules. If you change just crio.conf the other tools have no idea.

Alright, I changed the message to take `/etc/containers/registries.conf` into account before using `insecure_registries`.

**Comment by saschagrunert** [comment]
Found some more missing entries in `docs/crio.conf.5.md`, PTAL.

**Pull request merged**
