### PR TITLE
storage: disable fdatasync() for atomic writes and bump c/storage to v1.19.2

### PR DESCRIPTION
**Pull request by giuseppe**
#### What type of PR is this?

> /kind api-change
/kind bug
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### What this PR does / why we need it:

drop unuseful fdatasync calls

#### Which issue(s) this PR fixes:

fewer writes to the disk

#### Special notes for your reviewer:

I am vendoring a custom containers/storage branch (github.com/giuseppe/storage no-sync).

PR for containers/storage: https://github.com/containers/storage/pull/620

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mrunalp** [comment]
@giuseppe mind opening a release-1.18 PR to get e2e-aws run data as well? Thanks!

**Comment by giuseppe** [comment]
> @giuseppe mind opening a release-1.18 PR to get e2e-aws run data as well? Thanks!

opened here: https://github.com/cri-o/cri-o/pull/3750

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM.  If you could add "Bump c/storage to v1.19.2" or some such to the title, that would be appreciated.

**Comment by giuseppe** [comment]
how to restart circleci?

**Comment by haircommander** [comment]
retriggered

**Pull request merged**
