### PR TITLE
Support passing properties to RunUnderSystemScope

### PR DESCRIPTION
**Pull request by mrunalp**
This allows callers to set properties such as CollectMode.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

#### What type of PR is this?

/kind api-change

#### What this PR does / why we need it:
This PR adds functionality to pass properties to systemd scope creation utility function

#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?
No

```release-note
None
```

### CODE REVIEW

**Comment by mrunalp** [comment]
@giuseppe @saschagrunert ptal

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Pull request merged**
