### PR TITLE
[1.19] gh actions: fix workflow

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

/kind ci

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
@QiWang19 @wgahnagl @fgiudici PTAL

**Comment by QiWang19** [comment]
LGTM

**Review by fgiudici — APPROVED** [review]
LGTM!

**Comment by haircommander** [comment]
merge me please @wgahnagl @QiWang19 @fgiudici

**Pull request merged**
