### PR TITLE
WIP: Vendor/test containers/storage store load lock branch

### PR DESCRIPTION
**Pull request by saschagrunert**
For testing purposes of https://github.com/containers/storage/pull/493

### CODE REVIEW

**Comment by haircommander** [comment]
@saschagrunert do we still need this?

**Comment by saschagrunert** [comment]
> @saschagrunert do we still need this?

No, but let's keep it open until the PR in containers/storage got merged to keep it as a reminder. :)

**Comment by saschagrunert** [comment]
Took the integration test fix (https://github.com/cri-o/cri-o/pull/3161) on top of that change to see if anything else breaks.

**Pull request closed without merging**
