### PR TITLE
Remove duplicate check for enabled seccomp

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We already test for the availability of seccomp in `setupSeccomp()` so
we can remove the additional check.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons

**Comment by kolyshkin** [comment]
The code being removed was introduced by commit 44e7e88ff365da02237e672762f88bf53891585c (PR #368).

The setupSeccomp() call was added earlier (commit 78ee03a8fc, PR #211), and is only called when the container is not privileged.

Question is: can we still run a privileged container using cri-o compiled with seccomp on a seccomp-less machine?

**Comment by saschagrunert** [comment]
> Question is: can we still run a privileged container using cri-o compiled with seccomp on a seccomp-less machine?

Tested it locally with the (modified to `unconfined`) `test/testdata/sandbox_config_seccomp.json` and the code path ends up in https://github.com/cri-o/cri-o/blob/1c4d633661888bd6f3cd19cd130e9cfc3d4cf426/server/container_create.go#L616

**Pull request merged**
