### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
This is the weekly module update PR, this time with indirect dependencies included. This is necessary because some projects are now converted to use go modules and we would never get rid of these indirect dependencies when not updating them manually.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by mrunalp** [comment]
I think that we should make these update dependency PRs single commits.

**Comment by saschagrunert** [comment]
> I think that we should make these update dependency PRs single commits.

Alright, so I will squash them together and keep the details in the commit message if this fits better your needs.

**Pull request merged**
