### PR TITLE
add crio --profile test

### PR DESCRIPTION
**Pull request by kolyshkin**
/kind bug

(NB: why don't we have kind: ci?)

#### What this PR does / why we need it:

Adds a CI integration test to make sure crio --profile works

#### Which issue(s) this PR fixes:

This is a followup to #4011, addressing the https://github.com/cri-o/cri-o/pull/4016#issuecomment-663587938

```release-note
NONE
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
CI failures look unrelated

**Comment by mrunalp** [comment]
This looks fine. You want to remove the wip?

**Comment by kolyshkin** [comment]
yes, it's no longer a wip, forgot to remove the label

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
