### PR TITLE
conmon: fix cross-compilation

### PR DESCRIPTION
**Pull request by haircommander**
Update the function stub for printing to the journal

Fixes: #2327

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by saschagrunert** [comment]
LGTM, but we have to fix the CI pipeline before in https://github.com/cri-o/cri-o/pull/2329

**Comment by haircommander** [comment]
@mrunalp @umohnani8 @rhatdan ptal

**Pull request merged**
