### PR TITLE
[1.16] Add shell completion support

### PR DESCRIPTION
**Pull request by saschagrunert**
Cherry pick of https://github.com/cri-o/cri-o/pull/2835

### CODE REVIEW

**Comment by saschagrunert** [comment]
Rebased on top of the latest release-1.16 branch. I moved the completion package into the criocli package. I'll do this for the master as well.

**Comment by saschagrunert** [comment]
Note: After this one https://github.com/cri-o/cri-o/pull/2870/files can be cherry picked

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Pull request merged**
