### PR TITLE
Enable debug logs for release notes generation

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This helps to debug any issues we encounter within the CI.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by fidencio** [comment]
LGTM

**Comment by saschagrunert** [comment]
/retest

@haircommander the pipeline seems now to succeed...maybe the circle job terminated because of a GitHub flake/timeout?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by haircommander** [comment]
/retest
/lgtm

I fear the tests are borked upstream :\

**Pull request merged**
