### PR TITLE
Fix typo in install.md

### PR DESCRIPTION
**Pull request by discordianfish**
#### What type of PR is this?

/kind documentation

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve

LGTM, thank you @discordianfish 

@TomSweeneyRedHat @wgahnagl @fgiudici @fidencio @QiWang19 PTAL

**Review by fgiudici — APPROVED** [review]
LGTM, thanks!

**Comment by haircommander** [comment]
/override ci/prow/e2e-gcp
/override ci/prow/e2e-agnostic

(docs only fix)

**Pull request merged**
