### PR TITLE
Move docs and completions validation to GitHub actions

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
Both CircleCI are now running in GitHub actions, whereas a pipeline
passes the build artifacts to those new jobs.
#### Which issue(s) this PR fixes:

Refers to #4489 
#### Special notes for your reviewer:
Example run can be already found in the pipeline below.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
But I'm not at all a subject heavy for these kinds of changes.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
