### PR TITLE
Add arm64 static builds to v1.20 release.

### LINKED ISSUE #4717: Download Links for Release `v1.20.2` are Unavailable
**Description**

The download links for tagged release `v1.20.2` do not contain any artifacts, (e.g. The specified key does not exist.). Additionally, there are no `arm64` bundles available on the GitHub release page for `v1.20.2`.

**Steps to reproduce the issue:**
1. Go to the Releases page on GitHub.
2. Click on the downloads links: ( https://storage.googleapis.com/k8s-conform-cri-o/artifacts/cri-o.arm64.d5a999ad0a35d895ded554e1e18c142075501a98.tar.gz ).

**Describe the results you received:**
No such object: k8s-conform-cri-o/artifacts/cri-o.amd64.d5a999ad0a35d895ded554e1e18c142075501a98.tar.gz

**Describe the results you expected:**
A file is available for download.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `crio --version`:**
N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

### PR DESCRIPTION
**Pull request by nerditup**
> /kind ci

#### What this PR does / why we need it:

Adds arm64 static builds to v1.20 releases.

#### Which issue(s) this PR fixes:

Fixes #4717

#### Special notes for your reviewer:

A similar commit has been merged for v1.21 releases,
https://github.com/cri-o/cri-o/commit/4ff8662ffbb9c570fbd668b18671a46af42dac26#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test

thanks @nerditup LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by nerditup** [comment]
@TomSweeneyRedHat @haircommander - I'm unsure why I am getting this error in the `critest` job: 
```
failed to pull image: rpc error: code = Unknown desc = Error parsing image configuration: Error fetching blob: invalid status code from registry 403 (Forbidden)
```
I don't believe I made any changes that would cause any permission changes. Would either of you know why? Or tag someone who would be able to help here?

Reference job/error:
https://github.com/cri-o/cri-o/runs/2270709980?check_suite_focus=true#step:8:300

**Comment by haircommander** [comment]
cri test failures are not the fault of this PR FYI

**Comment by nerditup** [comment]
Ah, thank you for confirming @haircommander. I believe all of the changes I was hoping to put into this PR are implemented, I'm not sure how we would like to proceed in producing the artifacts? Do we need to tag this as a new release version even though it's just infra changes?
```
Skipping artifact upload to Google Cloud Bucket (no $GCS_BUCKET_SA set)
Skipping artifact upload to GitHub (not on a tag)
```

**Comment by saschagrunert** [comment]
> Do we need to tag this as a new release version even though it's just infra changes?

Yes, because PRs will not produce output artifacts

**Comment by nerditup** [comment]
Thanks @saschagrunert, what can I do to help getting this tagged and merged? I don't believe I am able to since I'm not a member of the CRI-O GitHub organization.

**Comment by haircommander** [comment]
/override ci/openshift-jenkins/critest_fedora 
/override ci/openshift-jenkins/critest_rhel
/test e2e_crun
/approve

LGTM, deferring to @saschagrunert for the final merge

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
