### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Updating all of our golang dependencies
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/test e2e-agnostic
/approve

LGTM

@kolyshkin @umohnani8 @mrunalp @QiWang19 @giuseppe PTAL

**Comment by saschagrunert** [comment]
e2e seems broken…

**Comment by saschagrunert** [comment]
Had to rebase to fixup the build issue

**Pull request merged**
