### PR TITLE
RFC: Use RuntimeContainerMetadata for passing container data

### PR DESCRIPTION
**Pull request by mtrmac**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The parameters to `createContainerOrPodSandbox` pass, individually, all but 2 fields of `RuntimeContainerMetadata`. Using a struct, where the parameters are named, seems much more readable, right now - OTOH that might depend on how the function API vs. metadata JSON format evolves.

Should not change behavior.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Just because I was working in this area.

I’m not at all sure the metadata struct and the parameters are going to remain so similar; it’s quite possible this is a bad idea, I’m perfectly fine with this PR being rejected.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
great idea!

/approve

LGTM, thanks

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/ok-to-test

**Pull request merged**
