### PR TITLE
migrate image_list to quay.io

### PR DESCRIPTION
**Pull request by rphillips**
Migrates more images to quay.io

```release-note
NONE
```

### CODE REVIEW

**Comment by haircommander** [comment]
/hold

I'm not sure this is working

**Comment by rphillips** [comment]
Thanks @haircommander. I updated the hashes once more... let's see if that helps.

**Comment by rphillips** [comment]
Looks like that might have helped. PR needs a lgtm. Were the extra retests for another flake or docker.io image I missed?

/hold cancel

**Comment by haircommander** [comment]
It was for ci-integration, though I didn't look into why it failed

/lgtm

**Pull request merged**
