### PR TITLE
[1.20] Revert "Set systemd property KillMode to mixed for containers"

### PR DESCRIPTION
**Pull request by mrunalp**
This reverts commit 8164338edc9677b7a14710d3959168e0a2f32636 (PR #4539).

https://bugzilla.redhat.com/show_bug.cgi?id=1925623

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

#### What type of PR is this?

/kind bug

#### Does this PR introduce a user-facing change?

```release-note
Revert systemd KillMode to control-group (default)
```

### CODE REVIEW

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
we're waiting on one possible avenue before removing this hold

**Pull request merged**
