### PR TITLE
config: add /dev/net/tun to default allowed devices

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
to help users run podman inside of containers
#### Does this PR introduce a user-facing change?

```release-note
config: add /dev/net/tun to default allowed devices
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by kwilczynski** [comment]
@haircommander, do you want this also in 1.29 and 1.28?

**Comment by haircommander** [comment]
I think just here is fine for now unless someone asks for it

**Pull request merged**
