### PR TITLE
Add missing EnvVars to command line interface

### PR DESCRIPTION
**Pull request by saschagrunert**
Some commands where missing the newly introduced `EnvVar` flag, which is
now complete again.

This fixes an inconsistency between `CONTAINERS_REGISTRIES_CONF` and
`CONTAINER_REGISTRIES_CONF` as well.

Cherry-picked: 58e4d6f864dd59f2188812927e5fc71d8b4f84d6

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by saschagrunert** [comment]
r/test integration_rhel

**Pull request merged**
