### PR TITLE
upgrade runc to v1.1.15

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind dependency-change

#### What this PR does / why we need it:
Upgrade runc to latest patch.
#### Does this PR introduce a user-facing change?

```release-note
upgrade runc to v1.1.15
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
Looks like we need to fix the gather logs script to scrape logs only when the _artifact folder is present. That change is recently added for e2e-node-test.

**Comment by sohankunkerkar** [comment]
https://github.com/openshift/release/blob/master/ci-operator/step-registry/cri-o/gather/cri-o-gather-commands.sh#L25

**Comment by sohankunkerkar** [comment]
https://github.com/openshift/release/pull/57774

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
