### PR TITLE
Update e2e-aws logic for 4.8

### PR DESCRIPTION
**Pull request by QiWang19**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:
Update e2e-aws logic for 4.8
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by QiWang19** [comment]
WIP until the ci gets fixed.

**Comment by mrunalp** [comment]
Let us get this in. The e2e-gcp failures need to be chased down on master/1.21.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
