### PR TITLE
oci: Fix a couple of deadlocks in container stop code

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
for reference, we have a [goroutine stack](https://bugzilla.redhat.com/attachment.cgi?id=1838992) that has a ridiculous number of go routines stuck on [this line](https://github.com/cri-o/cri-o/blob/2e9a7119f763fb1f4e3eb0aeef15a7132a869602/internal/oci/oci.go#L144)

While this more seems like the go routine didn't receive correctly on the close of chControl, adding the buffer would also let the function make forward progress. i.e. I am suspecting something funky about the go runtime, but maybe we can work around it?

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
so I didn't actually know why this could work but I guessed it would. looking at https://github.com/cri-o/cri-o/blob/main/internal/oci/oci.go#L139-L146
```
			case <-chControl:
				return
			default:
				// Check if the container is stopped
				if err := impl.UpdateContainerStatus(ctx, c); err != nil {
					done <- err
					return
				}
				if c.State().Status == ContainerStateStopped {
					done <- nil
					return
				}
```
if chControl is closed while UpdateContainerStatus is running, we will wait forever on done, when we should check chControl. buffering the channel will allow us to make forward progress (without really complicating the code that much)

**Comment by haircommander** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by haircommander** [comment]
related to https://bugzilla.redhat.com/show_bug.cgi?id=2003206

**Pull request merged**
