### PR TITLE
Avoid potential reallocs by pre-sizing some slices

### PR DESCRIPTION
**Pull request by fengshunli**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

By so pre-size these to avoid any reallocs to a higher capacity.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by kwilczynski** [comment]
@fengshunli, how did you come across this specific case? Code review? Some static analysis tool?

I am positive there are other such cases throughout the code base, for sure.

**Comment by fengshunli** [comment]
Code review found @kwilczynski

**Comment by fengshunli** [comment]
What is the reason why this CI failed? Do I need to modify anything? @kwilczynski  @saschagrunert

**Pull request merged**
