### PR TITLE
[release-1.24] resource store: save stage of resource creation and report to callers

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind feature
#### Does this PR introduce a user-facing change?

```release-note
CRI-O now logs the stage of container or pod creation under system load. This allows users to find why their creation requests are stalling.
```

### CODE REVIEW

**Comment by haircommander** [comment]
cherry-pick of https://github.com/cri-o/cri-o/pull/6238

**Comment by haircommander** [comment]
@saschagrunert PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
