### PR TITLE
go.{mod,sum}: update CDI dependency to v0.3.2.

### PR DESCRIPTION
**Pull request by klihub**
Pin container-device-interface dependencies to the latest version tagged in upstream.

#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:

Pins container-device-interface dependencies to the latest tagged version in upstream.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve
thanks!

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
just one unhappy test away from a clean slate!

**Comment by klihub** [comment]
> Changes LGTM just one unhappy test away from a clean slate!

Is there a trick that mere mortals could use to trigger rerunning just that failed workflow ? I can't do it the way I'm used to (from the workflow list/view, because I guess I'm lacking some of the prerequisite rights). Is sledge-hammering it to rerun all with a new force-push the only way ?

**Comment by haircommander** [comment]
for gh actions they've added the option to only rerun failed tests. prow (`/retest`) doesn't touch the github actions tests
regardless, the test that failed is a classicly flaky one

/lgtm

**Pull request merged**
