### PR TITLE
Fix validate-completions GitHub action

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
The already pre-installed storage.conf has unwanted influence on the test results. This means we now remove it in the same way we do in the other validation test.
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mrunalp** [comment]
@aojea We are failing on the new test https://prow.ci.openshift.org/view/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/4524/test_pull_request_crio_e2e_fedora/22522/

**Comment by haircommander** [comment]
those failed with
```
Kubernetes e2e suite: [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]
```
which *may* be related to https://github.com/kubernetes/kubernetes/pull/98299
[xref](https://prow.ci.openshift.org/view/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/4524/test_pull_request_crio_e2e_fedora/22519/)

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
