### PR TITLE
[1.19] Add logic for running openshift e2e-aws tests

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

#### What type of PR is this?

/kind failing-test

Not a failing test, but adding a new test.

#### What this PR does / why we need it:
Add the various specfile and Dockerfile needed to run the e2e-aws tests on PRs in the release-1.19 branch.

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by umohnani8** [comment]
@mrunalp @haircommander PTAL

**Comment by haircommander** [comment]
other than the shellcheck saddness LGTM

**Comment by mrunalp** [comment]
@umohnani8 Looks like the shell scripts being added are copied over from OpenShift? I am okay if we skip running shellcheck on those.

**Comment by umohnani8** [comment]
@mrunalp yeah they are.

**Comment by haircommander** [comment]
unit test flake fixed [here](https://github.com/cri-o/cri-o/pull/3839)

**Pull request merged**
