### PR TITLE
force clone critools

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind ci

#### What this PR does / why we need it:
Force clone cri-tools as we are hitting a cache bug where we are still using 1.28.0
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Comment by kannon92** [comment]
@sohankunkerkar @saschagrunert @haircommander 

I think the GCP flakes have resolved themselves so this PR should be ready to merge. Just need an approve label.

**Comment by kannon92** [comment]
@haircommander can I get a lgtm when you get a chance?

**Pull request merged**
