### PR TITLE
Fixed cidr standard net in documentation

### PR DESCRIPTION
**Pull request by kubealex**
cri-o bridge default subnet is 10.85.0.0 now, as per
https://github.com/cri-o/cri-o/blob/master/contrib/cni/10-crio-bridge.conf

What type of PR is this?
/kind documentation

What this PR does / why we need it:
Cleanup docs

### CODE REVIEW

**Comment by kubealex** [comment]
Done

**Comment by kubealex** [comment]
> /retest 

Please tell me if I have to di something else to unlock the situation.. master was aligned when i pushed.

**Comment by saschagrunert** [comment]
> > /retest
> 
> Please tell me if I have to di something else to unlock the situation.. master was aligned when i pushed.

No worries, there will be always some kind of test-flakyness because we’re testing a against the Kubernetes master branch. Your change should not introduce any regression. :)

**Comment by haircommander** [comment]
/lgtm
Thanks for the PR and your patience keeping the robots happy!

**Pull request merged**
