### PR TITLE
go.mod: update github.com/containerd/nri to 0.3.0.

### PR DESCRIPTION
**Pull request by klihub**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:

Update NRI dependency to the latest tagged version.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
/override ci/prow/e2e-gcp-ovn
/override ci/prow/e2e-aws-ovn

Thank you!

**Review by saschagrunert — APPROVED** [review]
/ok-to-test

**Comment by saschagrunert** [comment]
The static builds are being fixed in https://github.com/cri-o/cri-o/pull/6684

**Comment by klihub** [comment]
@saschagrunert Once #6684 goes in, I'll rebase this once more on main/HEAD.

Then once we're happy with things, I could file a backport PR against 1.26 with also #6645 and #6648 (the NRI integration fixes) included. @haircommander WDYT ?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by haircommander** [comment]
/override ci/prow/e2e-gcp-ovn
/override ci/prow/e2e-aws-ovn
/override ci/prow/ci-cgroupv2-integration
/override ci/prow/ci-fedora-integration
/lgtm

integration tests are failing because of https://github.com/cri-o/cri-o/pull/6705, so are unrelated

**Pull request merged**
