### PR TITLE
bundle: bump to conmon 2.1.6

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
(submitting this now to test conmon on cgroupv2 to make sure we didn't break anything, then I'll cut a conmon, and bump this version)

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
