### PR TITLE
container: move some relatively low hanging options

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Further the work moving contents of createPodSandbox() to the container pkg. These options were only a couple of lines each, most of the changes come from adding unit tests for the cases.
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM

**Comment by haircommander** [comment]
can someone throw me a lgtm
@saschagrunert @mrunalp

**Pull request merged**
