### PR TITLE
Update nix image and dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
This updates all nix package dependencies used for static builds. The
image is now available on the official CRI-O quay account as well.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
All kinds of test unhappiness @saschagrunert

**Comment by haircommander** [comment]
we seem to be hitting https://github.com/golang/go/issues/34085 :'(

**Comment by saschagrunert** [comment]
> we seem to be hitting [golang/go#34085](https://github.com/golang/go/issues/34085) :'(

I'll try something on https://github.com/cri-o/cri-o/pull/2957, I don't think that we have to download these dependencies by ourself.

**Comment by umohnani8** [comment]
LGTM
@saschagrunert please rebase

**Comment by saschagrunert** [comment]
> LGTM
> @saschagrunert please rebase

Rebased on top of the latest master branch.

**Pull request merged**
