### PR TITLE
config: use deep equal to compare workloads and runtimes

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

> /kind api-change
/kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:
otherwise, changing the runtime path doesn't print a new config
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Changes LGTM, but let's add some unit tests for `runtimesEqual` and `workloadsEqual`

**Comment by TomSweeneyRedHat** [comment]
LGTM
once @saschagrunert concerns are addressed

**Review by saschagrunert — APPROVED** [review]

**Comment by haircommander** [comment]
gcp passed
/override ci/prow/e2e-agnostic

**Pull request merged**
