### PR TITLE
Cleanup install docs

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Only use the new packaging repository and remove all legacy instructions since 1.27 is EOL.

#### Which issue(s) this PR fixes:

Fixes https://github.com/cri-o/cri-o/issues/8358
#### Special notes for your reviewer:
cc @SimonBaeumer
#### Does this PR introduce a user-facing change?

```release-note
Updated documentation to not mention legacy installation instructions any more.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Refers to https://github.com/cri-o/cri-o/issues/8353

**Comment by kwilczynski** [comment]
/hold

Please remove when it's time to merge.

**Comment by afbjorklund** [comment]
It could need some documents on how to install from binaries, similar to `dl.k8s.io`

**Comment by saschagrunert** [comment]
> It could need some documents on how to install from binaries, similar to `dl.k8s.io`
> 
> Then those binaries could still be used, after their package "wrappers" have expired.

Are you referring to this section: https://github.com/cri-o/cri-o?tab=readme-ov-file#installing-cri-o ?

We may wanna move it over to https://github.com/cri-o/packaging as well.

**Comment by afbjorklund** [comment]
I just meant that using binaries is currently the workaround for removed k8s packages.

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by kwilczynski** [comment]
Still looks good!

/approve
/lgtm

**Comment by afbjorklund** [comment]
> It could need some documents on how to install from binaries, similar to `dl.k8s.io`

Never mind, it was all in the script: https://raw.githubusercontent.com/cri-o/packaging/main/get

**Comment by saschagrunert** [comment]
> > It could need some documents on how to install from binaries, similar to `dl.k8s.io`
> 
> Never mind, it was all in the script: https://raw.githubusercontent.com/cri-o/packaging/main/get

Let's discuss in https://github.com/cri-o/cri-o/issues/8353 if there is anything else left open.

**Pull request merged**
