### PR TITLE
Fix container status for HostToContainer propagation

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/cri-o/cri-o/issues/5916

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — COMMENTED** [review]
Changes LGTM, can we add a bats integration test for this scenario?

**Comment by harche** [comment]
> Changes LGTM, can we add a bats integration test for this scenario?

There aren't any bats test covering that code path. Do you have a pointer on how to add a host volume to the sandbox/container json that uses HostToContainer like propagation. i.e. I am looking for how to translate this pod yaml,

```yaml 
apiVersion: v1
kind: Pod
metadata:
  name: proapagate-pod
spec:
  volumes:
  - name: host
    hostPath:
      path: /
  containers:
    - name: propagate-pod
      image: nginx
      securityContext:
        privileged: true
      volumeMounts:
       - name: host
         mountPath: /host
         mountPropagation: HostToContainer
```
to sandbox/container.json used by bats test. 

Also, I was wondering if this scenario can be tested with bats at all. The main issue here was, crio dumps volume information in container annotations.
```
$ cat crio_inspect_propogate_pod.log | jq .info.runtimeSpec.annotations[\"io.kubernetes.cri-o.Volumes\"]

"[{\"container_path\":\"/host\",\"host_path\":\"/\",\"readonly\":false},{\"container_path\":\"/etc/hosts\",\"host_path\":\"/var/lib/kubelet/pods/589373e7-2ed6-4b92-b4fc-8e49fcf02b0a/etc-hosts\",\"readonly\":false},{\"container_path\":\"/dev/termination-log\",\"host_path\":\"/var/lib/kubelet/pods/589373e7-2ed6-4b92-b4fc-8e49fcf02b0a/containers/propagate-pod/e47dba22\",\"readonly\":false},{\"container_path\":\"/var/run/secrets/kubernetes.io/serviceaccount\",\"host_path\":\"/var/lib/kubelet/pods/589373e7-2ed6-4b92-b4fc-8e49fcf02b0a/volumes/kubernetes.io~projected/kube-api-access-rdrxf\",\"readonly\":true}]"
```

 In that volume information mount propagation and selinux related info was missing. Once we started adding that missing info, and started reading it while constructing a response to get container status the issue was fixed.

**Comment by saschagrunert** [comment]
Going for a critest update in https://github.com/kubernetes-sigs/cri-tools/pull/946

**Comment by harche** [comment]
> @harche: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/openshift-jenkins/integration_crun_cgroupv2	[b296ed3](https://github.com/cri-o/cri-o/commit/b296ed3276034100ebb6a96ac4ab42c7e0351b1b)	[link](https://prow.ci.openshift.org/view/gs/origin-federated-results/pr-logs/pull/cri-o_cri-o/5981/test_pull_request_crio_integration_crun_fedora_cgroupv2/9394/)	false	`/test integration_cgroupv2`
> ci/openshift-jenkins/integration_rhel	[b296ed3](https://github.com/cri-o/cri-o/commit/b296ed3276034100ebb6a96ac4ab42c7e0351b1b)	[link](https://prow.ci.openshift.org/view/gs/origin-federated-results/pr-logs/pull/cri-o_cri-o/5981/test_pull_request_crio_integration_rhel/27469/)	true	`/test integration_rhel`
> ci/openshift-jenkins/integration_fedora	[b296ed3](https://github.com/cri-o/cri-o/commit/b296ed3276034100ebb6a96ac4ab42c7e0351b1b)	[link](https://prow.ci.openshift.org/view/gs/origin-federated-results/pr-logs/pull/cri-o_cri-o/5981/test_pull_request_crio_integration_fedora/26744/)	true	`/test integration_fedora`
> ci/openshift-jenkins/integration_crun	[b296ed3](https://github.com/cri-o/cri-o/commit/b296ed3276034100ebb6a96ac4ab42c7e0351b1b)	[link](https://prow.ci.openshift.org/view/gs/origin-federated-results/pr-logs/pull/cri-o_cri-o/5981/test_pull_request_crio_integration_crun_fedora/18775/)	true	`/test integration_crun`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=cri-o&repo=cri-o&pr=5981). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:harche).

@saschagrunert are these tests failing because the integration test added in this PR (no logs yet)? I am not able to run the integration tests locally either (even without my test/changes). So no way to know for me.

**Comment by saschagrunert** [comment]
@harche let's revert the test changes, having them in cri-tools should be enough :+1:

**Comment by harche** [comment]
> @harche let's revert the test changes, having them in cri-tools should be enough +1

Done. Thanks.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
critest is now green for CRI-O: https://github.com/kubernetes-sigs/cri-tools/runs/6986380402?check_suite_focus=true

**Pull request merged**
