### PR TITLE
use a more appropriate console with code block

### PR DESCRIPTION
**Pull request by utam0k**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Use a more appropriate console with a code block.
[renderd](https://github.com/cri-o/cri-o/blob/245a8804002c1e39c4dad4d0f5fa638a1b865b03/README.md)

#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve

LGTM thanks @utam0k !

@cri-o/ocicni-maintainers PTAL

**Comment by fgiudici** [comment]
/lgtm
thanks @utam0k !

**Pull request merged**
