### PR TITLE
[1.15] Allow default route to not be present

### PR DESCRIPTION
**Pull request by haircommander**
First, attempt to find an IP address from /proc/net/route. If we fail to do so, attempt to find a clear primary

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by saschagrunert** [comment]
I guess this needs https://github.com/cri-o/cri-o/pull/2659 to make the CircleCI pipeline happy again.

**Comment by umohnani8** [comment]
Changes LGTM

**Pull request merged**
