### PR TITLE
Add `--pull-progress-timeout` / `pull_progress_timeout` option

### LINKED ISSUE #8764: Dynamic Image pull timeout is not configurable and is fixed at 10 sec
Code where the value is fixed at 10 sec

https://github.com/cri-o/cri-o/blob/9910bc929b58809422b96263df7197bd72682cf6/server/image_pull.go#L243

This is causing frequent ImagePull Error and retries to pull the image when there is no progress for > 10s. But the problem is that, in image registries which are slower, this error is very promitent.

Can we have this 10sec timeout configurable so that it can be adjusted to best value based on the image registry we use?

Error observed 
```
rpc error: code = Canceled desc = copying system image from manifest list: copying config: context canceled
```

Impacted K8s version: v1.31.x

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Add the option to be able to fine-tune the pull progress timeout or even disable it.

#### Which issue(s) this PR fixes:

Fixes #8764 and #8760

#### Special notes for your reviewer:
Follow-up on: https://github.com/cri-o/cri-o/pull/7887

#### Does this PR introduce a user-facing change?

```release-note
Added `--pull-progress-timeout` / `pull_progress_timeout` option to fine-tune the timeout for making progress on image pull.
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
Related:

- https://github.com/cri-o/cri-o/pull/8619#pullrequestreview-2334184333
- https://github.com/containers/image/issues/2585

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

I was wondering if we need to backport this feature, as users are encountering this issue in earlier versions of CRI-O.

**Pull request merged**
