### PR TITLE
[1.14] e2e: turn on force_clone for kubetest

### PR DESCRIPTION
**Pull request by haircommander**
taking over https://github.com/cri-o/cri-o/pull/2828
cherry pick of https://github.com/cri-o/cri-o/pull/2825

but with an added fix for travis

### CODE REVIEW

**Comment by haircommander** [comment]
Finally! 
@saschagrunert @mrunalp @umohnani8 @rhatdan PTAL

**Comment by umohnani8** [comment]
/approve
LGTM

**Pull request merged**
