### PR TITLE
Move bundle to contrib and reuse version vars

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We now reuse the version vars from `./scripts/versions` and move the
whole bundle directory to `./contrib`.
#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
ah you've got a merge conflict

**Comment by saschagrunert** [comment]
Rebased on top of the latest master. :+1:

**Pull request merged**
