### PR TITLE
Fix server restore to not remove podman containers

### PR DESCRIPTION
**Pull request by saschagrunert**
The previous behavior was that CRI-O forcely tried to remove running
podman containers on startup, which only succeeded for the container
storage but not the running process. The result was was a running
container process in podman, which got broken because its storage got
removed.

This is now fixed by excluding podman containers on restore, discovered
by an common podman annotation.

A dedicated unit test has been added as well.

### CODE REVIEW

**Comment by rhatdan** [comment]
Should we call these out as Podman containers or just as nonCRI-O Containers?  Theoretically we could end up with Buildah containers or other tools that uses containers/storage.  Error messages should just be about Non CRI-O containers.

**Comment by saschagrunert** [comment]
> Should we call these out as Podman containers or just as nonCRI-O Containers? Theoretically we could end up with Buildah containers or other tools that uses containers/storage. Error messages should just be about Non CRI-O containers.

I agree, and vendored (https://github.com/containers/libpod/pull/3927) some idea about generally adding an annotation about the "container manager". I changed the error messages regarding this as well.

If https://github.com/containers/libpod/pull/3927 gets accepted, then we can continue here. If not, I will find another solution :innocent:

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but some of the tests are less than happy.

**Comment by saschagrunert** [comment]
This is now ready for review since the related PR has been merged. We could also wait for libpod 1.6.0.

**Comment by haircommander** [comment]
Yeah i say let's wait for the release

**Comment by saschagrunert** [comment]
Closing in favor of https://github.com/cri-o/cri-o/pull/2883

**Pull request closed without merging**
