### PR TITLE
ci: move docs-gen and completions to github actions

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

Move docs generation and completions validation to github actions.

These tasks are relatively small/quick and it would be nice to see the status earlier.

NOTE at the time both jobs are supposed to fail (#4415, #FIXME)

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM, thanks for driving this effort forward! :pray:

**Comment by haircommander** [comment]
I believe rebasing will fix the tests @kolyshkin

**Comment by haircommander** [comment]
is this still needed @kolyshkin @saschagrunert

**Comment by saschagrunert** [comment]
No this is already done, for example within this pipeline: https://github.com/cri-o/cri-o/actions/runs/623114625

/close

**Pull request closed without merging**
