### PR TITLE
server: cleanup sandbox cgroup after creation

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

> /kind api-change
/kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:
otherwise they leak
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
Do we need a test case?

**Comment by sohankunkerkar** [comment]
@haircommander Do you want to pursue this? Or I can cover this as part of the CRI-O stats PR.

**Comment by haircommander** [comment]
gosh I wish I had written down why I didn't push harder for this. I don't think these cgroups actually leak in practice because kubelet cleans them up, they only potentially leak when cgroups aren't being managed by the kubelet (like standalone with crictl) which is not really a supported case

**Comment by sohankunkerkar** [comment]
> gosh I wish I had written down why I didn't push harder for this. I don't think these cgroups actually leak in practice because kubelet cleans them up, they only potentially leak when cgroups aren't being managed by the kubelet (like standalone with crictl) which is not really a supported case

OK, it sounds like we don't need this anymore. I will close this PR then.

**Pull request closed without merging**
