### PR TITLE
Fix gh-pages content width

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Allow a larger content width by overriding the default theme style.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
@cevich @edsantiago @haircommander @TomSweeneyRedHat @umohnani8 PTAL

I know nothing about css and style pages...

**Comment by haircommander** [comment]
interesting, it seems you don't have approval rights on this branch

LGTM

**Comment by edsantiago** [comment]
I don't think I'm qualified to review. I don't know cri-o, and especially don't know the `gh-pages` branch; I've never heard of `.scss` files; and I have no context for where these pages are supposed to render or how to test. Sorry.

**Comment by saschagrunert** [comment]
> interesting, it seems you don't have approval rights on this branch
> 
> LGTM

I think this solves the issue: https://github.com/cri-o/cri-o/pull/3451

**Comment by saschagrunert** [comment]
> I don't think I'm qualified to review. I don't know cri-o, and especially don't know the `gh-pages` branch; I've never heard of `.scss` files; and I have no context for where these pages are supposed to render or how to test. Sorry.

I still appreciate your time to come over and say hi to us! :green_heart:

**Comment by rhatdan** [comment]
@edsantiago I was thinking you might understand web content better then me.  :^)

**Comment by saschagrunert** [comment]
So this should be now able to be approved by the maintainers

**Comment by rhatdan** [comment]
I will trust @saschagrunert ...
/lgtm

**Pull request merged**
