### PR TITLE
release-notes: fix flags

### PR DESCRIPTION
**Pull request by haircommander**
which changed after a k8s release-notes package bump

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]
LGTM
/retest

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
