### PR TITLE
Add checksum details for artifacts

### LINKED ISSUE #5600: Checksum details for the releases.
Hello team,

I'm looking for checksum details for the release in this link and not able find one. We need this to check the file integrity after every download.

https://github.com/cri-o/cri-o/releases/tag/v1.21.4

Thank you

### PR DESCRIPTION
**Pull request by hasan4791**
#### What type of PR is this?
/kind ci

#### What this PR does / why we need it:
Provide checksum details for the uploaded artifacts.

#### Which issue(s) this PR fixes:

Fixes #5600

#### Special notes for your reviewer:
Following checksum files would be generated for each artifacts.
```

Download one of our static release bundles via our Google Cloud Bucket:

cri-o.amd64.9b7f5ae815c22a1d754abfbc2890d8d4c10e240d.tar.gz
cri-o.amd64.9b7f5ae815c22a1d754abfbc2890d8d4c10e240d.tar.gz.sha256sum
cri-o.arm64.9b7f5ae815c22a1d754abfbc2890d8d4c10e240d.tar.gz
cri-o.arm64.9b7f5ae815c22a1d754abfbc2890d8d4c10e240d.tar.gz.sha256sum
```

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM
/ok-to-test

**Comment by saschagrunert** [comment]
@hasan4791 can you please fix the shfmt failure:
```diff
-sha256sum "$ARCHIVE" > "$ARCHIVE_SHA256SUM"
+sha256sum "$ARCHIVE" >"$ARCHIVE_SHA256SUM"
```

**Comment by hasan4791** [comment]
> @hasan4791 can you please fix the shfmt failure:
> 
> ```diff
> -sha256sum "$ARCHIVE" > "$ARCHIVE_SHA256SUM"
> +sha256sum "$ARCHIVE" >"$ARCHIVE_SHA256SUM"
> ```

Done.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
thank you @hasan4791 !

**Pull request merged**
