### PR TITLE
server: propagate the pinned status of an image when queried via crictl 

### PR DESCRIPTION
**Pull request by sohankunkerkar**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

```bash
$ sudo crictl inspecti registry.k8s.io/pause:3.9 | jq .status.pinned
true
```

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
@sohankunkerkar, would this be more of a bug since the information was missing?

**Comment by sohankunkerkar** [comment]
> @sohankunkerkar, would this be more of a bug since the information was missing?

IMO, this is more of a UX improvement than a bug as the image status was missing that information. Currently, we can get that information from `crictl images --pinned`.

**Comment by kwilczynski** [comment]
The **release-1.29** already included the code change referenced here through the following Pull Request:

- https://github.com/cri-o/cri-o/pull/8325

**Pull request merged**
