### PR TITLE
Move pkg/config/seccomp package to internal/config/seccomp

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
We do not want to expose these implementations to en-users
so we make them private.

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
if pkg/seccomp still exists, why not remove it?

**Comment by saschagrunert** [comment]
> if pkg/seccomp still exists, why not remove it?

Oh this one is just about the config part, we split up the config into an internal and public part. Or are you referring to something different?

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green tests buttons

**Comment by haircommander** [comment]
LGTM

**Comment by haircommander** [comment]
/retest

(failures look real, provisioning a vm to test)

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by saschagrunert** [comment]
I’m kind of in favor of a force merge until those e2e issues are resolved. 😱🤭

**Comment by rhatdan** [comment]
@saschagrunert Done, hopefully you don't get me in trouble.  :^)

**Pull request merged**
