### PR TITLE
Update Kubernetes to v1.18.0-alpha.2

### PR DESCRIPTION
**Pull request by saschagrunert**
Update k8s to the latest version.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hm, it's not causing the failures, so I guess we can take this in as a first step :)

**Comment by TomSweeneyRedHat** [comment]
LGTM once the tests are happy

**Comment by saschagrunert** [comment]
Rebased on top of the latest master to get the CI fixes in.

**Comment by TomSweeneyRedHat** [comment]
Happy green tests buttons on this one.

**Pull request merged**
