### PR TITLE
[1.13] Revert "update containers/{image,storage} dependencies"

### PR DESCRIPTION
**Pull request by umohnani8**
This reverts commit 3228c65c0f2a9c001cb44cd6094986f74a7f6f08.

We pulled in the c/storage issue with "layer not known" the commit above, so reverting.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@mrunalp @nalind @vrothberg PTAL

**Comment by runcom** [comment]
what is this causing to revert? (just curious)

**Comment by vrothberg** [comment]
Can't we update containers/storage to the latest version instead of reverting? Seeing all the changes, the next update on top of the 1.13 branch will be (again) a lot of work. I am not sure though if the latest storage fixes the unknown layer issue.

**Pull request merged**
