### PR TITLE
[1.15] test: add changes required for fedora 30 AMI

### PR DESCRIPTION
**Pull request by haircommander**
Including removing our own debugging callback
change from package to a manual shell call (because python2-dnf is sunsetted, but we still need python2 for oct)
disable nodev for userns test
Signed-off-by: Peter Hunt pehunt@redhat.com

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons

**Comment by haircommander** [comment]
I reverted the ami switch, so this passed against the old ami and isn't testing anything. 
/hold

**Comment by giuseppe** [comment]
LGTM

**Comment by haircommander** [comment]
/hold cancel

we will need this to merge PRs now that we switched to f30

**Comment by haircommander** [comment]
I added a cherry-pick of https://github.com/cri-o/cri-o/pull/2898 and https://github.com/cri-o/cri-o/pull/2888

**Comment by haircommander** [comment]
```
TASK [build cri-o] *************************************************************
task path: /go/src/github.com/cri-o/cri-o/contrib/test/integration/build/cri-o.yml:13
Killed by signal 15.
```
weird
/retest

**Comment by haircommander** [comment]
seeing
```
09:59:25 not ok 7 ctr remove
09:59:25 # (in test file ctr.bats, line 229)
09:59:25 #   `[ "$status" -eq 0 ]' failed
09:59:25 # time="2020-01-06T14:58:56Z" level=error msg="File descriptor 3 (pipe:[179390]) leaked on pvdisplay invocation. Parent PID 58335: /tmp/jenkins/workspace/kata-con\nFile descriptor 6 (/dev/mapper/control) leaked on pvdisplay invocation. Parent PID 58335: /tmp/jenkins/workspace/kata-con\n  Failed to find physical volume \"/dev/sdb\".\n" error="exit status 5"
09:59:25 # 0
```
in kata. Has this error happened before/was this branch missed? @chavafg

**Comment by chavafg** [comment]
Hi @haircommander 
I see that the container is still running when trying to remove it. Could this be a race condition? Although I see that the test is the same in other branches and it is not failing. 

```
10:47:47 # time="2020-01-06T16:47:45Z" level=error msg="container \"bae8e44013e11d35474cff9194591c7c29b0be327fa3106c077524502277bb37\" is running, please stop it first"
10:47:47 # time="2020-01-06T16:47:45Z" level=fatal msg="unable to remove container(s)"
```

these are the lines where the failures occur: 
```
run crictl start "$ctr_id"
echo "$output"
[ "$status" -eq 0 ]
run crictl rm "$ctr_id"
echo "$output"
[ "$status" -eq 0 ]
```

Btw, we were already testing branch 1.15, so not sure why it started to fail now.

**Comment by haircommander** [comment]
thanks for the input @chavafg! The page isn't loading for me anymore, so I'm going to retry. maybe it's magically fixed :smile: 

/retest

**Comment by chavafg** [comment]
@haircommander sorry, now we have an issue with our jenkins instance, we are trying to fix this asap, will let you know.

**Comment by chavafg** [comment]
ok, jenkins is now up and I see the job already running

**Comment by chavafg** [comment]
@haircommander can you send a retest please?

**Comment by chavafg** [comment]
ohh sorry, I see it is running.

**Comment by haircommander** [comment]
Thanks @chavafg 

@mrunalp @umohnani8 PTAL, and fast before the green tests go away :open_mouth:

**Comment by haircommander** [comment]
whyyyyy

/retest

**Pull request merged**
