### PR TITLE
Switch to uber maintained gomock

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
The Google version is not maintained any more and Uber has taken over the ship. Means we now switch vendoring this version instead.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Waiting on an answer on https://github.com/uber/mock/issues/37

**Comment by haircommander** [comment]
@saschagrunert did you still want this?

**Comment by saschagrunert** [comment]
> @saschagrunert did you still want this?

Yes, if https://github.com/uber-go/mock/issues/37 is resolved.

**Comment by kwilczynski** [comment]
@saschagrunert, is this something you still wish to do?

**Comment by saschagrunert** [comment]
> @saschagrunert, is this something you still wish to do?

Yes, if https://github.com/uber-go/mock/issues/37 is resolved.

**Comment by kwilczynski** [comment]
> > @saschagrunert, is this something you still wish to do?
> 
> Yes, if https://github.com/uber-go/mock/issues/37 is resolved.

Looks like their fork is somewhat unmaintained too 😞

**Pull request closed without merging**
