### PR TITLE
config: fix type of privileged_without_host_devices

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
it is a bool, not a string
#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where `crio config` would print a string for `privileged_without_host_devices`, not a boolean
```

### CODE REVIEW

**Comment by fidencio** [comment]
LGTM, thanks @haircommander!

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
