### PR TITLE
Release v1.16.0

### PR DESCRIPTION
**Pull request by mrunalp**
@haircommander @umohnani8 @saschagrunert @rhatdan ptal

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by haircommander** [comment]
/hold
waiting on https://github.com/cri-o/cri-o/pull/2922

**Comment by saschagrunert** [comment]
/retest

Yay! 🥳🎉

**Comment by Itxaka** [comment]
@haircommander #2922 is now merged, should the hold be removed from here? :D

**Comment by haircommander** [comment]
>  @haircommander #2922 is now merged, should the hold be removed from here? :D

Yup 😃 
/hold cancel

**Pull request merged**
