### PR TITLE
Run seccomp notifier tests on arm

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
Enable the tests for arm runners.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by kwilczynski** [comment]
@saschagrunert, what is the connection between enabling tests on Arm and adding swap space?

Otherwise, it looks fine. 🙂

**Comment by saschagrunert** [comment]
> @saschagrunert, what is the connection between enabling tests on Arm and adding swap space?
> 
> Otherwise, it looks fine. 🙂

There was no swap in the arm integration runner means that `swapoff` will be a noop and cannot be blocked by seccomp. We now ensure that we have a swap available everytime.

**Pull request merged**
