### PR TITLE
.github/workflows: auto approve dependabot PRs

### PR DESCRIPTION
**Pull request by sohankunkerkar**
#### What type of PR is this?

/kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mrunalp** [comment]
@haircommander @saschagrunert wdyt?

**Comment by TomSweeneyRedHat** [comment]
LGTM
neat addtion!

**Comment by sohankunkerkar** [comment]
> What if we changed the OWNERS file to include the reviewers as approvers of vendor? Anyone in the org can lgtm, so this would tighten the requirements to people who are in the reviewers category for other PRs

How about we restrict prow to accept `/lgtm` only from reviewers and approvers instead?

**Comment by haircommander** [comment]
> > What if we changed the OWNERS file to include the reviewers as approvers of vendor? Anyone in the org can lgtm, so this would tighten the requirements to people who are in the reviewers category for other PRs
> 
> How about we restrict prow to accept `/lgtm` only from reviewers (listed in the ONWERS file) and approvers instead?

that's an option though it may be a bit more complicated. If you'd like to try that out we can see, though the OWNERS changes to give /approve rights to the directory (and go.* files) sounds simpler to me. I'm open though!

**Comment by saschagrunert** [comment]
Hm, it will make CI only faster for one PR, because prow will retest if one merges and another gets `/lgtm`. I'd be in favor of something fully automated, but I'm not sure if that's too risky. Means:

- We auto approve dependabot PRs
- If the CI passes, then we automatically `/lgtm` / merge

**Comment by haircommander** [comment]
I would personally worry about that :\

Just faster for 1 PR is okay IMO. Having more people who can approve and lgtm will help get the PRs in faster.

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
/hold

@haircommander feel free to unhold if you're fine with those changes.

**Comment by haircommander** [comment]
/unhold

we can merge this. I still feel concerned about opening it up for everyone in the org, rather than the reveiewers, but we can see how it goes :)

**Pull request merged**
