### PR TITLE
Documentation: expand on CNI CIDRs in the kubeadm tutorial (RE: #5549)

### LINKED ISSUE #5549: Duplicate IPs / PLEG is not healthy
Note: I asked this on the Kube slack, and @haircommander recommended I raise a issue. 

**Description:** Applications on my cluster are having issues because pods appear to be getting "duplicate" IP addresses when using cri-o bridge. In researching this, I also found that I'm getting a "PLEG is not healthy" log in kubelet. 

This is a small Fedora 35 cluster (not CoreOS) running on libvirt, 1 master, 3 workers. There is basically no load on the cluster and it's 24 hours old. I don't mind if we want to run any destructive or dangerous tests on the cluster while debugging. 

One of the few projects on the cluster is airflow, and from this project you can see pods getting "duplicate" IPs; 

```
user@host: k get pods -n airflow -o wide
NAME                                 READY   STATUS                  RESTARTS   AGE   IP          NODE            NOMINATED NODE   READINESS GATES
airflow-flower-5d59bf75fc-zzn5v      0/1     CrashLoopBackOff        209        11h   10.85.0.2   kubeworker-01   <none>           <none>
airflow-postgresql-0                 0/1     Pending                 0          11h   <none>      <none>          <none>           <none>
airflow-redis-0                      0/1     Pending                 0          11h   <none>      <none>          <none>           <none>
airflow-scheduler-c7647fff-ndlt7     0/2     Init:0/1                99         11h   10.85.0.2   kubeworker-03   <none>           <none>
airflow-statsd-7586f9998-hmt8n       1/1     Running                 0          11h   10.85.0.2   kubeworker-02   <none>           <none>
airflow-triggerer-799fbf6779-jghlh   0/1     Init:CrashLoopBackOff   103        11h   10.85.0.3   kubeworker-02   <none>           <none>
airflow-webserver-656c857785-jx99q   0/1     Init:CrashLoopBackOff   107        11h   10.85.0.3   kubeworker-01   <none>           <none>
airflow-worker-0                     0/2     Pending                 0          11h   <none>      <none>          <none>           <none>
```

ie: `airflow-flower-5d59bf75fc-zzn5v` has **10.85.0.2** on kubeworker-01, and `airflow-scheduler-c7647fff-ndlt7` also has **10.85.0.2** on kubeworker-03. While investigating this, going down the rabbit hole, it seems that the PodCIDR is set correctly on the nodes, but is being ignored between kublet <-> cri-o. 

The PodCIDR is set on the nodes as expected;

```
user@host: k describe nodes | egrep 'Name:|PodCIDR:'
Name:               kubemaster
PodCIDR:                      10.85.0.0/24
Name:               kubeworker-01
PodCIDR:                      10.85.1.0/24
Name:               kubeworker-02
PodCIDR:                      10.85.2.0/24
Name:               kubeworker-03
PodCIDR:                      10.85.3.0/24
```

So, I went to look at kubeworker-01. As a sanity check, here is my CNI config (nothing changed from default); 

```
[root@kubeworker-01 ~]# ls /etc/cni/net.d/
100-crio-bridge.conf  200-loopback.conf
[root@kubeworker-01 ~]# cat /etc/cni/net.d/100-crio-bridge.conf
{
    "cniVersion": "0.3.1",
    "name": "crio",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "hairpinMode": true,
    "ipam": {
        "type": "host-local",
        "routes": [
            { "dst": "0.0.0.0/0" },
            { "dst": "1100:200::1/24" }
        ],
        "ranges": [
            [{ "subnet": "10.85.0.0/16" }],
            [{ "subnet": "1100:200::/24" }]
        ]
    }
}
```

The crio-status looks clean too;

```
[root@kubeworker-01 ~]# crio-status info
cgroup driver: systemd
storage driver: overlay
storage root: /var/lib/containers/storage
default GID mappings (format <container>:<host>:<size>):
  0:0:4294967295
default UID mappings (format <container>:<host>:<size>):
  0:0:4294967295
```

And then I sanity checked that cri-o is actually using the bridge, and it looks like it is - here is the **log from cri-o starting up**; 

```
Jan 18 10:40:31 kubeworker-01 systemd[1]: Starting Container Runtime Interface for OCI (CRI-O)...
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.438668621Z" level=info msg="Starting CRI-O, version: 1.21.3, git: ff0b7feb8e12509076b4b0e338b6334ce466b293(clean)"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.439151163Z" level=info msg="Node configuration value for hugetlb cgroup is true"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.439215557Z" level=info msg="Node configuration value for pid cgroup is true"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.439294291Z" level=info msg="Node configuration value for memoryswap cgroup is true"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.446573437Z" level=info msg="Node configuration value for systemd CollectMode is true"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.452919603Z" level=info msg="Node configuration value for systemd AllowedCPUs is true"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.495388261Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.502487867Z" level=info msg="Using default capabilities: CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_FSETID, CAP_FOWNER, CAP_SETGID, CAP_SETUID, CAP_SETPCAP, CAP_NET_BIND_SERVICE, CAP>
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.505665898Z" level=info msg="Conmon does support the --sync option"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.506101328Z" level=info msg="No seccomp profile specified, using the internal default"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.506225054Z" level=info msg="AppArmor is disabled by the system or at CRI-O build-time"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.517012959Z" level=info msg="Found CNI network crio (type=bridge) at /etc/cni/net.d/100-crio-bridge.conf"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.525393208Z" level=info msg="Found CNI network 200-loopback.conf (type=loopback) at /etc/cni/net.d/200-loopback.conf"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.525554221Z" level=info msg="Updated default CNI network name to crio"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.553400090Z" level=warning msg="Could not restore sandbox 11ca693a6cb6f0ab7fab2f7ca17cd27a764380267d8acd2ebf4c0b6adb1e8b71; deleting it and containers underneath it: failed>
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.574224482Z" level=warning msg="Could not restore sandbox f6d24d832132ef7f8abb4182f3bb56e6cb8d675e90110f82d63675d77bdd2d3d; deleting it and containers underneath it: failed>
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.648618861Z" level=warning msg="Could not restore sandbox 5fa5b457dabc65efa12b770e4ad085a6c35b72995a1c4fcca07653653b4aa0e7; deleting it and containers underneath it: failed>
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.715798456Z" level=warning msg="Ignoring error tearing down loopback interface: failed to Statfs \"\": no such file or directory"
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.715895293Z" level=info msg="Got pod network &{Name:airflow-webserver-656c857785-jx99q Namespace:airflow ID:5fa5b457dabc65efa12b770e4ad085a6c35b72995a1c4fcca07653653b4aa0e7>
Jan 18 10:40:31 kubeworker-01 crio[745]: time="2022-01-18 10:40:31.716037641Z" level=info msg="Deleting pod airflow_airflow-webserver-656c857785-jx99q from CNI network \"crio\" (type=bridge)"
```

So, I went to see if the kubelet was "seeing" this podCIDR. 

The log below is a snip from a fresh startup of kubelet on kubeworker-01 - you can see `PLEG is not healthy`, and also `Updating runtime config through cri with podcidr` .. `10.85.1.0` - but as you can see pods are not being assigned IPs on this CIDR (they're getting 10.85.0.x addresses). 

```
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.767911  197889 status_manager.go:157] "Starting to sync pod status with apiserver"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.767924  197889 kubelet.go:1853] "Starting kubelet main sync loop"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: E0118 10:19:44.767958  197889 kubelet.go:1877] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.801631  197889 cpu_manager.go:199] "Starting CPU manager" policy="none"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.801817  197889 cpu_manager.go:200] "Reconciling" reconcilePeriod="10s"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.801901  197889 state_mem.go:36] "Initialized new in-memory state store"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.802064  197889 state_mem.go:88] "Updated default CPUSet" cpuSet=""
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.802137  197889 state_mem.go:96] "Updated CPUSet assignments" assignments=map[]
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.802196  197889 policy_none.go:44] "None policy: Start"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.803017  197889 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.803285  197889 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.806869  197889 kuberuntime_manager.go:1044] "Updating runtime config through cri with podcidr" CIDR="10.85.1.0/24"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.819443  197889 kubelet_network.go:76] "Updating Pod CIDR" originalPodCIDR="" newPodCIDR="10.85.1.0/24"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.823240  197889 kubelet_node_status.go:71] "Attempting to register node" node="kubeworker-01"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.841407  197889 kubelet_node_status.go:109] "Node was previously registered" node="kubeworker-01"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.841535  197889 kubelet_node_status.go:74] "Successfully registered node" node="kubeworker-01"
Jan 18 10:19:44 kubeworker-01 kubelet[197889]: I0118 10:19:44.868975  197889 topology_manager.go:187] "Topology Admit Handler"
```

From my limited understanding of the PLEG, here are some metrics that may be useful?
```
[root@kubeworker-01 ~]# curl localhost:10255/metrics | grep -i pleg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP kubelet_pleg_discard_events [ALPHA] The number of discard events in PLEG.
# TYPE kubelet_pleg_discard_events counter
kubelet_pleg_discard_events 0
# HELP kubelet_pleg_last_seen_seconds [ALPHA] Timestamp in seconds when PLEG was last seen active.
# TYPE kubelet_pleg_last_seen_seconds gauge
kubelet_pleg_last_seen_seconds 1.642501613e+09
# HELP kubelet_pleg_relist_duration_seconds [ALPHA] Duration in seconds for relisting pods in PLEG.
# TYPE kubelet_pleg_relist_duration_seconds histogram
kubelet_pleg_relist_duration_seconds_bucket{le="0.005"} 429
kubelet_pleg_relist_duration_seconds_bucket{le="0.01"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="0.025"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="0.05"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="0.1"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="0.25"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="0.5"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="1"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="2.5"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="5"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="10"} 430
kubelet_pleg_relist_duration_seconds_bucket{le="+Inf"} 430
kubelet_pleg_relist_duration_seconds_sum 0.29550731699999994
kubelet_pleg_relist_duration_seconds_count 430
# HELP kubelet_pleg_relist_interval_seconds [ALPHA] Interval in seconds between relisting in PLEG.
# TYPE kubelet_pleg_relist_interval_seconds histogram
kubelet_pleg_relist_interval_seconds_bucket{le="0.005"} 0
kubelet_pleg_relist_interval_seconds_bucket{le="0.01"} 0
kubelet_pleg_relist_interval_seconds_bucket{le="0.025"} 0
kubelet_pleg_relist_interval_seconds_bucket{le="0.05"} 0
kubelet_pleg_relist_interval_seconds_bucket{le="0.1"} 0
kubelet_pleg_relist_interval_seconds_bucket{le="0.25"} 0
kubelet_pleg_relist_interval_seconds_bucket{le="0.5"} 0
kubelet_pleg_relist_interval_seconds_bucket{le="1"} 0
kubelet_pleg_relist_interval_seconds_bucket{le="2.5"} 429
kubelet_pleg_relist_interval_seconds_bucket{le="5"} 429
kubelet_pleg_relist_interval_seconds_bucket{le="10"} 429
kubelet_pleg_relist_interval_seconds_bucket{le="+Inf"} 429
kubelet_pleg_relist_interval_seconds_sum 429.55795694299985
kubelet_pleg_relist_interval_seconds_count 429
100  120k    0  120k    0     0  7651k      0 --:--:-- --:--:-- --:--:-- 8058k

```

At this point, I'm not sure what to do next.

**Steps to reproduce the issue:**
This is how I prepped the nodes - I  hope you can see nothing too funky going on there; https://github.com/jamesread/jwr-soe-ansible/blob/master/roles/machine_k8s/tasks/main.yml 

**Describe the results you received:**
Pod's getting duplicate IP addresses, PLEG is not healthy. 

**Describe the results you expected:**
Pod's getting IP addresses according to the node's PodCIDR, and PLEG  being healthy?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
[root@kubeworker-01 ~]# crio --version
crio version 1.21.3
Version:       1.21.3
GitCommit:     ff0b7feb8e12509076b4b0e338b6334ce466b293
GitTreeState:  clean
BuildDate:     2021-11-08T17:52:19Z
GoVersion:     go1.16.8
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic

user@host: ansible -a 'rpm -qa cri-o' kube
kubeworker-03 | CHANGED | rc=0 >>
cri-o-1.21.3-1.module_f35+13330+6bc9c749.x86_64
kubeworker-02 | CHANGED | rc=0 >>
cri-o-1.21.3-1.module_f35+13330+6bc9c749.x86_64
kubeworker-01 | CHANGED | rc=0 >>
cri-o-1.21.3-1.module_f35+13330+6bc9c749.x86_64
kubemaster | CHANGED | rc=0 >>
cri-o-1.21.3-1.module_f35+13330+6bc9c749.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
There is basically zero load on this cluster - the airflow pods are crash looping a lot, but that's probably due to these "duplicate IPs" - not being able to find the service they would expect. 

1 control-plane node, 3x worker nodes. Freshly installed cluster from Fedora 35. libvirt VMs. 

```
user@host: ansible -a 'rpm -qa kubernetes-node' kube
kubeworker-01 | CHANGED | rc=0 >>
kubernetes-node-1.21.0-2.fc35.x86_64
kubeworker-02 | CHANGED | rc=0 >>
kubernetes-node-1.21.0-2.fc35.x86_64
kubeworker-03 | CHANGED | rc=0 >>
kubernetes-node-1.21.0-2.fc35.x86_64
kubemaster | CHANGED | rc=0 >>
kubernetes-node-1.21.0-2.fc35.x86_64
```

```
user@host: k version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-07-22T00:00:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:46:22Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by jamesread**
Signed-off-by: jamesread <contact@jread.com>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Simply a clarification documentation, re the kubeadm tutorial for cri-o. I ran into an issue trying to use bridge by accident on a multiple-host cluster. 

#### Which issue(s) this PR fixes:

Fixes #5549 

#### Special notes for your reviewer:

This is my first PR on the project :-) I've read the CONTRIBUTING guide, and the notes in this PR. 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
/ok-to-test

Thank you @jamesread!

**Comment by jamesread** [comment]
Hey @saschagrunert , I don't understand all of cri-o's CI tests obviously, but it looks like something is broken in the main branch or the test infra - the tests aren't failing due to my bad docs, right? :-)

**Comment by saschagrunert** [comment]
@jamesread no those are usually flakes since we only change the documentation :)

**Comment by jamesread** [comment]
Do I need to poke these bots / tests to trigger re-runs on flaky tests, or shall I just leave this to the maintainers to settle?

**Comment by haircommander** [comment]
/override ci/prow/e2e-agnostic
/override ci/prow/e2e-gcp

failures certainly not the fault of this PR :smile:

**Pull request merged**
