### PR TITLE
Enable selinux for e2e tests

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by kolyshkin** [comment]
we're using kubernetes release-1.16 for CI (per `contrib/test/integration/main.yml`), so we have to wait until https://github.com/kubernetes/kubernetes/pull/87752 is merged

**Comment by kolyshkin** [comment]
> we're using kubernetes release-1.16 for CI (per contrib/test/integration/main.yml), so we have to wait until kubernetes/kubernetes#87752 is merged

Sorry, was looking into old checkout; now it's at release-1.17 (see 
https://github.com/cri-o/cri-o/blob/master/contrib/test/integration/main.yml) which needs https://github.com/kubernetes/kubernetes/pull/87753 (which needs https://github.com/kubernetes/kubernetes/pull/88352)

**Comment by kolyshkin** [comment]
I was wrong twice; @mrunalp points out that the `master` branch is used for actual CI as per https://github.com/cri-o/cri-o/blob/master/contrib/test/integration/main.yml#L170

**Comment by haircommander** [comment]
/retest

:crossed_fingers:

**Comment by haircommander** [comment]
test failures unrelated, fixed by https://github.com/cri-o/cri-o/pull/3793

**Comment by haircommander** [comment]
/retest

:thinking:

**Comment by TomSweeneyRedHat** [comment]
LGTM
but the tests are all kinds of red

**Comment by haircommander** [comment]
this has been done with the migration to prow

**Pull request closed without merging**
