### PR TITLE
README.md: fix a typo

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by saschagrunert** [comment]
LGTM

**Comment by haircommander** [comment]
/test integration_fedora

if this fails again I am tempted to hit the forbidden red button

**Comment by haircommander** [comment]
/retest

On Tuesday, May 21, 2019, OpenShift CI Robot <notifications@github.com>
wrote:
> @giuseppe: The following test failed, say /retest to rerun them all:
>
> Test name Commit Details Rerun command
> ci/openshift-jenkins/e2e_fedora bff7ded link /test e2e_fedora
>
> Full PR test history. Your PR dashboard. Please help us cut down on
flakes by linking to an open issue when you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available
here. If you have questions or suggestions related to my behavior, please
file an issue against the kubernetes/test-infra repository. I understand
the commands that are listed here.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/LXuk05pQrOU1ACo7Zyms9eGlajSFUPwiQgaqOKLz2O20uQSsm6wcsY1i2xa5s2HTe9Nas7Iesyj2x-RHG-Br3QznzVr2hP-9eR4vz8TjpjrH0-2jDraLyxRLfin4q8wE3XtAxUatotAZNIo6MzPK6mQHIZ0zZVgtWsq81XQ4_KTEnrYTRYQWCrzyATnNehBZ__MUT9crW48-1ue7j69t2PtqEFk3q4ZF9SzA6I9SKg=s0-d-e1-ft#https://github.com/notifications/beacon/ACFJQJ43WIRJGE3TIEMGIRDPWSOI3A5CNFSM4HOLDDOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODV5T7UQ.gif>

**Pull request merged**
