### PR TITLE
[1.20] release-notes: fix flags

### PR DESCRIPTION
**Pull request by haircommander**
which changed after a k8s release-notes package bump

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other
/kind bug

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by fidencio** [comment]
LGTM, but would be nice to point to the commit that required this change.

**Review by mrunalp — APPROVED** [review]

**Comment by haircommander** [comment]
```
not ok 172 stats
# (in test file ./stats.bats, line 17)
#   `id=$(crictl run "$TESTDATA"/container_redis.json "$TESTDATA"/sandbox_config.json)' failed
```
that's a new one

**Pull request merged**
