### PR TITLE
Fix zsh autocompletion

### PR DESCRIPTION
**Pull request by askervin**
- Fix unmatched ' issue on commands.
- Split commands and options on separate lines to make
  them easier to review and less prone to merge conflicts.

Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- This PR fixes crio command autocompletion on zsh.
- This PR makes `completion/zsh/_crio` less prone to merge conflicts. Currently all commits that add command line options will conflict due to this file. This helps reviewing zsh completion changes, too.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by haircommander** [comment]
thanks for the PR @askervin !

our zsh completions are autogenerated by a go template: https://github.com/cri-o/cri-o/blob/master/internal/criocli/completion.go#L75
Are you able to the template to output in a more suitable way?

**Comment by askervin** [comment]
> our zsh completions are autogenerated by a go template: https://github.com/cri-o/cri-o/blob/master/internal/criocli/completion.go#L75

Oh, that's great! Thanks for pointing this out, @haircommander. :)

> Are you able to the template to output in a more suitable way?

Sure thing. I hope this is fine. Escaping single quotes inside single quotes looks a bit complicated in shells, but it works...

**Comment by haircommander** [comment]
hm are you running `make completions-generation` to make sure the changes are reflected in the files? The completions job still shows it hasn't quite worked:
https://github.com/cri-o/cri-o/pull/4903/checks?check_run_id=2601859524
you can run `make completions-validation` to verify you'll pass the completions job here

**Comment by askervin** [comment]
> hm are you running `make completions-generation`

Ah, I was missing that. Generated changes amended and force-pushed.

Couldn't run `make completions-validation`, there doesn't seem to be such target in the Makefile.

**Comment by wgahnagl** [comment]
@askervin hello! Could you give this a rebase?

**Comment by askervin** [comment]
@wgahnagl, Thanks for reminder! Rebased and retested on top of the master branch.

**Comment by askervin** [comment]
@wgahnagl , @haircommander , I think this PR would be good to go. Fixes an error and results in fewer conflicts in `completions/_crio` when new command line parameters are added.

**Comment by haircommander** [comment]
/retest

(shfmt test failure is unrelated)
/approve

@QiWang19 @wgahnagl @fgiudici PTAL for final review

**Comment by askervin** [comment]
Already fixed by #5586 .

**Pull request closed without merging**
