### PR TITLE
Add dependabot config file

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This should enable dependabot for our repository and hopefully the
vendoring with the new version 2 format.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by saschagrunert** [comment]
@haircommander dependabot now supports vendoring, do we wanna go for an automatic dependency update?

**Comment by haircommander** [comment]
/retest

/approve
:robot: :robot: :robot:

**Comment by saschagrunert** [comment]
@haircommander fine with merging this?

**Pull request merged**
