### PR TITLE
Try to find `CONTAINER_CNI_PLUGIN_DIR` by binary lookup

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
We can use a CNI plugin binary if present in `$PATH` to lookup the `CONTAINER_CNI_PLUGIN_DIR` when running the integration tests locally. We still use `/opt/cni/bin` as fallback if the lookup fails.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM, just wondering--what's the motivation for this change? easier to setup a testing box?

**Comment by saschagrunert** [comment]
> LGTM, just wondering--what's the motivation for this change? easier to setup a testing box?

Yes, this is the only change required to run integration tests locally on my machine.

**Review by sohankunkerkar — APPROVED** [review]
/retest
/lgtm

**Pull request merged**
