### PR TITLE
build: make uninstall improvements

### PR DESCRIPTION
**Pull request by dougsland**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Make sure all installed files are removed.

### CODE REVIEW

**Comment by dougsland** [comment]
The ci/circleci: git-validation error is not valid. I have added a empty (TAB) line for readability and give space between cleanup codes.

**Comment by TomSweeneyRedHat** [comment]
LGTM once the tests are happy.

**Comment by haircommander** [comment]
LGTM, though I don't really want to totally break git validation, so I'd prefer you fix as it is asking

**Pull request merged**
