### PR TITLE
Remove containerd/release-tool dependency

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
We now use the Kubernetes release tooling in substitution for the
containerd/release-tool.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons

**Comment by haircommander** [comment]
merge conflict :\

**Comment by saschagrunert** [comment]
Rebased on top of the latest master to resolve the conflict

**Pull request merged**
