### PR TITLE
dashboard: Update data sources to use new metrics names

### PR DESCRIPTION
**Pull request by hdhoang**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Updates sample Grafana dashboard to changes after #7782.

#### Special notes for your reviewer:

Sorry that I missed the 1.30 release! I haven't recorded a new GIF, because the panels look mostly the same. Only an axis' scale changed.

I dedicate the changes to the public domain.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
@hdhoang, good catch! Thank you for sending the fix over! Appreciated! :smile:

**Comment by hdhoang** [comment]
/retest

seems like rate limit by github

**Review by saschagrunert — APPROVED** [review]
Thanks!

**Pull request merged**
