### PR TITLE
[1.22] oci: fix a couple of deadlocks in container stop code 

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
cherry-pick of https://github.com/cri-o/cri-o/pull/5433
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
related to https://bugzilla.redhat.com/show_bug.cgi?id=2021432

**Comment by saschagrunert** [comment]
@haircommander do we plan to backport to 4.8?

**Comment by haircommander** [comment]
yes I intend to bring this to all supported versions

**Review by saschagrunert — APPROVED** [review]
/lgtm
/retest-required

**Comment by haircommander** [comment]
related to https://bugzilla.redhat.com/show_bug.cgi?id=2021432

**Pull request merged**
