### PR TITLE
Sign static binary bundle via cosign

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

We now sign our static binary bundle via cosign keyless signing.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
We now sign the static binary bundle via sigstore signatures. This also includes support for the [get script](https://github.com/cri-o/cri-o/blob/main/scripts/get).
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Okay, this should work on `main` then. PTAL @cri-o/cri-o-maintainers

**Comment by saschagrunert** [comment]
@haircommander PTAL

**Comment by mrunalp** [comment]
Should we be using this - https://slsa.dev/blog/2022/06/slsa-github-workflows?

**Pull request merged**
