### PR TITLE
crio: use json-iterator/go instead of encoding/json

### PR DESCRIPTION
**Pull request by giuseppe**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

faster json encoding/decoding and better usage of memory since buffers can be added to a pool.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by giuseppe** [comment]
@mheon PTAL

**Comment by mheon** [comment]
LGTM

**Comment by kolyshkin** [comment]
LGTM (not a maintainer)

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by mrunalp** [comment]
Are there edge cases or known issues we should be worried about? We had attempted switching json libraries a long time and had to revert because we started seeing failures.

**Comment by mheon** [comment]
On the Podman side, it was a smooth transition - we've been using it on our database and REST API without issues.

**Comment by harche** [comment]
Nice, but I was wondering if the maintainers of `json-iterator` plan to contribute their optimizations back to `encoding/json`. Since we are moving away from the go built-in `encoding/json` we are trusting them with any potential future bug fixes, CVEs, enhancements etc. @giuseppe @mrunalp @kolyshkin @haircommander

**Comment by mrunalp** [comment]
@harche Those are valid points, but I am fine landing this in master and bake for a bit.

**Comment by haircommander** [comment]
/test integration_crun

provisioning

**Pull request merged**
