### PR TITLE
WIP test CI

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by haircommander** [comment]
```
10:23:47 # time="2021-01-19 15:23:47.412695374Z" level=debug msg="Response error: container create failed: Invalid command \"create\"\n" file="go-grpc-middleware/chain.go:25" id=51d73abb-8e8d-4be8-aac1-ecea6d204b8a name=/runtime.v1alpha2.RuntimeService/RunPodSandbox
```
failure in kata
cc @fidencio @fgiudici @chavafg 

[ref](http://jenkins.katacontainers.io/job/kata-containers-crio-PR/16266/console)

**Comment by fidencio** [comment]
@haircommander, thanks for pointing this out at our direction. It's failing since Yesterday night and the last green one is http://jenkins.katacontainers.io/job/kata-containers-crio-PR/16258/

**Comment by fidencio** [comment]
> ```
> 10:23:47 # time="2021-01-19 15:23:47.412695374Z" level=debug msg="Response error: container create failed: Invalid command \"create\"\n" file="go-grpc-middleware/chain.go:25" id=51d73abb-8e8d-4be8-aac1-ecea6d204b8a name=/runtime.v1alpha2.RuntimeService/RunPodSandbox
> ```
> 
> failure in kata
> cc @fidencio @fgiudici @chavafg
> 
> [ref](http://jenkins.katacontainers.io/job/kata-containers-crio-PR/16266/console)

@chavafg, who has a really good memory, suggested the issue was related to pointing the `2.0-dev` branch as the `main` one for the `kata-containers/tests` repository.  He changed the configurations on Kata Containers Jenkins instance and everything seems to be back to normal, at leat in the jobs I'm monitoring.

@chavafg, yet again, thanks a lot for the help!

**Pull request closed without merging**
