### PR TITLE
Close temporary image in PullImage

### PR DESCRIPTION
**Pull request by m4burns**
Signed-off-by: Marc Burns <m4burns@uwaterloo.ca>

**- What I did**

The `ImageServer` interface in `pkg/storage` documents that images returned by `PrepareImage()` should have `Close()` called. `PullImage()` currently fails to close an image returned by `PrepareImage()`, which causes `/var/tmp` to fill with large temporary files when using at least the `docker-archive` transport. I fixed this issue.

**- How I did it**

I modified the `ImageServer` interface to allow `Close()` to be called on images returned by `PrepareImage()`. I added a deferred call to `Close()` in `PullImage()`.

**- How to verify it**

I updated the unit tests to check that `Close()` is being called as prescribed by the `ImageServer` interface.

**- Description for the changelog**

Fix temporary file leak when using `docker-archive` transport.

### CODE REVIEW

**Comment by haircommander** [comment]
Thanks for the PR! Preliminary scan LGTM, I'll look at it more in depth tomorrow

**Comment by saschagrunert** [comment]
Hey @m4burns :wave:, thanks again for the change, generally it looks reasonable to me. Can you please give me more details on the actual issue? I think the files in `/var/tmp` gets cleaned up in any case, right?

**Comment by m4burns** [comment]
@saschagrunert hi! Sure, here's some more info:

- `/var/tmp` is cleaned up in a "site-specific manner"; it's specified that content should be preserved across reboots and recommended that cleanup occurs less frequently than `/tmp` [1].
- A vanilla `systemd` installation will clean `/var/tmp` every 30 days [2].
- The issue addressed by this PR only arises when using the `docker-archive` transport. The leaked temporary file is opened by the `tarfile` image source used by `docker-archive` [3].
- The issue is that each time an image is pulled, even when the image is already up-to-date, a temporary copy of the image is created in `/var/tmp`.
- When using Kubernetes to schedule a pod that restarts about once an hour with a ~2GB image, our ~100GB disk is full in a couple days.
- This issue could also be addressed by increasing the frequency of `/var/tmp` cleanup, but with sufficient image pull frequency or sufficiently large images this will not be enough. The chance that one of these files will be removed while still in use would also be increased.

Example of the issue arising:

```
[root@pf-1-b ~]# rm /var/tmp/docker-tar*
[root@pf-1-b ~]# crictl pull kn0x.io/assetlib
Image is up to date for kn0x.io/assetlib@sha256:979fed12f580f248b12802de317eb0c5de9e6bdad6dddd8f65d739b896c681af
[root@pf-1-b ~]# ls -lh /var/tmp/docker*
-rw------- 1 root root 1019M Jun  4 10:48 /var/tmp/docker-tar573014836
[root@pf-1-b ~]# crictl pull kn0x.io/assetlib
Image is up to date for kn0x.io/assetlib@sha256:979fed12f580f248b12802de317eb0c5de9e6bdad6dddd8f65d739b896c681af
[root@pf-1-b ~]# ls -lh /var/tmp/docker*
-rw------- 1 root root 1019M Jun  4 10:49 /var/tmp/docker-tar035813102
-rw------- 1 root root 1019M Jun  4 10:48 /var/tmp/docker-tar573014836
[root@pf-1-b ~]# sha1sum /var/tmp/docker*
cab199ec6db31e1802ba8a093b80a350f3a7e8f5  /var/tmp/docker-tar035813102
cab199ec6db31e1802ba8a093b80a350f3a7e8f5  /var/tmp/docker-tar573014836
```

Example of the issue not arising after this MR is applied:

```
[root@pf-1-b ~]# crictl pull kn0x.io/assetlib
Image is up to date for kn0x.io/assetlib@sha256:979fed12f580f248b12802de317eb0c5de9e6bdad6dddd8f65d739b896c681af
[root@pf-1-b ~]# ls -lh /var/tmp/docker*
ls: cannot access '/var/tmp/docker*': No such file or directory
```

[1] https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf
[2] https://github.com/systemd/systemd/blob/master/tmpfiles.d/tmp.conf#L12
[3] https://github.com/cri-o/cri-o/blob/master/vendor/github.com/containers/image/docker/tarfile/src.go#L77

**Comment by saschagrunert** [comment]
@m4burns Cool, thanks for the great explanation!

**Comment by m4burns** [comment]
Looks like I still need a /lgtm to merge. Can one of you issue the command, or should I ask someone else? @haircommander @saschagrunert 

Thanks!

**Pull request merged**
