### PR TITLE
Replace patch-release.go with release.go

### PR DESCRIPTION
**Pull request by olad5**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
- This PR removes the  scripts/release/release.go in favor of scripts/patch-release/patch-release.go to run automated patch releases

#### Does this PR introduce a user-facing change?
No

```release-note
None

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/ok-to-test

**Comment by saschagrunert** [comment]
> I maintain that removing this file means we lose the git history on it. I think it would be better if we used `release.go` instead of `patch-release.go` going forward so we preserve the git history for `release.go`. If other maintainers disagree then this is the last I'll mention the point :)

Right, then let's do it that way @olad5

**Review by saschagrunert — APPROVED** [review]

**Comment by haircommander** [comment]
/lgtm

thanks!

**Comment by kwilczynski** [comment]
/hold

The actual commit message has to be updated to reflect change in direction. Also, please, no semantic commits, it hasn't been a standard here.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
