### PR TITLE
[1.25]Enable block vol mod tests

### PR DESCRIPTION
**Pull request by sohankunkerkar**
#### What type of PR is this?

/kind ci

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
related to https://issues.redhat.com/browse/OCPBUGS-8093
I want to see if we are still hitting this issue.

**Comment by umohnani8** [comment]
changes LGTM
/retest

**Comment by haircommander** [comment]
note: this won't be run on any of the tests that run on this branch as we don't have upstream e2e tests running here. only openshift e2e, which use a different mechanism to choose which tests

**Pull request closed without merging**
