### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**
#### What type of PR is this?

> /kind cleanup
> /kind feature

#### Does this PR introduce a user-facing change?

```release-note
Update nix pin with `make nixpkgs`
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by mrunalp — APPROVED** [review]

**Comment by hswong3i** [comment]
`build-static` is successful, see https://app.circleci.com/pipelines/github/cri-o/cri-o/6597/workflows/b75b9659-3f53-4bff-be66-d0bf48c095b1/jobs/106564

**Review by saschagrunert — APPROVED** [review]
/retest
/lgtm

**Review by saschagrunert — APPROVED** [review]
/ok-to-test
LGTM

**Pull request merged**
