### PR TITLE
Remove check for CI env variable for release-notes and dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
The variable does not seem to be set in GitHub actions therefore we need
to remove it.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by haircommander** [comment]
```
time="2021-03-17T18:38:24Z" level=error msg="error copying docker://k8s.gcr.io/pause:3.2 to dir:/go/src/github.com/cri-o/cri-o/.artifacts/pause-image: Error initializing source docker://k8s.gcr.io/pause:3.2: Get \"https://k8s.gcr.io/v2/pause/manifests/3.2\": dial tcp 173.194.68.82:443: i/o timeout"
```
either pause:3.2 was removed or gcr is flaking

**Comment by saschagrunert** [comment]
> either pause:3.2 was removed or gcr is flaking
At least I can pull it locally

**Comment by haircommander** [comment]
actually

/override ci/prow/e2e-gcp

as this has nothing to do with it, and e2e-agnostic passed

**Comment by saschagrunert** [comment]
/override ci/openshift-jenkins/integration_crun_cgroupv2 ci/kata-jenkins

**Pull request merged**
