### PR TITLE
test/*bats: fixes

### PR DESCRIPTION
**Pull request by kolyshkin**
/kind bug

#### What this PR does / why we need it:

Assorted test fixes and improvements for
 - helpers.bash
 - ~~critest.bats~~ (update: moved to PR #4087)
 - apparmor.bats
 - cgroups.bats

See individual commit messages for details.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Please review commit by commit. See individual commit messages for details.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
many much needed changes :tada: 

seems you have some AppArmor sadness:
https://app.circleci.com/pipelines/github/cri-o/cri-o/5473/workflows/f4f32fa7-7eaa-4b5d-9ccb-70a8481f4f76/jobs/85012

**Comment by kolyshkin** [comment]
Moved commits related to critest.bats to PR #4087 as the changes in there expose the code error which one of them fix.

**Comment by kolyshkin** [comment]
Seems like all the tests are passing now, but the github status was not updated

/retest

**Comment by kolyshkin** [comment]
/retest

I'm not sure what is it with the failed tests, but it's definitely unrelated to my changes

**Pull request merged**
