### PR TITLE
Move server tests to the server package

### PR DESCRIPTION
**Pull request by cynepco3hahue**
#### What type of PR is this?

> /kind api-change
> /kind bug
/kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### What this PR does / why we need it:

It a good practice to have unit tests under the same package
as a code that should be tested.

It allows to:
- get rid of unneeded imports
- to test private consts and variables under unittests
- to test private methods

#### Does this PR introduce a user-facing change?

```release-note
NONE
```
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by kolyshkin** [comment]
> It a good practice to have unit tests under the same package as a code that should be tested.

Depending on approach, we might want to test the code as a black box -- for such cases we use `packagename_test` for the testing package. I am not sure if this was the intention for `server_test` though.

**Comment by cynepco3hahue** [comment]
> Depending on approach, we might want to test the code as a black box -- for such cases we use `packagename_test` for the testing package. I am not sure if this was the intention for `server_test` though.

I see, please give me know if you do not have the intention to change the server approach.

**Comment by haircommander** [comment]
I think both have a use. Unit testing internally is useful for checking things we cannot test from the outside, but a lot of our tests do assume the blackbox approach. I would say we should leave the existing tests as is (maybe move them to a different package directories if it gets too cluttered?) and then add internal tests as needed

**Comment by cynepco3hahue** [comment]
@haircommander Hi thanks for the answer, it makes sense. I will close a PR and will open a new one, once I will have enough additional internal tests.

**Pull request closed without merging**
