### PR TITLE
Update crun to v0.20.1

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Update crun to the latest release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated crun in static binary bundle to v0.20.1
```

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by saschagrunert** [comment]
Updated to the latest release, PTAL @haircommander

**Pull request merged**
