### PR TITLE
Vendor containers/image v4

### PR DESCRIPTION
**Pull request by saschagrunert**
Forward-port of https://github.com/cri-o/cri-o/pull/2874

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.  integration_rhel is being persnickety at the moment.

**Comment by saschagrunert** [comment]
Yeah, but they seem to work when @haircommander is around... :grin:

/test integration_rhel

**Comment by haircommander** [comment]
it's because I spam retest so much :smiley:

**Comment by rhatdan** [comment]
Needs a rebase.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Pull request merged**
