### PR TITLE
bump conmon to 2.0.12

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
bumps conmon to 2.0.12, which fixes a possible race with the kernel resulting in us missing an OOM kill event

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
```

TASK [install Go tools and dependencies] ***************************************
task path: /go/src/github.com/cri-o/cri-o/contrib/test/integration/golang.yml:51
changed: [localhost] => (item=onsi/ginkgo/ginkgo) => {"ansible_loop_var": "item", "changed": true, "cmd": "go get -u \"github.com/onsi/ginkgo/ginkgo\"", "delta": "0:00:05.833738", "end": "2020-03-16 17:47:20.969920", "item": "onsi/ginkgo/ginkgo", "rc": 0, "start": "2020-03-16 17:47:15.136182", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
Killed by signal 15.
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
Build was aborted
```
odd

/retest

**Comment by saschagrunert** [comment]
The bundle job seems not happy. :)

**Comment by saschagrunert** [comment]
Sadly needs a rebase

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM once rebased and happy tests

**Comment by haircommander** [comment]
happy tests :sunglasses:

**Comment by rhatdan** [comment]
/lgtm
But now conmon 2.0.13 is out...

**Pull request merged**
