### PR TITLE
Refactor memory stores to use generics

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This allows to remove one of the two double implementations and provide a generic memory store.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by kwilczynski** [comment]
Perhaps we should move to `sync.Map` here at the same time.

**Comment by saschagrunert** [comment]
> Perhaps we should move to `sync.Map` here at the same time.

Good point, doing that.

**Pull request merged**
