### PR TITLE
storage: succeed in DeleteContainer if container is unknown

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
/cherry-pick release-1.21

this is part of the series including
https://github.com/cri-o/cri-o/pull/4966 and https://github.com/cri-o/cri-o/pull/4900

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests.

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
```
TASK [build conmon] ************************************************************
task path: /go/src/github.com/cri-o/cri-o/contrib/test/integration/build/conmon.yml:9
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/bin/make", "msg": "In file included from src/seccomp_notify.h:4:0,\n                 from src/conmon.c:21:\nsrc/seccomp_notify_plugin.h:32:15: error: ‘struct seccomp_notif_resp’ declared inside parameter list [-Werror]\n        struct seccomp_notif_resp *sresp, int seccomp_fd, int *handled);\n               ^\nsrc/seccomp_notify_plugin.h:32:15: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]\nsrc/seccomp_notify_plugin.h:32:15: error: ‘struct seccomp_notif’ declared inside parameter list [-Werror]\nsrc/seccomp_notify_plugin.h:32:15: error: ‘struct seccomp_notif_sizes’ declared inside parameter list [-Werror]\ncc1: all warnings being treated as errors\nmake: *** [src/conmon.o] Error 1", "rc": 2, "stderr": "In file included from src/seccomp_notify.h:4:0,\n                 from src/conmon.c:21:\nsrc/seccomp_notify_plugin.h:32:15: error: ‘struct seccomp_notif_resp’ declared inside parameter list [-Werror]\n        struct seccomp_notif_resp *sresp, int seccomp_fd, int *handled);\n               ^\nsrc/seccomp_notify_plugin.h:32:15: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]\nsrc/seccomp_notify_plugin.h:32:15: error: ‘struct seccomp_notif’ declared inside parameter list [-Werror]\nsrc/seccomp_notify_plugin.h:32:15: error: ‘struct seccomp_notif_sizes’ declared inside parameter list [-Werror]\ncc1: all warnings being treated as errors\nmake: *** [src/conmon.o] Error 1\n", "stderr_lines": ["In file included from src/seccomp_notify.h:4:0,", "                 from src/conmon.c:21:", "src/seccomp_notify_plugin.h:32:15: error: ‘struct seccomp_notif_resp’ declared inside parameter list [-Werror]", "        struct seccomp_notif_resp *sresp, int seccomp_fd, int *handled);", "               ^", "src/seccomp_notify_plugin.h:32:15: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]", "src/seccomp_notify_plugin.h:32:15: error: ‘struct seccomp_notif’ declared inside parameter list [-Werror]", "src/seccomp_notify_plugin.h:32:15: error: ‘struct seccomp_notif_sizes’ declared inside parameter list [-Werror]", "cc1: all warnings being treated as errors", "make: *** [src/conmon.o] Error 1"], "stdout": "cc -std=c99 -Os -Wall -Wextra -Werror -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -DVERSION=\\\"2.0.30-dev\\\" -DGIT_COMMIT=\\\"\"75e067ed42fe44e7db00ca732c08540058e5e5fc\"\\\"   -D USE_JOURNALD=0   -D USE_SECCOMP=1  -o src/conmon.o -c src/conmon.c\n", "stdout_lines": ["cc -std=c99 -Os -Wall -Wextra -Werror -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -DVERSION=\\\"2.0.30-dev\\\" -DGIT_COMMIT=\\\"\"75e067ed42fe44e7db00ca732c08540058e5e5fc\"\\\"   -D USE_JOURNALD=0   -D USE_SECCOMP=1  -o src/conmon.o -c src/conmon.c"]}
	to retry, use: --limit @/go/src/github.com/cri-o/cri-o/contrib/test/integration/main.retry

```
it seems https://github.com/containers/conmon/pull/190 broke us

**Pull request merged**
