### PR TITLE
contrib/ci: remove duplicate directory

### PR DESCRIPTION
**Pull request by haircommander**
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
https://github.com/openshift/release/pull/45228 is an alternative, let's try that before this

**Comment by saschagrunert** [comment]
> [openshift/release#45228](https://github.com/openshift/release/pull/45228) is an alternative, let's try that before this

This does not seem to have the right effect.

**Comment by haircommander** [comment]
rebased, WDYT @sohankunkerkar ?

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Pull request merged**
