### PR TITLE
Shellcheck misc

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Misc shellcheck fixes and related improvements.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Please see individual commits for details.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM
/retest

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by kolyshkin** [comment]
Rebased on top of the current master to maybe fix the CI

**Comment by kolyshkin** [comment]
@mrunalp @haircommander @umohnani8 PTAL

**Comment by kolyshkin** [comment]
CI is all green now, except that `tide` status is not updated. Is there a way to force-merge this?

**Pull request merged**
