### PR TITLE
[1.22] Backport crio storage wipe

### PR DESCRIPTION
**Pull request by wgahnagl**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
cherry-pick of  #6022 
#### Which issue(s) this PR fixes:
https://issues.redhat.com/browse/OCPBUGS-3708 

#### Does this PR introduce a user-facing change?

```release-note
Update `version-file-persist` to be empty by default, and do not wipe images when it is so.
```

### CODE REVIEW

**Comment by haircommander** [comment]
I think you need to run `make docs-generation completions`

**Comment by jrvaldes** [comment]
@cri-o/cri-o-maintainers    As a follow-up for https://github.com/cri-o/cri-o/pull/6544#issuecomment-1396602162, does it makes sense to close this PR as 1.22 is out of support ?

**Comment by jrvaldes** [comment]
/close 

to leverage https://github.com/cri-o/cri-o/pull/6612

**Pull request closed without merging**
