### PR TITLE
Bump OpenShift CI cri-tools version and fix build path

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

We changed the output build path in cri-tools a while ago which would cause always falling back to the wrong version.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by fgiudici** [comment]
lgtm

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
/override ci/prow/e2e-agnostic

change is unrelated

**Pull request merged**
