### PR TITLE
[1.14] Add config to run conmon under a custom cgroup slice    

### PR DESCRIPTION
**Pull request by haircommander**
Including:
            add config value to run conmon under a custom cgroup slice
            add cli flag for --conmon-cgroup
            add config validation for conmon cgroup
            test: add test for conmon cgroup
            sandbox_run: log warning if we can't find the slice
            default to system.slice

### CODE REVIEW

**Comment by haircommander** [comment]
needs https://github.com/cri-o/cri-o/pull/2971

**Comment by haircommander** [comment]
@chavafg kata-jenkins is reliably funky on 1.14. can you PTAL :slightly_smiling_face:

**Comment by chavafg** [comment]
sure, taking a look :) 

I see that it failed doing an exec --sync:
```
run crictl exec --sync "$ctr_id" false
echo "$output"
[ "$status" -ne 0 ]
```

And the log of the exec:
```
08:49:03 # time="2019-12-18 14:49:01.548990481Z" level=info msg="Exec'd [false] in //"
08:49:03 # time="2019-12-18 14:49:01.549010282Z" level=debug msg="ExecSyncResponse: &ExecSyncResponse{Stdout:[],Stderr:[],ExitCode:1,}"
08:49:03 # 
08:49:03 # 
08:49:03 # Exit code: 1
```
but it seems that the actual return code of the exec is not `1`.

Will try to reproduce locally and will update

**Comment by chavafg** [comment]
@haircommander can you send a retest for kata please?

**Comment by haircommander** [comment]
thanks @chavafg!

**Comment by chavafg** [comment]
CI passed 😃

**Comment by rhatdan** [comment]
@haircommander Still need this?
/approve

**Comment by haircommander** [comment]
No I don't think we do, this should be replaced with https://github.com/cri-o/cri-o/pull/3378

**Pull request closed without merging**
