### PR TITLE
test: do not use CRI stats

### PR DESCRIPTION
**Pull request by haircommander**
as we're not testing what most production workloads use right now.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind other
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
I suspect these will fail

**Comment by haircommander** [comment]
/retest
prow cannot handle `'`

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by haircommander** [comment]
we test it with openshift tests, and tests in upstream kube

**Pull request closed without merging**
