### PR TITLE
Update runc test dependency to v1.0.0-rc8

### PR DESCRIPTION
**Pull request by saschagrunert**
Hey, if there are no concerns I would like to just use the latest static runc binary from GitHub for integration testing.

### CODE REVIEW

**Comment by saschagrunert** [comment]
I would like to leave the ami updates out of scope for now. We have to follow up on this with the help of someone who has direct access to the machines.

**Comment by rhatdan** [comment]
LGTM
@umohnani8 @haircommander @mrunalp @giuseppe PTAL

**Pull request merged**
