### PR TITLE
test: image-related fixes+improvements

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- tidy image prefetch and fix a few minor issues;
- rewrite `image_remove` test to dedup the code and fix some issues;
- fix shellcheck warnings while at it;

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Please review commit-by-commit.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by kolyshkin** [comment]
No logs for presumably failed integration-crun

/retest

**Review by saschagrunert — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
