### PR TITLE
Upload every successful built bundle to the GCS bucket

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
We now upload every successfully built release bundle to a dedicated
location on our Google Cloud Bucket, which is mentioned in the README as
well.

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
```release-note
- Provide the latest release bundle via a Google Cloud Storage Bucket at:
  https://console.cloud.google.com/storage/browser/k8s-conform-cri-o/artifacts
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
I have no permissions to edit files on that bucket, but I'm working on getting those as well. Then we could provide a convenience URL to grab the latest bundle.

**Comment by saschagrunert** [comment]
Ready for review.

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons

**Pull request merged**
