### PR TITLE
[1.16] bump containers image to v5.1.0

### PR DESCRIPTION
**Pull request by lumjjb**
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

**- What I did**

Bump containers image to v5.1.0

Testing to see effort for bumping to v5.1.0

**- How I did it**

```
go get github.com/containers/image/v5@v5.1.0
make vendor
```

**- How to verify it**
Check go.sum.

**- Description for the changelog**

Bump containers image to v5.1.0

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hey @lumjjb, can you run `make vendor` on your machine, it looks like that the corresponding [CI job](https://circleci.com/gh/cri-o/cri-o/26943?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) failed.

**Comment by lumjjb** [comment]
@saschagrunert I was having issues with go 1.13, for some reason using go 1.13 and 1.12 was giving me different output. I'm going to try to do this again from the start with go 1.12.

**Comment by haircommander** [comment]
kata-jenkins is known to be broken in this branch btw
e2e-aws should pass though...

**Comment by lumjjb** [comment]
@haircommander  Looks like it's passing now! 🎉

**Comment by haircommander** [comment]
LGTM, thanks for sticking through this @lumjjb

**Pull request merged**
