### PR TITLE
Update bats to v1.3.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Use the latest release of bats for integration testing.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
can we update in contrib/test/integration/build/bats.yml as well

**Comment by haircommander** [comment]
or is it in main.yml.. I forget

**Comment by saschagrunert** [comment]
> can we update in contrib/test/integration/build/bats.yml as well

Yep, updated it as well. :+1:

**Pull request merged**
