### PR TITLE
fix checking in openpgp_tag.sh

### PR DESCRIPTION
**Pull request by rockmenjack**
a handy fix, see https://github.com/cri-o/cri-o/issues/5219

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/ok-to-test

Thank you @rockmenjack

**Comment by saschagrunert** [comment]
@rockmenjack the verify/docs CI job fails, I think we can solve it by adding something like
https://github.com/cri-o/cri-o/blob/master/.github/workflows/integration.yml#L27
to
https://github.com/cri-o/cri-o/blob/177ed5f1a66294a69764676a864777bbfa4d09c4/.github/workflows/verify.yml#L38-L42

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
