### PR TITLE
Remove bashism in sh script

### LINKED ISSUE #5279: Static ./install script includes bashisms but runs sh
The `./install` script included with the static binaries runs `#!/usr/bin/env sh` and yet has bash-specific constructs.

https://github.com/cri-o/cri-o/blob/8118d4a58693d1c7211b5fa73df1be2db1f9404f/contrib/bundle/build#L96

Running on (eg) Armbian (basically Debian), which defaults to sh -> dash:

```console
$ sudo ./install
[...]
+ install -D -m 644 -t /usr/local/lib/systemd/system contrib/crio.service
+ install -D -m 755 -t /usr/local/bin bin/pinns
+ install -D -m 755 -t /usr/local/bin bin/crun
+ [[ arm64 == amd64 ]]
./install: 49: [[: not found
```

### PR DESCRIPTION
**Pull request by anguslees**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #5279

#### Special notes for your reviewer:

Alternatively, we can change the `#!` line to run bash.  But maximising portability seemed like the right choice here.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Good catch @anguslees! May I ask you to sign the commit via `git commit --amend --no-edit -s` and force-push again?

**Comment by haircommander** [comment]
can you also run `make get-script` please?
/ok-to-test

**Comment by TomSweeneyRedHat** [comment]
LGTM
once tests are hip

**Comment by haircommander** [comment]
thank you @anguslees for the submission!

**Pull request merged**
