### PR TITLE
oci_volumes: require crictl that can request OCI volumes

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind failing-test
#### What this PR does / why we need it:
alongside https://github.com/cri-o/cri-o/pull/8407 
fixes https://github.com/cri-o/cri-o/issues/8404

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
I think we still want https://github.com/cri-o/cri-o/pull/8407 but I think we also want this to immediately fix (the other requires a CI image rebuild)

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
seems like a registry flake
/retest

**Review by saschagrunert — APPROVED** [review]

**Review by littlejawa — APPROVED** [review]
The remaining issue in integration test is from https://github.com/cri-o/cri-o/issues/8389, unrelated to this PR.

/lgtm

**Pull request merged**
