### PR TITLE
Sync changes of PR#7719

### PR DESCRIPTION
**Pull request by hasan4791**
#### What type of PR is this?
/kind other

#### What this PR does / why we need it:
Sync the changes to _unsupported.go file from PR #7719 and other defaults as well. Since the secComp.go file is tag by linux & cgo, vscode isn't happy about adding cgo build tag which throws lot of errors in the podman deps from vendor and its really hard to segregate the error. These changes should make vscode happy & clean.

#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by kwilczynski** [comment]
@hasan4791 nice catch! Thank you!

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
