### PR TITLE
Automatically retrieve digest in test image builds

### PR DESCRIPTION
**Pull request by saschagrunert**
By using `buildah manifest inspect docker://golang:$TAG` we can
now automatically retrieve the latest digest for the available golang
base image architecture.

The dependencies have been updated as well.

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM

**Comment by saschagrunert** [comment]
Rebased on top of the latest master to fix the CI issues

**Comment by TomSweeneyRedHat** [comment]
Happy green tests on this too, just needs a /lgtm

**Pull request merged**
