### PR TITLE
[1.14] test: add changes required for fedora 30 AMI

### PR DESCRIPTION
**Pull request by haircommander**
Including removing our own debugging callback
change from package to a manual shell call (because python2-dnf is sunsetted, but we still need python2 for oct)
disable nodev for userns test
Signed-off-by: Peter Hunt pehunt@redhat.com

### CODE REVIEW

**Comment by haircommander** [comment]
I reverted the ami switch, so this passed against the old ami and isn't testing anything. 
/hold

**Comment by giuseppe** [comment]
LGTM

**Comment by haircommander** [comment]
/hold cancel

we will need this to merge PRs now that we switched to f30

**Comment by haircommander** [comment]
I added a cherry-pick of https://github.com/cri-o/cri-o/pull/2898 too

**Comment by umohnani8** [comment]
Looks like e2e-fedra is failing due to a test failing with permission denied.

**Comment by haircommander** [comment]
/retest
@saschagrunert PTAL, e2e_rhel has passed at least

**Comment by haircommander** [comment]
one e2e test passing is better than none, I am going to merge this

**Pull request merged**
