### PR TITLE
Update nixpkgs

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
Bumping a bunch of important dependencies:

```
Version changes:
[U.]  #01  audit               3.1.1, 3.1.1.tar.gz -> 3.1.2, 3.1.2.tar.gz
[C.]  #02  gcc                 12-gfortran-driving.patch, 12-no-sys-dirs.patch, 12.3.0, 12.3.0.tar.xz -> 12-no-sys-dirs.patch, 12.3.0, 12.3.0.tar.xz
[U.]  #03  git                 2.41.0.tar.xz -> 2.42.0.tar.xz
[U*]  #04  git-minimal         2.41.0 -> 2.42.0
[C*]  #05  go                  1.17.13-linux-amd64-bootstrap, 1.20.7, 1.21.0, 1.21.0-linux-amd64-bootstrap -> 1.17.13-linux-amd64-bootstrap, 1.20.8, 1.21.0-linux-amd64-bootstrap, 1.21.1
[U*]  #06  gpgme               1.21.0, 1.21.0.tar.bz2 -> 1.22.0, 1.22.0.tar.bz2
[U.]  #07  gzip                1.12, 1.12.tar.xz -> 1.13, 1.13.tar.xz
[U.]  #08  libxml2             2.11.4, 2.11.4.tar.xz -> 2.11.5, 2.11.5.tar.xz
[U.]  #09  mpfr                4.2.0 x2, 4.2.0.tar.xz -> 4.2.1 x2, 4.2.1.tar.xz
[U.]  #10  util-linux          2.39.1.tar.xz -> 2.39.2.tar.xz
[U.]  #11  util-linux-minimal  2.39.1 -> 2.39.2
[U.]  #12  zlib                1.2.13 x3, 1.2.13.tar.gz -> 1.3 x3, 1.3.tar.gz
Added packages:
[A.]  #1  go1.20.8.src.tar.gz  <none>
[A.]  #2  go1.21.1.src.tar.gz  <none>
Removed packages:
[R.]  #1  000-fix-static-attribute-malloc.diff  <none>
[R.]  #2  001-ignore-flexible-array.patch       <none>
[R.]  #3  gnat-cflags                           11.patch
[R.]  #4  go1.20.7.src.tar.gz                   <none>
[R.]  #5  go1.21.0.src.tar.gz                   <none>
```
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Build issues are related to https://github.com/NixOS/nixpkgs/pull/254497

**Comment by haircommander** [comment]
I wonder if we could have a bot that does this :thinking:

**Comment by saschagrunert** [comment]
> I wonder if we could have a bot that does this 🤔

A cronjob would work, maybe monthly?

**Comment by haircommander** [comment]
> A cronjob would work, maybe monthly?

wdyt about weekly or semi-weekly? I suppose we only need to do it before we recut a new patch version...

**Pull request closed without merging**
