### PR TITLE
Publish release notes on gh-pages branch

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Target is to publish the continuously built release notes on a gh-pages
branch, which can be published via GitHub pages.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM

**Comment by saschagrunert** [comment]
This is ready to be merged since the gh-pages branch is now up-to-date

**Comment by saschagrunert** [comment]
I'm seeing green tests incoming :grin:

**Comment by haircommander** [comment]
LGTM, where can we look at the release notes once this is merged

**Comment by saschagrunert** [comment]
> LGTM, where can we look at the release notes once this is merged

Hopefully here: https://cri-o.github.io/cri-o

The “update gh-pages” branch code part will only be executed on release and the master branch. If everything works well, then I’ll follow up with an update in the README.md

**Comment by saschagrunert** [comment]
/retest

🙏

**Comment by saschagrunert** [comment]
Tide seems to be stuck here

**Comment by rhatdan** [comment]
No idea how to restart it.
/retry

**Comment by saschagrunert** [comment]
Had to rebase on top of the latest master branch

**Comment by haircommander** [comment]
/lgtm
/retest

e2e_rhel seems stalled, maybe retest will trigger it

**Comment by haircommander** [comment]
today's favorite segfault rearing its ugly head again :) 
/retest

**Pull request merged**
