### PR TITLE
hack/build-rpms.sh: fix yum-builddep failures

### PR DESCRIPTION
**Pull request by kolyshkin**
/kind ci
/kind failing-test
/kind flake

#### What this PR does / why we need it:

This tries to solve a failure in building rpms, and consists of two fixes.

1. Looking into cri-o CI, this error seems common:

> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2600:1f16:c1:5e03:a992:8ee1:99d2:6f8: Network is unreachable"
> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2600:1f16:c1:5e03:a992:8ee1:99d2:6f8: Network is unreachable"
> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] HTTPS Error 301 - Moved Permanently
> [ERROR] hack/build-rpms.sh:31: `yum-builddep -y "${OS_RPM_SPECFILE}"` exited with status 1.

Apparently, vault.centos.org resolves to both IPv4 and IPv6 addresses,
and one of the addresses is used (randomly, I presume). If the node
does not have IPv6 connectivity (as it seems to be the case), as a
result we have 50% chance of failure.

Work around this by asking yum to only use IPv4 for address resolving.

2. vault.centos.org is super slow, resulting in numerous timeouts, often fatal:
    
> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 12] Timeout on http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 12] Timeout on http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 12] Timeout on http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 12] Timeout on http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
> [ERROR] hack/build-rpms.sh:38: `yum-builddep -y "${OS_RPM_SPECFILE}"` exited with status 1.
    
Let's use mirrors.kernel.org instead.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
Seeing the same failure :(

http://vault.centos.org/centos/7/os/Source/repodata/repomd...:1f13:2e7:2901:d2b0:c3b2:9347:934c: Network is unreachable"

**Comment by kolyshkin** [comment]
OK, this is centos 7 source repo, which is configured without mirrors, so yum has no alternative but to use vault.centos.org.

And vault.centos.org is super slow for some reason. I tried it locally and also see timeouts.

Let's try to use kernel.org mirror which has the sources, too.

**Comment by kolyshkin** [comment]
All right, that finally works! @haircommander PTAL

**Comment by haircommander** [comment]
amazing! thanks for digging into this @kolyshkin 

/approve

@cri-o/cri-o-maintainers PTAL

**Comment by TomSweeneyRedHat** [comment]
Pretty slick @kolyshkin 
LGTM

**Pull request merged**
