### PR TITLE
[release-1.26] cherry-pick related fixes, update NRI deps to 0.3.0.

### PR DESCRIPTION
**Pull request by klihub**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Cherry-pick of #6684:
We have to pin nix to v2.13.3 to avoid having the regression mentioned in [cachix/cachix-action#138 (comment)].(https://github.com/cachix/cachix-action/issues/138#issuecomment-1448952201)
This should fix the static builds.

Cherry-pick of #6648:
Update NRI dependency. The global configuration file in NRI has been removed. This makes enabling NRI a less awkward process (eliminating the need to create at least an empty configuration file). 

Cherry-pick of #6645:
If `nil` returned from nri call, set the current `LinuxContainerResources` data.
Integration test: Enabling nri in the server config.
If the protection is valid, tests should pass.
Additional info in #6642 

#### Which issue(s) this PR fixes:

#6642 (for release 1.26)

#### Does this PR introduce a user-facing change?

```release-note
action required ... if running with experimental NRI support enabled. NRI related block in the configuration file needs to be updated.

The NRI-related configuration and command line options have been updated to reflect the corresponding changes in NRI itself. In particular,
- remove 'nri_config_file' configuration file and '--nri-config-file' command line options
- add 'nri_plugin_config_dir' configuration and '--nri-plugin-config-dir' command line options to specify directory to scan for configuration of plugins pre-launched by the runtime
- add 'nri_disable_connections' configuration and '--nri-disable-connections' command line options to disable connections from externally launched plugins
- add 'nri_plugin_registration_timeout' configuration and '--nri-plugin-registration-timeout' command line options to allow overriding the default plugin registration timeout
- add 'nri_plugin_request_timeout' configuration and '--nri-plugin-request-timeout' command line options to allow overriding the default plugin request handling timeout
```

### CODE REVIEW

**Comment by klihub** [comment]
@haircommander Is this something we'd like to get in the 1.26 releases ?
@Tal-or PTAL

**Comment by Tal-or** [comment]
@klihub I don't see the changes in https://github.com/cri-o/cri-o/pull/6702/commits/3c1bb518cd1f2f07a5a859489b8f84e0fab3f2b2#diff-30fbdf6827c910404329a03cfac75f65882bb269e0e553e2f03baa2f57805318 ([vendor/github.com/containerd/nri/pkg/runtime-tools/generate/generate.go](https://github.com/cri-o/cri-o/commit/3c1bb518cd1f2f07a5a859489b8f84e0fab3f2b2#diff-30fbdf6827c910404329a03cfac75f65882bb269e0e553e2f03baa2f57805318)
under the master branch

**Comment by klihub** [comment]
> @klihub I don't see the changes in [3c1bb51#diff-30fbdf6827c910404329a03cfac75f65882bb269e0e553e2f03baa2f57805318](https://github.com/cri-o/cri-o/commit/3c1bb518cd1f2f07a5a859489b8f84e0fab3f2b2#diff-30fbdf6827c910404329a03cfac75f65882bb269e0e553e2f03baa2f57805318) ([vendor/github.com/containerd/nri/pkg/runtime-tools/generate/generate.go](https://github.com/cri-o/cri-o/commit/3c1bb518cd1f2f07a5a859489b8f84e0fab3f2b2#diff-30fbdf6827c910404329a03cfac75f65882bb269e0e553e2f03baa2f57805318)) under the master branch

I think those are pending for merge in #6682 .

**Comment by Tal-or** [comment]
> > @klihub I don't see the changes in [3c1bb51#diff-30fbdf6827c910404329a03cfac75f65882bb269e0e553e2f03baa2f57805318](https://github.com/cri-o/cri-o/commit/3c1bb518cd1f2f07a5a859489b8f84e0fab3f2b2#diff-30fbdf6827c910404329a03cfac75f65882bb269e0e553e2f03baa2f57805318) ([vendor/github.com/containerd/nri/pkg/runtime-tools/generate/generate.go](https://github.com/cri-o/cri-o/commit/3c1bb518cd1f2f07a5a859489b8f84e0fab3f2b2#diff-30fbdf6827c910404329a03cfac75f65882bb269e0e553e2f03baa2f57805318)) under the master branch
> 
> @Tal-or I think those are pending for merge in #6682 .

That's what I was looking for. Thanks!

**Comment by haircommander** [comment]
let's make sure to get https://github.com/cri-o/cri-o/pull/6682 in first

/hold

**Comment by saschagrunert** [comment]
https://github.com/cri-o/cri-o/pull/6682 merged
/unhold

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
