### PR TITLE
Add shell completion support

### PR DESCRIPTION
**Pull request by saschagrunert**
This adds generic bash, fish and zsh shell completion support via code
generation. The generated code is part of the repository and can be
installed into the correct locations via `make install`.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by haircommander** [comment]
/lgtm
as a follow up, we should add a circle ci target that runs the completions and checks if the tree is dirty (similar to the lint check or conmon config check) so we keep the completions up to date.

**Comment by saschagrunert** [comment]
> /lgtm
> as a follow up, we should add a circle ci target that runs the completions and checks if the tree is dirty (similar to the lint check or conmon config check) so we keep the completions up to date.

Yep, I can add this as well.

**Pull request merged**
