### PR TITLE
Switch to updated version of creack/pty

### LINKED ISSUE #4189: Executing commands in containers with --tty option results in error.
**Description**

Using cricitl exec -it *anycommand* in any container fails with error:

set 13 11:04:38 k8s-worker-2.k8s.lab crio[10506]: E0913 11:04:38.180305   10506 exec.go:71] error executing command in container: fork/exec /usr/bin/runc: Setctty set but Ctty not valid in child

**Steps to reproduce the issue:**

1. run crictl exec -it anycommand in anycontainer
 

**Describe the results you received:**

This happens in Kubernetes 1.19 with kubectl exec: 
set 13 11:04:38 k8s-worker-2.k8s.lab crio[10506]: E0913 11:04:38.180305   10506 exec.go:71] error executing command in container: fork/exec /usr/bin/runc: Setctty set but Ctty not valid in child

This is the same on the host:

[kube@k8s-worker-2 ~]$ sudo crictl exec -it 968e74ed4204f sh
FATA[0000] execing command in container failed: Internal error occurred: error executing command in container: fork/exec /usr/bin/runc: Setctty set but Ctty not valid in child

**Describe the results you expected:**
The command running in the container

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
[kube@k8s-worker-2 ~]$ crio version
Version:       1.18.3
GitCommit:     61de18161fb4ccda720768c001713592b5a04e46
GitTreeState:  clean
BuildDate:     2020-09-11T03:11:20Z
GoVersion:     go1.15
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Vms

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Looks like there is a regression which does not allow to run exec any
more when compiling CRI-O with newer go versions.

#### Which issue(s) this PR fixes:

Might fix #4189, https://github.com/kubernetes/kubernetes/issues/94750
Related to https://github.com/cri-o/cri-o/issues/4110
Backport of https://github.com/cri-o/cri-o/pull/4111
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
- Fixed regression where it was not able to run exec any more when compiling CRI-O with newer go versions
```

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
