### PR TITLE
Do not mark `kind/feature` issues as stale

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Feature requests should never become stale
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kwilczynski you need to `/lgtm`, my PR's are always `approved` on creation.

**Comment by kwilczynski** [comment]
> @kwilczynski you need to `/lgtm` if you're fine with the changes. My PR's are always `approved` on creation. 😇

I thought we enabled some option recently so that /approve has the same function as /lgtm? :smile:

**Comment by saschagrunert** [comment]
@kwilczynski Positive github review will act as `/lgtm`, yes.

**Pull request merged**
