### PR TITLE
[release-1.29] Bump ocicrypt to v1.1.10

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind dependency-change

#### What this PR does / why we need it:
Bump ocicrypt to v1.1.10 to fix potential issue with go-jose.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
https://github.com/cri-o/cri-o/actions/runs/8805530037/job/24168293660?pr=8063
I think we might need to bump up the priority of [cri-o/cri-o issue #7275](https://github.com/cri-o/cri-o/issues/7275).

**Comment by kannon92** [comment]
@sohankunkerkar should we disable the cyclo lint for this file?

**Comment by kannon92** [comment]
Added:

```
  gocyclo:
    min-complexity: 162
```

To this PR. It only fails for 1.29 so not sure backporting a refactor.

**Comment by kannon92** [comment]
@CodiumAI-Agent /review

**Comment by kannon92** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by saschagrunert — APPROVED** [review]

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Comment by kwilczynski** [comment]
Related:

- https://github.com/cri-o/cri-o/pull/7876

**Pull request merged**
