### PR TITLE
Vendor Kubernetes v1.15.0

### PR DESCRIPTION
**Pull request by saschagrunert**
This PR vendors the final version of 1.15:
https://github.com/kubernetes/kubernetes/releases/tag/v1.15.0

### CODE REVIEW

**Comment by rhatdan** [comment]
/retest
LGTM

**Comment by haircommander** [comment]
/retest
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by umohnani8** [comment]
LGTM

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch to get in the latest CI fixes.

**Pull request merged**
