### PR TITLE
Update CNI plugins to v1.2.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Update CNI plugins to their latest release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated CNI plugins to v1.2.0.
```

### CODE REVIEW

**Comment by haircommander** [comment]
would you also add a commit to check changing the bridge plugin config from 0.3.1 doesn't break things?

**Comment by haircommander** [comment]
also, while you're there, can you bring back https://github.com/cri-o/cri-o/pull/6273/ (the patch was accidentally reverted)

**Comment by meierra** [comment]
Just some quick feedback and testing... I've been getting parsing errors while using the default loopback.conflist.

First was: 
- error parsing configuration list: no 'name' key

Thus I reached out to have https://github.com/cri-o/cri-o/pull/6273 brought back, but while testing now, just adding a name key does not fully resolve,
Second error is:
- error parsing configuration list: no 'plugins' key

If I change the filename to loopback.conf then it does not complain, not sure if the right solution is to rename the file back to .conf or add all the required keys for .conflist?

**Comment by meierra** [comment]
little bit more troubleshooting, (sorry I'm very new at this) seems that this configuration works with conflist:
{
    "cniVersion": "1.0.0",
    "name": "loopback",
    "plugins": [
        {
            "type": "loopback"
        }
    ]
}

Seems that according to spec the plugin's used need to be in a list:
- plugins (list): A list of CNI plugins and their configuration, which is a list of plugin configuration objects.

Hope this helps!

**Comment by saschagrunert** [comment]
Thank you for the pointers @meierra and @haircommander, indeed it looks like that the new config works as expected. Updated as suggested.

**Comment by meierra** [comment]
@saschagrunert thanks, just check, I believe there may still be a typo in the correction, looks like the key "type" is repeated twice
image

the first instance should be "name"

**Comment by saschagrunert** [comment]
> @saschagrunert thanks, just check, I believe there may still be a typo in the correction, looks like the key "type" is repeated twice image
> 
> the first instance should be "name"

Good catch! Fixed as suggested :+1:

**Comment by haircommander** [comment]
one more, can you pick https://github.com/cri-o/cri-o/pull/6496/files to make sure 1.2.0 works as we want?

**Comment by saschagrunert** [comment]
> one more, can you pick https://github.com/cri-o/cri-o/pull/6496/files to make sure 1.2.0 works as we want?

Absolutely, let's see how that works out.

**Comment by haircommander** [comment]
woo! 

/override ci/prow/ci-rhel-integration
/override ci/prow/ci-e2e-conmonrs
/override ci/kata-jenkins

/lgtm

**Pull request merged**
