### PR TITLE
Don't fail CI on GitHub pages push

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
Updating the [release notes GitHub pages](https://cri-o.github.io/cri-o) can lead into merge conflicts if multiple jobs run on a single branch in parallel (for example for merge commits and tags). We do not consider this as fatal error any more, because we need the release notes output for the next CI steps.

Failure ref: https://github.com/cri-o/cri-o/actions/runs/9350292608/job/25733441349#step:5:271

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
Makes sense :+1: 

/approve
/lgtm

**Comment by saschagrunert** [comment]
/override ci/prow/ci-cgroupv2-integration
/override ci/prow/ci-fedora-critest

Not prow related

**Pull request merged**
