### PR TITLE
OCPBUGS-13980: [1.27] vendor: bump runc to 1.1.6

### PR DESCRIPTION
**Pull request by haircommander**
to not take init cgroup into account

#### Which issue(s) this PR fixes:
/kind bug

#### Special notes for your reviewer:
this only affects cri-o when it's in a separate cgroup from the root

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by haircommander** [comment]
actually, this does nothing because of the replace statement for libcontainer in our go.mod. This was done because podman fails to compile with newer libcontainer, which is being fixed in https://github.com/containers/podman/pull/19101

**Comment by haircommander** [comment]
cherry-picked https://github.com/cri-o/cri-o/pull/7120/files

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Pull request merged**
