### PR TITLE
readme: drop support for unsupported branches

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
we only support n-3 versions. now that 1.18 is out, let's drop support through 1.15
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by haircommander** [comment]
test fixes [here](https://github.com/cri-o/cri-o/pull/3643)

**Comment by saschagrunert** [comment]
Please rebase on top of the latest master to fix the test issues

**Pull request merged**
