### PR TITLE
[gitpod] use latest workspace full

### LINKED ISSUE #5664: Compilation fails on gitpod
### What happened?

Trying to compile cri-o in gitpod fails.

```
go: finding k8s.io/kubernetes/staging/src/k8s.io/mount-utils v0.0.0-20211207180839-ab69524f795c
# internal/race
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# internal/goexperiment
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# runtime/internal/sys
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# internal/unsafeheader
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# unicode/utf8
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# internal/itoa
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# crypto/internal/subtle
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# crypto/subtle
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# internal/nettrace
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# github.com/ulikunitz/xz/internal/hash
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# container/list
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# github.com/containers/common/version
compile: version "go1.17.5" does not match go tool version "go1.13.8"
note: module requires Go 1.15
# internal/abi
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# k8s.io/apimachinery/pkg/selection
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# github.com/google/go-cmp/cmp/internal/flags
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# k8s.io/apimachinery/pkg/types
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# runtime/internal/atomic
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# internal/cpu
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# vendor/golang.org/x/crypto/internal/subtle
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# github.com/intel/goresctrl/pkg/kubernetes
compile: version "go1.17.5" does not match go tool version "go1.13.8"
note: module requires Go 1.16
# github.com/containers/conmon/runner/config
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# google.golang.org/grpc/attributes
compile: version "go1.17.5" does not match go tool version "go1.13.8"
note: module requires Go 1.14
# google.golang.org/protobuf/internal/flags
compile: version "go1.17.5" does not match go tool version "go1.13.8"
# google.golang.org/grpc/serviceconfig
compile: version "go1.17.5" does not match go tool version "go1.13.8"
note: module requires Go 1.14
# math/bits
```

Probably `go` needs to be bumped up at https://github.com/cri-o/cri-o/blob/main/.gitpod.Dockerfile#L3

/cc @JanKoehnlein  

### What did you expect to happen?

Compilation to succeed. 

### How can we reproduce it (as minimally and precisely as possible)?

Launch gitpod and try to compile 

### Anything else we need to know?

_No response_

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl --version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

### PR DESCRIPTION
**Pull request by JanKoehnlein**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR makes this repo compile in Gitpod again.
- Use the latest version of the `gitpod/workspace-full` image by explicit tag to get the latest Go version
- added package `libgpgme-dev` to fix compile error

#### Which issue(s) this PR fixes:

Fixes #5664

#### Special notes for your reviewer:
Rebuilding the new docker image may take a few minutes. 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve

thank you @JanKoehnlein !

**Comment by TomSweeneyRedHat** [comment]
LGTM
slight concern that the date image in the Dockerfile might go wonky 6 months from now or whatever.

**Review by saschagrunert — APPROVED** [review]
/lgtm
/retest-required

**Comment by JanKoehnlein** [comment]
> slight concern that the date image in the Dockerfile might go wonky 6 months from now or whatever.

Gitpod stores custom Docker images and only rebuilds them on changes to the `.gitpod.Dockerfile`. So this should be safe.

**Comment by saschagrunert** [comment]
I'll merge to save the environment. Our CI does not interfere with the gitpod configuration file.

**Pull request merged**
