### PR TITLE
Fix travis badge URL

### PR DESCRIPTION
**Pull request by saschagrunert**
I simply adapted the URL within the README.md

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
Tests don't look happy though, can't imagine it's related to the change though.

**Comment by saschagrunert** [comment]
> LGTM
> Tests don't look happy though, can't imagine it's related to the change though.

Hm, it looks like quay.io has a major outage right now: http://status.quay.io/incidents/4lb8mr3fmpqg

**Comment by umohnani8** [comment]
thanks for the fix!
/lgtm

**Pull request merged**
