### PR TITLE
[1.21] bump c/storage to 1.31.1

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind dependency-change
#### Does this PR introduce a user-facing change?

```release-note
Fix possible segfault when image is deleted by podman while CRI-O is listing images
```

### CODE REVIEW

**Comment by haircommander** [comment]
fixes https://github.com/cri-o/cri-o/issues/4777

**Comment by mrunalp** [comment]
Need rebase

**Comment by haircommander** [comment]
rebased!

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
