### PR TITLE
[1.14] port forward: drain the stream on error

### PR DESCRIPTION
**Pull request by haircommander**
Before, we never drained the stream when we failed before calling pools.Copy(). A failure like this could happen if socat is not installed, or there is an invalid id found.

The problem is: if we never drain the streams, they stay open, and will cause kubelet to hang when trying to allocate one of its streams. If we don't drain on error, we can leak

fix this by draining the streams on error, until we actually want to copy data out of it

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
upon acceptance of this PR I'll forward port to 1.1{5..7} and master

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
