### PR TITLE
[1.16] Allow CRI-O to manage IPC and UTS namespaces

### PR DESCRIPTION
**Pull request by haircommander**
This includes:
    change the options ManageNetworkNSLifecycle to ManageNSLifecycle
    add a new set of files: internal/lib/sandbox/namespaces* that takes care of namespace related functionality
    create a generic NamespaceIface interface for interacting with all three kinds of namespaces
    refactor some of runPodSandbox to reduce cyclomatic complexity

Signed-off-by: Peter Hunt <pehunt@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM
/approve

**Comment by haircommander** [comment]
/hold
We may want a different approach here

**Comment by haircommander** [comment]
closing, as conmonmon fills the immediate need in this branch.

**Pull request closed without merging**
