### PR TITLE
bump containernetworking cni to 1.1.0

### PR DESCRIPTION
**Pull request by aojea**
Signed-off-by: Antonio Ojea <antonio.ojea.garcia@gmail.com>

/kind bug
/kind dependency-change

```release-note
libcni: handle empty version when parsing version (https://github.com/containernetworking/cni/pull/893). Without this, Delete failed for empty-version configs, which was a regression from v0.8.0.
```

### CODE REVIEW

**Comment by aojea** [comment]
I don't know if this also requires to revendor this too https://github.com/cri-o/ocicni/pull/103

/assign @mrunalp @dcbw @saschagrunert @haircommander @squeed

**Comment by saschagrunert** [comment]
> I don't know if this also requires to revendor this too [cri-o/ocicni#103](https://github.com/cri-o/ocicni/pull/103)
> 
> /assign @mrunalp @dcbw @saschagrunert @haircommander @squeed

I cut a new version of ocicni: https://github.com/cri-o/ocicni/releases/tag/v0.3.1 

Can you please vendor this one as well?

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by aojea** [comment]
> {  failed to create RBAC objects: timeout while waiting for dockercfg secret creation for service account "e2e-gcp": timed out waiting for the condition}

**Comment by saschagrunert** [comment]
/retest-required

Seeing those tests failing more often recently.

**Pull request merged**
