### PR TITLE
vendor github.com/containers/image/v5@v5.3.0

### PR DESCRIPTION
**Pull request by vrothberg**
* Fixed registries.conf
* Add Code of Conduct
* Bubbling up errors returned by copyBlobFromStream
* Re-order the members of archiveReference to a more logical orde
* Add docker/archive.NewReference
* Remove tarballReference.transport
* Add tarball.NewReference
* Add storage.Transport.GetStoreIfSet
* Simplify ID value check
* Add validateImageID
* Add storage.Transport.NewStoreReference
* registries.conf.d: add stances for the registries.conf
* Add $HOME/.config/containers/registries.conf to config path
* sysregistriesv2: drop "rewrite" debug messages
* Add $HOME/.config/containers/certs.d to perHostCertDirPath
* Intial authfile man page
* Return error when acquire semaphore lock gets error
* feat(docker): support docker registry token
* containers-registries.conf.d: refine semantics
* Updated warning about short names.
* Make UpdatedImage update after conversion of MIME type
* Support IdentityToken in registry authn
* Deprecate SupportsEncryption call in manifest interface
* oci manifest: do not require whitelist of layer types
* Fix crash on missing RootFS in docker/tarfile configs
* copy: try list conversions on list push failures
* Support architecture variants for multi-arch images and runtime
  compatibility checks

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

@umohnani8 @saschagrunert @haircommander @mrunalp PTAL

#### Does this PR introduce a user-facing change?

```release-note
Added support for drop-in registries.conf configuration files. Please refer to the registries.conf.d documentation (https://github.com/containers/image/blob/master/docs/containers-registries.conf.d.5.md) for further details.
```

### CODE REVIEW

**Comment by vrothberg** [comment]
> @vrothberg can we please stick to the PR template?

Thanks for the reminder! I developed the (bad) habit to just delete all the templates. Will make sure to use the template in the future :^)

> If this updates implies any user-facing change to CRI-O, then please note that in the ```release-notes code block as well.

I'll add a note about registries.conf.d :+1:

**Comment by vrothberg** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
FYI, we might have found issues with v5.3.0 in Podman...

**Comment by vrothberg** [comment]
> FYI, we might have found issues with v5.3.0 in Podman...
> [containers/libpod#5602](https://github.com/containers/libpod/pull/5602)

@umohnani8 @haircommander @saschagrunert @mrunalp ... let's wait with releases until we got that one sorted out

**Pull request merged**
