### PR TITLE
Update contrib systemd unit files to match project name

### LINKED ISSUE #2415: Update Unit File Description
**Description**

<minor nit pick>
The description in the unit file should be updated to reflect the current project name. 

I never noticed this until I had to troubleshoot a system where the daemon failed to start:
[FAILED] Failed to start Open Container Initiative Daemon.
See 'systemctl status crio.service' for details.

"Open Container initiative Daemon", or OCID, was the original name for this project. I'm surprised this is still around as an artifact. 

I propose we change this line to something like:
Description=cri-o
or 
Description=Container Runtime Interface for OCI
or even
Description=Container Runtime Interface for kubernetes

**Output of `crio --version`:**

```
$ crio -version
crio version 1.13.9-1.rhaos4.1.gitd70609a.el8
```

### PR DESCRIPTION
**Pull request by saschagrunert**
Closes #2415

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch. :)

**Pull request merged**
