### PR TITLE
 [release-1.19]  backports session timeout fix from 1.21 to 1.19

### PR DESCRIPTION
**Pull request by wgahnagl**
#### What type of PR is this?

> /kind api-change
 /kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:
backports session timeout fix from 1.21 to 1.18
https://github.com/cri-o/cri-o/pull/4529

#### Which issue(s) this PR fixes:

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1920300

#### Does this PR introduce a user-facing change?

```release-note
allows session timeout to to be set as a config 
```

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
once tests are righted.

**Comment by kolyshkin** [comment]
Will be helpful to provide links to original PRs/commits which are being backported in this PR description.

**Comment by kolyshkin** [comment]
Circleci build is failing because go version packaged has a bug resulting in bunch of errors like this

```
golang.org/x/crypto/openpgp/packet.(*Compressed).parse: relocation target compress/zlib.NewReaderDict not defined
github.com/docker/spdystream/spdy.(*Framer).uncorkHeaderDecompressor: relocation target compress/zlib.NewReaderDict not defined
github.com/docker/spdystream/spdy.NewFramer: relocation target compress/zlib.NewWriterLevelDict not defined
github.com/docker/spdystream/spdy.(*Framer).writeSynStreamFrame: relocation target compress/zlib.(*Writer).Flush not defined
github.com/docker/spdystream/spdy.(*Framer).writeSynReplyFrame: relocation target compress/zlib.(*Writer).Flush not defined
github.com/docker/spdystream/spdy.(*Framer).writeHeadersFrame: relocation target compress/zlib.(*Writer).Flush not defined
```

This can be fixed by using golang installed from golang.org, but I see that @haircommander is moving away from circleci to GHA (see https://github.com/cri-o/cri-o/pull/4604) so I think fixing circleci is useless (for now).

Still looking into integration-crun

**Comment by kolyshkin** [comment]
Tried to repro `integration_crun` failure with more diagnostics at https://github.com/cri-o/cri-o/pull/4605, and it works (i.e. integration tests are passing -- there is still a problem of uploading the results back to prow, described at https://github.com/cri-o/cri-o/pull/4605#issuecomment-786323726).

In here we have the same test failing (from https://prow.ci.openshift.org/log?job=test_pull_request_crio_integration_crun_fedora&id=1365076013226135552):

> TASK [run integration tests] ***************************************************
> task path: /go/src/github.com/cri-o/cri-o/contrib/test/integration/test.yml:21
> fatal: [localhost]: FAILED! => {"ansible_job_id": "72200651440.24472", "changed": true, "cmd": "make localintegration >& /tmp/artifacts/testout.txt", "delta": "0:07:13.553467", "end": "2021-02-25 23:22:51.995499", "finished": 1, "msg": "non-zero return code", "rc": 2, "start": "2021-02-25 23:15:38.442032", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

but as the detailed logs (testout) is not available, I can't say anything about what was wrong.

Which returns us back to the issue described at https://github.com/cri-o/cri-o/pull/4605#issuecomment-786323726

**Pull request merged**
