### PR TITLE
introduce seccomp override empty

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind feature
> /kind flake

#### What this PR does / why we need it:
right now, the CRI defaults to an unconfined profile when it's set to empty
However, it's possible admins want the behavior to default to the default profile instead.

add a knob to allow admins to override the empty behavior from unconfined to the default
Note, when set this technically makes CRI-O not CRI compliant, but for increased security, it's worth it.
#### Does this PR introduce a user-facing change?

```release-note
Add option `seccomp_override_empty` to override an unspecified seccomp profile from being unconfined to being the runtime default. Note: setting this option makes CRI-O not fully CRI compliant, but does increase security. 
```

### CODE REVIEW

**Comment by haircommander** [comment]
dropped the WIP commits, added an integration test

**Review by saschagrunert — COMMENTED** [review]
Do we have a chance to change the default in Kubernetes when graduating the CRI?

**Comment by haircommander** [comment]
> Do we have a chance to change the default in Kubernetes when graduating the CRI?

Possibly, when is seccomp going to be GA? possibly then as well. The issue is, unless either of those make 1.20 and also update the default, users won't get it for a while. If upstream k8s changes the default, we can go to that and drop this option. Until then, I think it's something admins should be given the choice for

**Review by kolyshkin — COMMENTED** [review]
Perpaps something like this instead?

```
--seccomp-empty=[unconfined|default]

Changes the meaning of an empty seccomp profile. By default (and according to CRI spec), empty profile means unconfined. This option allows to treat empty profile as default, which increases security.
```

**Comment by kolyshkin** [comment]
OK, one more alternative is boolean's `--seccomp-treat-empty-as-default`, which makes more sense for bool but it's still somewhat cumbersome.

**Comment by haircommander** [comment]
what about `--seccomp-use-default-when-empty` still verbose but definitely a clear boolean value

**Comment by haircommander** [comment]
> Perpaps something like this instead?
> 
> ```
> --seccomp-empty=[unconfined|default]
> 
> Changes the meaning of an empty seccomp profile. By default
> (and according to CRI spec), empty profile means unconfined.
> This option allows to treat an empty profile as default profile,
> which might increase security.
> ```
> 
> Overall, though, it's too complicated (== semantically overloaded) either way (yours or mine).

I like this verbiage, but it's pretty verbose for help text, I'll add it to the config text though

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by mrunalp — APPROVED** [review]

**Review by kolyshkin — APPROVED** [review]
The test case needs a revamp but AFAIK @wgahnagl is working on this one, so she can cover this, too.

**Pull request merged**
