### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**
#### What type of PR is this?

> /kind cleanup
> /kind feature

#### Does this PR introduce a user-facing change?

```release-note
Update nix pin with `make nixpkgs`
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by mrunalp — APPROVED** [review]

**Comment by hswong3i** [comment]
@saschagrunert shall failed tests not related to this PR?

/retest

**Comment by saschagrunert** [comment]
> @saschagrunert shall failed tests not related to this PR?

Can you please give it a rebase? I think the GH actions job should be fine afterwards.

**Comment by hswong3i** [comment]
> > @saschagrunert shall failed tests not related to this PR?
> 
> Can you please give it a rebase? I think the GH actions job should be fine afterwards.

@saschagrunert rebased

**Comment by hswong3i** [comment]
CI looks good enough now ;-)

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Pull request merged**
