### PR TITLE
Update cri-tools to v1.16.0

### PR DESCRIPTION
**Pull request by saschagrunert**
This uses the latest cri-tools version in the ansible based test setups.

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander do you know why this seems invalid syntax now?
```
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'cri'

The error appears to have been in '/go/src/github.com/cri-o/cri-o/contrib/test/integration/build/cri-tools.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: clone cri-tools source repo
  ^ here

```

**Comment by saschagrunert** [comment]
I think I need to do some fixing regarding the integration tests now 

/hold

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming the tests get happy.

**Pull request closed without merging**
