### PR TITLE
[1.12] test: Switch to cri-tools release-1.12 branch

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom @umohnani8 ptal.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp could you rebase and rekick tests? e2e dns is still broken but we could still get this in for critest

**Comment by runcom** [comment]
Needs rebase for dns tests

**Comment by runcom** [comment]
Ping @mrunal

**Comment by mrunalp** [comment]
Rebased.

**Comment by runcom** [comment]
we should update this as well I guess https://github.com/kubernetes-sigs/cri-o/blob/release-1.12/Dockerfile#L90

**Comment by umohnani8** [comment]
@mrunalp can you update the Dockerfile as well. I can take over as well :)

**Comment by rhatdan** [comment]
@mrunalp What is going on with this one?

**Comment by mrunalp** [comment]
We don't support 1.12 unless there is a specific request.

**Pull request closed without merging**
