### PR TITLE
Speed up mountinfo-related operations during container creation

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Speed up mountinfo-related operations during container creation.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Please see individual commits for details.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by haircommander** [comment]
/retest

e2e_crun has a ton of
```
Aug 18 02:28:29 ip-172-18-14-132.ec2.internal crio[2036]: time="2020-08-18 02:28:29.763568095Z" level=warning msg="Unable to get stats for container 8f47d679163b392c95a26434de88b66a7f51fe407f96d7318eee766fcb9f19a3: unable to load cgroup at kubepods-besteffort-pod6a9dd4a0_9398_4e07_bfea_b3c4f46f844f.slice: cgroup deleted" id=76c13fdc-8aea-4ddf-901f-fce401904467 name=/runtime.v1alpha2.RuntimeService/ListContainerStats
```
which seem unrelated [ref](https://prow.ci.openshift.org/view/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/4079/test_pull_request_crio_e2e_crun_fedora/8220/)

**Comment by kolyshkin** [comment]
CI is all green now, although `tide` status is not updated here

**Pull request merged**
