### PR TITLE
Fix gh-pages push for remote branch

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We do not have to prefix an `origin/` to the branch when pushing the
gh-pages branch.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.

**Pull request merged**
