### PR TITLE
fixes version_test.go

### PR DESCRIPTION
**Pull request by wgahnagl**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind ci
/kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:

fixes version_test.go to use ginkgo instead of testing

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Yay, that's cool! LGTM

**Review by giuseppe — APPROVED** [review]

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
