### PR TITLE
`go get github.com/containers/common@v0.57.0`

### PR DESCRIPTION
**Pull request by hswong3i**
#### What type of PR is this?

/kind bug
/kind dependency-change

#### What this PR does / why we need it:

`github.com/containers/common` need to bump to v0.57.0, for fixing AppArmor error with Ubuntu 23.10.

#### Which issue(s) this PR fixes:

Fixes https://github.com/cri-o/cri-o/issues/7490

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by kwilczynski** [comment]
@hswong3i, there is some issue with how the newly updated dependency was vendored. Can you have a look?

Most likely just a `go mod tidy` and `go mod vendor`, plus ensuring everything was added correctly (no files were ignored, etc.) from under the vendor directory as part of the Pull Request.

**Comment by hswong3i** [comment]
> @hswong3i, there is some issue with how the newly updated dependency was vendored. Can you have a look?
> 
> Most likely just a `go mod tidy` and `go mod vendor`, plus ensuring everything was added correctly (no files were ignored, etc.) from under the vendor directory as part of the Pull Request.

I did a try as below then force push:
```
go mod tidy
go mod download
go mod vendor
git add --all --force vendor
```

**Comment by kwilczynski** [comment]
@hswong3i, thank you!

This may be more involved than it looks at first glance. Have a look at:

- [actions/runs#6939632524](https://github.com/cri-o/cri-o/actions/runs/6939632524?pr=7491)

Do you know if it builds for you locally? I assume, yes, it does build fine.

**Comment by hswong3i** [comment]
@kwilczynski you are correct my local build also failed:
```
$ set -ex && \
    export CGO_ENABLED=1 && \
    go build \
        -mod vendor -buildmode pie -v \
        -ldflags "-s -w" \
        -tags "netgo osusergo exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp seccomp selinux" \
        -o ./bin/crio ./cmd/crio && \
    go build \
        -mod vendor -buildmode pie -v \
        -ldflags "-s -w" \
        -tags "netgo osusergo exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp seccomp selinux" \
        -o ./bin/crio-status ./cmd/crio-status && \
    make bin/pinns
+ export CGO_ENABLED=1
+ CGO_ENABLED=1
+ go build -mod vendor -buildmode pie -v -ldflags '-s -w' -tags 'netgo osusergo exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp seccomp selinux' -o ./bin/crio ./cmd/crio
github.com/containers/podman/v4/libpod/define
github.com/containers/podman/v4/utils
github.com/containers/conmon-rs/pkg/client
github.com/containers/buildah
# github.com/containers/podman/v4/libpod/define
vendor/github.com/containers/podman/v4/libpod/define/errors.go:96:19: undefined: util.ErrDetach
# github.com/containers/podman/v4/utils
vendor/github.com/containers/podman/v4/utils/utils_supported.go:29:23: undefined: cgroups.GetUserConnection
# github.com/containers/conmon-rs/pkg/client
vendor/github.com/containers/conmon-rs/pkg/client/attach.go:232:19: undefined: util.CopyDetachable
vendor/github.com/containers/conmon-rs/pkg/client/attach.go:429:26: undefined: util.ErrDetach
# github.com/containers/buildah
vendor/github.com/containers/buildah/run_common.go:65:39: invalid argument: defaultConfig.Containers.DNSServers (variable of type attributedstring.Slice) for len
vendor/github.com/containers/buildah/run_common.go:66:36: cannot use defaultConfig.Containers.DNSServers (variable of type attributedstring.Slice) as []string value in argument to append
vendor/github.com/containers/buildah/run_common.go:82:36: invalid argument: defaultConfig.Containers.DNSSearches (variable of type attributedstring.Slice) for len
vendor/github.com/containers/buildah/run_common.go:83:30: cannot use defaultConfig.Containers.DNSSearches (variable of type attributedstring.Slice) as []string value in argument to append
vendor/github.com/containers/buildah/run_common.go:86:35: invalid argument: defaultConfig.Containers.DNSOptions (variable of type attributedstring.Slice) for len
vendor/github.com/containers/buildah/run_common.go:87:28: cannot use defaultConfig.Containers.DNSOptions (variable of type attributedstring.Slice) as []string value in argument to append
vendor/github.com/containers/buildah/run_common.go:347:35: cannot use plugins (variable of type []string) as attributedstring.Slice value in assignment
vendor/github.com/containers/buildah/run_linux.go:466:45: cannot use defaultContainerConfig.Containers.DefaultUlimits (variable of type attributedstring.Slice) as []string value in argument to addRlimits
```

Since they are failed with `github.com/containers/podman`, `github.com/containers/conmon-rs` and `github.com/containers/buildah`, which also means our else dependencies couldn't handle common's v0.57.0 correctly.

Therefore I am suggesting individual patch release from common, see https://github.com/containers/common/issues/1746#issuecomment-1819891215, in order to reduce the amount of changes required.

**Comment by kwilczynski** [comment]
@hswong3i, OK.

You could also have tried to pin dependencies for the time being, with a comment added to remove the pins later once work on the direct dependencies upgrade is completed. Have you tried this approach?

**Comment by hswong3i** [comment]
> @hswong3i, OK.
> 
> You could also have tried to pin dependencies for the time being, with a comment added to remove the pins later once work on the direct dependencies upgrade is completed. Have you tried this approach?

Trying and looks good for main/v1.29/v1.28:
* https://github.com/cri-o/cri-o/pull/7496
* https://github.com/cri-o/cri-o/pull/7497
* https://github.com/cri-o/cri-o/pull/7498

Well, but surely it should be failed for v1.27/v1.26/v1.25:
* https://github.com/cri-o/cri-o/pull/7499
* https://github.com/cri-o/cri-o/pull/7500
* https://github.com/cri-o/cri-o/pull/7501

**Comment by kwilczynski** [comment]
@hswong3i, very true. I tried to pin down some dependencies, but it only goes as far. Sadly, there is no quick win here! :smile:

**Pull request closed without merging**
