### PR TITLE
go.mod: update github.com/containerd/nri.

### PR DESCRIPTION
**Pull request by klihub**
Fix a recently discovered panic/crash.

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

NRI [commit b3cabdec0657](https://github.com/containerd/nri/commit/b3cabdec06578b193da387b1bee4fd23aea8808e) fixes a recently discovered panic crash. Without that fix and NRI support enabled, a plugin requesting an unsolicited update to one or more containers triggers the bug and causes a crash.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/release-note-none
/override ci/kata-jenkins
/override ci/prow/ci-rhel-integration

/approve

LGTM

**Comment by haircommander** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
