### PR TITLE
update c/storage to v1.13.4

### PR DESCRIPTION
**Pull request by vrothberg**
* Update generated files
 * ImageBigData: distinguish between no-such-image and no-such-item
 * ImageSize: don't get tripped up by images with no layers
 * tarlogger: disable raw accouting

Fixes: #2847
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

@mrunalp @haircommander @umohnani8 @rhatdan PTAL

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by haircommander** [comment]
LGTM, e2e*fedora is a known flake and not the fault of this PR

**Comment by umohnani8** [comment]
LGTM

**Comment by vrothberg** [comment]
> LGTM, e2e*fedora is a known flake and not the fault of this PR

@haircommander, does that imply we can merge?

**Comment by haircommander** [comment]
@rhatdan the e2e*fedora  are known failures (surprise); I'm working on it

**Comment by rhatdan** [comment]
/retest
@haircommander Should these tests be passing now, or does this PR need a rebase?

**Comment by haircommander** [comment]
The tests will fail. I need to do some forwardports to master...

**Comment by haircommander** [comment]
can you rebase to pick up CI fixes?

**Comment by vrothberg** [comment]
> can you rebase to pick up CI fixes?

Done, thanks for the ping!

**Comment by saschagrunert** [comment]
> > can you rebase to pick up CI fixes?
> 
> Done, thanks for the ping!

Hey, can you please re-vendor once again to let the CI pass? :)

**Comment by vrothberg** [comment]
> Hey, can you please re-vendor once again to let the CI pass? :)

Done, thanks for checking!

**Comment by saschagrunert** [comment]
****

**Pull request merged**
