### PR TITLE
test: disable crictl pull on create

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
  
We already preload a bunch of images before running tests, and it makes
sense to disable pull during crictl create, as it should save some time
and result in less flakiness in the tests (related to network glitches).
    
crictl 1.19 added this option, and "no pull on create" is the new
default. This reverts the hunk of commit 40b9d971fe (PR #4150)
which changes the default.

For more details, see https://github.com/kubernetes-sigs/cri-tools/pull/627

#### Which issue(s) this PR fixes:

This should eventually fix the flakes caused by network issues
while running tests.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
So far just one failure:
```
not ok 88 container status when created by image list canonical reference
# (in test file ./image.bats, line 81)
#   `ctr_id=$(crictl create "$pod_id" "$TESTDIR"/ctr_by_imagelistref.json "$TESTDATA"/sandbox_config.json)' failed
# level=info msg="Using default capabilities: CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_FSETID, CAP_FOWNER, CAP_SETGID, CAP_SETUID, CAP_SETPCAP, CAP_NET_BIND_SERVICE, CAP_KILL"
# time="2020-10-28T03:10:23Z" level=fatal msg="creating container: rpc error: code = Unknown desc = image not known"
```

**Review by saschagrunert — APPROVED** [review]
/ok-to-test 
/lgtm

Thank you! 🙏

**Comment by kolyshkin** [comment]
Alas this wasn't entirely working because of crictl.yaml that also had these options added by commit ca1c466366326dc9a7427c5b922998a917e145cc

**Comment by kolyshkin** [comment]
> Alas this wasn't entirely working because of crictl.yaml that also had these options added by commit ca1c466

... but I am fixing this in #4377

**Pull request merged**
