### PR TITLE
main: create parent crio dir before creating clean.shutdown.supported

### PR DESCRIPTION
**Pull request by haircommander**
to ensure on initial installation it is installed.

Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### Which issue(s) this PR fixes:

fixes https://github.com/cri-o/cri-o/issues/6226

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by haircommander** [comment]
@saschagrunert I rebased, can you retag please :)

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Pull request merged**
