### PR TITLE
[1.20] Add container out of memory metrics

### PR DESCRIPTION
**Pull request by haircommander**
This patch adds a new metric
`container_runtime_crio_containers_oom_total` and
`container_runtime_crio_containers_oom`, which collects out of memory
(oom) metrics global and by container name. This also includes
sandboxes, since we reuse the CRI-O internal name for every container.

Signed-off-by: Sascha Grunert <sgrunert@redhat.com>

#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
cherry-pick of https://github.com/cri-o/cri-o/pull/4690
#### Does this PR introduce a user-facing change?

```release-note
Added `container_runtime_crio_containers_oom_total` and  `container_runtime_crio_containers_oom` metrics,
which collects out of memory (oom) containers.
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm
/retest-required

**Comment by saschagrunert** [comment]
Ah this needs more CI fixing
/lgtm-cancel

**Comment by saschagrunert** [comment]
A friendly reminder that this PR had no activity for 30 days.

**Comment by jiancheung** [comment]
hi @haircommander ! Appreciate the effort to get this backported to 1.20 and was wondering how we can help to move it along and getting it actually merged and released?

**Comment by haircommander** [comment]
I've rebased this @saschagrunert can you PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
