### PR TITLE
[1.14] netns can be nil which can cause a segfault

### LINKED ISSUE #2221: null pointer dereference when creating k8s container
I am running crio 1.14.0 on ClearLinux with k8s 1.14 and canal for networking. The static pods come up just fine, but when canal starts his second container, crio crashes with the below log.

```
Apr 04 21:42:47 clr-01 crio[30564]: panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                                       
Apr 04 21:42:47 clr-01 crio[30564]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1614bc2]                                                                                                                                                                      
Apr 04 21:42:47 clr-01 crio[30564]: goroutine 156 [running]:                                                                                                                                                                                                                      
Apr 04 21:42:47 clr-01 crio[30564]: panic(0x18d2360, 0x2e483b0)                                                                                                                                                                                                                   
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/panic.go:565 +0x2c5 fp=0xc000dac678 sp=0xc000dac5e8 pc=0x437615                                                                                                                                           
Apr 04 21:42:47 clr-01 crio[30564]: runtime.panicmem(...)                                                                                                                                                                                                                         
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/panic.go:82                                                                                                                                                                                               
Apr 04 21:42:47 clr-01 crio[30564]: runtime.sigpanic()                                                                                                                                                                                                                            
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/signal_unix.go:390 +0x411 fp=0xc000dac6a8 sp=0xc000dac678 pc=0x44d3f1                                                                                                                                     
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/lib/sandbox.(*NetNs).SymlinkCreate(0xc000936480, 0xc000c28230, 0x48, 0x0, 0x78d402ae)                                                                                                                        
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/lib/sandbox/sandbox_linux.go:68 +0x1d2 fp=0xc000dac760 sp=0xc000dac6a8 pc=0x1614bc2                                                                   
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/lib/sandbox.(*Sandbox).NetNsCreate(0xc000a90b60, 0x1e23b80, 0xc000936480, 0x1c, 0xc0003661c8)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/lib/sandbox/sandbox.go:414 +0x166 fp=0xc000dac7e0 sp=0xc000dac760 pc=0x16143b6
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/server.(*Server).runPodSandbox(0xc000426000, 0x1e101c0, 0xc0009899b0, 0xc000a3e580, 0x0, 0x0, 0x0)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/server/sandbox_run_linux.go:457 +0x67d6 fp=0xc000dadb80 sp=0xc000dac7e0 pc=0x16b31d6
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/server.(*Server).RunPodSandbox(0xc000426000, 0x1e101c0, 0xc0009899b0, 0xc000a3e580, 0xc000426000, 0xc0004e5e30, 0xc000067c28)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/server/sandbox_run.go:122 +0x49 fp=0xc000dadbc8 sp=0xc000dadb80 pc=0x16ac0d9
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2._RuntimeService_RunPodSandbox_Handler(0x1af6540, 0xc000426000, 0x1e101c0, 0xc0009899b0, 0xc0002cbbd0, 0x0, 0x0, 0x0, 0x1000, 0x7fc96ae8c000)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go:4183 +0x241 fp=0xc000dadc38 sp=0xc000dadbc8 pc=0x105e481
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000252780, 0x1e2a120, 0xc000b07340, 0xc000ce8e00, 0xc00091c300, 0x2e5d218, 0x0, 0x0, 0x0)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc/server.go:843 +0x94c fp=0xc000dade48 sp=0xc000dadc38 pc=0x104b97c
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000252780, 0x1e2a120, 0xc000b07340, 0xc000ce8e00, 0x0)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc/server.go:1040 +0x12b5 fp=0xc000dadf80 sp=0xc000dade48 pc=0x104e995
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000c9c1a0, 0xc000252780, 0x1e2a120, 0xc000b07340, 0xc000ce8e00)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc/server.go:589 +0x9f fp=0xc000dadfb8 sp=0xc000dadf80 pc=0x105027f
Apr 04 21:42:47 clr-01 crio[30564]: runtime.goexit()
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000dadfc0 sp=0xc000dadfb8 pc=0x4671c1
Apr 04 21:42:47 clr-01 crio[30564]: created by github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc/server.go:587 +0xa1
Apr 04 21:42:47 clr-01 crio[30564]: goroutine 1 [select]:
Apr 04 21:42:47 clr-01 crio[30564]: runtime.gopark(0x1bce7b8, 0x0, 0x1809, 0x1)
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/proc.go:301 +0xef fp=0xc000dc6940 sp=0xc000dc6920 pc=0x43972f
Apr 04 21:42:47 clr-01 crio[30564]: runtime.selectgo(0xc000dc6d38, 0xc000dc6b3c, 0x3, 0x1e17240, 0xc0008ed720)
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/select.go:313 +0xcb8 fp=0xc000dc6a68 sp=0xc000dc6940 pc=0x4494e8
Apr 04 21:42:47 clr-01 crio[30564]: main.main.func2(0xc0008ea2c0, 0xc0008ea2c0, 0xc000768dbf)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/cmd/crio/main.go:663 +0xc6c fp=0xc000dc6dc0 sp=0xc000dc6a68 pc=0x16f966c
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/vendor/github.com/urfave/cli.HandleAction(0x18592a0, 0xc0008b2670, 0xc0008ea2c0, 0xc0008b70e0, 0x0)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/vendor/github.com/urfave/cli/app.go:490 +0xc8 fp=0xc000dc6de8 sp=0xc000dc6dc0 pc=0x16cbf48
Apr 04 21:42:47 clr-01 crio[30564]: github.com/kubernetes-sigs/cri-o/vendor/github.com/urfave/cli.(*App).Run(0xc0008e6000, 0xc00009a170, 0x1, 0x1, 0x0, 0x0)
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/vendor/github.com/urfave/cli/app.go:264 +0x590 fp=0xc000dc70d8 sp=0xc000dc6de8 pc=0x16ca160
Apr 04 21:42:47 clr-01 crio[30564]: main.main()
Apr 04 21:42:47 clr-01 crio[30564]:         /builddir/build/BUILD/cri-o-1.14.0/_output/src/github.com/kubernetes-sigs/cri-o/cmd/crio/main.go:688 +0x2397 fp=0xc000dc7f98 sp=0xc000dc70d8 pc=0x16f74c7
Apr 04 21:42:47 clr-01 crio[30564]: runtime.main()
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/proc.go:200 +0x20c fp=0xc000dc7fe0 sp=0xc000dc7f98 pc=0x43933c
Apr 04 21:42:47 clr-01 crio[30564]: runtime.goexit()
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000dc7fe8 sp=0xc000dc7fe0 pc=0x4671c1
Apr 04 21:42:47 clr-01 crio[30564]: goroutine 2 [force gc (idle)]:
Apr 04 21:42:47 clr-01 crio[30564]: runtime.gopark(0x1bce778, 0x3004440, 0x1410, 0x1)
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/proc.go:301 +0xef fp=0xc000058fb0 sp=0xc000058f90 pc=0x43972f
Apr 04 21:42:47 clr-01 crio[30564]: runtime.goparkunlock(...)
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/proc.go:307
Apr 04 21:42:47 clr-01 crio[30564]: runtime.forcegchelper()
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/proc.go:250 +0xb7 fp=0xc000058fe0 sp=0xc000058fb0 pc=0x4395d7
Apr 04 21:42:47 clr-01 crio[30564]: runtime.goexit()
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0x4671c1
Apr 04 21:42:47 clr-01 crio[30564]: created by runtime.init.5
Apr 04 21:42:47 clr-01 crio[30564]:         /usr/lib/golang/src/runtime/proc.go:239 +0x35
Apr 04 21:42:47 clr-01 crio[30564]: goroutine 3 [GC sweep wait]:
```

### PR DESCRIPTION
**Pull request by saschagrunert**
This PR backports #2222

Closes #2221

### CODE REVIEW

**Comment by vrothberg** [comment]
Code LGTM but please make sure to add your signed-off-by to the commit message (and ideally mark it as a backport).

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by saschagrunert** [comment]
I updated the commit message to include the cherry pick and backport PR.

**Comment by vrothberg** [comment]
> I updated the commit message to include the cherry pick and backport PR.

Awesome, thanks a lot :+1:

**Pull request merged**
