### PR TITLE
Remove last traces of --default-mounts

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This option was obsoleted in May 2018 (see commit 1aab473cce, PR #1537) and
removed in Feb 2020 (see commit 7c535f29e4cf, PR #3119) but some traces of it
still remains.

Remove those.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
pipeline failures are due to timeouts (either circle-ci became slower recently, or it dies in the midst of testing, or our tests became slower...)

/retest

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
> pipeline failures are due to timeouts (either circle-ci became slower recently, or it dies in the midst of testing, or our tests became slower...)

Can someone please restart circleci job (i.e. "pipeline"), I don't have enough rights for some reason.

**Comment by saschagrunert** [comment]
Re-ran the CircleCI pipeline.

**Comment by haircommander** [comment]
nice, good find

/lgtm

**Pull request merged**
