### PR TITLE
Bump golang dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Bump the golang dependencies to their latest releases.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander PTAL

**Comment by saschagrunert** [comment]
@haircommander PTAL

**Comment by haircommander** [comment]
integration errors seem like registry pull failures
/retest

**Comment by saschagrunert** [comment]
/override ci/prow/ci-critest
/override ci/prow/ci-integration

They do not run

**Pull request merged**
