### PR TITLE
Fix naming unit test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
By using the right before-each function.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
