### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sohankunkerkar**
There are a good number of Dependabot pull requests that haven't been merged for a few weeks. Therefore, I'm creating this pull request to consolidate all the dependencies into a single PR. This will help avoid multiple CI runs and reduce the waiting time.

#### What type of PR is this?

/kind cleanup

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
cc @haircommander

**Comment by haircommander** [comment]
```
go build  -trimpath  -ldflags '-s -w -X github.com/cri-o/cri-o/internal/version.buildDate='2023-06-26T20:06:58Z' ' -tags "containers_image_ostree_stub apparmor    libdm_no_deferred_remove containers_image_openpgp seccomp selinux " -o bin/crio github.com/cri-o/cri-o/cmd/crio
# github.com/containers/image/v5/sif
Error: vendor/github.com/containers/image/v5/sif/src.go:100:3: unknown field Architecture in struct literal of type v1.Image
Error: vendor/github.com/containers/image/v5/sif/src.go:101:3: unknown field OS in struct literal of type v1.Image
```
some compile errors

**Comment by sohankunkerkar** [comment]
> ```
> go build  -trimpath  -ldflags '-s -w -X github.com/cri-o/cri-o/internal/version.buildDate='2023-06-26T20:06:58Z' ' -tags "containers_image_ostree_stub apparmor    libdm_no_deferred_remove containers_image_openpgp seccomp selinux " -o bin/crio github.com/cri-o/cri-o/cmd/crio
> # github.com/containers/image/v5/sif
> Error: vendor/github.com/containers/image/v5/sif/src.go:100:3: unknown field Architecture in struct literal of type v1.Image
> Error: vendor/github.com/containers/image/v5/sif/src.go:101:3: unknown field OS in struct literal of type v1.Image
> ```
> 
> some compile errors

oh, we don't have an `Architecture` field in the latest version of image-spec: https://github.com/opencontainers/image-spec/blob/v1.1.0-rc.3/specs-go/v1/config.go#L93

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
