### PR TITLE
Do not Wrapf errors if no format is specified

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We should stick to a usual `errors.Wrap` if not format specifier is available.

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by nalind** [comment]
LGTM

**Comment by haircommander** [comment]
`04:55:43 # time="2020-03-25 08:55:43.070931272Z" level=error msg="Container creation error: Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing\n" file="oci/runtime_oci.go:212"` 
[ref](http://jenkins.katacontainers.io/job/kata-containers-crio-PR/9305/console)

/test kata

**Comment by rhatdan** [comment]
/test kata-containers
LGTM

**Pull request merged**
