### PR TITLE
Support checkpointing infra less containers

### PR DESCRIPTION
**Pull request by adrianreber**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Add support to checkpoint and restore containers in pods without infrastructure containers.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
Added support to checkpoint and restore containers in pods without infrastructure containers.
```

### CODE REVIEW

**Comment by haircommander** [comment]
/lgtm

thanks @adrianreber I think there are some CI woes but I'll give you the tag in case they resolve themselves

**Review by saschagrunert — APPROVED** [review]
/retest

**Comment by adrianreber** [comment]
The failing kata test says:
```
golang.mk:60: *** "ERROR: golang minor version too old: got 1.18.1, need atleast 1.19".  Stop.
```
Not really clear why the conmonrs test fails. I see a couple of permission denied messages in combination with gcloud and scp. Not sure if that is expected.

**Comment by haircommander** [comment]
cc @littlejawa 

We have been having permission troubles on the new CI system so for now they're effectively expected

**Comment by littlejawa** [comment]
regarding the kata tests: we have an issue on the kata CI these days, it is being worked on.
The golang error should go away with https://github.com/kata-containers/tests/pull/5266, but I think we need to fix other stuff before merging that.
Sorry for the trouble :-(

**Comment by adrianreber** [comment]
Do I need to rebase or is CI still broken?

**Comment by saschagrunert** [comment]
> Do I need to rebase or is CI still broken?

I think it's still broken :-/

**Comment by haircommander** [comment]
@adrianreber can you rebase this? many of the tests have been fixed

**Comment by haircommander** [comment]
@adrianreber you've got a [linter error](https://github.com/cri-o/cri-o/actions/runs/3702386806/jobs/6272606603)

**Comment by adrianreber** [comment]
> @adrianreber you've got a [linter error](https://github.com/cri-o/cri-o/actions/runs/3702386806/jobs/6272606603)

Those linter errors are unrelated to my PR, but I added a commit to fix them to this PR.

**Comment by haircommander** [comment]
sorry, one more static checker failure: https://github.com/cri-o/cri-o/actions/runs/3707686650/jobs/6284397358

**Comment by haircommander** [comment]
wait
/hold
log capitalization is still failing @adrianreber https://github.com/cri-o/cri-o/actions/runs/3707997205/jobs/6285066872

**Comment by adrianreber** [comment]
I thought I removed that line. Let me check.

**Comment by adrianreber** [comment]
> wait /hold log capitalization is still failing @adrianreber https://github.com/cri-o/cri-o/actions/runs/3707997205/jobs/6285066872

I removed the line and force pushed.

**Comment by adrianreber** [comment]
It still fails. Strange.

**Comment by adrianreber** [comment]
Finally the line is gone.

**Pull request merged**
