### PR TITLE
server/sandbox_stop: Use lib/stop.go's ContainerStop for all containers except infra

### PR DESCRIPTION
**Pull request by wking**
This keeps us DRY, vs. repeating the early state guard and `StorageRuntimeServer().StopContainer` call here too.

### CODE REVIEW

**Comment by rhatdan** [comment]
@wking Travis Failures?

**Comment by wking** [comment]
Rebased onto #2111 with 2e64e4c3 -> e8198f05.  Review #2111 first.

**Comment by rhatdan** [comment]
@umohnani8 @haircommander @wking @saschagrunert Working on this?  Interns? Close?

**Comment by rhatdan** [comment]
@giuseppe PTAL Could you take this over and get it merged or close it, if it does not apply any longer?
@wking @umohnani8 @saschagrunert @haircommander @mrunalp Is this something we want?
Attempting to cleanup old CRI-O PRs

**Comment by giuseppe** [comment]
it is quite old (>1 year) refactoring, there are quite significant changes and rebasing it won't be a trivial task.  Let's just close it.

**Comment by umohnani8** [comment]
Closing

**Pull request closed without merging**
