### PR TITLE
bump containers image to 5.4.4

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
to fix issue in signature verification

#### Which issue(s) this PR fixes:
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1836442

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM

**Comment by saschagrunert** [comment]
This might be already included in https://github.com/cri-o/cri-o/pull/3783

**Comment by haircommander** [comment]
it is!

**Pull request closed without merging**
