### PR TITLE
[1.15] support manifest lists

### PR DESCRIPTION
**Pull request by nalind**
Vendor in WIP branches for manifest list support to let CI exercise the changes.  Basically, this is #2775 for 1.15.

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind What's the scoop on this one?  @mrunalp is this still needed?

**Comment by haircommander** [comment]
this is blocked in part by https://github.com/cri-o/cri-o/pull/2973

**Comment by haircommander** [comment]
hey @nalind can you rebase to fix test failures?

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green tests

**Pull request merged**
