### PR TITLE
vendor: bump containers/storage to v1.24.4

### PR DESCRIPTION
**Pull request by QiWang19**
#### What type of PR is this?

> /kind bug

#### What this PR does / why we need it:
This is mostly to have https://github.com/containers/storage/commit/83150e3a2fd6219d0a908102645e83770ed35856
which should fix the authentication failure during bootstrap node install.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1907770
#### Which issue(s) this PR fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1907770

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where image authentication failed from not finding the auth file.
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test

I am okay with this in master, but the original problem came in 1.19. Can we cherry-pick the required commits to a stable branch for 1.20 and 1.19?

**Comment by QiWang19** [comment]
The issue came in 1.19. Just backport to 1.20 should be ok I think. https://github.com/cri-o/cri-o/pull/4462

**Comment by QiWang19** [comment]
what `release-note` usually use in this kind of PR? @haircommander

**Comment by haircommander** [comment]
in the original PR description, at the bottom there's a `release-note` section. For this PR, you could add a note like:
`Fixed a bug where image authentication failed from not finding the auth file` or something like that

**Comment by haircommander** [comment]
it seems you'll need to run docs generation:
`make docs-generation`

specifically, the world is updating to `/run` instead of `/var/run` and that's caused a docs change:
https://app.circleci.com/pipelines/github/cri-o/cri-o/7136/workflows/8825ea29-f067-40d0-9ce8-6ef28486af6c/jobs/115433

**Comment by haircommander** [comment]
we'll probably need a more invasive/complete PR to fully make that change, but you can patch it for now here

**Pull request merged**
