### PR TITLE
Add linkmode to crio version output

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We now provide the linkmode to the `crio verison` subcommand output.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
I also refactored the tabwriter printing to use reflection to be a bit more flexible.
#### Does this PR introduce a user-facing change?

```release-note
- Added `linkmode` (dynamic or static) output to `crio version` subcommand
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by rhatdan** [comment]
Might be a little fragile, but better then nothing.
/lgtm

**Pull request merged**
