### PR TITLE
Fix links to installation documentation

### PR DESCRIPTION
**Pull request by markusthoemmes**
Signed-off-by: Markus Thömmes <markusthoemmes@me.com>

#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

This PR fixes a few links to a document that is no longer there but crucial during initial setup of cri-o.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm
/ok-to-test
Thank you!

**Comment by haircommander** [comment]
oops, good catch!

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
C'mon tests, behave!

**Comment by umohnani8** [comment]
Looks like a bunch of timeouts
/retest

**Pull request merged**
