### PR TITLE
contrib: add tests for cgroup v2

### PR DESCRIPTION
**Pull request by giuseppe**
Depends on: https://github.com/openshift/aos-cd-jobs/pull/2113

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
I need to make sure that these tests are allowed to fail

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
@mrunalp where should we set that the test can fail?

**Comment by giuseppe** [comment]
@haircommander @mrunalp if there is nothing terribly wrong let's merge it and we iterate more.

integration tests are failing because of an issue in the cgroupfs crun backend, I'll address them separately

**Comment by giuseppe** [comment]
depends on: https://github.com/openshift/aos-cd-jobs/pull/2121

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by giuseppe** [comment]
new crun release to fix integration tests: https://github.com/containers/crun/pull/272

**Comment by giuseppe** [comment]
I need again a lgtm

**Pull request merged**
