### PR TITLE
[1.21] Fix CI

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
This should make the CI green again on 1.21.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated static binary bundle crun version to v0.20
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander PTAL, GitHub actions are green again

**Comment by haircommander** [comment]
/hold

until https://github.com/containers/conmon/pull/268 merges

**Pull request merged**
