### PR TITLE
Update github.com/containers/image to v5.24.0

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

#### What type of PR is this?

/kind dependency-change

#### Does this PR introduce a user-facing change?

```release-note
Update github.com/containers/image to v5.24.0 for sigstore features
```

### CODE REVIEW

**Comment by mrunalp** [comment]
@haircommander @saschagrunert ptal

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
Hm, the integration tests seems to fail consistently :thinking: 

/lgtm cancel

**Comment by mrunalp** [comment]
@haircommander It looks like wipe related tests are failing. Anything jump out to you?

**Comment by haircommander** [comment]
I think it has to do with https://github.com/cri-o/cri-o/pull/6630, and I've reproduced in https://github.com/cri-o/cri-o/pull/6632, though haven't repoduced locally. We can ignore them here

**Pull request merged**
