### PR TITLE
run e2e tests using crun

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@rhatdan @mrunalp tests pass on Fedora.

Failures on RHEL are expected as there are missing build dependencies

**Comment by giuseppe** [comment]
I've pushed another version where crun installation can be configured.

crun tests won't run until https://github.com/openshift/aos-cd-jobs/pull/2027 is not merged

**Comment by haircommander** [comment]
(this will need https://github.com/cri-o/cri-o/pull/2955 to be in before any jenkins tests will pass BTW)

**Comment by haircommander** [comment]
LGTM @giuseppe can WIP be removed?

**Comment by giuseppe** [comment]
@mrunalp @haircommander PTAL

**Comment by rhatdan** [comment]
LGTM, but you still had one test fail.
Removed the WIP.

**Comment by haircommander** [comment]
Am i correct in thinking there aren't any tests running with crun yet? This seems to lay the skeleton

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
@haircommander Yup that is the idea.  The real goal is to get to the point we can run on cgroup V2 if kubernetes patches get in, prior to runc getting support.

**Comment by haircommander** [comment]
I've triggered the tests again. integration-static-glibc failed twice on the same test, but there are no clear changes here that could cause it (it was in network.bats). I'm hoping some sun spot flips a bit and it goes green

**Comment by giuseppe** [comment]
in a previous version I manually forced to run with crun and the e2e tests pass.  So I've changed it back to be configurable and we need: https://github.com/openshift/aos-cd-jobs/pull/2027 to run both crun and runc tests

**Comment by haircommander** [comment]
finally happy tests
/lgtm

**Pull request merged**
