### PR TITLE
dirnotifier: optimize accesses to Map

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
needs https://github.com/cri-o/cri-o/pull/5176

**Comment by haircommander** [comment]
needs  https://github.com/cri-o/cri-o/pull/5177 too

/hold

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
rebased

/unhold

PTAL @saschagrunert

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
