### PR TITLE
Update golangci lint to v1.26.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Update golangci lint to the latest release
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM once the tests are hip

**Comment by saschagrunert** [comment]
Rebased on master and bumped to v1.25.1

**Comment by saschagrunert** [comment]
Gave it another e

**Comment by saschagrunert** [comment]
Gave it another rebase on top of 1.26.0

/retest

**Pull request merged**
