### PR TITLE
[release-1.28] Bump to v1.28.2

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Bump the version to v1.28.2
#### Which issue(s) this PR fixes:

Refers to https://github.com/cri-o/cri-o/issues/7411
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
in my ideal we'd get 1.28 version of https://github.com/cri-o/cri-o/pull/7408 in here first

**Comment by saschagrunert** [comment]
@haircommander do we want to move forward with this PR?

**Pull request merged**
