### PR TITLE
Use conmon-rs as default monitor in static binary bundle

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Switching to conmon-rs over conmon after adding it to the bundle. Adapting the tests as needed.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Using conmon-rs as default container monitor in static binary bundles.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander @cri-o/cri-o-maintainers are we happy to switch over to conmon-rs as default? I'd like to adapt the packages in the same way afterwards.

**Comment by haircommander** [comment]
personally I am hesitant but not staunchly opposed. I am not sure we've gotten enough hands-on feedback for conmon-rs, and there still isn't podman support. I would ideally like to wait until we cut conmon-rs 1.0.0, have podman support and have some folks testing it to iron out any bugs before we make it the default. WDYT @saschagrunert ?

**Comment by saschagrunert** [comment]
> personally I am hesitant but not staunchly opposed. I am not sure we've gotten enough hands-on feedback for conmon-rs, and there still isn't podman support. I would ideally like to wait until we cut conmon-rs 1.0.0, have podman support and have some folks testing it to iron out any bugs before we make it the default. WDYT @saschagrunert ?

Sounds good to me!

**Pull request closed without merging**
