### PR TITLE
[1.19] Switch to containers/common for AppArmor

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Most of the source code previously part of libpod is now in
containers/common, which means that we can switch over here, too.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander do we wanna exlude this branch from e2e-aws as well?

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests.

**Comment by haircommander** [comment]
no, e2e-aws should block in 1.19, though I hardly think the failures here are related to this PR

/retest
/lgtm

**Comment by umohnani8** [comment]
Failures look unrelated
/test e2e-aws

**Review by saschagrunert — COMMENTED** [review]
/retest

**Pull request merged**
