### PR TITLE
server: use background context for network stop

### PR DESCRIPTION
**Pull request by haircommander**
or else the cleanup will always fail on cleanup from context deadline

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
pick of https://github.com/cri-o/cri-o/pull/4817
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by fidencio** [comment]
/approve
LGTM

thanks, @haircommander

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request closed without merging**
