### PR TITLE
Fix the kubeadm command

### PR DESCRIPTION
**Pull request by mkumatag**
#### What type of PR is this?

> /kind api-change

/kind bug
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### What this PR does / why we need it:
This will fix the documentation error for creating kubeadm cluster
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
/ok-to-test

Thank you for the contribution! 🙏

**Comment by dougsland** [comment]
The CI issues seems not related to the patch:
```
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:549
May 23 17:43:23.214: Expected
    <string>: 
to contain substring
    <string>: stdin closed
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:573
```

**Comment by umohnani8** [comment]
LGTM

**Comment by haircommander** [comment]
this is a docs only PR, and CI is still not in the happiest place. Force merging as such. thanks for the PR  @mkumatag

**Pull request merged**
