### PR TITLE
server: notify user when network is not ready yet

### PR DESCRIPTION
**Pull request by haircommander**
Or else they don't know why cri-o is waiting

also, catch server shutdown so the process does eventually shutdown.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
fix a bug where CRI-O would never shutdown if the networking plugin wasn't configured correctly
```

### CODE REVIEW

**Comment by fgiudici** [comment]
lgtm
Nice patch!

**Comment by TomSweeneyRedHat** [comment]
LGTM
once tests are happy

**Review by mrunalp — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
