### PR TITLE
Use google.golang.org/protobuf instead of gogo

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Rely on the official protobuf package instead of the deprecated gogo extension.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Pull request merged**
