### PR TITLE
Remove Update() method

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
The method is not used within CRI-O as well as the not needed `updateLock`.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
But I'm kind of surprised this isn't used anywhere.

**Comment by saschagrunert** [comment]
> LGTM
> But I'm kind of surprised this isn't used anywhere.

/shrug

**Comment by haircommander** [comment]
nice
/lgtm

**Pull request merged**
