### PR TITLE
[1.18] drop conmonmon

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
drop conmonmon (as amazing as the name was)

cherry-pick of https://github.com/cri-o/cri-o/pull/3363

conmonmon never really figured out how to handle a cgroup being torn down out of order (conmon before a container) and was generally pretty racy. With the integration of conmon 2.0.11, we now prevent conmon from ever being OOM killed. For now, drop conmonmon until a better solution is found
#### Which issue(s) this PR fixes:
should fix https://bugzilla.redhat.com/show_bug.cgi?id=1809593

#### Special notes for your reviewer:
In general, bumping conmon and droping this will lower the chance of false positive oom kills (where we think there was an oom but there actually wasn't)
#### Does this PR introduce a user-facing change?

```release-note
Fix bug resulting in false reports of OOM
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
I think we have to rebuild the CircleCI container images for the 1.18 release branch

**Comment by haircommander** [comment]
> I think we have to rebuild the CircleCI container images for the 1.18 release branch

https://github.com/cri-o/cri-o/pull/3417 passed without the need

**Comment by haircommander** [comment]
we're seeing a lot of 
```
Mar 19 17:03:10 ip-172-18-1-161.ec2.internal crio[14845]: time="2020-03-19 17:03:10.947852149Z" level=warning msg="Unable to get stats for container 289a5bc2c6f14d1621b37d8afe025467a2cb3d1e6735ade143df4487b0e9addd: unable to load cgroup at kubepods-burstable-pod16bd9bfb_76d7_48b4_930b_8c0042dc01fe.slice: cgroup deleted" id=54a6a1dc-eabb-419b-af18-4caeac1599d8
```
which https://github.com/cri-o/cri-o/pull/3398 will fix. There's also a lot of 
```

Mar 19 17:03:02 ip-172-18-1-161.ec2.internal crio[14845]: time="2020-03-19 17:03:02.277105938Z" level=warning msg="ImageStatus: error getting status from docker.io/library/httpd:2.4.38-alpine: size for layer \"5d4b2827cb944e51f2ad9da0bd1f69b672c5fd27ef4ea99e14c3b15a5e08d3d2\" is unknown, failing getSize()" id=a9f119d6-9788-45f0-9c7b-3b5d48e76000
```
and I don't know if that's a problem or something that requires fixing...

/retest

**Pull request merged**
