### PR TITLE
test: fix api server insecure port

### PR DESCRIPTION
**Pull request by haircommander**
commit https://github.com/kubernetes/kubernetes/commit/cfc2b330a7027e109ac26fc6a86b68898883099e
causes tests to fail because we're using the default insecure port of 8080, which is no longer valid

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind failing-test

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
I will also see how the change is taken in upstream k8s

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by giuseppe — COMMENTED** [review]
/retest
LGTM

**Comment by haircommander** [comment]
this was fixed upstream with https://github.com/kubernetes/kubernetes/pull/96025

**Pull request closed without merging**
