### PR TITLE
Clean capabilities if drop ALL

### PR DESCRIPTION
**Pull request by QiWang19**
#### What type of PR is this?

> /kind bug

#### What this PR does / why we need it:
Add call of function to clean up capabilities if configurations drop all of them.
#### Which issue(s) this PR fixes:

https://bugzilla.redhat.com/show_bug.cgi?id=1931838
#### Does this PR introduce a user-facing change?

```release-note
Fix drop all capabilities usring ALL.
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
if this fails e2e tests, then we know the old behaviour is expected. putting a
/hold

to do more investigation

**Pull request closed without merging**
