### PR TITLE
begin ADOPTERS.md file

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### What this PR does / why we need it:
more adopters to come
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM, I think we could also add SUSE CaaSP Platform 4 - 4.5 and kubic.

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by haircommander** [comment]
> LGTM, I think we could also add SUSE CaaSP Platform 4 - 4.5 and kubic.

yeah, I figured I'd let you write the blurb for SUSE pieces :smile:

**Comment by saschagrunert** [comment]
> > LGTM, I think we could also add SUSE CaaSP Platform 4 - 4.5 and kubic.
> 
> yeah, I figured I'd let you write the blurb for SUSE pieces

Sounds good, so let this get merged first :+1:

**Pull request merged**
