### PR TITLE
Update conmon-rs

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
To fix the CI.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
wow! happy green tests!

**Comment by saschagrunert** [comment]
@haircommander PTAL

**Comment by saschagrunert** [comment]
Tide seems to have troubles but all green, merging.

**Pull request merged**
