### PR TITLE
Add further kinds to pull request template

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
I think we can add those further kinds as we might want to apply them as well.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by haircommander** [comment]
can we get a dependency bump kind? I'm not sure the best language for it, but no other label seems to properly describe bumping a dependency version

**Comment by saschagrunert** [comment]
> can we get a dependency bump kind? I'm not sure the best language for it, but no other label seems to properly describe bumping a dependency version

Yes, for that we have to change the prow configuration. Let me check if that works:
/area dependency

**Comment by saschagrunert** [comment]
Hm, since we already have `area/dependency` I think it will be hard to justify a `kind/dependency{-change}`. :thinking: 

/retest

**Comment by haircommander** [comment]
since when do we even have an `area/` ?!

I'd still push for dependency change because prow forces a kind, and (probably) doesn't consider area as a replacement.

that can be addressed later  though

/lgtm

**Comment by saschagrunert** [comment]
@haircommander I think we can manually merge this. It's just the PR template.

**Pull request merged**
