### PR TITLE
Bump shellcheck to 0.8.0, fix or suppress new warnings

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind ci
/kind cleanup

#### What this PR does / why we need it:

Bumps shellcheck to 0.8.0, fixes or suppresses new warnings.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Please review commit-by-commit.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by kolyshkin** [comment]
> /hold shfmt seems unhappy

My bad; fixed.

**Review by saschagrunert — APPROVED** [review]
/unhold
/lgtm

**Comment by haircommander** [comment]
/hold

something is up here..

**Comment by haircommander** [comment]
```
./test/test_runner.sh 
++ time bats --jobs 16 --tap .
./test/test_runner.sh: line 25: time: command not found
```

uhh

**Comment by kolyshkin** [comment]
> ```
> ./test/test_runner.sh 
> ++ time bats --jobs 16 --tap .
> ./test/test_runner.sh: line 25: time: command not found
> ```
> 
> uhh

Weird. `time` is bash builtin, which is available since forever, and this is a bash script. It is also available as a standalone binary, but I'm not sure why builtin is not used.

Ah!  Using builtins is not working when doing substitutions. The fix is to use `time` explicitly, rather than passing it as a parameter.

Fix pushed.

**Pull request merged**
