### PR TITLE
[1.13] test: add changes required for fedora 30 AMI

### PR DESCRIPTION
**Pull request by haircommander**
Including removing our own debugging callback
change from package to a manual shell call (because python2-dnf is sunsetted, but we still need python2 for oct)
disable nodev for userns test
Signed-off-by: Peter Hunt pehunt@redhat.com

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.

**Comment by haircommander** [comment]
I reverted the ami switch, so this passed against the old ami and isn't testing anything. 
/hold

**Comment by giuseppe** [comment]
LGTM

**Comment by haircommander** [comment]
/hold cancel

we will need this to merge PRs now that we switched to f30

**Comment by saschagrunert** [comment]
I think I’m not allowed to do this on this branch but let’s give it a try:

/approve

**Comment by haircommander** [comment]
Finally, happy tests PTAL

**Pull request merged**
