### PR TITLE
[1.18] bump containers image to 5.4.4

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
to fix issue in signature verification

#### Which issue(s) this PR fixes:
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1836442

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM
/retest

**Comment by haircommander** [comment]
needs https://github.com/cri-o/cri-o/pull/3802

**Comment by haircommander** [comment]
@chavafg heya, got another set of reproducible errors. When you have a sec PTAL :smiley:

**Comment by chavafg** [comment]
Hi @haircommander, we have had issues today in the CI because some Azure services also had some issues, so I think this may be related. I see that at some point, the job lost connection with the VM. 
Can you restart the job?

**Comment by haircommander** [comment]
/retest

thanks :D

**Pull request merged**
