### PR TITLE
[1.18] use master circle images

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
switches to use master circle images, which will allow us to better stay in sync with master until v1.18.0 is cut

this also bumps 1.18 go version to 1.14
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
this is ready PTAL @umohnani8 @saschagrunert @rhatdan

**Comment by umohnani8** [comment]
LGTM, but needs a rebase

**Comment by haircommander** [comment]
> LGTM, but needs a rebase

curses! thanks for the ping :upside_down_face:

**Pull request merged**
