### PR TITLE
[1.16] port error: check for error

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
checks for an error when reporting there was an error
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
this is ready

**Comment by umohnani8** [comment]
@haircommander is this still needed?

**Comment by haircommander** [comment]
*needed* no, but a nice to have and not risky.

**Comment by haircommander** [comment]
1.16 is out of support

**Pull request closed without merging**
