### PR TITLE
server: filter sysctls passed through CRI if host namespace

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
fixes https://github.com/cri-o/cri-o/security/advisories/GHSA-w2j5-3rcx-vx7x
#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where a pod given a host IPC or network namespace could configure sysctls on the host
```

### CODE REVIEW

**Comment by haircommander** [comment]
running CI here to make sure nothing unexpected fails

**Review by giuseppe — APPROVED** [review]
LGTM

although I am not sure about the security implications.  For using a host namespace, the container is already privileged.  AFAIK, runc has already the same check and it was added to the last release of crun as well.

**Review by fgiudici — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
> although I am not sure about the security implications. For using a host namespace, the container is already privileged. AFAIK, runc has already the same check and it was added to the last release of crun as well.

yeah I waiver between this being moderate and low severity. most kubernetes clusters don't do anything to prevent users from using host namespaces (until updated PSP, which is fairly new), which makes it more nefarious for upstream consumers (OCP has SCC, which mitigates this). However, the underlying principle is that a container affects the host in a way that wasn't really intended, which does feel like a container breakout

**Pull request merged**
