### PR TITLE
Deflake RHEL layer removal integration test

### PR DESCRIPTION
**Pull request by saschagrunert**
Playing around with the CI to get more information how to deflake the test

Needs https://github.com/containers/storage/pull/495

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hehe...
/retest

**Comment by saschagrunert** [comment]
I give this another try via a force push to the same commit.

**Comment by saschagrunert** [comment]
This is a different issue related to the OOM test...
/retest

**Comment by haircommander** [comment]
I wonder if bumping the retries just a bit (going to 10 perhaps) would do the trick

**Comment by saschagrunert** [comment]
The change has been merged. I’ll rebase on top of containers/storage master tomorrow. :)

**Comment by saschagrunert** [comment]
The related PR got merged, I'm now vendoring contianers/storage lastest master.

**Comment by saschagrunert** [comment]
Looks like the test is now much more stable, PTAL

**Comment by haircommander** [comment]
/lgtm
Good find @saschagrunert 🙌

**Pull request merged**
