### PR TITLE
get script: fix conflist path

### PR DESCRIPTION
**Pull request by amarlearning**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

Fix the `get-script` job caused by `install: cannot stat 'contrib/10-crio-bridge.conflist': No such file or directory`

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by amarlearning** [comment]
@haircommander since you rolled back the CNI version of `11-crio-ipv4-bridge.conflist` from `1.0.0` to `0.3.1` in [this](https://github.com/cri-o/cri-o/pull/6468) PR.

We can find `11-crio-ipv4-bridge.conflist` file in the latest CRI-O artifact because it is on version `0.3.1` but other CNI example [files](https://github.com/cri-o/cri-o/tree/main/contrib/cni) are not present in the latest CRI-O artifacts ~since they are on version `1.0.0`.~

A probable reason why other files like `[10-crio-bridge.conflist](https://github.com/cri-o/cri-o/blob/main/contrib/cni/10-crio-bridge.conflist)` and `[99-loopback.conflist](https://github.com/cri-o/cri-o/blob/main/contrib/cni/99-loopback.conflist)` are not present in the CRI-O artifacts because they are not added in the build.

See this https://github.com/cri-o/cri-o/blob/214b77367c48acd75a08610ac8d0941540347691/contrib/bundle/build#L38-L42

We are only adding `11-crio-ipv4-bridge.conflist` to the build artifact and ignoring others.

Since you have already rolled back to `0.3.1`, fixing the pipeline considering that change.

**Comment by haircommander** [comment]
/ok-to-test

thanks for finding this @amarlearning !

**Comment by haircommander** [comment]
```

# github.com/containers/storage/drivers/btrfs
vendor/github.com/containers/storage/drivers/btrfs/btrfs.go:385:11: args.lim.max_referenced undefined (type _Ctype_struct_btrfs_qgroup_limit has no field or method max_referenced)
gmake: *** [Makefile:199: bin/crio] Error 2


```
(in fedora tests)
I think this should be fixed by https://github.com/cri-o/cri-o/pull/6479

**Comment by amarlearning** [comment]
@haircommander If you feel ok, I would to revert [this](https://github.com/cri-o/cri-o/commit/d06cae7c928cc661ed6d3ecf3c0d4385a58330ca) change.

I guess you made that change to resolve this issue.

**Comment by haircommander** [comment]
how would you feel about doing so as a follow up? you can pick this commit to a new PR to test.

**Comment by amarlearning** [comment]
@haircommander sure I will do it in separate PR. Thanks!

**Pull request merged**
