### PR TITLE
Bump static binary dependency versions

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change
#### What this PR does / why we need it:
This updates available dependencies for the static binary bundle.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Okay, conmon now seems to depend on go-md2man

**Comment by haircommander** [comment]
> Okay, conmon now seems to depend on go-md2man

yeah that came in before 2.0.23 I believe

**Pull request closed without merging**
