### PR TITLE
Add a hidden 'publish' command to CRI-O

### PR DESCRIPTION
**Pull request by fgiudici**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
The containerd shimv2 specification provides a 'publish-binary'
argument to allow reporting events from the shim up to the container
engine. The call to the publish binary is in the form:
$PUBLISH_BIN --address $ADDRESS publish --topic $TOPIC --namespace $NS

Usually the publish binary is the container engine itself: containerd
supports the "publish" command and shimv2 implementations use by
default the container engine as the publish binary.
Allow CRI-O to accept the "publish" command as required by the containerd
shimv2 specification, just ignoring the events without reporting errors.
#### Which issue(s) this PR fixes:
Right now when a kata-containers shimv2 workload is run with CRI-O,
the CRI-O binary is called by the containerd-shimv2 binary for every
sandbox event (e.g., sandbox creation, deletion, ...).
CRI-O returns an error as doesn't support the "publish" format above,
causing the containerd-shim-kata-v2 implementation to report an error
in the logs for each event.
Sample error:
time="2021-07-26T17:23:11.726445138+02:00" level=error msg="post event" error="failed to publish event: exit status 1" name=containerd-shim-v2 pid=9478 sandbox=6714bbfe5d600dc8c24f2c0fcf2e14857eb14cf85605aa213bb92660725335f3 source=containerd-kata-shim-v2

#### Special notes for your reviewer:
The "--address" global argument and "publish" command added are set to hidden but accepted without returning any error.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by saschagrunert** [comment]
Ah the completions have to be updated: https://github.com/cri-o/cri-o/pull/5129/checks?check_run_id=3163396027

**Comment by fgiudici** [comment]
> Ah the completions have to be updated: https://github.com/cri-o/cri-o/pull/5129/checks?check_run_id=3163396027

Oh, right, thanks Sascha!

**Comment by fidencio** [comment]
LGTM, as long as CI passes.
Thanks @fgiudici!

**Comment by haircommander** [comment]
you've still got some completions issues :\

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests
3 are not at the moment

**Comment by fgiudici** [comment]
@haircommander , @TomSweeneyRedHat : thanks, sure, I have to fix completion still.
I am using this PR to test tune a new Fedora 34 AMI image for CI, so I am taking this slowly...
retested all to see if the integration test would pass (it did). I expected also the  e2e_crun_cgroupv2 would have passed, let's see after I will update with the completion. Thanks!

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
/hold

I dont think we want ami_fedora retesting so much

**Comment by haircommander** [comment]
@fgiudici are you still using this to test it?

**Comment by fgiudici** [comment]
> @fgiudici are you still using this to test it?

yeah, thanks @haircommander  and sorry for letting this run. I need some more time before retesting the F34 ami.  
I would let this PR to move forward. Rebasing on master.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
