### PR TITLE
Use containerd v1.7.0-beta.0 

### LINKED ISSUE #6350: runtime_vm: golang panic: "protobuf tag not enough fields in Status.state" when handling errors from the kata shim
### What happened?

While testing kata with cri-o 1.25, we found that cri-o was crashing sometimes.
Further investigation shown that this is happening when the kata shim returns an error to cri-o on any calls it makes.

This is the same bug as #3991, but this time it occurs only on errors, not on every call.

Looking into the code, it seems the error was introduced by this commit: https://github.com/cri-o/cri-o/commit/40df9c9ae05e2ea376f65a8b8431a429b1ff112c

It is removing the "replace" directive we had in go.mod to downgrade genproto to a version that doesn't trigger this issue in gogo/protobuf.
The issue was not found immediately because it's not systematic anymore - I'm not sure why.

Downgrading genproto again seems not possible, as opentelemetry requires a higher version of genproto.

### What did you expect to happen?

cri-o should not crash

### How can we reproduce it (as minimally and precisely as possible)?

Modify the kata configuration to make the hypervisor path point to a non-existing binary.
When starting a container with the kata runtime, the kata shim will error out because of the wrong path.

### Anything else we need to know?

_No response_

### CRI-O and Kubernetes version

<details>

The issue was found in cri-o v1.25. It can also be seen on main.
It is not visible in 1.24

</details>

### OS version

<details>

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

### PR DESCRIPTION
**Pull request by littlejawa**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
containerd has released a new version v1.7.0-beta.0, where the gogo/protobuf dependency was removed.
I have tried it with cri-o, and it seems to be working as expected.

This is still a beta release though, so we have to be cautious in using it. But at least, it shows that the next release of containerd should fix our problem.

If accepted, this replaces the PR #6371 

#### Which issue(s) this PR fixes:

Fixes #6350 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
/lgtm

I don't think CI issues are related

**Review by fidencio — APPROVED** [review]
lgtm, thanks @littlejawa!

**Comment by littlejawa** [comment]
@haircommander - it seems I can't set the milestone here, but this is the PR that I think should be part of 1.26

**Comment by haircommander** [comment]
@littlejawa can you rebase to get the ci fixes

**Pull request merged**
