### PR TITLE
Bump github.com/containers/libpod from 1.2.0 to 1.3.1

### PR DESCRIPTION
**Pull request by saschagrunert**
Bumps [github.com/containers/libpod](https://github.com/containers/libpod) from 1.2.0 to 1.3.1.

<details>
<summary>Release notes</summary>

*Sourced from [github.com/containers/libpod's releases](https://github.com/containers/libpod/releases).*

> ## v1.3.1
> ## Features
> - The `podman cp` command can now read input redirected to `STDIN`, and output to `STDOUT` instead of a file, using `-` instead of an argument.
> - The Podman remote client now displays version information from both the client and server in `podman version`
> - The `podman unshare` command has been added, allowing easy entry into the user namespace set up by rootless Podman (allowing the removal of files created by rootless Podman, among other things)
> 
> ## Bugfixes
> - Fixed a bug where Podman containers with the `--rm` flag were removing created volumes when they were automatically removed ([#3071](https://github-redirect.dependabot.com/containers/libpod/issues/3071))
> - Fixed a bug where container and pod locks were incorrectly marked as released after a system reboot, causing errors on container and pod removal ([#2900](https://github-redirect.dependabot.com/containers/libpod/issues/2900))
> - Fixed a bug where Podman pods could not be removed if any container in the pod encountered an error during removal ([#3088](https://github-redirect.dependabot.com/containers/libpod/issues/3088))
> - Fixed a bug where Podman pods run with the `cgroupfs` CGroup driver would encounter a race condition during removal, potentially failing to remove the pod CGroup
> - Fixed a bug where the `podman container checkpoint` and `podman container restore` commands were not visible in the remote client
> - Fixed a bug where `podman remote ps --ns` would not print the container's namespaces ([#2938](https://github-redirect.dependabot.com/containers/libpod/issues/2938))
> - Fixed a bug where removing stopped containers with healthchecks could cause an error
> - Fixed a bug where the default `libpod.conf` file was causing parsing errors ([#3095](https://github-redirect.dependabot.com/containers/libpod/issues/3095))
> - Fixed a bug where pod locks were not being freed when pods were removed, potentially leading to lock exhaustion
> - Fixed a bug where 'podman run' with SD_NOTIFY set could, on short-running containers, create an inconsistent state rendering the container unusable
> 
> ## Misc
> - The remote Podman client now uses the Varlink bridge to establish remote connections by default
> 
> ## v1.3.0
> ## Features
> - Podman now supports container restart policies! The `--restart-policy` flag on `podman create` and `podman run` allows containers to be restarted after they exit. Please note that Podman cannot restart containers after a system reboot - for that, see our next feature
> - Podman `podman generate systemd` command was added to generate systemd unit files for managing Podman containers
> - The `podman runlabel` command now allows a `$GLOBAL_OPTS` variable, which will be populated by global options passed to the `podman runlabel` command, allowing custom storage configurations to be passed into containers run with `runlabel` ([#2399](https://github.com/containers/l\
> ibpod/issues/2399))
> - The `podman play kube` command now allows `File` and `FileOrCreate` volumes
> - The `podman pod prune` command was added to prune unused pods
> - Added the `podman system migrate` command to migrate containers using older configurations to allow their use by newer Libpod versions ([#2935](https://github-redirect.dependabot.com/containers/libpod/issues/2935))
> - Podman containers now forward proxy-related environment variables from the host into the container with the `--http-proxy` flag (enabled by default)
> - Read-only Podman containers can now create tmpfs filesystems on `/tmp`, `/var/tmp`, and `/run` with the `--read-only-tmpfs` flag (enabled by default)
> - The `podman init` command was added, performing all container pre-start tasks without starting the container to allow pre-run debugging
> 
> ## Bugfixes
> - Fixed a bug where `podman cp` would not copy folders ([#2836](https://github-redirect.dependabot.com/containers/libpod/issues/2836))
> - Fixed a bug where Podman would panic when the Varlink API attempted too pull a non-existent image ([#2860](https://github-redirect.dependabot.com/containers/libpod/issues/2860))
> - Fixed a bug where `podman rmi` sometimes did not produce an event when images were deleted
> - Fixed a bug where Podman would panic when the Varlink API passed improperly-formatted options when attempting to build ([#2869](https://github-redirect.dependabot.com/containers/libpod/issues/2869))
> - Fixed a bug where `podman images` would not print a header if no images were present ([#2877](https://github-redirect.dependabot.com/containers/libpod/pull/2877))
> - Fixed a bug where the `podman images` command with `--filter dangling=false` would incorrectly print dangling images instead of images which are not dangling ([#2884](https://github-redirect.dependabot.com/containers/libpod/issues/2884))
> - Fixed a bug where rootless Podman would panic when any command was run after the system was rebooted ([#2894](https://github-redirect.dependabot.com/containers/libpod/issues/2894))
> - Fixed a bug where Podman containers in user namespaces would include undesired directories from the host in `/sys/kernel`
> - Fixed a bug where `podman create` would panic when trying to create a container whose name already existed
> - Fixed a bug where `podman pull` would exit 0 on failing to pull an image ([#2785](https://github-redirect.dependabot.com/containers/libpod/issues/2785))
> - Fixed a bug where `podman pull` would not properly print the cause of errors that occurred ([#2710](https://github-redirect.dependabot.com/containers/libpod/issues/2710))
> - Fixed a bug where rootless Podman commands were not properly suspended via `ctrl-z` in a shell ([#2775](https://github-redirect.dependabot.com/containers/libpod/issues/2775))
> - Fixed a bug where Podman would error when cleaning up containers when some container mountpoints in `/sys/` were cleaned up already by the closing of the mount namespace
> - Fixed a bug where `podman play kube` was not including environment variables from the image run ([#2930](https://github-redirect.dependabot.com/containers/libpod/issues/2930))
> - Fixed a bug where `podman play kube` would not properly clean up partially-created pods when encountering an error
></tr></table> ... (truncated)
</details>
<details>
<summary>Changelog</summary>

*Sourced from [github.com/containers/libpod's changelog](https://github.com/containers/libpod/blob/master/changelog.txt).*

> - Changelog for v1.3.1 (2019-05-16)
>   * More release notes
>   * Add unshare to podman
>   * Release notes for 1.3.1
>   * Kill os.Exit() in tests, replace with asserts
>   * Minor capitalization fix in Readme
>   * Add debug mode to Ginkgo, collect debug logs in Cirrus
>   * set default event logger based on build tags
>   * Add VarlinkCall.RequiresUpgrade() type and method
>   * Ensure that start() in StartAndAttach() is locked
>   * When removing pods, free their locks
>   * network: raise a clearer error when using CNI
>   * Fix libpod.conf option ordering
>   * split remote tests from distro tests
>   * varlink: fix usage message, URI is now optional
>   * Update containerd/cgroups to 4994991857f9b0ae
>   * healthcheck benign error
>   * Add `systemd` build tag
>   * podman: fix events help string
>   * When removing a pod with CGroupfs, set pids limit to 0
>   * Add fix for an issue breaking our CI
>   * Use standard remove functions for removing pod ctrs
>   * implement cp reads tar file from stdin/stdout
>   * Add information when running podman version on client
>   * add varlink bridge
>   * Add negative command-line test
>   * Preserve errors returned by removing pods
>   * Improve robustness of pod removal
>   * enable integration tests for remote-client
>   * fix podman-remote ps --ns
>   * podman-run|create man updates
>   * Update installation instructions
>   * remote-podman checkpoint and restore add to container submenu
>   * Remove tests for deprecated podman-refresh command
>   * When refreshing after a reboot, force lock allocation
>   * Do not remove volumes when --rm removes a container
>   * add unit tests for generate systemd
>   * Bump gitvalidation epoch
>   * Bump to v1.3.1-dev
>   * Upgrade to latest criu and selinux-policy
>   * Only run checkpoint/restore tests on Fedora >= 29
>   * Fix API.md
>   * Cirrus: Add missing task dependencies
>   * Cirrus: Add check for make varlink_api_generate
> 
> - Changelog for v1.3.0 (2019-05-06)
>   * Update release notes for 1.3.0 release
>   * Bump to Buildah v1.8.2
>   * Document events logger options in libpod.conf manpage
>   * Try and fix restart-policy tests
></tr></table> ... (truncated)
</details>
<details>
<summary>Commits</summary>

- [`7210727`](https://github.com/containers/libpod/commit/7210727e205c333af9a2d0ed0bb66adcf92a6369) Bump to v1.3.1
- [`e2cd3d2`](https://github.com/containers/libpod/commit/e2cd3d2eec0124ffe2097cfbe40f5956e1e7b5ca) Merge pull request [#3141](https://github-redirect.dependabot.com/containers/libpod/issues/3141) from mheon/revert_3090
- [`601fc2c`](https://github.com/containers/libpod/commit/601fc2ce4fa888cdd0cc33c41f6eee7ca39f585c) Revert "Add VarlinkCall.RequiresUpgrade() type and method"
- [`8161802`](https://github.com/containers/libpod/commit/8161802f7df857e0850f842261079c83290f9891) Merge pull request [#3135](https://github-redirect.dependabot.com/containers/libpod/issues/3135) from mheon/release_notes_1.3.1
- [`ff70b60`](https://github.com/containers/libpod/commit/ff70b6031a5f02844af9ff23a64d6681e0c385fc) Merge pull request [#3090](https://github-redirect.dependabot.com/containers/libpod/issues/3090) from jwhonce/wip/upgrade_link
- [`9b81b0d`](https://github.com/containers/libpod/commit/9b81b0dd59b93f7286681a0401be3afaed1651b3) More release notes
- [`bd21a99`](https://github.com/containers/libpod/commit/bd21a99501ca088e0fd6a36bc8007c931bc5d5ef) Merge pull request [#3121](https://github-redirect.dependabot.com/containers/libpod/issues/3121) from giuseppe/rootless-error-cni
- [`2bb1487`](https://github.com/containers/libpod/commit/2bb1487a00d23bb38314b7d7ee861952b7c6517e) Merge pull request [#2969](https://github-redirect.dependabot.com/containers/libpod/issues/2969) from weirdwiz/master
- [`2a961a7`](https://github.com/containers/libpod/commit/2a961a711312375273aa17f784d795b9c13b9e6e) Add unshare to podman
- [`5445d7d`](https://github.com/containers/libpod/commit/5445d7d104087974f57f1c9c7d9774d83427895e) Merge pull request [#3123](https://github-redirect.dependabot.com/containers/libpod/issues/3123) from mheon/release_notes_1.3.1
- Additional commits viewable in [compare view](https://github.com/containers/libpod/compare/v1.2.0...v1.3.1)
</details>

This dependency update comes as a separate PR because I had to remove parts of the container server.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but tests aren't hip

**Comment by giuseppe** [comment]
/test e2e_rhel
test e2e_fedora

**Pull request merged**
