### PR TITLE
TEST: force manage_network_ns_lifecycle

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@mrunalp @haircommander is this enough for testing the `manage_network_ns_lifecycle` setting?

**Comment by haircommander** [comment]
yeah this would work. we mine as well also remove the existence of `manage_network_ns_lifecycle` in the ansible

**Comment by giuseppe** [comment]
the failure doesn't seem to be a flake

**Comment by haircommander** [comment]
test failures are unrelated to the PR. they can be fixed once the jenkins jobs are updated, which I'm working on getting done

**Comment by mrunalp** [comment]
We can test this with OCP is by opening a PR to machine-config-operator to change the crio.conf.

**Pull request closed without merging**
