### PR TITLE
[1.19] bump containers/storage to 1.20.5 to fix EINTR

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

_(this is similar to #4334 but for 1.19 release branch)_

This is mostly to have the backport of containers/storage#757 brought in
which should fix occasional CI failures (and probably real failures, too).

#### Which issue(s) this PR fixes:

> time="2020-11-02T19:00:03Z" level=fatal msg="creating container: rpc error: code = Unknown desc = error creating an ID-mapped copy of layer "01d6f430ddfdf1203b505fbb03c6479802a3366609d5e0231a30f85f412f873d": exit status 1: error during chown: storage-chown-by-maps: chown("lib/apk/db/scripts.tar"): lchown lib/apk/db/scripts.tar: interrupted system call"

periodically caught by CI

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
Fix occasional "chown: interrupted system call" error on container creation.
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by kolyshkin** [comment]
build-static step failed in pipeline with this (from [here](https://circleci.com/api/v1.1/project/github/cri-o/cri-o/106070/output/104/0?file=true&allocation-id=5fa17aa0c50450771afa064b-0-build%2F8CDBE6C)

```
cri-o> ./.cache/store/.links/1w3sqaz9rca7jxiinbma87prdkx23s95k7wvv9gydvfsv2im5dz6: unsupported interpreter directive "/usr/bin/env -S nix-build --no-out-link" (set dontPatchShebangs=1 and handle shebang patching yourself)
```

and I don't have a slightest idea of what it is. 

Restarted.

**Comment by kolyshkin** [comment]
/retest

still don't know what to do with nix build

**Comment by kolyshkin** [comment]
Other PRs from 1.19 branch were merged with the same CI issue (pipeline static nix build) not solved (e.g. https://github.com/cri-o/cri-o/pull/4355), so I guess this one can also be merged.

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
