### PR TITLE
WIP: improve the irqbalance restore flow

### PR DESCRIPTION
**Pull request by fromanirh**
#### What type of PR is this?

/kind cleanup
/kind feature

#### What this PR does / why we need it:
Since https://github.com/cri-o/cri-o/pull/4441 , to support the dynamic irqbalance configuration in turn needed by the high
performance hooks, CRI-O runs the restore code at startup.

In some configuration scenarios it's preferred to have more control over this step. Some configuration wants
to have more control over the mask to be restored, or to disable the restore flow entirely.

For this reason, we add an option to provide a user-supplied restore file. Users wishing to exert more control can provide
their data, or they can disable the flow entirely setting the path to the restore file to empty string ("").

The new option defaults are meant to ensure full backward compatibility.

#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?

```release-note
Add configuration option to control the irqbalance configuration restore process for high performance hooks dynamic IRQ pinning.
```

### CODE REVIEW

**Comment by mrunalp** [comment]
Can you rebase to pick up ci fixes?

**Comment by rphillips** [comment]
hmm. alpine image is still being fetched from docker.io

**Comment by rphillips** [comment]
https://github.com/cri-o/cri-o/pull/6106 migrates more images to quay

**Comment by fromanirh** [comment]
> @fromanirh could you do one more rebase on top of latest main branch?

sure, done. Thanks!

**Comment by fromanirh** [comment]
closing in favor of https://github.com/cri-o/cri-o/pull/6388

**Pull request closed without merging**
