### PR TITLE
WIP: Make the OCI interface public

### PR DESCRIPTION
**Pull request by saschagrunert**
A first approach in splitting external and internal OCI types.

### CODE REVIEW

**Comment by haircommander** [comment]
a quick skim LGTM, I'll do a more thorough review in a bit

my one concern is I wanted to start reducing duplication between libpod's oci implementation and cri-o's. Included in this was ensuring feature pairity of the oci runtime interface to the needs of libpod. I can escalate that work if this PR is desired, but I'd like to make sure libpod doesn't need an API extension before we make this public.

WDYT @vrothberg @saschagrunert

**Comment by saschagrunert** [comment]
> a quick skim LGTM, I'll do a more thorough review in a bit
> 
> my one concern is I wanted to start reducing duplication between libpod's oci implementation and cri-o's. Included in this was ensuring feature pairity of the oci runtime interface to the needs of libpod. I can escalate that work if this PR is desired, but I'd like to make sure libpod doesn't need an API extension before we make this public.
> 
> WDYT @vrothberg @saschagrunert

Sounds good, I agree we should not do the work multiple times. Lets also wait for #2255 to see if such an API fits.

**Comment by vrothberg** [comment]
> my one concern is I wanted to start reducing duplication between libpod's oci implementation and cri-o's. Included in this was ensuring feature pairity of the oci runtime interface to the needs of libpod. I can escalate that work if this PR is desired, but I'd like to make sure libpod doesn't need an API extension before we make this public.
> 
> WDYT @vrothberg @saschagrunert

In general, I have a bad feeling about exposing APIs. Containers are moving fast, and the golang ecosystem is not as strict as the C community when it comes to stability etc. Making other projects depend on CRI-O on that level makes me _very_ nervous. Using libpod would make sense as this would (or should) be the common ground of many projects. I cannot quantify it (yet) but I find libpod's API cleaner than CRI-O's. Less redundancy, less scattering, etc.

**Comment by rhatdan** [comment]
I agree the interface should be in libpod, not CRI-O.

**Comment by saschagrunert** [comment]
As I understood https://github.com/cri-o/cri-o/issues/2255 correctly, CRI-O should be able to depend on runtime implementations which follow a common functionality. If we now put the interface into libpod, then developers have to depend on libpod to build a runtime for CRI-O?

Do we want to add the runtime interface I exposed here to libpod and depend on that implementation?

**Comment by rhatdan** [comment]
I want to eventually move most of the internals of CRI-O to libpod, and better unify the projects.

**Comment by saschagrunert** [comment]
> I want to eventually move most of the internals of CRI-O to libpod, and better unify the projects.

Sounds reasonable, I will close this one for now.

**Pull request closed without merging**
