### PR TITLE
vendor: pin shfmt to v3.2.0

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

> /kind flake

#### What this PR does / why we need it:

Commit 4c998460305ced958da (PR #4259) had to use shfmt from master/HEAD as
there were no released version that supported bats syntax.

Now there is (https://github.com/mvdan/sh/releases/tag/v3.2.0), so let's
pin it to avoid sudden regressions caused by changes in master branch.

Brought to you by:

	go get mvdan.cc/sh/v3@v3.2.0
	go mod vendor
	go mod tidy
	git add vendor
	git commit -as

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by kolyshkin** [comment]
Obviously, CI failures are unrelated 

/retest

**Review by saschagrunert — APPROVED** [review]
/lgtm
/retest

**Comment by kolyshkin** [comment]
CI failures are all the same; there's an issue about it: kubernetes/kubernetes#96222

Saying `/retest` won't help until the above issue is fixed. Alternatively, we can exclude the test (slowly working on that).

**Comment by kolyshkin** [comment]
> Saying /retest won't help until the above issue is fixed.

Ahhh, it seems to be fixed.

/retest

**Pull request merged**
