### PR TITLE
Automatically `chcon` and `restorecon` on get script

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This allows SELinux enabled distributions to automatically set the right contexts.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Automatically `chcon` and `restorecon` on get script for SELinux enabled distributions.
```

### CODE REVIEW

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by saschagrunert** [comment]
/override ci/openshift-jenkins/integration_fedora
/override ci/openshift-jenkins/integration_rhel

This script is not being used by those tests. I think they're broken in general.

**Pull request merged**
