### PR TITLE
test: use kata 3.1.3

### PR DESCRIPTION
**Pull request by littlejawa**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

Use the latest version of kata-containers for the kata integration tests

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by littlejawa** [comment]
/hold
Looks like we get a regression on the stats tests.

**Comment by littlejawa** [comment]
Added a fix for cgroupv2 metrics structure that kata is now returning.

/unhold

**Comment by littlejawa** [comment]
Testing on my side: I have other fixes to add to this PR

/hold

**Comment by littlejawa** [comment]
/unhold

I had to modify the way to check what cgroup version we get: the guest VM may be using a different version than the host, so I can't just look at the host's settings to decide how to deal with the data.

Also: I'm retrieving page fault numbers, even though at the moment they're not returned by the kata shim. I will work on the kata side to put them in the structure. In the meantime, they will be 0.

**Review by sohankunkerkar — COMMENTED** [review]
/retest
/lgtm

**Pull request merged**
