### PR TITLE
Downgrade golangci-lint to v1.23.8

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
This is a workaround to stabilize our CI and reduce to out of memory
kills in CircleCI.
#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but some tests are still not happy

**Comment by saschagrunert** [comment]
This test is not required :)

/test e2e_cgroupv2

**Pull request merged**
