### PR TITLE
Do not take config dir into account on config creation

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
The local configuration should have no influence on the created config
so we now reset the "-d" option as well.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by saschagrunert** [comment]
@haircommander I think this might be ready to be merged.

**Pull request merged**
