### PR TITLE
Disable short name mode

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

#### What this PR does / why we need it:

Disable the short name mode so we don't use the alias table
when pulling images. We will revisit this is in the next release.

#### Which issue(s) this PR fixes:

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1969599

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by mtrmac** [comment]
> Disable the short name mode so we don't use the alias table when pulling images

For the record, that’s not what that option does; it doesn’t affect alias resolution in any way, and assuming CRI-O is run in non-interactive mode without a TTY attached, this PR has absolutely no effect.

**Pull request merged**
