### PR TITLE
Bump Kubernetes to v1.23.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Bump vendored Kubernetes to the latest release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
We need go 1.17 for this. :-/

**Comment by haircommander** [comment]
I believe you need to apply 
```diff
**diff --git a/contrib/test/ci/cri-o.spec b/contrib/test/ci/cri-o.spec
index c723830ac1..7265b62516 100644
--- a/contrib/test/ci/cri-o.spec
+++ b/contrib/test/ci/cri-o.spec
@@ -13,7 +13,7 @@
 
 %if ! 0%{?centos} && 0%{?rhel}
 # Golang minor version
-%global gominver 16
+%global gominver 17
 %define gobuild(o:) scl enable go-toolset-1.%{gominver} -- go build -buildmode pie -compiler gc -tags="rpm_crashtraceback no_openssl ${BUILDTAGS:-}" -ldflags "${LDFLAGS:-} -B 0x$(head -c20 /dev/urandom|od -An -tx1|tr -d ' \\n') -extldflags '%__global_ldflags'" -a -v -x %{?**};
 %else
 %define gobuild(o:) go build -buildmode pie -compiler gc -tags="rpm_crashtraceback no_openssl ${BUILDTAGS:-}" -ldflags "${LDFLAGS:-} -B 0x$(head -c20 /dev/urandom|od -An -tx1|tr -d ' \\n') -extldflags '%__global_ldflags'" -a -v -x %{?**};
```

to fix openshift e2e

**Comment by saschagrunert** [comment]
> to fix openshift e2e

Thank you! I bumped the go version and rebased.

**Comment by saschagrunert** [comment]
@fidencio it looks like that kata is broken across several PRs:
```
09:07:47 Failed at 578: bash ${script_dir}/../../../ci/install_libseccomp.sh "${libseccomp_install_dir}" "${gperf_install_dir}"
09:07:48 make: *** [Makefile:93: /tmp/jenkins/workspace/kata-containers-2-crio-PR/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/.ubuntu_rootfs.done] Error 7
09:07:48 [install_kata_image.sh:50] ERROR: sudo -E USE_DOCKER= DISTRO=ubuntu make -e image
09:07:48 [install_kata.sh:22] ERROR: .ci/install_kata_image.sh 
```
May I ask you to give it a look?

**Comment by saschagrunert** [comment]
Okay I think we have to switch the image base as well: https://github.com/openshift/release/pull/24591

**Pull request merged**
