### PR TITLE
Bump the CRI-O commit used for node testing to the tip of main

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

It will allow to use the OOM killer fixes done in k/k testing, see discussion: https://github.com/kubernetes/kubernetes/pull/113205#issuecomment-1415968592.

This will yet require a bump of the image reference in the test-infra. A commit similar to this one: https://github.com/kubernetes/test-infra/commit/2b30f2e31d90eabcc47f7616e19e3485b09a9f59.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
/assign @haircommander
PTAL

**Comment by haircommander** [comment]
/approve

LGTM thanks! PTAL @cri-o/cri-o-maintainers

**Comment by haircommander** [comment]
@littlejawa another kata failure, is this one legit?

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
We also have to bump it in test-infra: https://github.com/kubernetes/test-infra/blob/b7f08bba13f078d9c42084c60143c0bbdebe26a0/jobs/e2e_node/crio/templates/base/crio-install.yaml#L17

**Comment by littlejawa** [comment]
> @littlejawa another kata failure, is this one legit?

sorry for the late reply. I missed the notification.
No, it's not legit. Not sure why, but it broke during the CI job setup - nothing to do with cri-o.
I ran it again (outside of this PR) and it went fine.

**Pull request merged**
