### PR TITLE
OCPBUGS-29398: [release-1.26] Fix wrong umask by updating c/common

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Refers to https://issues.redhat.com/browse/OCPBUGS-29398
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Fixed wrong umask of `0000`.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@cri-o/ocicni-maintainers PTAL

**Comment by saschagrunert** [comment]
/hold 

needs https://github.com/containers/common/pull/1858

**Comment by haircommander** [comment]
/hold

we need to keep this branch in sync with podman v4.4.1-crio branch, so we'll need to pick it back to a different branch

**Comment by saschagrunert** [comment]
Updated that PR to the latest commit on https://github.com/containers/common/tree/crio-1.26

**Pull request merged**
