### PR TITLE
conmon cgroups: don't create cgroupfs group for systemd

### PR DESCRIPTION
**Pull request by vrothberg**
Don't create a cgroupfs cgroup when running with systemd as the cgroups
manager.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@giuseppe, @rhatdan ... more clean ups will follow in other PRs.

**Comment by haircommander** [comment]
wowzers that's a clear bug LGTM, though you may need to add an integration test or something to make codecov happy

**Comment by haircommander** [comment]
marking this as needs backport because I have a feeling this leak exists elsewhere...

**Comment by vrothberg** [comment]
> marking this as needs backport because I have a feeling this leak exists elsewhere...

There's another issue, namely that those cgroups are not cleaned, so the leaks are even bigger :^) I'll wrap something up for that soon.

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
LGTM

**Comment by vrothberg** [comment]
@saschagrunert, are you okay with merging this?

**Comment by saschagrunert** [comment]
Merging manually since codecov is not happy and I see no need for another rebase on top of the latest fixes.

**Comment by vrothberg** [comment]
Thanks, @saschagrunert :pray:

**Pull request merged**
