### PR TITLE
Close the stdin/tty on server start to avoid shortname prompts

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This avoids prompting for shortname expansion if CRI-O runs inside of a terminal.

#### Which issue(s) this PR fixes:

Refers to https://github.com/cri-o/cri-o/pull/4455
#### Special notes for your reviewer:
/assign @vrothberg 
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
This should not happen in CRI-O unless CRI-O leaves stdin/tty open which it shouldn't as a daemon.  Forcing to disabled mode may not be desired when user want to enforce it in the registries.conf.

Did you run into CRI-O prompting?

**Comment by saschagrunert** [comment]
> Did you run into CRI-O prompting?

Yes, I think we will not run into this issue when using CRI-O with systemd.

When running CRI-O in a standard TTY like my development setup, then it will ask for the name to resolve which seems annoying. Do you see a way to disable at least the prompt without breaking the behavior?

/hold

**Comment by vrothberg** [comment]
> > Did you run into CRI-O prompting?
> 
> Yes. So, we will not run into this issue when using CRI-O with systemd.
> 
> When running CRI-O in a standard TTY like my development setup, then it will ask for the name to resolve which seems annoying. Do you see a way to disable at least the prompt without breaking the behavior?

Oh that's unfortunate - I should have caught that in my PR. Thanks for tackling that so quickly!

I think CRI-O could use the same trick as we applied to Podman: https://github.com/containers/podman/commit/b96c3489d043

**Comment by saschagrunert** [comment]
Thank you for the hint to the commit @vrothberg, changed the PR as suggested.

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks @saschagrunert !

**Comment by rhatdan** [comment]
lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
