### PR TITLE
test/*bats: simplify, fix, improve, and enable shellcheck

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

A set of assorted improvements for integration tests:
 - remove some testdata files
 - use `jq` (rather than python or sed) to edit json
 - fix ~~some~~ all shellcheck warnings
 - enable shellcheck for bats files :tada: 

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None
~~Currently based on top of https://github.com/cri-o/cri-o/pull/4405~~

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
rebased

**Comment by kolyshkin** [comment]
Wow, and all this even works! :dancers:

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
