### PR TITLE
Switch to go 1.15

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
k8s 1.19 is going to release with go 1.15

#### Does this PR introduce a user-facing change?

```release-note
Compile with go 1.15
```

### CODE REVIEW

**Comment by haircommander** [comment]
```
/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:182 failed to create TempDir "": pattern contains path separator Unexpected error: <*errors.errorString | 0xc000066270>: { s: "pattern contains path separator", } pattern contains path separator occurred /go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:407
```
:\

**Comment by umohnani8** [comment]
@sboeuf @chavafg the kata test seems to be stalling, could you please take a look.

**Comment by chavafg** [comment]
We had an issue with the CI yesterday night and now we have lot of jobs in queue, I see job already started running and should report back soon. Sorry for the inconvenience

**Comment by umohnani8** [comment]
Awesome! Thanks for the update :)

**Pull request merged**
