### PR TITLE
drop specgen from crio

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Drop specgen from podman in crio. This was not a dependency that podman wanted to export into containers/common. Looking at the change, its a pretty simple port to crio.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — CHANGES_REQUESTED** [review]
We need to run `go mod tidy && go mod vendor` to make the vendor check happy:
https://github.com/cri-o/cri-o/actions/runs/8287671745/job/22680552194?pr=7891

**Comment by kannon92** [comment]
I think the CRIO CI hates me..

I ran `make check-vendor`

```
kehannon@kehannon-thinkpadp1gen4i:~/Work/cri-o$ make check-vendor 
go mod tidy
go mod vendor
go mod verify
all modules verified
./hack/tree_status.sh
tree is clean
```
So not really sure why it is failing now..

**Comment by kannon92** [comment]
Not sure if this is related.

```
# time="2024-03-15 13:51:36.711953601Z" level=debug msg="Error pulling image quay.io/crio/alpine@sha256:414e0518bb9228d35e4cd5165567fb91d26c6a214e9c95899e1e056fcd349011: copying system image from manifest list: reading signatures: reading manifest sha256-65b3a80ebe7471beecbc090c5b2cdd0aafeaefa0715f8f12e40dc918a3a70e32.sig in quay.io/crio/alpine: received unexpected HTTP status: 502 Bad Gateway" file="server/image_pull.go:259" id=27a63b6d-44cd-4c13-8fce-58055b646021 name=/runtime.v1.ImageService/PullImage
# time="2024-03-15 13:51:36.712165402Z" level=debug msg="Response error: copying system image from manifest list: reading signatures: reading manifest sha256-65b3a80ebe7471beecbc090c5b2cdd0aafeaefa0715f8f12e40dc918a3a70e32.sig in quay.io/crio/alpine: received unexpected HTTP status: 502 Bad Gateway" file="otel-collector/interceptors.go:71" id=27a63b6d-44cd-4c13-8fce-58055b646021 name=/runtime.v1.ImageService/PullImage
```
/retest

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
