### PR TITLE
[1.17] move default version file location a tmpfs

### PR DESCRIPTION
**Pull request by haircommander**
as we should really wipe crio after every reboot, so let's put it on a tmpfs

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
/retest

LGTM

**Comment by saschagrunert** [comment]
/test launch-aws
--

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Pull request merged**
