### PR TITLE
Update golangci lint and apply fixes

### PR DESCRIPTION
**Pull request by saschagrunert**
The new recommended way is to use the golangci install script,
which we now use. All new linter issues have been fixed and
additionally added linters are commented out per default.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Tests aren't hip.  Changes LGTM, but I'm shocked by the number of vendored files removed by this.

**Comment by saschagrunert** [comment]
Had to rebase on top of the latest master to resolve the conflicts

**Pull request merged**
