### PR TITLE
[1.25] Fix cgroup leak for systemd cgroup driver

### LINKED ISSUE #6349: 1.24.3 leaks pidns with cgroup v2
### What happened?

Observed that on a node where many cronjobs get scheduled (i.e.many pods being created than stopped), syslog entries appear:
```
Nov 07 08:22:18 k8s-node16 kubelet[699]: W1107 08:22:18.605965     699 container.go:589] Failed to update stats for container "/pids/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podeb779fdd_e230_4fb0_b027_f9f91f117b46.slice/crio-f1800404321299f38a4ba5dfedf95df94b825507597527b48bf3a6d9f2f3eb13.scope": unable to determine device info for dir: /var/lib/containers/storage/overlay/304bfd8df6d35aaf9a5632b9bcdc69bdd54aa9277baf2c18c4930072d017514c/diff: stat failed on /var/lib/containers/storage/overlay/304bfd8df6d35aaf9a5632b9bcdc69bdd54aa9277baf2c18c4930072d017514c/diff with error: no such file or directory, continuing to push stats
```

That is because entries under `/sys/fs/cgroup/pids/kubepods.slice/kubepods-burstable.slice/` are not cleaned up. I suspect the count of `crictl pods` and entries under the mentioned dir should be in sync, but I may be wrong.

```
# crictl pods
POD ID              CREATED             STATE               NAME                     NAMESPACE           ATTEMPT             RUNTIME
6b309d1ef5223       13 minutes ago      Ready               kube-router-dr2vh        kube-system         0                   (default)
41b1338d583b2       13 minutes ago      Ready               truenas-csi-node-5lkh5   truenas-csi         0                   (default)
b12fd8fb24ccb       13 minutes ago      Ready               promtail-vfflj           monitoring          0                   (default)
950e109f187a0       13 minutes ago      Ready               node-exporter-km99c      kube-system         0                   (default)
# ls -la /sys/fs/cgroup/pids/kubepods.slice/kubepods-burstable.slice/
total 0
drwxr-xr-x 11 root root 0 Nov  7 08:13 .
drwxr-xr-x  3 root root 0 Nov  7 08:13 ..
-r--r--r--  1 root root 0 Nov  7 08:13 cgroup.controllers
-r--r--r--  1 root root 0 Nov  7 08:13 cgroup.events
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.freeze
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.max.depth
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.max.descendants
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.procs
-r--r--r--  1 root root 0 Nov  7 08:13 cgroup.stat
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.subtree_control
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.threads
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.type
-rw-r--r--  1 root root 0 Nov  7 08:13 cpu.pressure
-r--r--r--  1 root root 0 Nov  7 08:13 cpu.stat
-rw-r--r--  1 root root 0 Nov  7 08:13 io.pressure
drwxr-xr-x  3 root root 0 Nov  7 08:34 kubepods-burstable-pod321a0667_9839_4537_8dfe_8a2f42ed2a01.slice
drwxr-xr-x  3 root root 0 Nov  7 08:13 kubepods-burstable-pod571e43da_a130_438b_86d8_5b5fea8c2180.slice
drwxr-xr-x  3 root root 0 Nov  7 08:13 kubepods-burstable-pod57769bbc_9867_42a7_83bd_7a65fc4791ab.slice
drwxr-xr-x  3 root root 0 Nov  7 08:29 kubepods-burstable-pod5872eef3_b96b_488c_8338_265e32a9b87c.slice
drwxr-xr-x  3 root root 0 Nov  7 08:16 kubepods-burstable-podb2f5e0d7_a53b_4a33_a4ab_ca4ac994e365.slice
drwxr-xr-x  3 root root 0 Nov  7 08:13 kubepods-burstable-podb3174e7f_0cb1_47d5_8b6e_5c1b9904f07e.slice
drwxr-xr-x  3 root root 0 Nov  7 08:34 kubepods-burstable-podb3e4520f_03ad_46e0_bfcc_c1dc739260e8.slice
drwxr-xr-x  3 root root 0 Nov  7 08:16 kubepods-burstable-podeb779fdd_e230_4fb0_b027_f9f91f117b46.slice
drwxr-xr-x  3 root root 0 Nov  7 08:13 kubepods-burstable-podec55611f_6ee5_481f_9e8b_f6ae883baf29.slice
-rw-r--r--  1 root root 0 Nov  7 08:13 memory.pressure
```

Howewer I have 4 running pods, and 9 entries under /sys. kubelet/cadvisor then logs warning messages for pid namespaces not cleaned up, and this floods my logs.

### What did you expect to happen?

Expected every resource cleaned up after pod termination, logs being not flooded.

### How can we reproduce it (as minimally and precisely as possible)?

Have cgroups v2 with crio-1.24. Start and stop a pod on the node, and observe entries not being removed from `/sys/fs/cgroup/pids/kubepods.slice/kubepods-burstable.slice`.

### Anything else we need to know?

It is to be noted that with v1.25 `/sys/fs/cgroup/pids` just does not exist.

### CRI-O and Kubernetes version

<details>

```console
# crio --version
crio version 1.24.3
Version:          1.24.3
GitCommit:        251db4e7a44dd5b76586bd2f8d818691ed8413f7
GitTreeState:     clean
BuildDate:        2022-11-07T06:13:20Z
GoVersion:        go1.18.8
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        apparmor, exclude_graphdriver_devicemapper, containers_image_openpgp, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  true
```

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```
</details>

### OS version

<details>

```console
# On Linux:
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# uname -a
Linux k8s-node16 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Bare metal
</details>

### PR DESCRIPTION
**Pull request by n4j**
Backmerge PR

Closes #6349

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR fixes an issue whereby cgroups are not cleaned up after a Pod is terminated, this is an issue with cri-o versions prior to `1.26`

#### Which issue(s) this PR fixes:
Fixes #6349 

#### Does this PR introduce a user-facing change?
No

```release-note

```

### CODE REVIEW

**Comment by n4j** [comment]
@haircommander

**Comment by n4j** [comment]
@haircommander I ran workloads.bats integration tests on `release-1.25` branch and exact same test cases are failing as in  action `test-cgroupfs` in this PR with the exact same error.

Here's how I ran the suite on `release-1.25` branch which doesn't contain my code
```bash
sudo \
 CONTAINER_CGROUP_MANAGER=cgroupfs \
 CONTAINER_CONMON_CGROUP=pod \
 bats test/workloads.bats
```

### Test failures

```
 ✗ test workload pod gets configured to defaults
   (from function `check_conmon_fields' in file test/workloads.bats, line 71,
    in test file test/workloads.bats, line 190)
     `check_conmon_fields "$ctr_id" "$shares" "$set"' failed

 ✗ test workload pod should override infra_ctr_cpuset option
   (from function `check_conmon_fields' in file test/workloads.bats, line 71,
    in test file test/workloads.bats, line 289)
     `check_conmon_fields "$ctr_id" "$shares" "$set"' failed

✗ test workload can override pod defaults
   (from function `check_conmon_fields' in file test/workloads.bats, line 71,
    in test file test/workloads.bats, line 216)
     `check_conmon_fields "$ctr_id" "$shares" "$set"' failed

✗ test workload pod should not be set if not defaulted or specified
   (from function `check_conmon_fields' in file test/workloads.bats, line 71,
    in test file test/workloads.bats, line 242)
     `check_conmon_fields "$ctr_id" "$shares" "$set"' failed

✗ test workload pod should not be set if annotation not specified
   (from function `check_conmon_fields' in file test/workloads.bats, line 71,
    in test file test/workloads.bats, line 263)
     `check_conmon_fields "$ctr_id" "$shares" "$set"' failed
```

I believe the error is thrown from `check_conmon_fields` and below is the offending suite

```bash 
# Line 67, below is the root cause
found_cpushares=$(cat "$cpushare_path/pod_123-456/crio-conmon-$ctr_id/$cpushare_filename")
if [ -z "$cpushares" ]; then
        [[ $(cat "$cpushare_path/pod_123-456/$cpushare_filename") == *"$found_cpushares"* ]]
else
        [[ "$cpushares" == *"$found_cpushares"* ]] # Line 71, offending line
fi
```

IMHO, this is an existing flak, I checked via some debug logs that `systemd.go:CreateSandboxCgroup` doesn't get called when the driver is `cgroupfs`.

**Comment by n4j** [comment]
@haircommander could you give an /ok-to-test approval on this PR?

**Review by saschagrunert — COMMENTED** [review]
/ok-to-test

**Pull request merged**
