### PR TITLE
Update setup.md

### LINKED ISSUE #2450: Build cri-o failed because of golang version is not match
**Description**

**Steps to reproduce the issue:**
1.Install golang 1.10.2 on  amd64 ubuntu 16.04
2.`go get -u github.com/cri-o/cri-o`
3.`cd ~/goPath/src/github.com/cri-o/cri-o/ `
4.`make`

**Describe the results you received:**
```
go build -ldflags '-s -w -X main.gitCommit="66eaece433489575f46261b90252c84c58b7e93e" -X main.buildInfo=1559785299' -tags "containers_image_ostree_stub     libdm_no_deferred_remove  seccomp selinux" -o bin/crio github.com/cri-o/cri-o/cmd/crio
# github.com/cri-o/cri-o/oci
oci/runtime_vm.go:175:20: undefined: strings.ReplaceAll
Makefile:120: recipe for target 'bin/crio' failed
make: *** [bin/crio] Error 2
```

**Describe the results you expected:**
can build cri-o successfully
**Additional information you deem important (e.g. issue happens only occasionally):**
 I follow the setup.md building the cri-o.The doc indicated that I should use golang `1.8.x`or higher.I use golang 1.10.2 but build failed.
 Can we update on doc about the accurate golang version?

### PR DESCRIPTION
**Pull request by hmtai**
Update  golang version

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

Fix #2450

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
Thanks for the PR @hmtai! Changes LGTM--you'll need to run
`git commit --amend -s` to sign off your commit.

**Comment by rhatdan** [comment]
Thanks @hmtai for helping out.

**Pull request merged**
