### PR TITLE
docs: improve installation instructions for debian

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind documentation
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by fidencio** [comment]
LGTM.

On a site note, how's it affecting Ubuntu?

**Comment by haircommander** [comment]
> LGTM.
> 
> On a site note, how's it affecting Ubuntu?

quick test on 18.04 seemed to work without this

**Comment by lsm5** [comment]
@haircommander i think buster-backports entries exist in /etc/apt/sources.list by default.

**Comment by lsm5** [comment]
> @haircommander i think buster-backports entries exist in /etc/apt/sources.list by default.

err no, my bad.

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
