### PR TITLE
server: update container status if state has bogus information

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug 
#### What this PR does / why we need it:
if CreatedAt is zero, the Kubelet will complain and also be confused by the container.
Attempt to update in this case.

Signed-off-by: Peter Hunt <pehunt@redhat.com>
#### Does this PR introduce a user-facing change?

```release-note
fix a bug where the status of a container ends up being bogus, causing Kubelet to print `verify ContainerStatus failed" err="status.CreatedAt is not set` repeatedly.
```

### CODE REVIEW

**Comment by haircommander** [comment]
related to https://github.com/kubernetes/kubernetes/issues/105332 and https://bugzilla.redhat.com/show_bug.cgi?id=2094865

**Review by saschagrunert — APPROVED** [review]
LGTM, I assume we cannot reproduce this scenario and therefore have no integration test for it?

**Comment by haircommander** [comment]
no reproducer yet, but I did add a unit test :)

**Comment by haircommander** [comment]
possible alternative to this: https://github.com/cri-o/cri-o/pull/6026

if we go that route, we could potentially backport this fix to older branches, and leave that one for 1.25

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Pull request closed without merging**
