### PR TITLE
Update golangci-lint and config

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We now update the golangci-lint version to the latest release as well as
the configuration. This enables the linters bidichk, decorder, errchkjson,
grouper, tenv as well as new gocritic linters and fixes their reports.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve 
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
