### PR TITLE
Add `namespaces{-_}dir` CLI and config option

### PR DESCRIPTION
**Pull request by saschagrunert**
This makes the namespaces dir configurable in its location.

### CODE REVIEW

**Comment by haircommander** [comment]
I would mention that we only use it when we're managing ns lifecycle in all the docs, otherwise LGTM

**Comment by saschagrunert** [comment]
> I would mention that we only use it when we're managing ns lifecycle in all the docs, otherwise LGTM

Sure, I added this as well and rebased on top of the latest master branch.

**Comment by saschagrunert** [comment]
Had to rebase to resolve the conflicts.

**Comment by saschagrunert** [comment]
/test e2e_fedora
--

**Pull request merged**
