### PR TITLE
Move crio defaults back to /etc/crio/crio.conf

### PR DESCRIPTION
**Pull request by umohnani8**
#### What type of PR is this?

/kind design

#### What this PR does / why we need it:
The config default should be in /etc/crio/crio.conf and not
in /etc/crio/crio.conf.d/00-defaults.conf.

#### Does this PR introduce a user-facing change?

```release-note

```

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
/retest

LGTM

PTAL @saschagrunert

**Comment by haircommander** [comment]
we have talked about maybe having 1.18 deprecate the use of crio.conf, then 1.19 fully use crio.conf.d

**Comment by TomSweeneyRedHat** [comment]
LGTM, but would like a head nod from @saschagrunert

**Pull request merged**
