### PR TITLE
[1.9] Fix possible out of bounds access during log parsing

### PR DESCRIPTION
**Pull request by saschagrunert**
This PR backports #2180

### CODE REVIEW

**Comment by saschagrunert** [comment]
Travis for the 1.9 release branch seems broken for some time. :thinking:

**Comment by umohnani8** [comment]
LGTM

**Comment by umohnani8** [comment]
Travis is failing on `make testunit`

**Comment by saschagrunert** [comment]
> Travis is failing on `make testunit`

The `go get` on `go-md2man` fails because they do not support go 1.8 any more. How do we want to proceed here? I could prepare a fix for that on a separate branch I guess.

**Comment by rhatdan** [comment]
I think we should just force merge.
@mrunalp WDYT?

**Comment by mrunalp** [comment]
yeah merging.

**Pull request merged**
