### PR TITLE
OWNERS: allow cri-o reviewers to approve dependabot PRs

### PR DESCRIPTION
**Pull request by sohankunkerkar**
#### What type of PR is this?

/kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve

LGTM, @cri-o/cri-o-maintainers PTAL
(we may want to add a blurb to the GOVERNANCE.md file to describe this change)

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
