### PR TITLE
[1.19] introduce seccomp override empty

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind feature
> /kind flake

#### What this PR does / why we need it:
right now, the CRI defaults to an unconfined profile when it's set to empty
However, it's possible admins want the behavior to default to the default profile instead.

add a knob to allow admins to override the empty behavior from unconfined to the default
Note, when set this technically makes CRI-O not CRI compliant, but for increased security, it's worth it.
#### Does this PR introduce a user-facing change?

```release-note
Add option `seccomp_override_empty` to override an unspecified seccomp profile from being unconfined to being the runtime default. Note: setting this option makes CRI-O not fully CRI compliant, but does increase security. 
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander what's the reasoning behind this backport? I think we should be conservative about cherry-picking features like this.

**Comment by haircommander** [comment]
yeah I agree we should generally be careful, but this is a useful feature that allows users to cover a class of problems that are annoying to cover otherwise (making the seccomp profile applied by default)

**Review by saschagrunert — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
