### PR TITLE
update go to 1.17 in go.mod

### PR DESCRIPTION
**Pull request by QiWang19**
Update go to 1.17 in go.mod (Replace  https://github.com/cri-o/cri-o/pull/5473)

Signed-off-by: rockmenjack <rockmen1@gmail.com>
Signed-off-by: Qi Wang <qiwan@redhat.com>

#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
golang 1.15 can no longer compile cri-o because kubernetes/client-go@ef1d5d2 has introduced io/fs which comes with golang 1.17
```
# make binaries
mkdir -p "/root/cri-o/_output/src/github.com/cri-o"
ln -s "/root/cri-o" "/root/cri-o/_output/src/github.com/cri-o/cri-o"
touch "/root/cri-o/_output/.gopathok"
go build -trimpath  -ldflags '-s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate='2021-11-24T03:40:58Z' -X github.com/cri-o/cri-o/internal/version.gitCommit=2811bd6afea913deb176acd667b904978c273e81 -X github.com/cri-o/cri-o/internal/version.gitTreeState=clean ' -tags "containers_image_ostree_stub  exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove    " -o bin/crio github.com/cri-o/cri-o/cmd/crio
vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/metrics.go:21:2: cannot find package "." in:
        /root/cri-o/vendor/io/fs
make: *** [Makefile:172: bin/crio] Error 1
```
#### Which issue(s) this PR fixes:
this PR just update go.mod to reflect dependency on golang 1.17+

#### Does this PR introduce a user-facing change?

```release-note
update go to 1.17 in go.mod
```

### CODE REVIEW

**Comment by QiWang19** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by haircommander** [comment]
thanks for taking this over, openshift CI is sad today. if it doesn't get fixed by tomorrow, I'll push this through

/approve

**Comment by haircommander** [comment]
can you rebase to fix CI @QiWang19 ?

**Pull request merged**
