### PR TITLE
managed ns: report namespace cleanup failure by default

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

 /kind cleanup

#### What this PR does / why we need it:
it could be useful to know whether the namespaces are actually getting cleaned up
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
