### PR TITLE
[1.15] cgroupfs fixes

### PR DESCRIPTION
**Pull request by vrothberg**
Backports of:
* https://github.com/cri-o/cri-o/pull/2601
* https://github.com/cri-o/cri-o/pull/2587

### CODE REVIEW

**Comment by vrothberg** [comment]
| /test e2e_features_rhel
-- | --

**Comment by vrothberg** [comment]
@saschagrunert, can we make codecov report but not block for 1.15 as well?

**Comment by saschagrunert** [comment]
> @saschagrunert, can we make codecov report but not block for 1.15 as well?

Yes, this will be done globally with https://github.com/openshift/release/pull/4354

**Comment by vrothberg** [comment]
Awesome, thanks @saschagrunert !

**Comment by vrothberg** [comment]
@giuseppe @rhatdan @umohnani8 @mrunalp PTAL

**Comment by haircommander** [comment]
/lgtm
/retest
@saschagrunert was there a codecov fix 1.15 missed? #2611 didn't fail

**Pull request merged**
