### PR TITLE
changes in README

### PR DESCRIPTION
**Pull request by vikash2310**
Signed-off-by: vikash <singh.vikash2310@gmail.com>

#### What type of PR is this?
/kind documentation

#### Special notes for your reviewer:
Fixed multiple typos in the README file including correcting the spelling of convenience earlier it was convinience.

#### Does this PR introduce a user-facing change?
None

```release-note

```

### CODE REVIEW

**Comment by umohnani8** [comment]
/approve

Thanks @vikash2310 for the PR! Can you please add some description to the commit message on what the changes are, something like "fix multiple typos in the readme". And please fill in the fields in the initial description template https://github.com/cri-o/cri-o/pull/5902#issue-1242955272

**Comment by vikash2310** [comment]
Hey @umohnani8 I've updated the description message in comment

**Review by saschagrunert — APPROVED** [review]
Thank you!
/lgtm

**Comment by vikash2310** [comment]
Thanks @haircommander @saschagrunert @umohnani8

**Pull request merged**
