### PR TITLE
[1.18] Allow release notes for release branches

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This changes the release notes generation script to also work for
release branches.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
Needs a forward-port to the master branch as well.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by saschagrunert** [comment]
Hm, I'll cherry-pick manually

**Pull request merged**
