### PR TITLE
Make integration-cgroupfs tests depdent on results

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This should bring the CI in order again to not slip-through the recently
added integration suite.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by haircommander** [comment]
oops!
/lgtm

**Comment by umohnani8** [comment]
/retest
LGTM

**Pull request merged**
