### PR TITLE
Add OBS package build jobs

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

On every `main` commit we will now build packages within OBS:

- https://build.opensuse.org/project/show/isv:kubernetes:addons:cri-o:prerelease:main:build

This also happens for future tags, for example

- https://build.opensuse.org/project/show/isv:kubernetes:addons:cri-o:stable:v1.29:build

#### Which issue(s) this PR fixes:

Refers to https://github.com/cri-o/cri-o/issues/7280 and https://github.com/kubernetes/release/issues/3214

#### Special notes for your reviewer:

The cronjob for releasing the packages into the dedicated release repos is right now only working for `main` on a daily basis.

- https://build.opensuse.org/project/show/isv:kubernetes:addons:cri-o:prerelease:main

I'll blog about this at some later point and add documentation as follow-up if everything works as expected.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by hasan4791** [comment]
One thing, the changelog portion in the spec file is empty. Is that fine?
https://build.opensuse.org/package/view_file/isv:kubernetes:addons:cri-o:prerelease:main:build/cri-o/cri-o.spec?expand=1

**Comment by saschagrunert** [comment]
> One thing, the changelog portion in the spec file is empty. Is that fine? https://build.opensuse.org/package/view_file/isv:kubernetes:addons:cri-o:prerelease:main:build/cri-o/cri-o.spec?expand=1

Yep, that’s intentional right now. :)

**Comment by saschagrunert** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by haircommander** [comment]
Something we've hit with the release-notes actions is we have sometimes challenging dependency issue of having the git source of the script definition being in the same location as the code it's attempting to analyze. WDYT about having a separate repo `github.com/cri-o/packaging` or something that has this cron job and checks out the required branches of cri-o? then, we could concentrate changes to a single branch (instead of needing to backport changes) as well as change the packaging code independently of the source

**Comment by haircommander** [comment]
awesome work btw, I'm so excited for this

**Comment by saschagrunert** [comment]
@haircommander sounds good to me, can you create the repo and provide me admin access? This way I could move all bits over there. 😊

**Comment by haircommander** [comment]
> @haircommander sounds good to me, can you create the repo and provide me admin access? This way I could move all bits over there. 😊

done! you also should have been an admin on cri-o org a long time ago, so I added you there too

**Comment by saschagrunert** [comment]
Closing, moving everything over to the new repo.

**Pull request closed without merging**
