### PR TITLE
docs: drop IRC

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind documentation
#### What this PR does / why we need it:
we didn't really spend that much time there anyway, and the hostile take over presents us a good opportunity to sunset it.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Comment by TomSweeneyRedHat** [comment]
LGTM
but as an internet dinosaur, I'm sorry to see.

**Comment by haircommander** [comment]
I said

/override ci/prow/e2e-agnostic

**Pull request merged**
