### PR TITLE
Bump Kubernetes to v1.25.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Update Kubernetes to the latest release.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
Holding off for the final Kubernetes release.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
@saschagrunert is this still work in progress?

**Comment by saschagrunert** [comment]
> @saschagrunert is this still work in progress?

Yes, let's wait for the final release to be published.

**Pull request merged**
