### PR TITLE
contrib/test/int: assorted minor cleanups

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

Assorted fixes and cleanups to contrib/test/integration.

Please see individual commits for details.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by kolyshkin** [comment]
Failures in circleci (in `docs-generation` and `completions-validation`) do not make any sense; restarted

**Comment by kolyshkin** [comment]
@haircommander there is a failure in integration_rhel+userns (see https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/4419/test_pull_request_crio_integration_rhel/21891/artifacts/testout_userns.txt)

> not ok 182 should not clean up container after timeout
>  (in test file ./timeout.bats, line 69)
>   `created_ctr_id=$("$CONTAINER_RUNTIME" --root "$RUNTIME_ROOT" list -q | grep -v "$pod_id")' failed
> time="2020-12-09T02:02:14Z" level=fatal msg="creating container: rpc error: code = DeadlineExceeded desc = context deadline exceeded"

The test case is from https://github.com/cri-o/cri-o/pull/4394; but this branch does not have it. I guess CI is testing commits from this PR applied on top of latest master.

Anyway, my guess is 2s is too low for our slow and highly parallel CI.

**Comment by kolyshkin** [comment]
> there is a failure in integration_rhel+userns 

Trying to address that in https://github.com/cri-o/cri-o/pull/4422

/retest

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by mrunalp — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
