### PR TITLE
test: fix timeout metric test

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind failing-test
#### What this PR does / why we need it:
fixes https://github.com/cri-o/cri-o/issues/7018
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
Alas it still fails (https://github.com/cri-o/cri-o/actions/runs/5180990183/jobs/9335888439?pr=7019)

```
not ok 291 emit metric when container is re-requested
# (in test file ./timeout.bats, line 239)
#   `[[ "$METRIC" == 'container_runtime_crio_resources_stalled_at_stage{stage="container runtime creation"} 1' ]]' failed
```

**Comment by haircommander** [comment]
only remaining failure is the oom issue, this is ready

PTAL @cri-o/cri-o-maintainers

**Comment by haircommander** [comment]
this is ready @cri-o/cri-o-maintainers

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
