### PR TITLE
Skip already uploaded artifacts with gsutil

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
It might be possible that we re-run the CI and the artifact already
exists. In that case we will not fail the `results` step.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by dougsland** [comment]
@saschagrunert looks good to me but I am wondering if we should clean the artifacts every-time we re-run the job instead of use cp -n?

**Comment by saschagrunert** [comment]
> @saschagrunert looks good to me but I am wondering if we should clean the artifacts every-time we re-run the job instead of use cp -n? Might generate a false positive?

The retention strategy of the bucket does not allow removing or modifying files for 10 years. 😅 At least they’re safe.

**Comment by saschagrunert** [comment]
> LGTM if you can get that last pesky test to behave.

This test is not marked as `required` and failing recently. I think we can ignore it in this change. 🤷🏻‍♂️

**Comment by dougsland** [comment]
> > @saschagrunert looks good to me but I am wondering if we should clean the artifacts every-time we re-run the job instead of use cp -n? Might generate a false positive?
> 
> The retention strategy of the bucket does not allow removing or modifying files for 10 years.  At
>  least they’re safe.

Ah, I see. /me nods

**Pull request merged**
