### PR TITLE
Code clean up in containers_create_linux.go

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Noticed there was a TODO to assign GetSecurityContext()
a variable and use that through out the create function.

#### Does this PR introduce a user-facing change?

```release-note
None

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
Nice and tidy!

**Comment by haircommander** [comment]
:sunglasses: LGTM

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
