### PR TITLE
Use staging `k8s.io/kubelet/cri/streaming` package

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

After the merge of https://github.com/kubernetes/kubernetes/pull/118253, we can now use the upstream alternative rather than our own implementation to avoid code duplication.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
Is it possible to keep the generated code in a separate commit? It might help reviewers.

**Comment by saschagrunert** [comment]
> Is it possible to keep the generated code in a separate commit? It might help reviewers.

Hm, everything in `vendor` is usually hidden from the GitHub diff output. I'm not a big fan of having commits that don't build in the history, but I get your point. There are some code changes required for this (switching the resize channel type), though.

**Comment by sohankunkerkar** [comment]
> > Is it possible to keep the generated code in a separate commit? It might help reviewers.
> 
> Hm, everything in `vendor` is usually hidden from the GitHub diff output. I'm not a big fan of having commits that don't build in the history, but I get your point. There are some code changes required for this (switching the resize channel type), though.

ok

**Pull request merged**
