### PR TITLE
pass portmappings to cni if hostport mapping disabled on CRI-O

### PR DESCRIPTION
**Pull request by girishsg24**
The feature to disable hostport mapping on CRI-O expects the CNI to handle hostport mapping but CRI-O is not passing the mappings, this commit fixes the bug

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
With the new feature to disable hostport mapping on CRI-O to delegate the functionality to CNI, the expectation is to send the portmappings into the CNIPlugin.SetUpPodWithContext which is missing. This commit fixes the bug and handles both pod create and delete scenario

```
// pod spec
 ports:
    - containerPort: 50001
      hostPort: 50001
      name: extserver
      protocol: TCP

```
```
journalctl -u crio --since '10 minutes ago' | grep 'Got pod network' | grep foo
Aug 15 06:37:33 node1 crio.bin[1117391]: time="2023-08-15 06:37:33.865572528Z" level=info msg="Got pod network &{Name:foo-0 Namespace:foo ID:9892968458c4fb057d03cfda1f5aebf68081cbdf8505effee9a72302694e41c8 UID:7b44b270-917c-4517-a6c5-819abc7e2557 NetNS:/var/run/netns/80a1f624-a394-453e-8d8f-f13c097c1603 Networks:[] RuntimeConfig:map[multus-cni:{IP: MAC: PortMappings:[] Bandwidth:<nil> IpRanges:[] CgroupPath:kubepods-burstable-pod7b44b270_917c_4517_a6c5_819abc7e2557.slice}] Aliases:map[]}" file="ocicni/ocicni.go:795"
Aug 15 06:37:34 node1 crio.bin[1117391]: time="2023-08-15 06:37:34.027172910Z" level=info msg="Got pod network &{Name:foo-0 Namespace:foo ID:9892968458c4fb057d03cfda1f5aebf68081cbdf8505effee9a72302694e41c8 UID:7b44b270-917c-4517-a6c5-819abc7e2557 NetNS:/var/run/netns/80a1f624-a394-453e-8d8f-f13c097c1603 Networks:[] RuntimeConfig:map[multus-cni:{IP: MAC: PortMappings:[] Bandwidth:<nil> IpRanges:[] CgroupPath:kubepods-burstable-pod7b44b270_917c_4517_a6c5_819abc7e2557.slice}] Aliases:map[]}" file="ocicni/ocicni.go:795" 
```
```
PortMappings:[] is empty regardless
```

```
// After the fix
Aug 15 14:49:19 node1 crio.bin[2724298]: time="2023-08-15 14:49:19.332286443Z" level=info msg="Got pod network &{Name:foo-0 Namespace:foo ID:f95f82f357fcb765ce0e2eef34500c4e04722067411d52b835c99827f1900c19 UID:2ac8f5af-1fc7-469f-a892-79251fb7d59f NetNS:/var/run/netns/7f96cb59-6535-4fdd-8cf0-26b1e383c9cd Networks:[] RuntimeConfig:map[multus-cni:{IP: MAC: PortMappings:[{HostPort:50001 ContainerPort:50001 Protocol:TCP HostIP:}] Bandwidth:<nil> IpRanges:[] CgroupPath:kubepods-burstable-pod2ac8f5af_1fc7_469f_a892_79251fb7d59f.slice}] Aliases:map[]}" file="ocicni/ocicni.go:795"

PortMappings:[{HostPort:50001 ContainerPort:50001 Protocol:TCP HostIP:}]

IPtable rules are created in the NAT table by portmap plugin
```

#### Which issue(s) this PR fixes:
https://github.com/cri-o/cri-o/issues/7217

#### Does this PR introduce a user-facing change?

`None`

### CODE REVIEW

**Comment by girishsg24** [comment]
> I think we need an integration test for that use case.

I can add one. any pointers? 
Also i see the metrics container test 181 failed and looks like its failing for other pr too (#7129 )

**Comment by saschagrunert** [comment]
Yeah we have a hostport connection test here: https://github.com/cri-o/cri-o/blob/032e17f65387e17851b0ed2bab51edf7baf123d3/test/network.bats#L77-L101

We can also specify the CNI plugin and type in the tests directly, like there: https://github.com/cri-o/cri-o/blob/032e17f65387e17851b0ed2bab51edf7baf123d3/test/network.bats#L63

**Comment by EmilyShepherd** [comment]
This change is good - it would be a shame if it were not merged in some form or another at some point.

cri-o's current behaviour, of not passing portMappings onto the CNI plugins under any circumstances, is not the behaviour I would have expected.

**Pull request closed without merging**
