### PR TITLE
go.mod: update CDI dependency to 0.6.2.

### PR DESCRIPTION
**Pull request by klihub**
Update CDI dependecy to v0.6.2 and re-vendor.

#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:

Update CDI dependency to the latest tagged v0.6.2 version.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

CDI has now been fully migrated to `tags.cncf.io`. This is reflected in `vendor/tags.cncf.io/container-device-interface` being populated from scratch in this PR. However, we still have an indirect dependency on the original CDI location through `podman`. I'd like to wait a bit and see if podman gets a release tagged with a similar update soon. If that happens, we could consider bumping our podman dep to get rid of vendoring CDI from the original location altogether. 

#### Does this PR introduce a user-facing change?

None

```release-note
Bump CDI dependency to v0.6.2 (relocates CDI to tags.cncf.io).
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
@klihub, do you think we are somewhat closer to being able to merge this one?

**Comment by klihub** [comment]
> @klihub, do you think we are somewhat closer to being able to merge this one?

Looks like in podman only main and v4.8 gets a similar CDI dep update. I rebased on this on latest main/HEAD. If nothing new shows up in CI, I think this would be ready to go in and I'll remove the draft marker.

**Comment by klihub** [comment]
Closing. Effectively same changes has already been merged as part of #7526/493dfea424bb792ec8dc9fab61043d9f626c61f7.

**Pull request closed without merging**
