### PR TITLE
Use libpod registrar instead of pkg/registrar

### PR DESCRIPTION
**Pull request by saschagrunert**
We should use the registrar implementation of libpod since it does not
differentiate from the internal one. The registrar tests from this
repo have been migrated to libpod, so it is fine to continue the
maintenance there.

### CODE REVIEW

**Comment by vrothberg** [comment]
LGTM

**Comment by haircommander** [comment]
LGTM

**Comment by haircommander** [comment]
@stevekuznetsov we are still experiencing tide issues :/ PTAL

**Comment by stevekuznetsov** [comment]
Did any action get taken? @mrunalp @cblecker did we move to a different DCO plugin, or turn off Travis?

**Comment by cblecker** [comment]
https://github.com/openshift/release/pull/3405 will fix things once merged

**Comment by rhatdan** [comment]
Awesome thanks.

**Pull request merged**
