### PR TITLE
Pin `github.com/u-root/u-root`

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
The `dependencies` GitHub action fails since quite some time because of
this dependency:

https://github.com/cri-o/cri-o/actions/workflows/test.yml?query=branch%3Amain

```
go run ./scripts/dependencies \
	--output-path /home/runner/work/cri-o/cri-o/build/dependencies
level=info msg="Ensuring output path /home/runner/work/cri-o/cri-o/build/dependencies"
level=info msg="Getting go modules"
level=fatal msg="Unable to listing go modules: command /opt/hostedtoolcache/go/1.17.7/x64/bin/go list --mod=mod -u -m --json all did not succeed: go list -m: github.com/u-root/u-root@v7.0.0+incompatible: retracted by module author: Published v7 too early (before migrating to go modules)\n"
exit status 1
```

We now pin it to the latest `HEAD` to solve that problem.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
/hold
CI is broken

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by saschagrunert** [comment]
Fixed :)

**Pull request merged**
