### PR TITLE
[1.14]: Add disk usage for ListContainerStats

### PR DESCRIPTION
**Pull request by QiWang19**
Signed-off-by: Qi Wang <qiwan@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

Follows PR #2942 
Show disk usage in the container stats

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
thanks @QiWang19 

we typically prepend the title of the PR with [$VERSION]
for instance here we'd do `[1.14]: Add disk usage for ListContainerStats`

**Comment by QiWang19** [comment]
@haircommander changed the name. thanks :)

**Comment by haircommander** [comment]
I think this will need at least https://github.com/cri-o/cri-o/pull/2971

**Pull request merged**
