### PR TITLE
[1.18] keep conmons created by execsyncs as direct children

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
When a pod has excessive exec sync calls (say 1/second for ~100 pods), systemd has trouble keeping up with all of its new children.
While double forking in conmon is vital for calls like create container where we want to be able to detatch, for execsync calls, we already wait for the command to exit, so there's no reason to not keep conmon as a direct child

this PR adds `--sync` to calls to conmon for execsync, which tells conmon to only fork once

~wip because the conmon PR needs review and merging~
#### Special notes for your reviewer:
~this will introduce a breaking change mid release~
#### Does this PR introduce a user-facing change?

```release-note
If conmon is v2.0.19 or greater, ExecSync requests will not double fork, causing systemd to have fewer conmons re-parented to it
```

### CODE REVIEW

**Comment by haircommander** [comment]
```

[sig-node] RuntimeClass should run a Pod requesting a RuntimeClass with scheduling [NodeFeature:RuntimeHandler] [Disruptive]  expand_less | 5s
-- | --
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/node/runtimeclass.go:61 Jul  9 19:40:58.382: Error creating Pod Unexpected error:     <*errors.StatusError \| 0xc000e5d400>: {         ErrStatus: {             TypeMeta: {Kind: "", APIVersion: ""},             ListMeta: {                 SelfLink: "",                 ResourceVersion: "",                 Continue: "",                 RemainingItemCount: nil,             },             Status: "Failure",             Message: "pods \"test-runtimeclass-runtimeclass-1763-non-conflict-runtimeclass-\" is forbidden: pod rejected: RuntimeClass \"runtimeclass-1763-non-conflict-runtimeclass\" not found",             Reason: "Forbidden",             Details: {                 Name: "test-runtimeclass-runtimeclass-1763-non-conflict-runtimeclass-",                 Group: "",                 Kind: "pods",                 UID: "",                 Causes: nil,                 RetryAfterSeconds: 0,             },             Code: 403,         },     }     pods "test-runtimeclass-runtimeclass-1763-non-conflict-runtimeclass-" is forbidden: pod rejected: RuntimeClass "runtimeclass-1763-non-conflict-runtimeclass" not found occurred /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:83
```

/test e2e_features_fedora

**Comment by haircommander** [comment]
this is about ready, the last piece is getting the conmon fix in officially. I'd like reviews on the approach before I merge that

PTAL @saschagrunert @umohnani8 @mrunalp @rhatdan @kolyshkin

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
