### PR TITLE
update setup info for Debian, Raspbian and Ubuntu

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@mrunalp @umohnani8 @haircommander @saschagrunert @vrothberg PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
couldn't find convenient stuff in `/etc/os-release` for debian to generalize repo info for all 3 variants of it, so I just let them be.

**Comment by saschagrunert** [comment]
Huge thanks @lsm5

**Comment by lsm5** [comment]
> Huge thanks @lsm5 pray We probably want to link those in the main README.md side-by-side to the release versions

Ah yes, I'll update the PR with the README change. Thanks

**Comment by lsm5** [comment]
alright, ready for another review, PTAL ...

**Comment by haircommander** [comment]
tests are busted all over the place, manually merging this one

**Pull request merged**
