### PR TITLE
[1.18] fast forward from master

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
pulls all commits from latest master into 1.18, and merges the merge conflicts between cherry-picked PRs to it.
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by haircommander** [comment]
> Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.
> 
> memo **Please follow instructions in the [contributing guide](https://github.com/cri-o/cri-o/blob/master/CONTRIBUTING.md) to update your commits with the DCO**
> 
> Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).
> 
> **The list of commits missing DCO signoff**:

hypocrite
:thinking:

**Comment by haircommander** [comment]
@saschagrunert do you know how k8s deals with the merge robot not signing (does k8s merge robot sign?)

**Comment by saschagrunert** [comment]
> @saschagrunert do you know how k8s deals with the merge robot not signing (does k8s merge robot sign?)

Unfortunately the bot does not sign. How did you do the merge? Do you have specified any merge strategy?

**Pull request closed without merging**
