### PR TITLE
Add upgrade path integration tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Adding upgrade path tests to ensure correct container restore between CRI-O versions.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
neat idea! maybe we should build off of the latest in the release branches?

**Comment by saschagrunert** [comment]
> neat idea! maybe we should build off of the latest in the release branches?

We can! :)

Do you suggest do build it from source instead of using the static binaries?

**Comment by haircommander** [comment]
> > neat idea! maybe we should build off of the latest in the release branches?
> 
> We can! :)
> 
> Do you suggest do build it from source instead of using the static binaries?

I think from the latest tagged release on each branch would be sufficient

**Comment by saschagrunert** [comment]
/retest

I'm pretty sure that there is an issue but I cannot access any logs :-/

**Comment by saschagrunert** [comment]
I have to reopen this PR since I changed the forks.

**Pull request closed without merging**
