### PR TITLE
updating vendor packages

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>

**- What I did**
`make vendor` 
**- How I did it**

**- How to verify it**

**- Description for the changelog**
When `make vendor` is run against master, some files show up in the `vendor` folder.

### CODE REVIEW

**Comment by harche** [comment]
This is affecting https://github.com/cri-o/cri-o/pull/2813, the changes seen in `vendor` folder have nothing to do with that PR. The changes in `vendor` folder show up anyway with upstream master branch too.

**Comment by saschagrunert** [comment]
This might be related to one of the recent merges, so I think this is fine here. :+1: Master is failing too currently: https://circleci.com/workflow-run/a0083324-bba5-4f54-b0d4-1cc11cd89b74

/ok-to-test

**Comment by haircommander** [comment]
/retest
/lgtm
integration_rhel gets one more chance

**Pull request merged**
