### PR TITLE
Switch to updated version of creack/pty

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Looks like there is a regression which does not allow to run exec any
more when compiling CRI-O with newer go versions.

#### Which issue(s) this PR fixes:

Fixes https://github.com/cri-o/cri-o/issues/4110
#### Special notes for your reviewer:
@rkojedzinszky may I ask you if the code changes in this PR work for you? 
#### Does this PR introduce a user-facing change?

```release-note
- Fixed regression where it was not able to run exec any more when compiling CRI-O with newer go versions
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by haircommander** [comment]
LGTM

**Comment by mrunalp** [comment]
We should probably add an integration test for this.

**Comment by saschagrunert** [comment]
Should not be neccesary to cherry-pick into master/release-1.19 because the dependency is already there.

**Comment by haircommander** [comment]
ah I didn't realize this was 1.17, makes sense :smile:

**Pull request merged**
