### PR TITLE
[release-1.29] OCPBUGS-33350: Reload config should remove pinned images when an empty list is provided

### PR DESCRIPTION
**Pull request by sohankunkerkar**
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8213

/assign sohankunkerkar

```release-note
Reload config should remove pinned images when an empty list is provided
```

### CODE REVIEW

**Comment by haircommander** [comment]
```
not ok 275 reload config should remove pinned images when an empty list is provided
``` 
hm https://github.com/cri-o/cri-o/actions/runs/9713747811/job/26811202548?pr=8325 this may not be working on ghactions

**Comment by haircommander** [comment]
/approve

LGTM, @cri-o/cri-o-maintainers PTAL

**Comment by sohankunkerkar** [comment]
Closing this in favor of https://github.com/cri-o/cri-o/pull/8362, will backport the changes soon.

**Comment by sohankunkerkar** [comment]
It looks like the PR got stuck in the merge pool for a long time, so I merging it manually.

**Pull request merged**
