### PR TITLE
config, docs, completions: enable NRI by default.

### PR DESCRIPTION
**Pull request by klihub**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Flip NRI on in the default configuration.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

As discussed in the last community meeting, this PR flips NRI on in the default configuration.

For maintaining command line backward compatibility this PR leaves the original `--enable-nri` command line option intact, only changing its default to `true` from `false` (as opposed to flipping it to `--disable-nri=[false]`). Hence, NRI can now be disabled on the command line using the `--enable-nri=false` option.

#### Does this PR introduce a user-facing change?

```release-note
Flip NRI on by default.
To revert to a configuration with NRI disabled, either either pass the `--enable-nri=false` option to crio
on the command line, or set the `enable_nri = false` in the `[crio.nri]` section of the configuration.
```

### CODE REVIEW

**Comment by klihub** [comment]
/hold

@saschagrunert @haircommander 
I think I know what's wrong. Some of the tests (that used to run with NRI turned off) now clash on the stock NRI socket path when run in parallel... I'll take a look at it.

**Review by sohankunkerkar — APPROVED** [review]
/retest
/lgtm

**Comment by klihub** [comment]
@haircommander I recall having seen occasional failures of the timezone tests in images.bat, and IIRC either with [this local timezone test](https://github.com/cri-o/cri-o/blob/bf30758326e51d3fed59d941c97500b6cbc9c653/test/image.bats#L366) failing or the previous one with the explicit/specific timezone test.

I cannot prove it at the moment without doubt, but looking at the actual test case implementation, I suspect the reason for flakes is that it implicitly assumes that running foo=$(date ...) twice, once on the host then in the container and with second resolution will always produce the same timestamp. IOW, it is assumed that running the first date command will never happen close enough to the 'end' of a second with the second date run taking long enough for the time to flip over to the next second... in which case the test is guaranteed to fail.

I have a change (I'd like to call it a fix but in lack of definite proof I won't), which takes a single timestamp in seconds and reuses that in both date formatting to verify that the timezones are correctly taken into account... which is what the test really tries to test.

@haircommander Do you think it is worth PR/fix for me to file ?

**Comment by haircommander** [comment]
> @haircommander Do you think it is worth a PR/fix for me to file 

absolutely!

**Pull request merged**
