### PR TITLE
Add bats test for infra_ctr_cpuset taskset

### PR DESCRIPTION
**Pull request by lack**
Signed-off-by: Jim Ramsay <jramsay@redhat.com>

#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

This adds a bats test to check the code change in #5514

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Awesome, thanks! LGTM

**Comment by haircommander** [comment]
/approve
/lgtm

thanks @lack 

I wish there was a way to make sure every child of crio was always in the right cpuset. the real nefarious behavior comes if the process is scheduled wrong from the beginning, but that's hard (impossible?) to check

**Comment by lack** [comment]
> I wish there was a way to make sure every child of crio was always in the right cpuset. the real nefarious behavior comes if the process is scheduled wrong from the beginning, but that's hard (impossible?) to check

Do you mean "the process" as in crio itself?

We could have a test that resets crio's taskset after starting it, then checks that a container and the related conmon are both taskset correctly?

**Comment by haircommander** [comment]
ah I mean the process as in conmon, runc, taskset basically all the processes crio and its children start. we've seen issues where it looks like the processes aren't being put in the right place and it would be sweet to rule out that possiblity

**Comment by lack** [comment]
> ah I mean the process as in conmon, runc, taskset basically all the processes crio and its children start. we've seen issues where it looks like the processes aren't being put in the right place and it would be sweet to rule out that possiblity

Cool, I'll see what I can come up with...

**Pull request merged**
