### PR TITLE
Vendor Kubernetes v1.30.0

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind dependency-change
#### Does this PR introduce a user-facing change?

```release-note
Bump to kubernetes 1.30.0
```

### CODE REVIEW

**Comment by haircommander** [comment]
okay so I think I've fixed the openshift ci tests here. I think in doing so I've broken the lint job, but I think for the time being that is acceptable to get 1.30.0 out. PTAL @cri-o/cri-o-maintainers

**Comment by sohankunkerkar** [comment]
can you comment out https://github.com/cri-o/cri-o/blob/main/.golangci.yml#L53?

**Comment by sohankunkerkar** [comment]
> okay so I think I've fixed the openshift ci tests here. I think in doing so I've broken the lint job, but I think for the time being that is acceptable to get 1.30.0 out. PTAL @cri-o/cri-o-maintainers

related https://github.com/golangci/golangci-lint/issues/4629

**Comment by saschagrunert** [comment]
We should fix the CI either here or in another PR first:
```
 Error: The copy of the 'for' variable "p" can be deleted (Go 1.22+) (copyloopvar)
  Error: The copy of the 'for' variable "device" can be deleted (Go 1.22+) (copyloopvar)
  Error: The copy of the 'for' variable "test" can be deleted (Go 1.22+) (copyloopvar)
  Error: The copy of the 'for' variable "test" can be deleted (Go 1.22+) (copyloopvar)
  Error: The copy of the 'for' variable "test" can be deleted (Go 1.22+) (copyloopvar)
  Error: The copy of the 'for' variable "sb" can be deleted (Go 1.22+) (copyloopvar)
  Error: The copy of the 'for' variable "tc" can be deleted (Go 1.22+) (copyloopvar)
  Error: The copy of the 'for' variable "image" can be deleted (Go 1.22+) (copyloopvar)
```

**Comment by kwilczynski** [comment]
Let's do it! 🎉

**Pull request merged**
