### PR TITLE
Remove terminal watch after success

### PR DESCRIPTION
**Pull request by haircommander**
We used to continue to listen on the console socket for our terminal master, even though we've already cleaned everything else up.

Instead, we should just remove the callback, so there's no chance of calling it later and printing a very confusing looking loop of "trying to connect, failed to connect".

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
(this PR is part fix, part test to see if this fix actually breaks something)

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
@giuseppe ptal.

**Comment by haircommander** [comment]
@mrunalp @giuseppe approve? :)

**Pull request merged**
