### PR TITLE
[1.24] server: move StartContainer calls to clarify stage

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
This was missed from backporting from main
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
@saschagrunert PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

I assume that we do not need a BZ reference for that, right? 
/hold

Feel free to unhold if true.

**Comment by haircommander** [comment]
yeah correct, this is mostly a cosmetic change for consistency between branches

/unhold

**Pull request merged**
