### PR TITLE
Update golangci-lint to v1.23.8

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Update golangci-lint to the latest release and enable it based on our standard CI container.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by haircommander** [comment]
LGTM

**Comment by rhatdan** [comment]
Is today just a bad day for the CI.
/retest

**Comment by haircommander** [comment]
> Is today just a bad day for the CI.
> /retest

I think the offending pr is https://github.com/kubernetes/kubernetes/commit/1f9f2390cb57832f5fbd02e53d39023b81500cc2#diff-6dc833c65b9c544adfb2d654d2f7cbd3
I'm speaking with the author now to try to get to the bottom of it

/test e2e_fedora

**Pull request merged**
