### PR TITLE
systemd: use on-failure as restart policy

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
There are some cases that cri-o should actually restart if it's failed (specifically, when network manager flips back and fourth). To prevent it from spamming a lot, give it restart seconds of 10 too
#### Does this PR introduce a user-facing change?

```release-note
Update systemd unit restart policy to be `on-failure`
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by aleskandro** [comment]
can you cherry-pick to release-1.24?

**Comment by kwilczynski** [comment]
@aleskandro, let me see if I can do it for you.

**Comment by aleskandro** [comment]
Thanks @kwilczynski!

**Pull request merged**
