### PR TITLE
Enable seccomp tests for arm64 arch

### PR DESCRIPTION
**Pull request by hasan4791**
#### What type of PR is this?
/kind ci

#### What this PR does / why we need it:
Enable seccomp tests for arm64 arch

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Comment by hasan4791** [comment]
@saschagrunert Weird, it does work here!!!
Btw the images we use for containers is available for both x86 & aarch64 right?

**Comment by saschagrunert** [comment]
> @saschagrunert Weird, it does work here!!! Btw the images we use for containers in integration tests is available for both x86 & aarch64 right?

Yes, they should be multi-arch.

**Comment by hasan4791** [comment]
> > @saschagrunert Weird, it does work here!!! Btw the images we use for containers in integration tests is available for both x86 & aarch64 right?
> 
> Yes, they should be multi-arch.

Yes, where can I find more about the runner we're using for arm46?

**Comment by saschagrunert** [comment]
> > > @saschagrunert Weird, it does work here!!! Btw the images we use for containers in integration tests is available for both x86 & aarch64 right?
> > 
> > 
> > Yes, they should be multi-arch.
> 
> Yes, where can I find more details about the runner we're using for arm64?

Which information do you need? We're running on the default actuated runners.

**Comment by saschagrunert** [comment]
This is done, thank you!

**Pull request closed without merging**
