### PR TITLE
WIP: test reverting f22b67dd8f9f4c1ce7

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by haircommander** [comment]
/retest
had to drop 2c79ffe274c3bb5a2dad38cde866425018033e10 from kubernetes because it has some weird ssh breaking change. If this passes, we now have two culprits to fix :\

**Comment by saschagrunert** [comment]
> /retest
> had to drop 2c79ffe274c3bb5a2dad38cde866425018033e10 from kubernetes because it has some weird ssh breaking change. If this passes, we now have two culprits to fix :\

Which one? I’d like to help you out :)

**Comment by haircommander** [comment]
https://github.com/kubernetes/kubernetes/pull/81163 is the culprit of the ssh failures on the last run
https://github.com/kubernetes/kubernetes/pull/81305 seems to be the problem we've been seeing where the tests don't spawn (not positive, but the commit before passes and it and the one after it fails...) if this PR passes, then those are our two issues

**Comment by mrunalp** [comment]
@saschagrunert @haircommander It looks like we need to setup KUBE_SSH_USER for these tests in the e2e.

**Comment by mrunalp** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/ssh/ssh.go#L163 We can create a keypair and setup root to be able to ssh locally.

**Comment by haircommander** [comment]
testing again for a sanity check

**Comment by haircommander** [comment]
this particular issue is not present anymore

**Pull request closed without merging**
