### PR TITLE
Allow restoring of containers with different names

### PR DESCRIPTION
**Pull request by adrianreber**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This allows that containers can be correctly restored in differently named namespaces, pods and containers.

This changes only updates the metadata from the checkpointed container before passing that information to the restored container.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the tests get happy

**Comment by adrianreber** [comment]
Integration tests are failing with ` not ok 95 ctr oom` which seems unrelated to this PR. Everything else is green.

**Review by jrvaldes — COMMENTED** [review]
/lgtm

**Comment by sohankunkerkar** [comment]
I think `tide` tried retesting 17 jobs twice even though all tests were passed.

**Comment by haircommander** [comment]
sometimes tide needs reminding

/retest

**Pull request merged**
