### PR TITLE
Specify runtime table format in  the error message

### PR DESCRIPTION
**Pull request by QiWang19**
Close:https://github.com/cri-o/cri-o/issues/5394:
Specify runtime table format in  the error message to make it more clearer to understand.

Signed-off-by: Qi Wang <qiwan@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Specify runtime table format in  the error message
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve

LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
