### PR TITLE
move shm setup for sandbox to internal/factory/sandbox

### PR DESCRIPTION
**Pull request by arcolife**
#### What type of PR is this?

first step towards the PR in compartmentalizing sandbox infra setup  

#### What this PR does / why we need it:

commit introduces the desired change (work towards #4622)

#### Which issue(s) this PR fixes:

#4622

#### Special notes for your reviewer:

~Do not merge yet.~

TODO:

- [x] ~needs rebase off of master once #4623 is merged~
- [x] ~add tests~

#### Does this PR introduce a user-facing change?

No

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
ooof, sorry, this fell to the wayside.
can you rebase this @arcolife we definitely still want it

**Comment by arcolife** [comment]
> hey @arcolife are you around to rebase this?

Yep yep. And week of July 9th I’ll re attempt the PR and close this work. Thanks for your patience Peter! I’ll dm over slack soon with updates.

**Comment by haircommander** [comment]
> > hey @arcolife are you around to rebase this?
> 
> Yep yep. And week of July 9th I’ll re attempt the PR and close this work. Thanks for your patience Peter! I’ll dm over slack soon with updates.

Excellent to hear!

**Comment by arcolife** [comment]
( _still got this_ )

I'd rebased this then but when I read up on changes made in ~~pkg/sandbox~~  internal/factory/sandbox via https://github.com/cri-o/cri-o/pull/5623/files#diff-dfc52cc2ef8431d1a8b470f203bb0ff238db57c42117957b71c50cf920600f4bR21-R22 I started summarizing the work in my notes on changes expected and didn't really get to it in the week of 9th July.

..so now I've scheduled to work on this in the week of 4th Sept.

**Comment by haircommander** [comment]
@arcolife can you rebase to get test fixes?

**Comment by haircommander** [comment]
you've got a lint failure too @arcolife https://github.com/cri-o/cri-o/actions/runs/3718950544/jobs/6307495464

**Comment by arcolife** [comment]
flaky tests..

**Comment by haircommander** [comment]
/approve

LGTM, those test failures are known flakes. Thanks for your work here @arcolife 

@cri-o/cri-o-maintainers PTAL

**Comment by haircommander** [comment]
/lgtm

thanks for sticking through with this @arcolife !

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
