### PR TITLE
[1.18] bump to version 1.18.0

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by haircommander** [comment]
/retest

/hold

until conversation in https://github.com/cri-o/cri-o/pull/3621 is resolved

**Comment by saschagrunert** [comment]
@haircommander do you want to push the tag? Then we can re-trigger the CI to build the release

**Comment by haircommander** [comment]
@saschagrunert pushed!

**Pull request merged**
