### PR TITLE
bump containers image to v5.1.0

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>

**- What I did**
Bump `containers/image` to `v5.1.0`

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by harche** [comment]
Needed for https://github.com/cri-o/cri-o/pull/2813

**Comment by haircommander** [comment]
LGTM

**Comment by lumjjb** [comment]
All green!

**Pull request merged**
