### PR TITLE
[1.17] Fix docs generation

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
Fixing the failing CI test.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
/cc @vrothberg 
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@giuseppe the cgroupsv2 tests seem to fail consistently on 1.17 PRs. Can you take a look?

**Comment by haircommander** [comment]
/lgtm

cgroupsv2 tests don't block, and I don't even know if we expect them to pass on 1.17 (we certainly don't need to wait for them to)

**Pull request merged**
