### PR TITLE
pin container-selinux package

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

#### What type of PR is this?

/kind ci
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by sohankunkerkar — COMMENTED** [review]
I think it should be `container-selinux-2.188.0-1`

**Comment by rhatdan** [comment]
Looks like there is a fix for this going into RHEL9. Basic problem is selinux-policy needs to be updated before container-selinux as I understand it.  @lsm5 is preparing a fix.

**Comment by haircommander** [comment]
@rhatdan @lsm5 do you have a rough eta on the fix trickling into the repos?

**Comment by lsm5** [comment]
> @rhatdan @lsm5 do you have a rough eta on the fix trickling into the repos?

@jnovy ^

**Pull request closed without merging**
