### PR TITLE
update install linke

### PR DESCRIPTION
**Pull request by lovebaby979**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### Does this PR introduce a user-facing change?

```release-note
update broken link for install cri-o
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM
/ok-to-test

Thank you for the fix @lovebaby979 !

**Comment by umohnani8** [comment]
@lovebaby979 can you please sign off your commit `git commit --amend -s` and we can get this moving along!

**Comment by fgiudici** [comment]
This is no more relevant, I think we can close this.

**Comment by saschagrunert** [comment]
Alright
/close

**Pull request closed without merging**
