### PR TITLE
Use CircleCI cache for static builds

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Using the CircleCI cache should speed-up building the static binary.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by hswong3i** [comment]
Could we just simply preserve/restore the `/nix` directory with CI cache? This could be more portable as example for crun/conmon/skopeo/build/podman with different CI service?

**Comment by saschagrunert** [comment]
> Could we just simply preserve/restore the `/nix` directory with CI cache? This could be more portable as example for crun/conmon/skopeo/build/podman with different CI service?

Thank you for the hint, I more or less thought the same during the implementation, let my give it a try :)

**Comment by saschagrunert** [comment]
Way faster, PTAL @haircommander @hswong3i

**Comment by hswong3i** [comment]
@saschagrunert https://github.com/cri-o/cri-o/pull/4012 include this changes and cache now working, too.

Some more founding:
- Due to `nixos/nix` limitation which without `bash` bundled, not every CI with Docker engine direct support would happy with :-(
- Caching `/nix` directly may also make some CI not happy due to permission issue; therefore I cache it with `.cache` and export/import it in case already warm up, else copy from `nixos/nix` directly.
- Cache for Circle CI (for [CRI-O](https://github.com/cri-o/cri-o)) and GitHub Actions (for [crun](https://github.com/containers/crun)) are running well across multiple build with same cache key; BTW Cirrus CI (for [conmon](https://github.com/containers/conmon), [Skopeo](https://github.com/containers/skopeo) and [Buildah](https://github.com/containers/buildah)) only preserve it across multiple tasks inside a single build (please correct me) so caching didn't seems really functioning (although cache is generated and upload correctly, but always say "cache miss" during initial cache fetching phase) :-(

**Comment by saschagrunert** [comment]
> @saschagrunert #4012 include this changes and cache now working, too.
> 
> Some more founding:
> 
> * Due to `nixos/nix` limitation which without `bash` bundled, not every CI with Docker engine direct support would happy with :-(

CircleCI does, so I prefer to use the native image over the vm-wrapped approach.

> * Caching `/nix` directly may also make some CI not happy due to permission issue; therefore I cache it with `.cache` and export/import it in case already warm up, else copy from `nixos/nix` directly.

This issue should be gone if we cache directly in nixos/nix (see the CI run here).

**Pull request closed without merging**
