### PR TITLE
test: use correct flags instead of deprecated env var

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:
so that kubetest stops yelling at us
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by haircommander** [comment]
note: this *may* not actually fix the problem...

**Comment by haircommander** [comment]
I am starting to think it's go 1.14.4...

**Comment by haircommander** [comment]
ooh e2e_cgroupv2 (with crun) is passing, I bet it's go 1.14.4 + runc

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but a rebase is needed now

**Pull request closed without merging**
