### PR TITLE
service file: add alias for cri-o

### PR DESCRIPTION
**Pull request by haircommander**
so packages don't have to symlink explicitly

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind other
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by Conan-Kudo — APPROVED** [review]

**Comment by haircommander** [comment]
I rebased to make sure e2e tests pass, but I'll need my tag back :pray: @saschagrunert

**Pull request merged**
