### PR TITLE
internal/oci/runtime_vm: lock around map access

### PR DESCRIPTION
**Pull request by kolyshkin**
It looks like a concurrent map accces can occur here, since the only
lock taken is per-container. Guard such accesses with a mutex lock.

/kind bug

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/retest

LGTM, good catch
/approve

**Comment by kolyshkin** [comment]
Wow, adding a lock to the structure revealed a typo :)

Fixed by adding a small commit before mine.

**Comment by harche** [comment]
good catch. lgtm.

**Comment by fidencio** [comment]
lgtm!

**Comment by saschagrunert** [comment]
e2e_crun_cgroupv2 seems broken, may you have a look @giuseppe ?

**Pull request merged**
