### PR TITLE
[CLI] "crio config" only prints the fields that are different than the default

### LINKED ISSUE #4506: `crio config` fixes
Currently, calling `crio config` spits out an entire config file. However, it would be prudent for us to move away from the monolithic config file, in favor of smart defaults, and drop-in files.

However, to do this, there needs to be a way for users to quickly create drop-in files, and have them not override the defaults where they don't need to.

The main advantage to this approach is it allows us to change defaults without as much churn in config files.

This proposal is to change `crio config` to render the configuration/flags it's passed, and only print the toml for the fields that are different than the default.

Sample could be:
`crio --log-level debug config`
would only output
```
[crio]
[crio.runtime]
log_level = "debug"
```

/kind feature

### PR DESCRIPTION
**Pull request by ityuhui**
#### What this PR does / why we need it:
As described in #4506 , this PR lets ``crio config`` only prints the fields that are different than the default.

#### Which issue(s) this PR fixes:
Fixes #4506

#### Does this PR introduce a user-facing change?
Yes.

```release-note
"crio config" only prints the fields that are different than the default configuration.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Thank you @ityuhui 
/ok-to-test

**Comment by haircommander** [comment]
this is an awesome @ityuhui !

I think I'd like to see more unit tests and integration tests. Unit tests can be added in `pkg/config` in go, and integration tests can be added in `test/` in bats.

**Comment by haircommander** [comment]
thanks for taking this on

**Comment by mrunalp** [comment]
We should have a boolean to control the behavior so we can still print everything if we want to.

**Comment by haircommander** [comment]
we have the `crio config --default` flag to do so :)

**Comment by ityuhui** [comment]
> I think I'd like to see more unit tests and integration tests. Unit tests can be added in `pkg/config` in go, and integration tests can be added in `test/` in bats.

Sure. I will do it.

**Comment by ityuhui** [comment]
> we have the `crio config --default` flag to do so :)

Hi @haircommander 

The flag ``crio config --default`` will print all **default** configurations, other than all default + configured by crio.conf or crio.conf.d

Do we need add a new flag ``crio config --print-all`` to meet this requirement ?

**Comment by haircommander** [comment]
> > we have the `crio config --default` flag to do so :)
> 
> Hi @haircommander
> 
> The flag `crio config --default` will print all **default** configurations, other than all default + configured by crio.conf or crio.conf.d
> 
> Do we need add a new flag `crio config --print-all` to meet this requirement ?

honestly, I don't think we want this. Moving forward, I think we should really push users to either use the cri-o defaults, or use a drop-in to override. the `--default` could just be for packagers that *really* want some defaults. But I don't think we should have a special flag that prints all the fields, including that which was overridden. That's what the `/etc/crio/crio.conf.d` is for :)

**Comment by haircommander** [comment]
I also wonder if this can be refactored to be a bit more structured. Right now, there are like 4 places someone has to change to add a new config value, and I think this will add another. IT would be really cool if we could iterate through a slice of structs like
```go
type ConfigValue struct {
  templateString string,
  cliFlag              string,
  kind                  reflect.Kind, // may be useful for accessing the data
  compFunc        func(struct{}, struct{}) bool, // verify the two fields are the same
  defaultValue     struct{},
...
}
```

or something and iterate through that to apply these diffs/add template values.

Not really a blocking nit for this PR, but a general direction I think would be good. If you have the time to try something like that here, I'd be interested in seeing what you put together :smile:

**Comment by ityuhui** [comment]
> I also wonder if this can be refactored to be a bit more structured. Right now, there are like 4 places someone has to change to add a new config value, and I think this will add another. IT would be really cool if we could iterate through a slice of structs like
> 
> ```go
> type ConfigValue struct {
>   templateString string,
>   cliFlag              string,
>   kind                  reflect.Kind, // may be useful for accessing the data
>   compFunc        func(struct{}, struct{}) bool, // verify the two fields are the same
>   defaultValue     struct{},
> ...
> }
> ```
> 
> or something and iterate through that to apply these diffs/add template values.
> 

I'd like to try.

**Pull request closed without merging**
