### PR TITLE
[1.14] sandbox_run: Log a warning if we can't find a slice

### PR DESCRIPTION
**Pull request by mrunalp**
Don't fail hard if we can't find a slice.

Port of #2307 

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by haircommander** [comment]
Unfortunately, these aren't the flakes we're seeing in master these are consistent errors. Something changed with networking and i'm not really sure what. I don't think we'll succeed in spamming retest :/

**Comment by saschagrunert** [comment]
We have to backport the `parse_pod_ip` fix of https://github.com/cri-o/cri-o/commit/73e72fcdf238156710ad0c4d6e58a6b64f35b2d7 to `release-1.1x`. 

The AMI update applies to all branches, which contained the CNI plugins update. I think it would be useful to have dedicated AMIs for the release branches to decouple the dependencies.

**Pull request merged**
