### PR TITLE
Move `completion` into `criocli` package

### PR DESCRIPTION
**Pull request by saschagrunert**
Both packages have the same purpose so we should merge them into one.

### CODE REVIEW

**Comment by saschagrunert** [comment]
There seems a general problem with the integration tests on RHEL, @haircommander do you have any deeper insights there?

**Comment by haircommander** [comment]
@saschagrunert yeah integration_rhel is busted. Not really sure why, it's failing at pod cleanup. this LGTM and I'm fine merging manually. PTAL @umohnani8 @mrunalp @rhatdan

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
