### PR TITLE
Enable more feature tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
Let's see if we can enable more `Feature.*` tests.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander PTAL, we now doubled the e2e feature tests which are run :)

**Comment by haircommander** [comment]
hooray more tests! LGTM

**Comment by haircommander** [comment]
(e2e tests are still borked btw)

**Comment by saschagrunert** [comment]
The “application is not available”

/retest

**Comment by saschagrunert** [comment]
@haircommander PTAL

**Comment by haircommander** [comment]
woo more tests
/lgtm

**Pull request merged**
