### PR TITLE
Remove server update lock

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Just a test to check if we can remove this lock from the server package.
#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM

@mrunalp can you comment on this historical need for this?

**Comment by mrunalp** [comment]
Look at this commit - be5084387c0c45b45709939fef9866e24eae7ce7

**Comment by saschagrunert** [comment]
Yep, closing. Thank you for the closer look. 🙂

**Pull request closed without merging**
