### PR TITLE
Pin nixos/nix version

### PR DESCRIPTION
**Pull request by discordianfish**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Pin nixos/nix version

Newer nix versions fail with:

    error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

### CODE REVIEW

**Comment by haircommander** [comment]
/approve
/ok-to-test

LGTM @saschagrunert PTAL

**Comment by TomSweeneyRedHat** [comment]
The changes LGTM, but I'm always leery about pinning to a particular version like this.  I've seen a few cases where it's forgotten about for a few years, and the version becomes ancient as people forget to bump it, or why it was fixed in the first place.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
It will not affect the fedora integration tests:
/override ci/openshift-jenkins/integration_fedora

**Pull request merged**
