### PR TITLE
Add gofumpt linter and apply lint fixes

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Just applied gofumpt, a more strict variant of gofmt.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM

**Comment by saschagrunert** [comment]
Had to rebase to resolve the conflict.

**Pull request merged**
