### PR TITLE
[1.19] image pull: close progress chan

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

> /kind api-change
/kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:
cherry-pick https://github.com/cri-o/cri-o/pull/4412
#### Does this PR introduce a user-facing change?

```release-note
fix a goroutine leak when checking image pulling progress
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm
/retest

**Review by giuseppe — APPROVED** [review]

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
