### PR TITLE
test: set cri-o systemd restart policy to no

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
While in production we want cri-o to restart when it crashes, when we're testing we'd like to catch panics and crashes. Set restart policy in the systemd unit file to never restart, so we fail tests that make cri-o panic

also drop make install.{systemd,config} when building cri-o, as the targets are already hit when running make install

I consider this a failing test because we are failing to catch when CRI-O crashes
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
```

TASK [install cri-o] ***********************************************************
task path: /go/src/github.com/cri-o/cri-o/contrib/test/integration/build/cri-o.yml:29
Killed by signal 15.
++ export status=FAILURE
++ status=FAILURE
```
???
/retest

**Comment by mrunalp** [comment]
@haircommander This is great. Fail fast in CI :+1:

**Pull request merged**
