### PR TITLE
oci: use conmon for exec again

### PR DESCRIPTION
**Pull request by haircommander**
After a long saga of bug fixing and issue squashing, it turns out this is not the correct approach.

Naively, one may exepct removing conmon from the picture would help reduce the load on the system.

However, the way the go runtime hogs memory after it's been aquired, and because conmon is comparatively lighter weight,
dropping conmon from exec syncs causes a memory regression in CRI-O.

We will have to find a new solution for the excessive defunct processes.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### Special notes for your reviewer:
reverts https://github.com/cri-o/cri-o/pull/4943 https://github.com/cri-o/cri-o/pull/4999 https://github.com/cri-o/cri-o/pull/5067 https://github.com/cri-o/cri-o/pull/5107 https://github.com/cri-o/cri-o/pull/5136
#### Does this PR introduce a user-facing change?

```release-note
Fix an RSS regression with exec sync requests
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
and bummer.
Tests need further massaging

**Comment by saschagrunert** [comment]
The log capitalization test needs to be fixed :)

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
