### PR TITLE
Remove git-validation in favor of prow/golangci-lint

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
The whitespace checks are mostly done by our linters and the DCO
verification will be done by prow. This means we can remove
git-validation if we agree on skipping the git commit message check.
#### Which issue(s) this PR fixes:

Refers to https://github.com/cri-o/cri-o/pull/4112
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@saschagrunert for clarity, what does the "git commit message check" do/check?

**Comment by saschagrunert** [comment]
> @saschagrunert for clarity, what does the "git commit message check" do/check?

Just that the commit message subject is not longer than 90 characters.

**Comment by umohnani8** [comment]
LGTM. I am fine with removing the 90 character check for the commit subject. @mrunalp @haircommander wdyt?

**Pull request merged**
