### PR TITLE
refresh apt before installation

### PR DESCRIPTION
**Pull request by dusansusic**
**- What I did**
Updated docs for easier copy/paste experience

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hey @dusansusic, :wave:. The changes are looking good to me, thank you for the contribution. You still have to DCO sign-off your commit by commiting via `git commit -s`. You can simply amend and force push to this PR to make it work:
```
$ git commit --amend --no-edit -s
$ git push -f
```

**Comment by saschagrunert** [comment]
I have one more thing: Can you please drop your commit fe53feaed7d4f9e5b73435fe155c27dc6ce2e73a and only add the necessary changes to a single commit?

**Comment by TomSweeneyRedHat** [comment]
OK, probably pre-tea for me, but what is "c/p"?

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but I thought @haircommander had done similar recently?  Or was that to a different version?

**Comment by haircommander** [comment]
> Changes LGTM, but I thought @haircommander had done similar recently? Or was that to a different version?

Nope I don't think I had added this before!

**Comment by saschagrunert** [comment]
@dusansusic I guess we have to fix our CI pipeline before continuing here. Big sorry for the inconvenience! :innocent:

**Comment by haircommander** [comment]
@rhatdan @mrunalp @saschagrunert @umohnani8 @giuseppe we could use approval here :)

**Pull request merged**
