### PR TITLE
Update various CI and build time dependencies prior to a new release

### PR DESCRIPTION
**Pull request by kwilczynski**
#### What type of PR is this?

/kind ci
/kind dependency-change
/assign kwilczynski

#### What this PR does / why we need it:

Update various CI and build time dependencies prior to a new release. This change also closes several dependency changes that had been open for a while.

Related:

- [github/codeql-action: v2.22.8](https://github.com/github/codeql-action/releases/tag/v2.22.8)
- [golangci/golangci-lint: v1.55.2](https://github.com/golangci/golangci-lint/releases/tag/v1.55.2)
- [kubernetes/release: v0.16.4](https://github.com/kubernetes/release/releases/tag/v0.16.4)
- [mvdan/sh: v3.7.0](https://github.com/mvdan/sh/releases/tag/v3.7.0)
- [NixOS/nix: 2.19.2](https://github.com/NixOS/nix/releases/tag/2.19.2) / [Release 2.19](https://nixos.org/manual/nix/stable/release-notes/rl-2.19)
- [securego/gosec: v2.18.2](https://github.com/securego/gosec/releases/tag/v2.18.2)

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

This is a follow-up to a Pull Request https://github.com/cri-o/cri-o/pull/7559.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by sohankunkerkar** [comment]
@kwilczynski could you rebase this PR on top of the main branch to pick the CI fix?

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/retest

**Comment by haircommander** [comment]
plus GCP passed
/override ci/prow/e2e-aws-ovn

**Pull request merged**
