### PR TITLE
Bump static binary dependency versions

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
This updates available dependencies for the static binary bundle.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
/assign @haircommander 

this should fix the k/k CI after the dependency update.

**Comment by harche** [comment]
We need this for fixing failing[ crio tests ](https://prow.k8s.io/?job=*crio*).

/cc @mrunalp @haircommander

**Pull request merged**
