### PR TITLE
Switch default cgroup manager to systemd

### PR DESCRIPTION
**Pull request by saschagrunert**
This provides a stronger default and implies the recommendation to use `systemd` as cgroup manager.

### CODE REVIEW

**Comment by haircommander** [comment]
@saschagrunert if you updated the comment block here, would the release-notes get updated?

**Comment by saschagrunert** [comment]
> @saschagrunert if you updated the comment block here, would the release-notes get updated?

I don't think so since this is already part of 1.18.0. Ah damn this has been slipped through.

**Comment by haircommander** [comment]
growing pains :confused:

**Comment by haircommander** [comment]
we can manually push the gh-pages branch though right?

**Comment by saschagrunert** [comment]
Yes, that would be fine :)

**Pull request merged**
