### PR TITLE
Add HERE Technologies to ADOPTERS.md

### PR DESCRIPTION
**Pull request by matthias50**
#### What type of PR is this?
 
/kind documentation

#### What this PR does / why we need it:

Adding update to ADOPTERS.md per request of @haircommander 

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?
```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve

thanks @matthias50 LGTM

**Review by mrunalp — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
