### PR TITLE
server: do not check storage for image name on inspect

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by mrunalp** [comment]
@nalind ptal

**Comment by TomSweeneyRedHat** [comment]
LGTM
but cgroupv2 test isn't terribly happy.

**Review by saschagrunert — APPROVED** [review]
LGTM, this should only affect the http info endpoint and not the CRI implementation.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by nalind** [comment]
LGTM

**Comment by haircommander** [comment]
I've rebased to make sure this doesn't break e2e, but I'll need the tag back here too @saschagrunert please

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
