### PR TITLE
[release-1.29] Pin govulncheck to specific version to match Go version requirements

### PR DESCRIPTION
**Pull request by kwilczynski**
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8572

/assign kwilczynski

```release-note
None
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
@cri-o/cri-o-maintainers, please have a look. Thank you!

**Review by saschagrunert — APPROVED** [review]

**Comment by kwilczynski** [comment]
@saschagrunert, thank you! But, this won't merge without some overrides.

So we can override things, or just hit the "merge" button, so to speak.

**Pull request merged**
