### PR TITLE
Update containerd vendor

### PR DESCRIPTION
**Pull request by littlejawa**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:

Update containerd golang dependency

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

This PR completes the work done on #5917 

#### Does this PR introduce a user-facing change?

None

### CODE REVIEW

**Comment by littlejawa** [comment]
@saschagrunert can you have a look?

**Comment by littlejawa** [comment]
> @littlejawa, the code itself seems reasonable, but I really would like to have as much info as possible in the commit message describing why we need this change.
> [...]
> WDYT?

Sure, I will add that :-)

**Review by saschagrunert — APPROVED** [review]
/lgtm
/release-note-none

**Comment by fidencio** [comment]
@littlejawa, could you add the following comment to the commit that's actually doing that?
```
Had to modify the way we call the Command() function from containerd:
- use of the CommandConfig structure as parameter
- use the actual binary name
  (no more converting to containerd binary naming pattern)

This later change was needed as in Containerd 1.6, the validation of the given
binary path is not done in Command() anymore - the path is used as is, allowing
custom runtime paths.
(see https://github.com/containerd/containerd/commit/6870f3b1)
```

**Comment by littlejawa** [comment]
> @littlejawa, could you add the following comment to the commit that's actually doing that?

I did (I think?). The commit with this comment is updating containerd AND modifying runtim_vm.go to make it compatible with the new API. That what is described here.

The other commit is cleanup, that remove the function that is no longer called (because of the change in the first commit).

Am I missing something? Or should I rephrase it somehow?

**Comment by fidencio** [comment]
> > could you add the following comment to the commit that's actually doing that?
> 
> @fidencio - I did (I think?). The commit with this comment is updating containerd AND modifying runtim_vm.go to make it compatible with the new API. That what is described here.
> 
> The other commit is cleanup, that remove the function that is no longer called (because of the change in the first commit).
> 
> Am I missing something? Or should I rephrase it somehow?

Oh, no, we're fine.  I missed one bit here on my side. :-)

**Comment by fidencio** [comment]
LGTM!

**Pull request merged**
