### PR TITLE
[1.13] Vendor containers/storage

### PR DESCRIPTION
**Pull request by umohnani8**
Pick up changes to overlay for recreating symlinks.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@mrunalp @rhatdan PTAL

**Comment by haircommander** [comment]
is this an official vendor or did you just change the code? will this mess with `make vendor` calls later? @umohnani8

**Comment by umohnani8** [comment]
@haircommander it is an official vendor. We don't have make vendor in 1.13, so I used the normal vndr tool.

**Comment by haircommander** [comment]
hm wondering why vendor.conf isn't changed too, but if it ends up being a problem we can fix later

/lgtm

**Comment by umohnani8** [comment]
@haircommander because I updated the branch we already had in vendor.conf, so just had to run vndr to pull in the changes

**Pull request merged**
