### PR TITLE
Update package paths to be internal

### PR DESCRIPTION
**Pull request by saschagrunert**
This commit applies part of the [golang-standards project layout]
structure and moves private parts of CRI-O into the `internal` package.
The public API persists in `pkg`, which makes the overall repo structure
a bit more dense.

- `client`  → `internal/client`
- `lib`     → `internal/lib`
- `oci`     → `internal/oci`
- `pkg`     → `internal/pkg`
- `tools`   → `internal/tools`
- `version` → `internal/version`
- `types`   → `pkg/types`

[golang-standards project layout]: https://github.com/golang-standards/project-layout

### CODE REVIEW

**Comment by rhatdan** [comment]
I am fine with this, only problem is that this will cause cherry-picking and back porting to be a lot more difficult.
@mrunalp WDYT?

**Comment by haircommander** [comment]
I agree with @rhatdan but it seems like a change that should happen. I'd vote getting it into release-1.15 if we're getting this in to make it easier to backport there and make our headaches go away a couple of months earlier :)

**Comment by vrothberg** [comment]
What's the reason for `client` to be public? I was checking but could not find a reference.

**Comment by saschagrunert** [comment]
> What's the reason for `client` to be public? I was checking but could not find a reference.

I thought this public interface to the HTTP API could be used by customers right now :man_shrugging:

**Comment by saschagrunert** [comment]
As discussed, moved the client to `internal/client` and we can follow up in providing a CLI to that one in a follow-up PR.

**Comment by vrothberg** [comment]
/approve
LGTM :+1:

**Comment by rhatdan** [comment]
Sadly needs a rebase.  But we will need to get this in soon, or it will be continuous rebase.  I agree with @haircommander Lets get this into 1.15 also, to make our future lives easier.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch to resolve the conflicts.

**Comment by rhatdan** [comment]
I want @mrunalp to have his say on this one.

**Comment by mrunalp** [comment]
Reviewing.

**Comment by saschagrunert** [comment]
Had to rebase on top of the latest master branch.

**Comment by vrothberg** [comment]
Is @mrunalp cool with the change? Then we could merge and avoid collisions when the US awakes :^)

**Comment by saschagrunert** [comment]
> Is @mrunalp cool with the change? Then we could merge and avoid collisions when the US awakes :^)

I'm unsure so I think we have to wait :innocent:

**Comment by vrothberg** [comment]
@saschagrunert, maybe we need to sync this PR with the open ones from @mtrmac. I am just a bit worried about the merge conflicts.

**Comment by saschagrunert** [comment]
> @saschagrunert, maybe we need to sync this PR with the open ones from @mtrmac. I am just a bit worried about the merge conflicts.

Yes, would be fine for me to give him precedence and rebase again.

**Comment by mtrmac** [comment]
> > @saschagrunert, maybe we need to sync this PR with the open ones from @mtrmac. I am just a bit worried about the merge conflicts.
> 
> Yes, would be fine for me to give him precedence and rebase again.

I appreciate the thought, but updating this PR is much more work than updating the mock change; so, feel free to merge this one first, or even to hold the mock change if necessary.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by saschagrunert** [comment]
> I appreciate the thought, but updating this PR is much more work than updating the mock change; so, feel free to merge this one first, or even to hold the mock change if necessary.

No worries, git is very great in rebasing since I already have a local record of the merge conflict resolution. :+1:

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch to resolve latest conflicts.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by rhatdan** [comment]
@mrunalp This is ready to go in, but needs your approval.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by mrunalp** [comment]
I think some of these packages such as utils could be top level. We can clean up internal dependencies for these packages if needed.

**Comment by saschagrunert** [comment]
> I think some of these packages such as utils could be top level. We can clean up internal dependencies for these packages if needed.

Okay, only `util` or some others as well?

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch and moved `utils` back to the root level. @mrunalp PTAL :innocent:

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch to resolve the conflicts :grin:

**Comment by runcom** [comment]
see https://github.com/cri-o/cri-o/pull/2572#issuecomment-537581572

this is wrong and should be fixed asap, this broke between 1.14 and 1.16. 1.17 would have been the kube version to fully drop this, _after_ 2 releases

**Pull request merged**
