### PR TITLE
Add upgrade path integration tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Adding tests to handle possible upgrade scenarios in CRI-O
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hm, retest

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
but tests don't look to happy yet.

**Pull request closed without merging**
