### PR TITLE
Bump version to 1.25.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
There are several CI jobs like the release notes generation which rely on that version. So we should reflect the actual development status of it.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander PTAL

**Comment by haircommander** [comment]
/hold

had a thought about the -dev

**Comment by saschagrunert** [comment]
@haircommander I removed the dev, should work in the same way for the release notes etc.

**Pull request merged**
