### PR TITLE
[1.16] replace crio-wipe with crio wipe

### PR DESCRIPTION
**Pull request by haircommander**
before, crio-wipe would nuke the entire storage directory, not worrying about there being podman containers
instead, let's be more fine grained about wiping before an upgrade.

add a crio subcommand wipe, which wipes only crio storage.
update tests and docs accordingly
introduce package criocli that makes main code cleaner, and allows for sharing with wipe.go

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
@saschagrunert you're looking for https://github.com/cri-o/cri-o/pull/2746 :)

**Comment by saschagrunert** [comment]
> @saschagrunert you're looking for #2746 :)

Ah thanks, ...we have to keep the order of the cherry-picks to not get lost in merge conflicts :innocent:

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
