### PR TITLE
CI: always install required BATS version.

### PR DESCRIPTION
**Pull request by klihub**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

Currently CI nodes are expected to be set up correctly by regularly scheduled
ansible runs with the `setup` tag. However, empirical evidence (logging BATS
version from `integration` runs on CI nodes) proves that many of the CI nodes
are still running older versions (1.2.1 or 1.2.1-dev).

So instead of relying nodes to get independently set up with the correct BATS
version this PR installs that one right before running the tests. Furthermore, it
makes sure that the freshly installed version is correctly symlinked in place, to
replace any previously present/distro-provided versions.

#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve

LGTM

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
