### PR TITLE
version: bump to v1.21.2

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Which issue(s) this PR fixes:
/kind documentation

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
assuming happy tests

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
