### PR TITLE
[1.17] bump c/image to 5.4.4

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

> /kind dependency-change

#### What this PR does / why we need it:
fixes platform matching issues
#### Which issue(s) this PR fixes:
fixes https://github.com/cri-o/cri-o/issues/3233

#### Does this PR introduce a user-facing change?

```release-note
Fix bug with platform matching when pulling images
```

### CODE REVIEW

**Comment by haircommander** [comment]
cgroupv2 are expected to fail here, PTAL @umohnani8 @mrunalp

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
