### PR TITLE
config: drop infra container by default

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind feature
#### Does this PR introduce a user-facing change?

```release-note
the config field `drop_infra_ctr` is now true by default
```

### CODE REVIEW

**Comment by haircommander** [comment]
https://github.com/cri-o/cri-o/pull/5113/commits/75703142b73fb7f84069296f313f1ffa6df18a35 is probably worthy of backporting, but not super urgent as dropping infra was considered experimental

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
