### PR TITLE
[release-1.18] backports layer pull fix from 1.19 to 1.18

### LINKED ISSUE #4156: [1.18] crio reports image up to date while still downloading
Version:       1.18.0
GitCommit:     7d79f42b28ad00cf2e7d86604a5a4007303ac328
GitTreeState:  dirty
BuildDate:     2020-08-04T01:21:36Z
GoVersion:     go1.13.8
Compiler:      gc
Platform:      linux/amd64
Linkmode:      unknown: `ldd /root/crio` failed: ldd: /root/crio: No such file or directory
  (exit status 1)

image

image is big around 4GB before unpacking

### PR DESCRIPTION
**Pull request by wgahnagl**
#### What type of PR is this?

> /kind api-change
/kind bug
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### What this PR does / why we need it:
fixes images reporting incorrect up to date, fixed in 1.19  
#### Which issue(s) this PR fixes:

fixes #4156  

#### Does this PR introduce a user-facing change?

```release-note
None

```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM
@haircommander @saschagrunert @kolyshkin  PTAL

**Comment by haircommander** [comment]
@gattyto PTAL, does this fix your issue?

code LGTM, though I'm not totally sure this PR fixes the linked issue...

**Comment by umohnani8** [comment]
I think we can get this moving along. @mrunalp @saschagrunert PTAL

**Comment by umohnani8** [comment]
Bumping this up, @haircommander @kolyshkin @mrunalp PTAL

**Comment by haircommander** [comment]
/hold

I just checked, and I'm not convinced this is actually broken in 1.18 [ref](https://github.com/cri-o/cri-o/issues/4156#issuecomment-737502192)
asking the reporter for feedback, but we may actually not go this route, as the code that's being added here is adding metrics, which, while probably harmless, is more of a feature than a bug fix (and also updates dependencies that we should probably leave in such an old and stable branch)

**Comment by umohnani8** [comment]
@haircommander the issue seems to occur with larger images, maybe try an image that is bigger than 1GB? I believe @wgahnagl was able to reproduce the issue without this patch. What made you think of backporting this patch btw?

**Comment by haircommander** [comment]
1.18 is EOL

**Pull request closed without merging**
