### PR TITLE
[DNM] [WIP] Revert "server: prevent segfault by not using a potentially nil sandbox"

### PR DESCRIPTION
**Pull request by stbenjam**
*Do not merge* -- OpenShift GCP upgrades are broken, and we only have a couple of possible culprits. It's unlikely to be this one, but I need this PR to convince the bots to test an upgrade with the revert.

This reverts commit 2a1d38d34e6b0314f2b53815d6df2197f619e989.

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by fidencio** [comment]
@stbenjam, a few comments:
1. I think we should first treat this one on `master` and then backport this to the stable branches when we get to a reasonable solution.
2. I don't fully understand why you're reverting that commit.  For sure `sb` can be `nil` at that point and we'd be re-introducing the possibility to crash CRI-O.  So, what's the problem you're trying to solve?  Maybe elaborating on that will help us to better evaluate the proposed fix.

Best Regards.

**Comment by haircommander** [comment]
@stbenjam was this the culprit?

**Comment by stbenjam** [comment]
@fidencio This PR is just for my testing, I didn't mean for it to get a review by anyone yet, I'll share more if it turns out we need it (and of course start with master).

**Comment by stbenjam** [comment]
@haircommander It's starting to look that way, but I don't understand why -- would we get a crash log somewhere in the CI gathered logs? That would help verify. We're also really only seeing this on GCP.

However, we ran 6 upgrades on Friday with this revert, and none failed the ingress disruption we're seeing in CI.  We had a couple other culprits, but those were dead ends.

**Comment by stbenjam** [comment]
/close

Closing for now, while we investigate some other avenues.

**Pull request closed without merging**
