### PR TITLE
Add CI bundle tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This adds a dedicated test for the release bundle we provide, which installs the bundle on the machine and runs a container workload on top of it.

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
should this live in `contrib` ? 

this is very much needed :smile: code LGTM

**Comment by saschagrunert** [comment]
> should this live in `contrib` ?

The overall bundle directory or only the tests? I was thinking to have the tests close to the bundling logic somehow :man_shrugging:

**Comment by saschagrunert** [comment]
> should this live in `contrib` ?

The overall bundle directory or only the tests? I was thinking to have the tests close to the bundling logic somehow :man_shrugging:

**Comment by haircommander** [comment]
> > should this live in `contrib` ?
> 
> The overall bundle directory or only the tests? I was thinking to have the tests close to the bundling logic somehow man_shrugging

all of it, our top level directory is getting a bit bloated, and I'm not sure this directory is full enough to warrant its spot there

**Comment by saschagrunert** [comment]
/retest

> > > should this live in `contrib` ?
> > 
> > 
> > The overall bundle directory or only the tests? I was thinking to have the tests close to the bundling logic somehow man_shrugging
> 
> all of it, our top level directory is getting a bit bloated, and I'm not sure this directory is full enough to warrant its spot there

Makes sense, I can follow-up on that. I also wanted to add the new `crio.conf.d` directory structure to the install targets (another TODO).

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Pull request merged**
