### PR TITLE
broken link

### PR DESCRIPTION
**Pull request by lovebaby979**
Signed-off-by: wangjibao.lc <wangjibao.lc@inspur.com>

#### What type of PR is this?

documentation

#### What this PR does / why we need it:
update broken link for tutorials

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
update broken link for tutorials
#### Does this PR introduce a user-facing change?
None

```release-note
update broken link for tutorials
```

### CODE REVIEW

**Comment by lovebaby979** [comment]
@nalind

**Comment by haircommander** [comment]
/ok-to-test
/approve

thanks  @lovebaby979 LGTM

**Pull request merged**
