### PR TITLE
tree_status: show the git diff

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
it is often the case that there's some git diff in hack/tree_status.sh in CI, but we don't know what it is. Fix this by printing it out when there is something different
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM
/approve

**Comment by haircommander** [comment]
the reasoning behind these failures is unclear to me
/retest

**Pull request merged**
