### PR TITLE
fix shfmt

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### What type of PR is this?

/kind ci
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by nalind** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
now to get that one last test to be happy.

**Comment by haircommander** [comment]
@wgahnagl @QiWang19 @fgiudici PTAL

**Comment by fgiudici** [comment]
LGTM!

**Review by nalind — APPROVED** [review]

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
