### PR TITLE
add libbtrfs-dev to unit tests

### PR DESCRIPTION
**Pull request by rphillips**
Fix unit tests by adding libbtrfs-dev to be installed.

Signed-off-by: Ryan Phillips <rphillips@redhat.com>

#### What type of PR is this?
/kind ci

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by kolyshkin — CHANGES_REQUESTED** [review]
NACK. We already run apt-get below (`scripts/github-action-packages`), and that script should be amended to include `libbtrfs-dev`

**Comment by mrunalp** [comment]
/hold 
to address @kolyshkin comment

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
huh uncooperative tests today...

/test critest_fedora

**Comment by haircommander** [comment]
/override ci/prow/e2e-agnostic
/override ci/prow/e2e-gcp

This has nothing to do with openshift tests

**Pull request merged**
