### PR TITLE
Portmap support for dual-stack

### PR DESCRIPTION
**Pull request by aojea**
/kind bug

#### What this PR does / why we need it:

Backport of https://github.com/cri-o/cri-o/pull/4361

#### Which issue(s) this PR fixes:

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1872128

```release-note
crio-o portMapping dual-stack support
```

### CODE REVIEW

**Comment by aojea** [comment]
ping @haircommander 
fixed the conflict,

**Comment by aojea** [comment]
it went through CI, ping @haircommander

**Comment by saschagrunert** [comment]
@aojea the vendor job failed. please run `make vendor` and commit the changes together with this PR.

**Comment by aojea** [comment]
> @aojea the vendor job failed. please run `make vendor` and commit the changes together with this PR.

thanks for noticing it @saschagrunert , it seem that I didn't commit the changes that removed the files from the vendor folder :sweat: , it should be fixed now

**Review by saschagrunert — APPROVED** [review]
LGTM
The static build does to not work any more for the release-1.19 branch. This change seems not related.

**Pull request merged**
