### PR TITLE
Log version at startup

### LINKED ISSUE #4332: log version at startup
**Description**

It would be nice if crio could output its version at startup for troubleshooting/diagnosis purposes.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
1.19.0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by hafe**
Signed-off-by: Hans Feldt <feldt.hans@gmail.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
/lgtm

thanks @hafe

**Pull request merged**
