### PR TITLE
Fix make vendor

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This fixes running `go mod tidy` as a part of `make vendor` target.
Please see commits for details.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by mrunalp** [comment]
@saschagrunert ptal

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
wow good find, unfortunately, you've got a merge conflict

**Comment by TomSweeneyRedHat** [comment]
LGTM
but a rebase is needed @kolyshkin

**Comment by kolyshkin** [comment]
rebased

**Comment by kolyshkin** [comment]
Added more changes (removed `GO111MODULE` and `-mod=vendor`, slightly improved CONTRIBUTING.md)

**Comment by kolyshkin** [comment]
CI error in integration_rhel is unrelated. It comes from 

https://github.com/cri-o/cri-o/blob/876dd0db2b40a60e85d9967d68b3027b4b8b2af1/test/ctr.bats#L1623

which is trying to remove pod (should probably not be the part of the test).

The error is:

# removing the pod sandbox "0d30f7428dba595155095cbfa805bad939876f05529ff6438ade6c2848ea9b9c": rpc error: code = Unknown desc = unable to remove managed namespaces: Removing namespaces encountered the following errors [unlinkat /var/run/netns/4302c201-43fd-4cd1-9cc0-efbba1762f3d: device or resource busy]


The pod is then removed successfully from `teardown()`.

**Comment by kolyshkin** [comment]
integration-rhel failed again, also while removing a pod, same problem, different test case (same file though), different namespace though.

> removing the pod sandbox "ab9323d6260790ac37c994417911f432ccd6ef3f00184379df23cbdc15ad4b55": rpc error: code = Unknown desc = unable to remove managed namespaces: Removing namespaces encountered the following errors [unlinkat /var/run/utsns/ff1968b2-a9f2-420e-9ed3-b97651d8999c: device or resource busy unlinkat /var/run/ipcns/ff1968b2-a9f2-420e-9ed3-b97651d8999c: device or resource busy]

Might be related to commit  ab82e12e08f62f as it speeds things up (by removing unnecessary code) and now namespace removal happens a bit earlier.

Not sure though why I'm the only one seeing this (and it's def unrelated to what is done in this PR)

**Comment by kolyshkin** [comment]
> integration-rhel failed again, also while removing a pod, same problem, different test case (same file though), different namespace though.

FYI this is addressed by https://github.com/cri-o/cri-o/pull/4217

**Comment by kolyshkin** [comment]
rebased on top of just-merged #4217; let's see how CI goes

**Comment by kolyshkin** [comment]
A bunch of weird errors from ci/prow/e2e-aws [logs here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/4208/pull-ci-cri-o-cri-o-master-e2e-aws/1310744513592954880), for example:

> nodes/ip-10-0-136-92.us-west-2.compute.internal/journal.gz:Sep 29 01:22:55.326053 ip-10-0-136-92 kernel: ovs-vswitchd[2490]: segfault at 21 ip 0000556a8c3d93d4 sp 00007ffc0fb172c0 error 4 in ovs-vswitchd[556a8c06d000+629000]

Otherwise everything seems much better.

/test e2e-aws

**Comment by haircommander** [comment]
I'm not convinced e2e-aws ever really passes on master, I think there's something up with the setup.
/lgtm

**Pull request merged**
