### PR TITLE
[release-1.19] Bug 1881694: Add pull source as info level log

### PR DESCRIPTION
**Pull request by QiWang19**
#### What this PR does / why we need it:
Backport fix #4438 to release-1.19 for 4.6.
#### Which issue(s) this PR fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1976293

#### Does this PR introduce a user-facing change?

```release-note
Crio adds info level log of the physical image source.
```

### CODE REVIEW

**Comment by QiWang19** [comment]
Test failed with storeMock. The `test/mocks/containerstorage/containerstorage.go` might need to regenerate since the github/containners/storage has been upgraded. What commend is used to generate this file
```
$ mockgen -source=/home/qiwan/go/src/github.com/crio/cri-o/vendor/github.com/containers/storage/store.go -aux_files github.com/containers/storage=/home/qiwan/go/src/github.com/crio/cri-o/vendor/github.com/containers/storage/lockfile_compat.go -destination=/home/qiwan/go/src/github.com/crio/cri-o/test/mocks/containerstorage/containerstorage.go -package=containerstoragemock
2021/06/26 22:16:38 Loading input failed: /home/qiwan/go/src/github.com/crio/cri-o/vendor/github.com/containers/storage/store.go:47:2: unknown embedded interface Locker
```

**Comment by haircommander** [comment]
@QiWang19 you can run `make mockgen`

**Comment by haircommander** [comment]
is there any chance we can have the patch backported to https://github.com/containers/image/tree/release-5.5 instead of updating so far ahead?

**Comment by QiWang19** [comment]
https://github.com/containers/image/pull/1280 for backporting to https://github.com/containers/image/tree/release-5.5

**Pull request closed without merging**
