### PR TITLE
[1.13] Changes to rpm build and Dockerfile for ci

### PR DESCRIPTION
**Pull request by umohnani8**
Make changes to the rpm build and Dockerfile for
running the e2e-aws tests.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@haircommander @mrunalp PTAL

**Comment by haircommander** [comment]
LGTM

**Comment by haircommander** [comment]
@rhatdan @mrunalp needs an approval

**Pull request merged**
