### PR TITLE
image pull: close progress chan

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

 /kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:
so we don't leak a goroutine

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
fix a goroutine leak when checking image pulling progress
```

### CODE REVIEW

**Comment by haircommander** [comment]
fixes https://github.com/containers/image/issues/1095

**Comment by kolyshkin** [comment]
Wow, nice catch!

/lgtm

**Review by saschagrunert — APPROVED** [review]
/retest
/lgtm

Thanks for the fix! :pray:

**Pull request merged**
