### PR TITLE
[1.16] Add missing EnvVars to command line interface

### PR DESCRIPTION
**Pull request by saschagrunert**
Some commands where missing the newly introduced `EnvVar` flag, which is
now complete again.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by saschagrunert** [comment]
/retest

Looked not that good this morning.

**Comment by haircommander** [comment]
can you rebase to pick up CI fixes?

**Comment by saschagrunert** [comment]
Rebased on release-1.16

**Comment by giuseppe** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by haircommander** [comment]
and just like that, it passes magically with no explanation :upside_down_face:

**Pull request merged**
