### PR TITLE
Update cri-tools to v1.18.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Update cri-tools to v1.18.0
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
Clashes with https://github.com/cri-o/cri-o/pull/3517
#### Does this PR introduce a user-facing change?

```release-note
- Update cri-tools to v1.18.0 in static release bundle
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Blocked by https://github.com/cri-o/cri-o/issues/3522 now

**Comment by saschagrunert** [comment]
/retest 
(to see if the integration tests pass in the CI)

**Comment by umohnani8** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by saschagrunert** [comment]
Waiting for new libpod release to contain the fix

**Comment by saschagrunert** [comment]
Rebased on top of https://github.com/cri-o/cri-o/pull/3602/files to see if the tests pass

**Comment by saschagrunert** [comment]
I think kata is not able to apply the patch

**Comment by saschagrunert** [comment]
Green @haircommander :)

**Pull request merged**
