### PR TITLE
oci: always reap conmon zombies

### PR DESCRIPTION
**Pull request by haircommander**
Even if we kill the process, we still need to wait for it, or else we'll reap a zombie.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Fix a case where conmon children are sometimes leaked
```

### CODE REVIEW

**Review by mrunalp — COMMENTED** [review]
/lgtm

**Comment by haircommander** [comment]
related https://bugzilla.redhat.com/show_bug.cgi?id=2019346

**Pull request merged**
