### PR TITLE
update runtime spec to 1.2

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
Testing if runtime spec is causing CI failures with crun.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
/lgtm cancel

See the same issue here:
```
CreateContainerError: container create failed: unknown version specified
```

**Comment by elezar** [comment]
Seems like we need to bump the crun version used in the tests to at least https://github.com/containers/crun/releases/tag/1.14.2 to handle the updated spec.

**Comment by sohankunkerkar** [comment]
We already built the new images yesterday. This PR needs to rebase on top of the main branch to pick the new changes.

**Comment by saschagrunert** [comment]
> We already built the new images yesterday. This PR needs to rebase on top of the main branch to pick the new changes.

That would be odd, I thought prow picks the changes on top of `main`.

**Comment by sohankunkerkar** [comment]
> > We already built the new images yesterday. This PR needs to rebase on top of the main branch to pick the new changes.
> 
> https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-cri-o-cri-o-main-periodics-setup-periodic/1778211421650161664 looks like it failed.
> 
> I kicked off another build. I couldn't really see the reason for the failure of the image in the logs.

Strange, I built the rhel image yesterday: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/50803/rehearse-50803-periodic-ci-cri-o-cri-o-main-periodics-setup-periodic/1778232169311768576/artifacts/setup-periodic/cri-o-setup-test/build-log.txt

**Comment by saschagrunert** [comment]
We should link the image build jobs to README.md or something else. I'm always searching for them.

**Comment by klihub** [comment]
I still saw in the previous failed run's kubelet logs before triggering a retest:

'''
E0411 12:52:59.345173   19530 remote_runtime.go:319] "CreateContainer in sandbox from runtime service failed" err=<
	rpc error: code = Unknown desc = container create failed: unknown version specified
 > podSandboxID="f73dba6966d916504f61fa17706b1e1afa7a9f4300d50553f655f418f34c4382
'''

So still an old crun lurking somewhere ?

**Comment by klihub** [comment]
And again the same after the re-trigger:
'''
E0411 14:38:12.478324   19574 remote_runtime.go:319] "CreateContainer in sandbox from runtime service failed" err=<
	rpc error: code = Unknown desc = container create failed: unknown version specified
 > podSandboxID="9d78481bc7c86bed81fc2e19d868c8f1f17907da17401e9f6832551ad9e0c0bb"
I0411 14:38:12.478483   19574 event.go:376] "Event occurred" object="kube-system/coredns-69cbfb9798-8njqk" fieldPath="spec.containers{coredns}" kind="Pod" apiVersion="v1" type="Warning" reason="Failed" message=<
	Error: container create failed: unknown version specified
 >
 '''

**Comment by kannon92** [comment]
https://github.com/openshift/release/pull/50803#issuecomment-2050894874

hopefully when this finishes we can test this PR again to see if ci is good

**Comment by klihub** [comment]
> [openshift/release#50803 (comment)](https://github.com/openshift/release/pull/50803#issuecomment-2050894874)
> 
> hopefully when this finishes we can test this PR again to see if ci is good

@kannon92 There are a few failures there and at least for #7971 re-triggering the failing tests still fail the same way...

**Comment by klihub** [comment]
Argh, same old, same old:
> E0415 07:14:11.904452   19486 remote_runtime.go:319] "CreateContainer in sandbox from runtime service failed" err=<
	rpc error: code = Unknown desc = container create failed: unknown version specified
 > podSandboxID="c23400c9e7de0cf3d7038ec611f0454104a981ba489f6ae68462e24abbaf942c"

**Comment by klihub** [comment]
Could rebasing to include [08365649092e92707f6e15157518dbcb9e1a203d]( https://github.com/cri-o/cri-o/commit/08365649092e92707f6e15157518dbcb9e1a203d) help ?

**Comment by klihub** [comment]
> Could rebasing to include [08365649092e92707f6e15157518dbcb9e1a203d](https://github.com/cri-o/cri-o/commit/08365649092e92707f6e15157518dbcb9e1a203d) help ?

Answering to myself, nope, at least in #7971 it did not help.

**Comment by saschagrunert** [comment]
The issue may also be related to conmon. :thinking:

**Comment by saschagrunert** [comment]
It looks like that we're still not using the latest crun version in CI, the version check we see got dropped in v1.14.3:

https://github.com/containers/crun/pull/1419/files

**Comment by elezar** [comment]
As a matter of interest? Do we log the crun version we're using anywhere?

**Comment by saschagrunert** [comment]
> As a matter of interest? Do we log the crun version we're using anywhere?

We don't as far as I'm aware of, but we probably should :+1:

**Comment by kannon92** [comment]
@sohankunkerkar was working on https://github.com/openshift/release/pull/50873 late last week but it looks like that PR is not yet complete.

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Pull request merged**
