### PR TITLE
Update conmon to v2.0.3

### PR DESCRIPTION
**Pull request by saschagrunert**
- Bump go module
- Bump test images
- Bump conmon for ansible based tests

WIP because test images are not pushed yet.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Ready for review

**Comment by rhatdan** [comment]
LGTM
@umohnani8 @haircommander @mrunalp PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.

**Pull request merged**
