### PR TITLE
[release-1.26] OCPBUGS-23929: Update various dependencies to fix outstanding CVEs

### PR DESCRIPTION
**Pull request by kwilczynski**
#### What type of PR is this?

/kind dependency-change
/assign kwilczynski

#### What this PR does / why we need it:

Update the following dependencies to fix outstanding CVEs:

- go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp [GHSA-rcjv-mgp8-qvmr](https://osv.dev/vulnerability/GHSA-rcjv-mgp8-qvmr)
- go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc  [GHSA-8pgv-569h-w5rw](https://osv.dev/vulnerability/GHSA-8pgv-569h-w5rw)
- github.com/go-jose/go-jose/v3 [GHSA-2c7c-3mj9-8fqh](https://osv.dev/vulnerability/GHSA-2c7c-3mj9-8fqh) / [GO-2023-2334](https://pkg.go.dev/vuln/GO-2023-2334)

Related:

- https://github.com/cri-o/cri-o/pull/7526
- https://github.com/cri-o/cri-o/pull/7504
- https://github.com/cri-o/cri-o/pull/7489
- https://github.com/cri-o/cri-o/pull/7527
- https://github.com/cri-o/cri-o/pull/7537
- https://github.com/cri-o/cri-o/pull/7545
- [cc956e6: Move to use stats handlers over deprecated interceptors](https://github.com/cri-o/cri-o/pull/7526/commits/cc956e6ba68f1dc0eedcf72bd29d3f6c2d5da801)

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
> > @cri-o/cri-o-maintainers, this should be ready for merge.
> 
> @kwilczynski we usually merge [release-1.27](https://github.com/cri-o/cri-o/pull/7556) before this to avoid regressions. What's the reason that we can do it all simultaneously?

See: https://github.com/cri-o/cri-o/pull/7556#issuecomment-1845073869

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
