### PR TITLE
Fix integration tests by adjusting image digest

### PR DESCRIPTION
**Pull request by saschagrunert**
Beside that, I removed the digest test for architectures we do not test at all.

### CODE REVIEW

**Comment by saschagrunert** [comment]
I added the unit test fix on top of that PR too to make the CI green again.

**Comment by haircommander** [comment]
LGTM, @nalind PTAL

**Comment by TomSweeneyRedHat** [comment]
Personally I'd rather keep the other arch in place, even if we're not using them at the moment.  I'm fine with letting this go in, but would like a tie breaker from someone else.

**Comment by nalind** [comment]
Not entirely up to speed on what was failing there, but we definitely test on amd64.  Was the error that the digests of the arch-specific images no longer matched the ones in the manifest list when we switched which manifest list we were looking at?

**Comment by saschagrunert** [comment]
> Not entirely up to speed on what was failing there, but we definitely test on amd64. Was the error that the digests of the arch-specific images no longer matched the ones in the manifest list when we switched which manifest list we were looking at?

Yes exactly. :)

**Comment by nalind** [comment]
Well, we should at least keep the amd64 test, because we want to verify that we end up saving both the arch-specific image's manifest and the manifest list.  The updated digest values for the various arches can be dug out of `skopeo inspect --raw docker://docker.io/library/alpine@sha256:115731bab0862031b44766733890091c17924f9b7781b79997f5f163be262178`.

**Comment by saschagrunert** [comment]
Alright, I re-added the amd64 test

**Pull request merged**
