### PR TITLE
namespace: drop and replace stop method

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
Unfortunately, having an unmounted namespace in /var/run/netns causes `ip a` to report `Error: Peer netns reference is invalid`. To fix this, we need to partially revert https://github.com/cri-o/cri-o/pull/5336/commits/efcf8afe6a7b7f942833746a1b357e591000153c and replace it.
#### Special notes for your reviewer:
related to https://bugzilla.redhat.com/show_bug.cgi?id=2035969
#### Does this PR introduce a user-facing change?

```release-note
Fix bug where `ip a` reports `Error: Peer netns reference is invalid`
```

### CODE REVIEW

**Comment by haircommander** [comment]
carrying https://github.com/cri-o/cri-o/pull/5532 to fix tests

**Comment by haircommander** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
