### PR TITLE
[release-1.29] OCPNODE-2247: Implement configurable container minimum memory limit per OCI runtime.

### PR DESCRIPTION
**Pull request by kwilczynski**
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7832

/assign kwilczynski

```release-note
None
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
**To the reviewer:**

The **verify/lint** check failure is a known and unrelated problem.

**Comment by saschagrunert** [comment]
> For which reason do we need to backport a feature like this?

Alright we clarified that this is an exception to our usual policy.

**Review by saschagrunert — APPROVED** [review]

**Comment by kwilczynski** [comment]
> > For which reason do we need to backport a feature like this?
> 
> Alright we clarified that this is an exception to our usual policy.

To add more background here:

This feature development has been sponsored by an OpenShift user (a Red Hat customer). However, they won't be moving to the latest release just yet; hence the backport to the version they are willing to upgrade eventually.

**Pull request merged**
