### PR TITLE
Add stats integration test

### PR DESCRIPTION
**Pull request by saschagrunert**
We also modify the test images to contain `jq` for testing purposes as
well as updating cri-tools.

### CODE REVIEW

**Comment by haircommander** [comment]
I would rather not drop the `master-` prefix. I'd like the branch we're using in the circle images to be clear. If you'd rather, `1.17` works for me too.

**Comment by haircommander** [comment]
`# /tmp/bats.31786.src: line 27: jq: command not found`
we may need an AMI update to install jq for the jenkins tests

**Comment by saschagrunert** [comment]
> I would rather not drop the `master-` prefix. I'd like the branch we're using in the circle images to be clear. If you'd rather, `1.17` works for me too.

Alright, I re-push the images with the prefix.

> `# /tmp/bats.31786.src: line 27: jq: command not found`
> we may need an AMI update to install jq for the jenkins tests

Yep I see, I added an install `jq.yml`, let's see if that works.

**Comment by saschagrunert** [comment]
Yeah it looks like that it’s working now.

/test integration_rhel

**Comment by haircommander** [comment]
/test integration_rhel
/lgtm
(though one day I think we should move jq installation to ami build time)

**Comment by saschagrunert** [comment]
@haircommander may I ask for a manual merge, I think we could skip the AMI tests in that case, WDYT?

**Pull request merged**
