### PR TITLE
Fix CRI-O apt-get version

### PR DESCRIPTION
**Pull request by KentaTada**
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>

**- What I did**
Modify README.md to install the CRI-O package correctly.

**- How I did it**
Change the apt-get install command  on Ubuntu distributions.

**- How to verify it**
I actually installed CRI-O using my modified README.md.
In addition to that, I confirmed below Kubernetes's document.
https://v1-15.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/

**- Description for the changelog**
Fix CRI-O apt-get version

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, I'm not sure why the tests have gone off the rails however.

**Comment by rhatdan** [comment]
LGTM, Will manually saving the planet from excessive tests that will not test this change.

**Comment by rhatdan** [comment]
@KentaTada Thanks for the contribution.

**Pull request merged**
