### PR TITLE
[1.16] backport ci fixes

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind failing-test
#### What this PR does / why we need it:
backports https://github.com/cri-o/cri-o/pull/3667 and https://github.com/cri-o/cri-o/pull/3661/ 
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by haircommander** [comment]
circle ci integration tests are failing with
```
cat: /tmp/bats-run-28111/parallel_output/1/stdout: No such file or directory
# bats warning: Executed 0 instead of expected 1 tests
```
which is certainly not the fault of this PR (maybe a gnu parallel problem?)

cgroup v2 tests are expected to fail

**Pull request merged**
