### PR TITLE
[release-1.16] Stop container when there is error in createSandboxContainer

### PR DESCRIPTION
**Pull request by tedyu**
/kind bug

#### What this PR does / why we need it:
If createSandboxContainer returns non-nil error, we should stop the container.

This is backport of #3607

#### Which issue(s) this PR fixes:

```release-note
None
```

### CODE REVIEW

**Comment by mrunalp** [comment]
build is failing in this PR

**Comment by mrunalp** [comment]
```
# github.com/cri-o/cri-o/server
server/container_create_linux.go:800:6: undefined: errRet
make: *** [Makefile:129: bin/crio] Error 2
make: *** Waiting for unfinished jobs....
# github.com/cri-o/cri-o/server
server/container_create_linux.go:800:6: undefined: errRet
make: *** [Makefile:132: bin/crio-status] Error 2
```

**Comment by tedyu** [comment]
@mrunalp 
Build issue has been resolved.

**Comment by tedyu** [comment]
Also fixed the error variable in the deferred func for s.StorageRuntimeServer().DeleteContainer()

**Comment by tedyu** [comment]
@mrunalp 
Can you take another look ?

**Comment by umohnani8** [comment]
LGTM
/ok-to-test

**Comment by TomSweeneyRedHat** [comment]
LGTM, but tests are still unhappy.

**Comment by haircommander** [comment]
cgroupsv2 tests are expected to fail, this needs an /approve label @mrunalp @rhatdan @saschagrunert

**Comment by haircommander** [comment]
can you rebase to catch (some) ci fixes @tedyu

**Comment by tedyu** [comment]
@haircommander 
I have rebased.

**Pull request merged**
