### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
- Bump Kubernetes from v1.16.0-alpha.1 to v1.16.0-alpha.3
- Bump github.com/containers/storage from v1.12.14 to v1.13.1
- Bump github.com/prometheus/client_golang from v1.0.0 to v1.1.0
- Bump google.golang.org/grpc from v1.22.0 to v1.22.1
- github.com/Microsoft/go-winio from v0.4.13 to v0.4.14
- Bump github.com/containers/buildah from v1.9.2 to v1.10.0
- Bump github.com/containers/image from v2.0.1+incompatible to
  v3.0.2+incompatible
- Bump github.com/gogo/protobuf from v1.2.1 to
  v1.2.2-0.20190723190241-65acae22fc9d
- Bump github.com/urfave/cli from v1.20.0 to v1.21.0
- Bump golang.org/x/sys from v0.0.0-20190626221950-04f50cda93cb to
  v0.0.0-20190804053845-51ab0e2deafa
- Bump k8s.io/utils from v0.0.0-20190607212802-c55fbcfc754a to
  v0.0.0-20190801114015-581e00157fb1

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
@saschagrunert, could you bump c/image to v3.0.2 here? I'm currently on Flock and won't find much time to push https://github.com/cri-o/cri-o/pull/2694 through the CI, so I hoped we can get it in with this PR here.

**Comment by saschagrunert** [comment]
> @saschagrunert, could you bump c/image to v3.0.2 here? I'm currently on Flock and won't find much time to push #2694 through the CI, so I hoped we can get it in with this PR here.

Yes sure, I will also update Kubernetes 1.16 to alpha 3 :)

**Comment by vrothberg** [comment]
Thanks 🙏

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.  Thanks a bunch @saschagrunert

**Pull request merged**
