### PR TITLE
exec: Close pipe fds to prevent hangs

### PR DESCRIPTION
**Pull request by umohnani8**
Cherry-pick of https://github.com/cri-o/cri-o/pull/3243

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
/retest

LGTM

**Comment by mrunalp** [comment]
We need backports as well.

**Pull request merged**
