### PR TITLE
tests: added metrics test to ctr.bats and command.bats

### PR DESCRIPTION
**Pull request by chuanchang**
$ bats -f "ctr expose metrics" test/ctr.bats 
 ✓ ctr expose metrics with default port
 ✓ ctr expose metrics with custom port

2 tests, 0 failures

$ bats -f "invalid metrics port" test/command.bats 
 ✓ invalid metrics port

1 test, 0 failures

Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>

**- What I did**
added metrics test to ctr.bats and command.bats

**- How I did it**

- add positive testing to ctr.bats

  - [x]     expose metrics with default port
  - [x]     expose metrics with custom port

- add negative testing to command.bats
  - [x]    invalid metrics port

**- How to verify it**
$ bats -f "ctr expose metrics" test/ctr.bats 
$ bats -f "invalid metrics port" test/command.bats 

**- Description for the changelog**

### CODE REVIEW

**Comment by giuseppe** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM
/test e2e

**Pull request merged**
