### PR TITLE
vendor: update seccomp/containers-golang to v0.4.1

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by mrunalp** [comment]
restarted integration on circle

**Comment by giuseppe** [comment]
> Does this add any user-facing change?

the only difference is that the seccomp policy understands a new fiend (`errnoRet`)

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by giuseppe** [comment]
@mrunalp PTAL

**Pull request merged**
