### PR TITLE
[release-1.30] ci: fix reload config for empty pinned image test 

### PR DESCRIPTION
**Pull request by kwilczynski**
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8399

/assign kwilczynski

```release-note
None
```

### CODE REVIEW

**Comment by kwilczynski** [comment]
@cri-o/cri-o-maintainers, please have a look, thank you!

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Comment by kwilczynski** [comment]
Hello @cri-o/cri-o-maintainers, please have a look. Thank you!

**Comment by sohankunkerkar** [comment]
@haircommander we also need `/approve` from you. :)

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
