### PR TITLE
Remove etcd dependency replacement

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
The latest `main` of etcd already contains the correct dependency tree, so we can now use it instead of pinning to a fork.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Had to rebase this one.

**Comment by haircommander** [comment]
seems to need a rebase

**Comment by saschagrunert** [comment]
> seems to need a rebase

Done :+1:

**Comment by saschagrunert** [comment]
@haircommander this would require a new set of approvals :)

**Pull request merged**
