### PR TITLE
oci: move channel close to writer goroutine

### PR DESCRIPTION
**Pull request by giuseppe**
solves the crash:

goroutine 7073 [running]:
github.com/cri-o/cri-o/internal/oci.(*Runtime).WaitContainerStateStopped.func1(0xc000bda240,
0x23e36a0, 0xc000bdc030, 0xc0001b11e0, 0xc000bda1e0)
	src/github.com/cri-o/cri-o/internal/oci/oci.go:132 +0xdc
created by github.com/cri-o/cri-o/internal/oci.(*Runtime).WaitContainerStateStopped
	src/github.com/cri-o/cri-o/internal/oci/oci.go:120 +0x156

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### What type of PR is this?

/kind bug

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by giuseppe** [comment]
@mrunalp I think we want  this for 1.19

@tedyu PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
