### PR TITLE
Vendor kubernetes v1.17.0

### PR DESCRIPTION
**Pull request by saschagrunert**
That's an easy one, because we have no further code changes between the latest RC vendored and the final tag.

### CODE REVIEW

**Comment by rhatdan** [comment]
Does this mean we should cut a release?

**Comment by saschagrunert** [comment]
> Does this mean we should cut a release?

I think we should definitely do before Christmas. From my point of view these four would be good to be part of the release: #3029, #2991, #2988, #2912

**Comment by saschagrunert** [comment]
I label them for the release

**Pull request merged**
