### PR TITLE
Implement pod sandbox for FreeBSD

### PR DESCRIPTION
**Pull request by dfr**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This implements the sandbox lifecycle for FreeBSD, allowing pods to be created and destroyed. I have not included the code for container lifecycle to attempt to reduce the scope of this PR to the minimum. Part of #6492.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by dfr** [comment]
Rebased

**Comment by dfr** [comment]
Rebased

**Comment by haircommander** [comment]
/approve

LGTM, thanks @dfr

**Comment by dfr** [comment]
All the tests are green except for ci/kata-jenkins which is showing as 'Expected — Waiting for status to be reported'. Is that normal? Should I try to restart it?

**Comment by saschagrunert** [comment]
@dfr yes that's normal, all tests are green

**Comment by haircommander** [comment]
@cri-o/cri-o-maintainers any additional thoughts or are we good to merge?

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
