### PR TITLE
Rollback gocapability vendor bump

### LINKED ISSUE #4466: Kubernetes NodeConformance and NodeFeatures jobs failing with latest CRIO
**Description**

**Steps to reproduce the issue:**
1. [Prow CRIO periodic jobs](https://prow.k8s.io/?job=*crio*)

**Describe the results you received:**
Kubernetes NodeConformance and NodeFeatures jobs failing with latest CRIO

**Describe the results you expected:**
 NodeConformance and NodeFeatures jobs were running fine before https://github.com/cri-o/cri-o/commit/78261109b1311427d9cd9d935e9f21daa84d36b6 was merged. That change bumps `github.com/syndtr/gocapability v0.0.0-20180916011248-d98352740cb2` to `github.com/syndtr/gocapability v0.0.0-20200815063812-42c35b437635`. 
 
 This makes the prow test in upstream k8s fail with following error, 

```
Jan 11 06:53:40.801: INFO: At 2021-01-11 06:48:43 +0000 UTC - event for pod-host-path-test: {kubelet tmp-node-e2e-ea1796c0-fedora-coreos-33-20201214-3-1-gcp-x86-64} Failed: Error: container create failed: time="2021-01-11T06:48:43Z" level=error msg="container_linux.go:370: starting container process caused: unknown capability \"CAP_PERFMON\""
``` 

It's nicely documented by [Sebastiaan van Stijn](https://github.com/thaJeztah) at https://github.com/moby/moby/pull/41563 on why we should keep the `github.com/syndtr/gocapability` pinned at `v0.0.0-20180916011248-d98352740cb2` until the new `runc` is released. 

I will send the PR to fix it. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

#### What type of PR is this?

> /kind api-change
/kind bug
> /kind ci
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind other

#### Which issue(s) this PR fixes:

Fixes #4466 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/ok-to-test
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
Assuming happy tests

**Comment by haircommander** [comment]
/approve
/lgtm

thanks for tracking his down @harche

**Comment by haircommander** [comment]
we also got a segfault in the unit tests which may need some eyes https://app.circleci.com/pipelines/github/cri-o/cri-o/7171/workflows/25af0ac5-05b6-439d-b0db-42f2e1936b72/jobs/115965/parallel-runs/0/steps/0-107

**Pull request merged**
