### PR TITLE
[CLI] "crio config" only prints the fields that are different than the default

### LINKED ISSUE #4506: `crio config` fixes
Currently, calling `crio config` spits out an entire config file. However, it would be prudent for us to move away from the monolithic config file, in favor of smart defaults, and drop-in files.

However, to do this, there needs to be a way for users to quickly create drop-in files, and have them not override the defaults where they don't need to.

The main advantage to this approach is it allows us to change defaults without as much churn in config files.

This proposal is to change `crio config` to render the configuration/flags it's passed, and only print the toml for the fields that are different than the default.

Sample could be:
`crio --log-level debug config`
would only output
```
[crio]
[crio.runtime]
log_level = "debug"
```

/kind feature

### PR DESCRIPTION
**Pull request by ityuhui**
#### What this PR does / why we need it:
As described in #4506 , this PR lets ``crio config`` only prints the fields that are different than the default.

#### Which issue(s) this PR fixes:
Fixes #4506

#### Does this PR introduce a user-facing change?
Yes.

```release-note
"crio config" only prints the fields that are different than the default configuration.
```

### CODE REVIEW

**Comment by haircommander** [comment]
WOW this is better than what I was imagining 
/ok-to-test

there are some test failures, and I'll have a deeper look at the code, but at a glance this looks great :tada:

**Comment by haircommander** [comment]
error is:
```
not ok 141 pod pause image matches configured image in crio.conf
# (in test file ./pod.bats, line 249)
#   `conf_pause_image=$(grep -oP 'pause_image = \K"[^"]+"' "$CRIO_CONFIG")' failed

```
you can run it with
`sudo bats test/pod.bats -f "pod pause image"`

**Comment by ityuhui** [comment]
Hi @haircommander

I have fixed all errors for Github/Actions. 
Could you please help check why the 4 ci/openshift-* checks failed ?

**Comment by haircommander** [comment]
/retest

they could be flakes, or a regression in crun

**Comment by ityuhui** [comment]
Hi @haircommander

I have retest 3 times, but there are still 3 ci/openshift-jenkins check failed.

**Comment by haircommander** [comment]
@saschagrunert @kolyshkin @umohnani8 @mrunal @QiWang19 PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by haircommander** [comment]
sorry @ityuhui you have a merge conflict, can you rebase?

**Comment by haircommander** [comment]
/hold

to make bot stop

**Comment by ityuhui** [comment]
> sorry @ityuhui you have a merge conflict, can you rebase?

Sure. I have rebased the code and fix the conflict.

**Comment by ityuhui** [comment]
Hi @haircommander 

The integration/critest (and ci/openshift-jenkins/critest_fedora, ci/openshift-jenkins/critest_rhel) check failed, I don't think it relate with this PR. Could you please help take a look ?

**Comment by haircommander** [comment]
sorry! I commented on others but not this one. You're correct, cri test failures are not the fault of this PR. they're getting investigated

**Comment by haircommander** [comment]
/override ci/openshift-jenkins/critest_fedora
/override ci/openshift-jenkins/critest_rhel

gh actions critest passed

/retest

**Comment by haircommander** [comment]
/hold
integration_crun failure is legit, I'm looking into it

**Comment by haircommander** [comment]
@ityuhui sorry, can you apply the following diff:
```
diff --git a/test/config.bats b/test/config.bats
index 50fba2901..578b4c0e9 100644
--- a/test/config.bats
+++ b/test/config.bats
@@ -42,7 +42,7 @@ function teardown() {
 @test "replace default runtime should succeed" {
 	# when
 	unset CONTAINER_RUNTIMES
-	RES=$("$CRIO_BINARY_PATH" -c "$TESTDATA"/50-crun-default.conf config 2>&1)
+	RES=$("$CRIO_BINARY_PATH" -c "$TESTDATA"/50-crun-default.conf -d "" config 2>&1)
 
 	# then
 	[[ "$RES" == *"default_runtime = \"crun\""* ]]
```

**Comment by haircommander** [comment]
@ityuhui you'll need a rebase while we're at it. thanks for sticking with this, I'd like it to land in 1.21.0 :)

**Comment by ityuhui** [comment]
> @ityuhui you'll need a rebase while we're at it. thanks for sticking with this, I'd like it to land in 1.21.0 :)

Both rebase and `config.bats` update have done.

**Comment by haircommander** [comment]
thanks a bunch for the contribution @ityuhui!

**Pull request merged**
