### PR TITLE
Change `progressGoRoutine` to `consumeImagePullProgress`

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Follow-up on https://github.com/cri-o/cri-o/pull/7887#discussion_r1544648429

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
/override ci/prow/ci-fedora-integration
known flake

**Comment by com6056** [comment]
Any chance we can get this and https://github.com/cri-o/cri-o/pull/7887 cherry-picked into 1.27? 🙏

**Comment by saschagrunert** [comment]
> Any chance we can get this and #7887 cherry-picked into 1.27/1.28/1.29? 🙏

@cri-o/cri-o-maintainers I'm a bit opposed to that due to the risk of regressions. Do you have thoughts on a backport?

**Comment by kwilczynski** [comment]
> Any chance we can get this and #7887 cherry-picked into 1.27/1.28/1.29? 🙏

@com6056, any path for you to upgrade to the version that has the required feature?

**Comment by com6056** [comment]
> > Any chance we can get this and #7887 cherry-picked into 1.27/1.28/1.29? 🙏
> 
> @com6056, any path for you to upgrade to the version that has the required feature?

Unfortunately we're quite a bit behind on K8s versions right now so it might be a bit before we can get to a compatible version 😢

**Pull request merged**
