### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
Bump google.golang.org/grpc from 1.24.0 to 1.25.1
Bump github.com/containernetworking/plugins from 0.8.2 to 0.8.3
Bump github.com/containerd/containerd from 1.3.0 to 1.3.1

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, tests results aren't happy though.

**Comment by giuseppe** [comment]
LGTM

/retest

**Comment by saschagrunert** [comment]
Hm, it looks like that the `checkout -f` changes we merged yesterday are not applied somehow :thinking:

**Pull request merged**
