### PR TITLE
Fix GitHub artifact upload via new upload-artifacts target

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
We do not need to filter on tags any more in CircleCI since this has no
influence on the build process.

Beside that, we fix the upload by moving the logic into a script and
setting the right bash execution parameters.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by saschagrunert** [comment]
Green tests I guess this is ready to be merged @haircommander

**Pull request merged**
