### PR TITLE
[1.11] klog: don't write to /tmp

### PR DESCRIPTION
**Pull request by haircommander**
klog currently doesn't have an API to not write to /tmp. One has to "pass" down flags to it.
since cri-o uses libraries that use klog, we need this hack to not write klog logs to /tmp

closes: https://bugzilla.redhat.com/show_bug.cgi?id=1796066

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
@chavafg if you have a moment, can you PTAL at these failures? this is a very old branch, so don't worry if none of the errors make sense, but if you have any fix off the top of your head it would be much appreciated

**Comment by haircommander** [comment]
in the meantime, reviewers: this is ready, I don't think we should require kata to pass to get prs into such an old branch
PTAL @mrunalp @rhatdan @umohnani8 @saschagrunert

**Comment by chavafg** [comment]
@haircommander should be fixed, want to restart kata job?

**Comment by haircommander** [comment]
> @haircommander should be fixed, want to restart kata job?

@chavafg ++, thanks a bunch!

/retest

**Comment by haircommander** [comment]
```
 [MIRROR] containernetworking-plugins-0.8.5-1.fc30.x86_64.rpm: Curl error (28): Timeout was reached for http://mirrors.oit.uci.edu/fedora/linux/updates/30/Everything/x86_64/Packages/c/containernetworking-plugins-0.8.5-1.fc30.x86_64.rpm [Connection timed out after 30000 milliseconds] 
```
/retest

**Comment by rhatdan** [comment]
@haircommander Does this need a rebase?
/retest

**Comment by haircommander** [comment]
we're carrying this as a patch, and I don't have the cycles to try to hack it together here.

**Pull request closed without merging**
