### PR TITLE
[1.18] Bump version to v1.18.2

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Some important fixes are part of the release branch and I guess we're ready for a new release, right?
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.

**Comment by haircommander** [comment]
LGTM, I say let's get https://github.com/cri-o/cri-o/pull/3851 first

**Comment by saschagrunert** [comment]
> LGTM, I say let's get #3851 first

Sounds good.

**Comment by dirkmueller** [comment]
#3851 is in now I think. Anything else we want to wait on?

**Comment by saschagrunert** [comment]
> #3851 is in now I think. Anything else we want to wait on?

I think we’re fine. 

@haircommander should I create the release+tag (via GitHub interface) on the latest `release-1.18` commit if this one got merged? 😇 the automation should work then, but we need an official “GitHub release” to be able to upload the binaries automatically.

**Comment by haircommander** [comment]
> > #3851 is in now I think. Anything else we want to wait on?
> 
> I think we’re fine.
> 
> @haircommander should I create the release+tag (via GitHub interface) on the latest `release-1.18` commit if this one got merged? innocent the automation should work then, but we need an official “GitHub release” to be able to upload the binaries automatically.

are we not able to merge this, then tag the release?

**Comment by saschagrunert** [comment]
> > > #3851 is in now I think. Anything else we want to wait on?
> > 
> > 
> > I think we’re fine.
> > @haircommander should I create the release+tag (via GitHub interface) on the latest `release-1.18` commit if this one got merged? innocent the automation should work then, but we need an official “GitHub release” to be able to upload the binaries automatically.
> 
> are we not able to merge this, then tag the release?

That's what I meant. Merge this one and then tag (but via a GitHub release, not via git tag ...) :) Would this work for you?

**Comment by haircommander** [comment]
> > > > #3851 is in now I think. Anything else we want to wait on?
> > > 
> > > 
> > > I think we’re fine.
> > > @haircommander should I create the release+tag (via GitHub interface) on the latest `release-1.18` commit if this one got merged? innocent the automation should work then, but we need an official “GitHub release” to be able to upload the binaries automatically.
> > 
> > 
> > are we not able to merge this, then tag the release?
> 
> That's what I meant. Merge this one and then tag (but via a GitHub release, not via git tag ...) :) Would this work for you?

works with me, can you take care of it?
/lgtm

**Comment by saschagrunert** [comment]
/test critest_fedora

Yep.

**Comment by saschagrunert** [comment]
@dirkmueller I’ll cut the release. Unfortunately I’m currently on vacation so I can’t update it in OBS. feel free to submit it there and ping @rhafer or @sysrich to accept it.

**Comment by dirkmueller** [comment]
@saschagrunert did so already, thanks a lot for your help during 'vacation' ;-)

**Pull request merged**
