### PR TITLE
[1.24] crio storage wipe backport

### PR DESCRIPTION
**Pull request by wgahnagl**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
cherry-pick of https://github.com/cri-o/cri-o/pull/6022 

#### Which issue(s) this PR fixes:
https://issues.redhat.com/browse/OCPBUGS-3708 

#### Does this PR introduce a user-facing change?

```release-note
Update `version-file-persist` to be empty by default, and do not wipe images when it is so.
```

### CODE REVIEW

**Comment by jrvaldes** [comment]
> docs and completions validation still need love

@haircommander  [validate-completions job](https://github.com/cri-o/cri-o/actions/runs/3689468299/jobs/6245527696#logs) failed with: 
```
rm: cannot remove '/etc/containers/storage.conf': No such file or directory
```

This was changed for `main` branch by https://github.com/cri-o/cri-o/pull/4503. Missing a backport maybe? cc @wgahnagl

**Comment by haircommander** [comment]
hm, when I run
`git diff upstream/release-1.24..upstream/main -- .github/workflows/test.yml`
I get 
```
-      - run: |
-          chmod -R +x bin
-          sudo rm /etc/containers/storage.conf
+      - run: chmod -R +x bin
```
I am having trouble finding the commit that we removed  that line, but that would help

**Comment by jrvaldes** [comment]
> #4503.

See https://github.com/cri-o/cri-o/pull/6449#issuecomment-1373850063

**Comment by haircommander** [comment]
:upside_down_face: sorry I missed you mentioned it! that one is already a part of 1.21 and later (see https://github.com/cri-o/cri-o/pull/4503/commits/a0568ace64283ece31c329bff793751331df3fcc) so it's a Pr that came later

**Comment by jrvaldes** [comment]
> upside_down_face sorry I missed you mentioned it! that one is already a part of 1.21 and later (see [a0568ac](https://github.com/cri-o/cri-o/commit/a0568ace64283ece31c329bff793751331df3fcc)) so it's a Pr that came later

This PR removed the above-mentioned line

- https://github.com/cri-o/cri-o/pull/6392

**Comment by haircommander** [comment]
nice find! @jrvaldes would you like to initiate the cherry-pick process of that one? It looks like it's in 1.26 already, so we can begin with 1.25, and pull it back down  (one-by-one merging in reverse order of age)

**Comment by jrvaldes** [comment]
> nice find! @jrvaldes would you like to initiate the cherry-pick process of that one? It looks like it's in 1.26 already, so we can begin with 1.25, and pull it back down (one-by-one merging in reverse order of age)

@haircommander  PR https://github.com/cri-o/cri-o/pull/6392 includes several adjustments (that may not be related to the missing changes) is it safe to backport them all? Should they be analyzed individually? If so, a manual cherry-pick may be required.

**Comment by haircommander** [comment]
> > nice find! @jrvaldes would you like to initiate the cherry-pick process of that one? It looks like it's in 1.26 already, so we can begin with 1.25, and pull it back down (one-by-one merging in reverse order of age)
> 
> @haircommander PR #6392 includes several adjustments (that may not be related to the missing changes) is it safe to backport them all? Should they be analyzed individually? If so, a manual cherry-pick may be required.

How about you manually backport to 1.25 and find the pieces needed to fix that. If they all seem like they will improve the situation in 1.24 and earlier, we can automatically backport there, and we can add more/remove some manually if needed

**Comment by jrvaldes** [comment]
@haircommander  

> nice find! @jrvaldes would you like to initiate the cherry-pick process of that one? It looks like it's in 1.26 already, so we can begin with 1.25, and pull it back down (one-by-one merging in reverse order of age)

@haircommander , I asked the bot for help with an automatic cherry-pick. 

- https://github.com/cri-o/cri-o/pull/6505

**Comment by jrvaldes** [comment]
> > > nice find! @jrvaldes would you like to initiate the cherry-pick process of that one? It looks like it's in 1.26 already, so we can begin with 1.25, and pull it back down (one-by-one merging in reverse order of age)
> > 
> > 
> > @haircommander PR #6392 includes several adjustments (that may not be related to the missing changes) is it safe to backport them all? Should they be analyzed individually? If so, a manual cherry-pick may be required.
> 
> How about you manually backport to 1.25 and find the pieces needed to fix that. If they all seem like they will improve the situation in 1.24 and earlier, we can automatically backport there, and we can add more/remove some manually if needed

Agree. Will open specifics manual backports if case there are conflicts.

**Comment by jrvaldes** [comment]
/hold

Depends on:
- https://github.com/cri-o/cri-o/pull/6506

**Comment by jrvaldes** [comment]
/hold cancel

https://github.com/cri-o/cri-o/pull/6506 merged.

**Comment by jrvaldes** [comment]
/close 

in favor of https://github.com/cri-o/cri-o/pull/6509

**Pull request closed without merging**
