### PR TITLE
add vrothberg to OWNERS file

### PR DESCRIPTION
**Pull request by vrothberg**
I'm contributing to CRI-O for almost a year, helped maintain, debug, and improve. Other (most) contributions happen indirectly via the containers/image, c/storage, and c/libpod libraries.

This will ultimately allow me to approve Pull Requests and share some power across the continents :^)

@rhatdan @mrunalp @saschagrunert @umohnani8 @sboeuf @sameo PTAL

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM :smile:

**Comment by saschagrunert** [comment]
:tada: LGTM :tada:

**Comment by haircommander** [comment]
Hoping to get this into release-1.15 so we have another active approver for backports :)

**Comment by vrothberg** [comment]
> Hoping to get this into release-1.15 so we have another active approver for backports :)

Good point. Let's hope for CI to behave :^)

**Comment by umohnani8** [comment]
LGTM :tada:

**Comment by haircommander** [comment]
for some reason e2e_features_* has been down this morning. Investigating...

**Comment by vrothberg** [comment]
In theory, we could force merge. Throwing CI at this change is just creating heat.

**Comment by rhatdan** [comment]
Forcing Merge

**Pull request merged**
