### PR TITLE
Fix kubeadm.md typo

### PR DESCRIPTION
**Pull request by imvalient**
Fixed a typo in the kubeadm.md file. The `script` word.

Signed-off-by: Imanol Valiente <me@imanol.dev>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

It fixes a little typo in the kubeadm.md documentation file.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

None

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve

LGTM, thanks @imvalient !

**Comment by saschagrunert** [comment]
Test issues are not related
/override ci/prow/e2e-gcp
/override ci/prow/e2e-agnostic

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
