### PR TITLE
Bump GRPC to v1.27.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
This fixes the build of the release-note tool, which previously failed
with:

```
vendor/google.golang.org/api/internal/conn_pool.go:29:2: undefined: grpc.ClientConnInterface
```
#### Which issue(s) this PR fixes:

Refers to 15aa81b
Forward-port of https://github.com/cri-o/cri-o/pull/4190
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by mrunalp — APPROVED** [review]

**Comment by mrunalp** [comment]
@fidencio Can you check that this keeps kata happy?

**Comment by fidencio** [comment]
Sure, gimme an hour or two and I'll get to this.

**Comment by fidencio** [comment]
@mrunalp, @saschagrunert,

I've just tested this and it doesn't break anything on kata. Based on this ...
/lgtm

**Comment by saschagrunert** [comment]
Thank you @fidencio :heart: 
/retest

**Comment by mrunalp** [comment]
Rebase needed for test fixes

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Pull request merged**
