### PR TITLE
Refactor Stop and Remove methods in ContainerServer and Server

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
I personally find it confusing that the ContainerServer has a stop and remove method. Besides server restore (which is a separate matter) it is not the entities that provision the storage/cgroup/container, yet it has methods to stop and remove them. I think it makes more sense to have these methods in one place, and Server seems like the better fit.

This also includes some deduplication of methods
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming the last few tests get hip

**Comment by haircommander** [comment]
@saschagrunert I think some CI failures will be fixed by this, can you PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
