### PR TITLE
Add /sys/dev as a masked path

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
If the container is not privileged, mask the /sys/dev
path so that we don't leak extra devices in a container.

#### Which issue(s) this PR fixes:
Fixes #1772993 (https://bugzilla.redhat.com/show_bug.cgi?id=1772993)

#### Does this PR introduce a user-facing change?

```release-note
None

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
Assuming happy tests

**Comment by mrunalp** [comment]
@kolyshkin ptal

**Comment by rhatdan** [comment]
This was already blocked in podman and Buildah, we got to get more sharing of code between the packages.

**Pull request merged**
