### PR TITLE
Allow SELinux unconfined containers

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

We now let process labels starting with `unconfined_u:unconfined_r:unconfined_t` be applied by CRI-O.

#### Which issue(s) this PR fixes:

Refers to https://github.com/openshift/oc/pull/842#issuecomment-1491051478

#### Special notes for your reviewer:

For discussion @mrunalp @haircommander 
#### Does this PR introduce a user-facing change?

```release-note
Allow SELinux process labels being applied starting with `unconfined_u:unconfined_r:unconfined_t`.
```

### CODE REVIEW

**Comment by travier** [comment]
This might need a new rule in the policy to allow that domain transition.

**Comment by travier** [comment]
https://github.com/containers/container-selinux/blob/main/container.te#L652 > This would suggest that this is already allowed but not sure.

**Comment by rhatdan** [comment]
You do not need to transition the user or the role.

system_u:system_t:unconfined_t:MCS is fine.

This should be allowed.

**Comment by saschagrunert** [comment]
This is not required any more due to https://github.com/containers/container-selinux/releases/tag/v2.208.0

**Pull request closed without merging**
