### PR TITLE
Switch to logrus 1.6.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
This should fix the issues we had with 1.5.0.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons

**Comment by saschagrunert** [comment]
Rebased on top of the latest master to resolve the conflict

**Pull request merged**
