### PR TITLE
WIP - CI TEST COPY DETECTION

### PR DESCRIPTION
**Pull request by vrothberg**
Do not merge. This a CI PR. I will break some updates out to unblock other PRs that require newer versions of containers/image and friends.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
```
pkg/storage/runtime_test.go:864:61: cannot use storeMock (variable of type *github.com/kubernetes-sigs/cri-o/test/mocks/containerstorage.MockStore) as github.com/kubernetes-sigs/cri-o/vendor/github.com/containers/storage.Store value in argument to istorage.Transport.ParseStoreReference: missing method GetDigestLock (typecheck)
			pulledRef, err := istorage.Transport.ParseStoreReference(storeMock, "pauseimagename")
			                                                         ^
pkg/storage/image_test.go:35:31: cannot use storeMock (variable of type *github.com/kubernetes-sigs/cri-o/test/mocks/containerstorage.MockStore) as github.com/kubernetes-sigs/cri-o/vendor/github.com/containers/storage.Store value in argument to storage.GetImageService: missing method GetDigestLock (typecheck)
			context.Background(), nil, storeMock, "",
```

@saschagrunert @mrunalp, I don't find it maintainable that the mocks need to implement the interfaces of containers/storage. It's pretty much breaking the separation of concerns and I expect it to cause more work in the future if the tests do this for more non-local interfaces. I will try to update it but please reconsider going down this path.

**Comment by vrothberg** [comment]
A critical point for reavaluation: The containers/* libraries don't (yet) give any guarantee for API stability.

**Comment by haircommander** [comment]
@vrothberg we haven't stabilized CI yet after the move, so there is no chance tests are going to pass now :)

**Comment by vrothberg** [comment]
Closing in favour of Closing in favour of https://github.com/containers/image/pull/611.

**Pull request closed without merging**
