### PR TITLE
Add template and command line flags validation

### PR DESCRIPTION
**Pull request by saschagrunert**
We move the template string and writing logic into the `config` package
to reuse them by the newly introduced `docs-validation` tool. This tool
mainly discovers all `toml` tags by reflection and verifies them against
the documentation (CLI and config options). The CI job has been added as
well which regulary validates the configuration documentation.

Requires: https://github.com/cri-o/cri-o/pull/2612
Example output: https://circleci.com/gh/openSUSE/cri-o/13098

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Looks good in general, but it looks like you've some tweaking to do yet.  A number of options are failing in the docs-integration tests.

**Comment by saschagrunert** [comment]
> Looks good in general, but it looks like you've some tweaking to do yet. A number of options are failing in the docs-integration tests.

Thanks :pray:. Yes I found some formatting issues and inconsistencies in our documentation which should be fixed before actually removing the *WIP* here. 

I also thought about going the other way around and directly generating the man pages (or just markdown) directly from the structures and CLI flags. Maybe this would be worth a look, too...

**Comment by saschagrunert** [comment]
Rebased on top of the latest master and its magically green, PTAL :)

**Pull request merged**
