### PR TITLE
[1.19] runtime_vm: set Pid and InitPid for VM runtimes

### LINKED ISSUE #4264: [1.19] invalid infra container using crictl with vm type runtime (kata)
**Description**

CRI-O 1.19 and cri-tools v1.19.0 installed.
Kata containers shimv2 installed and configured as default runtime for CRI-O.
[Basic example from cri-tools](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md#create-container-in-the-pod-sandbox-with-config-file) fails.

**Steps to reproduce the issue:**
Start CRI-O 1.19 with _containerd-shim-kata-v2_ as the default runtime an run the [cri-tools example](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md#create-container-in-the-pod-sandbox-with-config-file):

`# crictl runp pod-config.json`
175d4a12122cdd3ee51e0e74b8d111f67245aa3ba0373694eba188668707f544
`]# crictl create 175d4a12122cdd3ee51e0e74b8d111f67245aa3ba0373694eba188668707f544 container-config.json pod-config.json`
FATA[0010] creating container: rpc error: code = Unknown desc = PID namespace requested, but sandbox infra container invalid

**Additional information you deem important (e.g. issue happens only occasionally):**
When the pod is created, the infra container has the state InitPid not initialized (set to 0).
This triggers the error on container creation.

### PR DESCRIPTION
**Pull request by fgiudici**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Initialize the InitPid when starting a pod with a _vm_ runtime.

#### Which issue(s) this PR fixes:
Fixes #4264 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test

thanks @fgiudici, when we target against a release branch, we usually prefix the title with `[1.19]` to make it easier to see where it's targeted. could you retitle please?

/approve

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by fidencio** [comment]
/lgtm

Thanks, @fgiudici!

**Pull request merged**
