### PR TITLE
Return empty DecryptConfig when no keys to force decryption

### LINKED ISSUE #3913: Decryption error not propagating if keys dir doesn't exists
**Description**

crio returns "archive/tar: invalid tar header" error instead of "decryption error" when an encrypted image is run if keys directory doesn't exists. Instead of correctly propagating a decryption error. 

(Thanks @maia-iyer for highlighting this behavior)

**Steps to reproduce the issue:**
1. Run crio with `--decryption-keys-path` flag
2. Ensure the directory doesn't exist
3. See error returned by runtime

```
vagrant@ubuntu-bionic:~$ sudo crictl -r unix:///var/run/crio/crio.sock pull --creds iamapikey:x_egxeGnaXi4GfKMbp0pYw0iErUAIjn5uYQIHTZ2RKof us.icr.io/ecins/encrypted_image:encrypted
FATA[0006] pulling image failed: rpc error: code = Unknown desc = Error committing the finished image: error adding layer with blob "sha256:ecbef970c60906b9d4249b47273113ef008b91ce8046f6ae9d82761b9ffcc3c0": Error processing tar file(exit status 1): archive/tar: invalid tar header
vagrant@ubuntu-bionic:~$ mkdir /etc/crio/keys
mkdir: cannot create directory ‘/etc/crio/keys’: Permission denied
vagrant@ubuntu-bionic:~$ sudo mkdir /etc/crio/keys
vagrant@ubuntu-bionic:~$ sudo crictl -r unix:///var/run/crio/crio.sock pull --creds iamapikey:x_egxeGnaXi4GfKMbp0pYw0iErUAIjn5uYQIHTZ2RKof us.icr.io/ecins/encrypted_image:encrypted
FATA[0003] pulling image failed: rpc error: code = Unknown desc = Error decrypting layer sha256:ecbef970c60906b9d4249b47273113ef008b91ce8046f6ae9d82761b9ffcc3c0: missing private key needed for decryption
```

**Describe the results you received:**

When running an encrypted image, 

If the /etc/crio/keys folder doesn't exists, it still gives the error:
```
Failed to pull image "us.icr.io/ecins/nginx:encrypted": rpc error: code = Unknown desc = Error committing the finished image: error adding layer with blob "sha256:ecbef970c60906b9d4249b47273113ef008b91ce8046f6ae9d82761b9ffcc3c0": Error processing tar file(exit status 1): archive/tar: invalid tar header
```

with mkdir /etc/crio/keys , it gives the correct error:
```
 Failed to pull image "us.icr.io/ecins/nginx:encrypted": rpc error: code = Unknown desc = Error decrypting layer sha256:ecbef970c60906b9d4249b47273113ef008b91ce8046f6ae9d82761b9ffcc3c0: missing private key needed for decryption
```

**Describe the results you expected:**
Result should be the following regardless of existence of keys directory
```
 Failed to pull image "us.icr.io/ecins/nginx:encrypted": rpc error: code = Unknown desc = Error decrypting layer sha256:ecbef970c60906b9d4249b47273113ef008b91ce8046f6ae9d82761b9ffcc3c0: missing private key needed for decryption
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.17.4-12.dev.rhaos4.4.git2be4d9c.el8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMWare

### PR DESCRIPTION
**Pull request by lumjjb**
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

#### What type of PR is this?

> /kind api-change

/kind bug
> /kind cleanup
> /kind dependency-change
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

#### What this PR does / why we need it:

Initializes decrypt config to appropriate value if decryption-keys directory doesn't exist.

#### Which issue(s) this PR fixes:

Fixes #3913 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve

LGTM

**Comment by haircommander** [comment]
e2e tests are known to be busted btw :smiley:

**Comment by lumjjb** [comment]
>e2e tests are known to be busted btw 😃

I can empathize with this problem :)

**Comment by haircommander** [comment]
@lumjjb finally, our tests are fix, please rebase :)

**Comment by lumjjb** [comment]
@haircommander looks like one integration test is still failing, is that a known error? 

`not ok 113 Ping pod from another pod`

**Comment by haircommander** [comment]
those tests aren't triggered by prow, I have retriggered it and it seems to be happy again

**Comment by TomSweeneyRedHat** [comment]
LGTM 
and happy green test buttons

**Pull request merged**
