### PR TITLE
[1.19] vendor: bump c/storage to latest v1.20-stable

### PR DESCRIPTION
**Pull request by haircommander**
and pickup fix about recreating link dir symlinks

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Which issue(s) this PR fixes:

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where container storage can get corrupted if the `link` directory is missing.
```

### CODE REVIEW

**Comment by haircommander** [comment]
basically just grabbing https://github.com/containers/storage/pull/859

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
