### PR TITLE
Add network setup metrics

### LINKED ISSUE #2906: Add metric for CNI network setup time
We want to be able to accurately measure and improve pod startup time. We should track the time it takes for CNI to set up the network namespace for a pod so we can improve the performance and help debug issues in running clusters.

cc: @smarterclayton

### PR DESCRIPTION
**Pull request by saschagrunert**
This adds two new metrics `network_setup_pod` and
`network_setup_overall` which provides a better way for network startup
time debugging.

Closes #2906

---

As a follow-up I suggest adding a documentation part about the available metrics and what they actually do.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@haircommander @umohnani8 @mrunalp @giuseppe PTAL

**Comment by haircommander** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM integration-userns test isn't happy, might be a flake.

**Pull request merged**
