### PR TITLE
Update CNI plugin test dependency to v0.7.5

### PR DESCRIPTION
**Pull request by saschagrunert**
Update container and ansible dependencies for the CNI plugins as well as
two tests in test/network.bats.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hm, I see two package related dependency issues on RHEL for `device-mapper-devel` and `glibc-static`. The other issue seems more hardware related:
```
TASK [ensure the new space is empty] *******************************************
task path: /var/lib/jenkins/origin-ci-tool/2b40f3e11aadb569dc9c0c9fb90e7273658ce6ed/lib/python2.7/site-packages/oct/ansible/oct/playbooks/provision/aws-docker-storage.yml:33
fatal: [172.18.23.51]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/usr/bin/dd", 
        "if=/dev/zero", 
        "of=/dev/xvdb", 
        "bs=1M"
    ], 
    "delta": "0:09:35.188209", 
    "end": "2019-04-29 21:02:35.375816", 
    "failed": true, 
    "generated_timestamp": "2019-04-29 17:02:35.403489", 
    "rc": 1, 
    "start": "2019-04-29 20:53:00.187607", 
    "stderr": [
        "/usr/bin/dd: error writing ‘/dev/xvdb’: No space left on device", 
        "51201+0 records in", 
        "51200+0 records out", 
        "53687091200 bytes (54 GB) copied, 575.184 s, 93.3 MB/s"
    ], 
    "stdout": [], 
    "warnings": []
}
```
What would a good way to solve this?

**Comment by saschagrunert** [comment]
The same as for the runc update: I leave the ami updates out of scope for now and we have to follow up on these.

**Comment by rhatdan** [comment]
LGTM
@umohnani8 @haircommander @vrothberg @mrunalp PTAL

**Pull request merged**
