### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by kangclzjc**
Signed-off-by: Kang.Zhang <Kang.zhang@intel.com>

#### What type of PR is this?
Very small PR to fix : `sitaution` to `situation`

#### What this PR does / why we need it:
Change typo
#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
/approve
/lgtm

thanks @kangclzjc !

**Comment by kangclzjc** [comment]
@haircommander np, I am new to cri-o, so I want to contribute to this project. BTW, why do check always fail. It keeps checking. How to remove this flag -> [do-not-merge/release-note-label-needed](https://github.com/cri-o/cri-o/labels/do-not-merge%2Frelease-note-label-needed). Thanks, haircommander.

**Comment by haircommander** [comment]
Excellent to hear! Please let me know if there's anything in particular you want to work on, or want help finding tasks! You need to put `none` in the release-note block, you put `no` above it, which I believe would mean there would be a release note... I've updated the block to contain `none` for you!

**Comment by kangclzjc** [comment]
Yeah, I am looking for what I can do and if you have any tasks, you can assign to me. I'd love to work on it

**Pull request merged**
