### PR TITLE
Flatten internal/pkg/* packages to internal/*

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The sub-package `pkg` in `internal` adds an unnecessary package
hierarchy which can be avoided.

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
Sadly needs a rebase.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch

**Comment by saschagrunert** [comment]
Rebased on top of the latest master to fix the CI issues

**Comment by umohnani8** [comment]
LGTM, but needs rebase

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by haircommander** [comment]
/cherry-pick release-1.18

(needs rebase @saschagrunert)

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Pull request merged**
