### PR TITLE
Some more test fixes

### PR DESCRIPTION
**Pull request by kolyshkin**
~~This builds on top of #6950. Draft until that one is merged.~~

```release-note
NONE
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
The only failure I see is "metrics oom" which is being worked on in https://github.com/cri-o/cri-o/pull/6973. So I guess these fixes are OK.

**Comment by sohankunkerkar** [comment]
@kolyshkin could you rebase this PR on top of the main branch?

**Pull request closed without merging**
