### PR TITLE
[1.21] oci: wait until pidfile to be written before starting timer

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### Does this PR introduce a user-facing change?

```release-note
fix a bug where a container exec process received a little less time than the timeout provided

```

### CODE REVIEW

**Comment by haircommander** [comment]
cherry-pick of https://github.com/cri-o/cri-o/pull/5067 dropping the test because it may be flaky

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
