### PR TITLE
Vendor c/storage test branch and add integration tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This change should verify that we can fix the layers.json corruption from c/storage.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
Refers to https://github.com/containers/storage/pull/943
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
/hold

let's not merge the vendored dependency change :)

**Comment by fidencio** [comment]
@saschagrunert, please, Tomorrow remind me to test this with kata-container locally.  I need to understand whether the CI is flaky or if this is actually something we should worry about.

**Comment by saschagrunert** [comment]
@fidencio I should remind you to test that PR with kata-containers locally. :upside_down_face:

**Comment by fidencio** [comment]
@saschagrunert, as far as I could see CI was flaky and it was not related to this PR.
Please, rebase it and let's rerun the tests (which are now green), if we hit a failure again I will do a deep dive on that.

Thanks for the reminder! :-)

**Comment by fidencio** [comment]
LGTM, thanks @saschagrunert!

**Comment by saschagrunert** [comment]
The bump to c/storage v1.32.3 will fix this automatically via dependabot.

**Pull request closed without merging**
