### PR TITLE
[1.16] Run integration tests natively in CI

### PR DESCRIPTION
**Pull request by saschagrunert**
Backport of https://github.com/cri-o/cri-o/pull/3133

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM

**Comment by haircommander** [comment]
/retest
:crossed_fingers:

**Comment by TomSweeneyRedHat** [comment]
LGTM, some test issues to work through still.

**Comment by mrunalp** [comment]
Merging this since relevant tests have passed.

**Pull request merged**
