### PR TITLE
[release-1.29] Make container and image removal/stop idempotent

### PR DESCRIPTION
**Pull request by sohankunkerkar**
This is the manual cherry-pick of https://github.com/cri-o/cri-o/pull/8431

/assign sohankunkerkar

```release-note
None
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by kwilczynski** [comment]
/hold

For 1.30 release merge.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
