### PR TITLE
test/devices.bats: nits

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:

A few minor fixes and improvements to test/devices.bats. Please see individual commits for details.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by haircommander** [comment]
/approve
LGTM

**Review by mrunalp — APPROVED** [review]

**Comment by kolyshkin** [comment]
OK, we need to fix the test to use a device other than `/dev/loop-control`, as it is not supposed to be read from or written to (it's used with ioctls).

```
not ok 80 additional devices permissions
# (in test file ./devices.bats, line 79)
#   `[[ "$output" == *"Invalid argument"* ]]' failed
# time="2020-11-14T04:11:21Z" level=info msg="Starting CRI-O, version: 1.20.0-dev, git: 245ed8e754e9e084519dc9545d071cf06a1509c7(dirty)"
# level=info msg="Using default capabilities: CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_FSETID, CAP_FOWNER, CAP_SETGID, CAP_SETUID, CAP_SETPCAP, CAP_NET_BIND_SERVICE, CAP_KILL"
# 2bcf6fb7938c51d616187edc92d1fd7d2f22b602d743cf4b0e18ac759fc6a609
# /dev/loop-control
```

So adding WIP for now.

**Comment by kolyshkin** [comment]
`/dev/kmsg` seems like a good fit. Updated.

**Comment by kolyshkin** [comment]
Seems like some tests failed to restart after a force push

/retest

**Comment by kolyshkin** [comment]
/retest

(e2e-aws is still supposed to fail)

**Comment by kolyshkin** [comment]
This one is ready

**Comment by kolyshkin** [comment]
OK it seems that https://github.com/openshift/release/pull/13708 was a mistake :(

Opened a revert PR: https://github.com/openshift/release/pull/13736

**Comment by kolyshkin** [comment]
Same failure in `e2e-agnistic` and `images`:

> the build machine-os-content failed after 2m14s with reason DockerBuildFailed: Dockerfile build strategy has failed.
>
> Error: Failed to synchronize cache for repo 'updates'
> subprocess exited with status 1
> subprocess exited with status 1
> STEP 5: FROM image-registry.openshift-image->registry.svc:5...3fc231a7ed11a3cf5a3be7574f867b84455890a6389e15fc14c84621283
> error: build error: error building at STEP "RUN set -x && ...-ci-dev overlay RPMs" --branch=cri-o-ci-dev": exit status 1

/test images
/test e2e-agnostic

**Comment by kolyshkin** [comment]
/retest

(two jobs never reported status back, and e2e-agnostic got many failures)

**Pull request merged**
