### PR TITLE
update drop_infra.bats

### LINKED ISSUE #5860: cri-o/test/drop_infra.bats test case should be reworked
Since cri-o version 1.23 Container_manage_ns_lifecycle has been removed and container_drop_infra_ctr has been defaulted to true.
The set of tests in drop_infra.bats should be reworked to do the following:

1. take the defaults (drop_infra_ctr is true) and verify that runc list does not show the infrastructure container and that crictl inspectp does not see the pid of the infrastructure container
2. start crio specifying drop_infr_ctr = false and verify that runc list shows the infrastructure container and that crictl inspectp sees the pid for the infrastructure container

There is no need to setup the tests with the following:
CONTAINER_MANAGE_NS_LIFECYCLE=true CONTAINER_DROP_INFRA_CTR=true start_crio

### PR DESCRIPTION
**Pull request by furman-d1**
#### What type of PR is this?

/kind other
#### What this PR does / why we need it:
As of cri-o release 1.23 container_manage_ns_lifecycle was removed and container_drop_infra_ctr has been defaulted to true.
This PR request is to remove CONTAINER_MANAGE_NS_LIFECYCLE=true CONTAINER_DROP_INFRA_CTR=true from the setup() function.
#### Which issue(s) this PR fixes:

Fixes #5860
#### Special notes for your reviewer:
I also removed the TODO section in the setup() function since container_manage_ns_lifecycle was removed. The test seemed to work when run this way, but I wasn't sure what this was actually skipping, so please review this change to see if it was necessary.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by furman-d1** [comment]
I don't understand why the dco is missing.  I added the Signed-off-by text in the commit.  If someone would please let me know wh
at I am missing, I'd appreciate it. Thank you.  (this is the first time I'm contributing and I thought I read through the instructions)

**Comment by haircommander** [comment]
> I don't understand why the dco is missing. I added the Signed-off-by text in the commit. If someone would please let me know what I am missing, I'd appreciate it. Thank you. (this is the first time I'm contributing and I thought I read through the instructions)

I think it needs to be on a newline, like:
```
update setup() to remove container_manage_ns_lifecycle and container_drop_infra_ctr.

Signed-off-by: Debbie Furman <debbyt@us.ibm.com>
```

thanks @furman-d1 !
/ok-to-test
/approve

**Comment by saschagrunert** [comment]
A friendly reminder that this PR had no activity for 30 days.

**Comment by furman-d1** [comment]
@haircommander I did a `git commit --amend` and put my dco on a separate line.  Then, I did a git push.  Looks like it created a separate commit, but didn't update the first commit with the correct dco.  I'm struggling with git and don't know how to update the first commit to put the dco on its own separate line.  Any ideas?

**Comment by furman-d1** [comment]
Okay.  this is becoming a class on how to use git. 
Apparently my upstream is not set correctly. 
When I issued `git rebase -i upstream/main`  I get the following error
`fatal: invalid upstream 'upstream/main'`
I'm assuming I need to have upstream set to my fork of the repository?
What git command do I use to set upstream to https://github.com/furman-d1/cri-o (which is the name of my fork). 

I appreciate you help with this.

**Comment by furman-d1** [comment]
Now, I can't seem to get authenticated to git@github.com.  When trying to issue the fetch upstream I am getting the following error: 
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

I had authenticated for the push by using the `gh auth login` and then authenticating by login with a web browser.  I have no idea if I set up public/private keys.

**Comment by furman-d1** [comment]
I apologize for being such a pain, but I'm still having trouble with the steps you provided.
I issued the following:  `git rebase -i HEAD~3`  I updated the rebase screen as instructed and received message   
```
error: cannot 'squash' without a previous commit  
You can fix this with 'git rebase --edit-todo' and then run 'git rebase --continue'.  
Or you can abort the rebase with 'git rebase --abort'.    
``` 

I then issued `git rebase --edit-todo` and received message
`error: cannot 'squash' without a previous commit 
`
I then issued `git rebase --continue` and received message
`Successfully rebased and updated refs/heads/main. `

I then isssued `git commit` and received messages
`On branch main nothing to commit, working tree clean`

So, I never got a commit screen to update the sign off on a separate line. (sigh)

**Comment by haircommander** [comment]
Imagine the rebase screen looks like:
```
pick 03df96267 server: take container server Stop method
pick 68d7e736a container_server: drop StopContainerAndWait
pick 696b6b27b oci: unconditionally set as not stopping after a stop stops stopping
```

What I'm suggesting your screen should look like is

```
r 03df96267 server: take container server Stop method
s 68d7e736a container_server: drop StopContainerAndWait
s 696b6b27b oci: unconditionally set as not stopping after a stop stops stopping
```
so the bottom two commits squash into the top, and the top one is renamed

Then in the rename screen, you can edit the signature

**Comment by furman-d1** [comment]
Whew! Finally got the DCO sign-off correct.  Thanks for all the git educational help!

**Comment by furman-d1** [comment]
ugh.  I tried to do the rebase but never got the chance to add comment to the commit (ie. the dco statement).  So am back to square one where the rebased commit doesn't have the dco statement.  I'm at a loss on how to wrangle git.  Should I just remove this fork, start from scratch (create another fork, add my 1 change with the correct commit comment with dco statement, then ask for re-review?)

**Pull request closed without merging**
