### PR TITLE
bump c/image from v5.10.5 to v5.11.0

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### What type of PR is this?

> /kind feature

#### What this PR does / why we need it:

c/image v5.11.0 includes support for subdomain matching in registries.conf and policy.json

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
```

### CODE REVIEW

**Comment by lsm5** [comment]
@umohnani8 PTAL and let me know what kind of info is relevant for release-note etc. on the cri-o side.

**Comment by haircommander** [comment]
what go version did you use? something's funky with the vendor...

/ok-to-test

**Comment by lsm5** [comment]
> what go version did you use? something's funky with the vendor...

```
$ go version
go version go1.16 linux/amd64

$ rpm -q golang
golang-1.16-2.fc34.x86_64
```

**Comment by haircommander** [comment]
hm, can you run
`make vendor`
again? the tree is dirty when run in gh actions

**Comment by lsm5** [comment]
> hm, can you run
> `make vendor`
> again? the tree is dirty when run in gh actions

ah ok. So far I just tried: 
```
go mod tidy
go mod vendor
```

Let me try make vendor.

**Comment by lsm5** [comment]
well, `make vendor` gives me an empty diff. So, nothing else to push from my side :|

**Comment by lsm5** [comment]
should i try an older golang ? maybe fedora 33?

**Comment by saschagrunert** [comment]
Hey, this may be a duplicate of https://github.com/cri-o/cri-o/pull/4746. Please feel free to close one if them in favor of the other.

**Comment by lsm5** [comment]
@saschagrunert awesome. thanks a lot!

**Pull request closed without merging**
