### PR TITLE
vendor: bump containers/storage to v1.24.0

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This is mostly to have https://github.com/containers/storage/pull/757
which should fix occasional CI failures (and probably real failures, too).

#### Which issue(s) this PR fixes:

> time="2020-11-02T19:00:03Z" level=fatal msg="creating container: rpc error: code = Unknown desc = error creating an ID-mapped copy of layer "01d6f430ddfdf1203b505fbb03c6479802a3366609d5e0231a30f85f412f873d": exit status 1: error during chown: storage-chown-by-maps: chown("lib/apk/db/scripts.tar"): lchown lib/apk/db/scripts.tar: interrupted system call"

periodically caught by CI

#### Special notes for your reviewer:

This is currently blocked by https://github.com/cri-o/cri-o/pull/4371

Backports:

- 1.20: no need
- 1.19: #4340
- 1.18: #4341

#### Does this PR introduce a user-facing change?

```release-note
Fix occasional "chown: interrupted system call" error on container creation.
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by kolyshkin** [comment]
Backports:
* 1.20: no need
* 1.19: #4337 (need to fix containers/storage version to 1.12.x once released)

**Comment by kolyshkin** [comment]
Summarizing 3 Failures:

[Fail] [k8s.io] AppArmor runtime should support apparmor [It] should enforce a permissive profile 
/home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/apparmor_linux.go:143

[Fail] [k8s.io] AppArmor runtime should support apparmor [It] should enforce a permissive profile 
/home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/apparmor_linux.go:143

[Fail] [k8s.io] AppArmor runtime should support apparmor [It] should enforce a permissive profile 
/home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/apparmor_linux.go:143

I have audited the logs (https://circleci.com/api/v1.1/project/github/cri-o/cri-o/105877/output/107/0?file=true&allocation-id=5fa1278c1be5695c9ebd99d7-0-build%2F7DFD59DA) but it's not clear what happened (other than the `touch foo` returned 1 while it is expected to return 0).

**Comment by kolyshkin** [comment]
rebased on top of current master; maybe this will help ci :-\

**Comment by kolyshkin** [comment]
Updated to 1.23.9

**Comment by kolyshkin** [comment]
critest failure:

```
• Failure [2.711 seconds]
[k8s.io] AppArmor
/home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:72
  runtime should support apparmor
  /home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/apparmor_linux.go:69
    should enforce a permissive profile [It]
    /home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/apparmor_linux.go:96

    Expected
        <int32>: 1
    to equal
        <int32>: 0

....

Ran 76 of 83 Specs in 71.642 seconds
FAIL! -- 75 Passed | 1 Failed | 0 Flaked | 0 Pending | 7 Skipped
```

**Comment by kolyshkin** [comment]
Same apparmor failure as earlier. Most probably caused by https://github.com/containers/storage/pull/743 as we touch the file in the root directory. The fix (in critest) is easy but I'm not sure the new default won't bring any other breakage.

**Comment by saschagrunert** [comment]
> Same apparmor failure as earlier. Most probably caused by [containers/storage#743](https://github.com/containers/storage/pull/743) as we touch the file in the root directory. The fix (in critest) is easy but I'm not sure the new default won't bring any other breakage.

I have the same issue in this PR: https://github.com/cri-o/cri-o/pull/4358

**Comment by kolyshkin** [comment]
> I have the same issue in this PR: #4358

All new PR

**Comment by kolyshkin** [comment]
closed by mistake

**Comment by kolyshkin** [comment]
> I have the same issue in this PR: #4358

@saschagrunert this is probably because your PR also bumps containers/storage to 1.23.10-dev-something, which includes https://github.com/containers/storage/pull/743. Let's see if https://github.com/kubernetes-sigs/cri-tools/pull/682 helps (testing via https://github.com/cri-o/cri-o/pull/4366)

**Comment by kolyshkin** [comment]
OK, due to containers/storage#743 this needs https://github.com/kubernetes-sigs/cri-tools/pull/682 and a new critools release.

**Comment by saschagrunert** [comment]
> OK, due to [containers/storage#743](https://github.com/containers/storage/pull/743) this needs [kubernetes-sigs/cri-tools#682](https://github.com/kubernetes-sigs/cri-tools/pull/682) and a new critools release.

Hm, but isn't this a regression in containers/storage? My plan was to cut a new cri-tools release with k8s 1.20.0 but now this seems kind of urgent. :-/

**Comment by kolyshkin** [comment]
> Hm, but isn't this a regression in containers/storage?

It's hard to say whether it's a regression or not. Looks more like a fortifying measure.

> My plan was to cut a new cri-tools release with k8s 1.20.0 but now this seems kind of urgent. :-/

Alternatively, we can use critools master as I did in https://github.com/cri-o/cri-o/pull/4366. One side benefit is we'll be able to catch bugs like https://github.com/kubernetes-sigs/cri-tools/pull/683 earlier.

@mrunalp @haircommander @saschagrunert WDYT?

**Comment by kolyshkin** [comment]
> Alternatively, we can use critools master as I did in #4366. One side benefit is we'll be able to catch bugs like [kubernetes-sigs/cri-tools#683](https://github.com/kubernetes-sigs/cri-tools/pull/683) earlier.

See https://github.com/cri-o/cri-o/pull/4371

**Comment by saschagrunert** [comment]
> Alternatively, we can use critools master as I did in #4366. One side benefit is we'll be able to catch bugs like [kubernetes-sigs/cri-tools#683](https://github.com/kubernetes-sigs/cri-tools/pull/683) earlier.

I'm in favor of switching to the master for now. I will cut a new cri-tools release together with Kubernetes v1.20.0 in any case.

**Comment by kolyshkin** [comment]
Rebased on top of recently merged https://github.com/cri-o/cri-o/pull/4371 to fix critest woes.

Assuming the CI is green (except e2e-aws which is broken globally atm), this one should be good to go.

**Comment by kolyshkin** [comment]
failure in e2e_rhel (`[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container`) is known (https://github.com/kubernetes/kubernetes/issues/96565)

**Pull request merged**
