### PR TITLE
do not wipe images by default

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
many users don't want the crio wipe functionality that removes images on reboot. Update internal wipe to not do so by default
#### Does this PR introduce a user-facing change?

```release-note
Update `version-file-persist` to be empty by default, and do not wipe images when it is so.
```

### CODE REVIEW

**Comment by haircommander** [comment]
fixes https://github.com/cri-o/cri-o/issues/5352

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
