### PR TITLE
OCPNODE-1286: Add a CI job to run cri-o e2e tests by enabling the evented pleg feature

### PR DESCRIPTION
**Pull request by sairameshv**
#### What type of PR is this?

/kind ci
#### What this PR does / why we need it:
This PR enables a new ci job to run e2e tests with the evented pleg feature enabled both in the kubelet and the cri-o configurations
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
Linked PR in the `openshift/release` repository
https://github.com/openshift/release/pull/39629 
#### Does this PR introduce a user-facing change?
No

```release-note
`None`
```

### CODE REVIEW

**Comment by sairameshv** [comment]
/cc @sohankunkerkar @saschagrunert @harche 
Could you PTAL?

Thanks

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
