### PR TITLE
nri: enable otel tracing

### PR DESCRIPTION
**Pull request by klihub**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

This PR updates our NRI dependency enabling OpenTelemetry trace context propagation over ttrpc connections. Additionally the PR also enables automatic OpenTelemetry instrumentation of NRI ttrpc calls when tracing is globally enabled in cri-o.  

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

`None`

```release-note
- Enable automatic OpenTelemetry instrumentation of ttrpc calls to NRI plugins when tracing is globally enabled in cri-o.
- Bumping our NRI deps also fixes a bug where starting a cri-o launched NRI plugin could cause the accidental closing of an unrelated fd (socket, file, etc.) due to an fd double-close bug.
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thank you! Code LGTM

**Comment by klihub** [comment]
> Thank you! Code LGTM

@saschagrunert ttrpc got tagged a new version. Updated deps to point the latest tag. That cost me your earlier lgtm.

**Comment by kwilczynski** [comment]
> > Thank you! Code LGTM
> 
> @saschagrunert ttrpc got tagged a new version. Updated deps to point the latest tag. That cost me your earlier lgtm.

@klihub, might be a silly question, but... can we use the normal OTEL package we already have? Or does it have to be `ttrpc` explicitly (e.g., no way to adapt the other one in any way, etc.)?

**Comment by kwilczynski** [comment]
[...]
> > @klihub, might be a silly question, but... can we use the normal OTEL package we already have? Or does it have to be `ttrpc` explicitly (e.g., no way to adapt the other one in any way, etc.)?
> 
> otelttrpc tries to be for ttrpc what otelgrpc is for grpc. Currently it implements instrumenting unary client and server interceptors which enable 2 things:

Makes sense. Since NRI uses ttrpc as its protocol of choice. Thank you!

**Comment by kwilczynski** [comment]
@klihub, sorry to appear out of the blue on this closed Pull Request, but I have a question.

The [containerd/otelttrpc](https://github.com/containerd/otelttrpc) package, which we now use, seems to be causing some build issues when we build CRI-O binary packages (RPMs) for use in OpenShift per:

```console
_output/src/github.com/cri-o/cri-o/vendor/github.com/containerd/otelttrpc/interceptor.go:50:2: code in directory /builddir/build/BUILD/cri-o-4fa897e3b639c3bf19ad0152f2429162548e5698/_output/src/github.com/cri-o/cri-o/vendor/github.com/containerd/otelttrpc/internal expects import "github.com/containerd/ttrpc/otelttrpc"
```

This seems to be due to the "import path checking" feature you are using there.

Just wondering, do you think this is something that you need to leverage in this specific package?

**Comment by klihub** [comment]
@kwilczynski Filed here: https://github.com/containerd/otelttrpc/pull/1. Once that gets merged, I'll file corresponding PRs to update the cri-o otelttrpc dependency

**Pull request merged**
