### PR TITLE
OWNERS: add myself

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

I have no idea :-0

#### What this PR does / why we need it:

Add myself (@kolyshkin) to OWNERS file.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM, welcome!

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by haircommander** [comment]
/approve

:tada:

**Pull request merged**
