### PR TITLE
[1.14] Vendor in containers/storage release-1.13

### PR DESCRIPTION
**Pull request by umohnani8**
Vendor in changes from containers/storage to recreate symlinks
in overlay/l when they are not found.
Had to revert https://github.com/cri-o/cri-o/commit/1c8170a285f64fc89c38f37be27ba9ab7f038d94 to be able to vendor in c/storage release-1.13.
Once we figure out the c/storage issue we should revert this revert.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, but e2e_rhel test doesn't look hip.

**Comment by saschagrunert** [comment]
Please regnerate the mocks via `make mockgen`

**Comment by umohnani8** [comment]
Tests are green. @mrunalp @rhatdan PTAL

**Comment by mrunalp** [comment]
Is this getting in the same code as in `release-1.13`?

**Comment by umohnani8** [comment]
@mrunalp nope, this is ahead than release-1.13. Should it be the same?

**Comment by mrunalp** [comment]
@umohnani8 Anything ahead than release-1.13 is known to fail on a cluster. So, it should be the same unless we know that we have fixed the issue in newer versions.

**Comment by umohnani8** [comment]
@mrunalp 1.14 is currently on v1.12.1 of c/storage, which is already ahead of what is being used in 1.13. Using the release-1.13 branch from c/storage for cri-o 1.14 would mean going back in the c/storage vendored version, is that fine?

**Comment by mrunalp** [comment]
@umohnani8 Yes, we should use the same version that we have in `release-1.13`.

**Comment by umohnani8** [comment]
Correct version of c/storage is being vendored in now. @mrunalp @rhatdan @vrothberg @haircommander PTAL

**Comment by haircommander** [comment]
LGTM, is there a reason we are also tagging 1.14.2 so quickly?

**Comment by rhatdan** [comment]
LGTM.
@umohnani8 In latest containers/storage do we still have the issue?

**Comment by nalind** [comment]
I'm pretty sure that was fixed in https://github.com/containers/storage/pull/342.

**Comment by mrunalp** [comment]
@nalind Does that fix the layer size not known and image not found issues we hit in OpenShift?

**Comment by nalind** [comment]
It _should_, I think.

**Comment by umohnani8** [comment]
@haircommander yeah, figured we should tag it and create a build before we start getting pinged on the same issue.
@rhatdan yeah as of about 1.5 weeks ago we were seeing the c/storage issue.

**Comment by mrunalp** [comment]
I will merge after #2409 is merged.

**Comment by umohnani8** [comment]
@mrunalp @rhatdan #2409 is in, can we get this merged as well.

**Pull request merged**
