### PR TITLE
runtime_vm: set container creation time

### PR DESCRIPTION
**Pull request by snir911**
If not set it may result in silently ignored probes by the kubelet

Fixes: https://github.com/kata-containers/runtime/issues/2769
Signed-off-by: Snir Sheriber <snir911@gmail.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fixes: https://github.com/kata-containers/runtime/issues/2769

#### Which issue(s) this PR fixes:

Fixes: https://github.com/kata-containers/runtime/issues/2769

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by haircommander** [comment]
nice, thanks @snir911 

/retest
/lgtm

**Comment by umohnani8** [comment]
LGTM
/retest

**Pull request merged**
