### PR TITLE
Remove unused containerd release-tool

### PR DESCRIPTION
**Pull request by saschagrunert**
We're not using this tool anymore so we can remove it, right? :innocent:

### CODE REVIEW

**Comment by haircommander** [comment]
I do use it to draft the releases, but we can just rely on it being out of tree

**Comment by saschagrunert** [comment]
> I do use it to draft the releases, but we can just rely on it being out of tree

Hm, do you use the version in this repo? Is there another script invocation somewhere? :eyes:

**Comment by haircommander** [comment]
I use the latest after at least https://github.com/containerd/release-tool/commit/234eed92eab8c824a2b83c823ac2eef23db44b0b so we can use go modules in 1.14+

**Comment by saschagrunert** [comment]
Okay, so closing this now. :+1:

**Pull request closed without merging**
