### PR TITLE
[1.14] Backport empty CircleCI config

### PR DESCRIPTION
**Pull request by saschagrunert**
We now add a stub that CircleCi does not complain any more.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@umohnani8 @vrothberg @haircommander @mrunalp PTAL

**Comment by haircommander** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM

**Comment by haircommander** [comment]
once https://github.com/cri-o/cri-o/pull/2526 lands I'll probably manually merge this to get https://github.com/cri-o/cri-o/pull/2477 and https://github.com/cri-o/cri-o/pull/2532 in to finally cut 1.14.5

**Comment by rhatdan** [comment]
Manually merging, now that circle CI Passed.

**Pull request merged**
