### PR TITLE
[1.13] Bump version to 1.13.12

### PR DESCRIPTION
**Pull request by umohnani8**
Bump up version to 1.13.12 for a new release.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@haircommander @vrothberg PTAL

**Comment by umohnani8** [comment]
@mrunalp can you approve please

**Comment by haircommander** [comment]
/hold

https://github.com/cri-o/cri-o/pull/3211 didn't actually make it in

**Pull request merged**
