### PR TITLE
[1.14] Add global_auth_file option to crio.image config

### PR DESCRIPTION
**Pull request by mtrmac**
> Add a global_auth_file option under crio.image to the crio config. This option points to a json file that holds the credentials required to pull images from a secure registry. The json file is similar to that of .docker/config.json.
>
> Will forward-port to master as well.

This starts with #2498, and:
- removes some dead code
- fixes the case when the CRI client provides credentials (for the primary registry)
- adds use of `globalAuthFile` for the pause image if no specific credentials are provided

This is a functionally minimal set of changes that reflect how the API is probably _intended_ to be used, but not quite exhaustive for how it _could_ be used (e.g. it seems that calling CRI `ImageStatus` with a `docker://example.com/foo:tar` image name would actually try to contact the remote registry!). I do plan to clean all of this up / make it explicit, but that will be a separate `master`-only PR.

### CODE REVIEW

**Comment by mrunalp** [comment]
@vrothberg ptal

**Comment by mtrmac** [comment]
`master` version: #2510.

**Comment by mtrmac** [comment]
> `master` version: #2510.

Oops, #2511.

**Comment by vrothberg** [comment]
@umohnani8 @mrunalp @saschagrunert PTAL

**Comment by haircommander** [comment]
@mtrmac changes LGTM, but just to make sure-if this member is absent from the crio.conf, does CRI-O behave as expected? We need to make sure upgrades using an old crio.conf allow CRI-O to boot up.

**Comment by TomSweeneyRedHat** [comment]
Nothing over the other comments.  Otherwise LGTM

**Comment by umohnani8** [comment]
LGTM
@haircommander yeah it should be fine if this option is missing from crio.conf. We are not failing if value for this option is empty, in fact by default it is going to be empty n cri-o. MCO is the one that will be setting it.

**Comment by mrunalp** [comment]
@saschagrunert We can have a follow-on PR for the flag.

**Comment by saschagrunert** [comment]
Yes. :) no worries about that.

**Pull request merged**
