### PR TITLE
Bump test images to go1.15

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind dependency-change

#### What this PR does / why we need it:
This also updates some of the dependencies and adapts the CI to use the
new images.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the tests are happy

**Comment by saschagrunert** [comment]
/retest
Almost. :)

**Comment by umohnani8** [comment]
LGTM
/retest

**Pull request merged**
