### PR TITLE
Add `--metrics-socket`/`metrics_socket` config option

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This allows users to retrieve CRI-O metrics in containers via a simple
host path binding to the metrics socket without having the need to rely
on host networks.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
- Added `--metrics-socket`/`metrics_socket` configuration option to allow exposing the metrics endpoint on a local socket path
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM but cgroupsv2 testing is still upset

**Comment by haircommander** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Happy green test buttons.

**Pull request merged**
