### PR TITLE
Add CodeQL Github actions

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Add standard CodeQL Github actions with autobuild.

#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
CodeQL is a static analysis tool and we need it because it can help find bugs. CodeQL is an official Github product: https://github.com/github/codeql-action

#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?
No, unless the CI is considered a user-facing change, am not sure? 

```release-note
none
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
but this is a bit out of my wheelhouse
@cevich, do you have experience with CodeQL GitHub actions?

**Comment by haircommander** [comment]
/ok-to-test
/approve
/release-note none

thanks @DavidKorczynski LGTM

**Comment by haircommander** [comment]
/lgtm

we can follow up with fixing these issues

**Comment by DavidKorczynski** [comment]
> we can follow up with fixing these issues

Sounds good. For reference, these issues were publicly available before (https://lgtm.com/projects/g/cri-o/cri-o/?mode=list) and we also discussed these issues at our internal meeting before making the commit.

**Pull request merged**
