### PR TITLE
[1.17] bump to 1.17.2

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
bumps to 1.17.2
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by tanweernoor** [comment]
@mrunalp can someone review/ merge this please ?

**Comment by haircommander** [comment]
> LGTM, but why do we have only 1 commit and not 2 as usual?

we dropped the `-dev` idiom a bit ago. It's because we're releasing into openshift automatically and directly on release branches, and `-dev` would end up in downstream consumers rpm queries

**Comment by haircommander** [comment]
PTAL @umohnani8 @mrunalp

**Pull request merged**
