### PR TITLE
[1.18] runtimeVM backports to release-1.18 branch

### PR DESCRIPTION
**Pull request by fidencio**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This is the backport of a bunch of PRs touching the runtimeVM, which would be really good to have them as part of 1.18 stable branch.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by fidencio** [comment]
@haircommander, @mrunalp, @umohnani8, please, take a look.

**Comment by haircommander** [comment]
LGTM
/approve

**Comment by haircommander** [comment]
PTAL @umohnani8 @saschagrunert @mrunalp @giuseppe

**Pull request merged**
