### PR TITLE
[1.14] Update github.com/containers/* dependencies

### PR DESCRIPTION
**Pull request by saschagrunert**
This PR is the backport of #2195

### CODE REVIEW

**Comment by haircommander** [comment]
@saschagrunert please rebase to pick up CI fixes :)

**Comment by saschagrunert** [comment]
Alright, I rebased on top of the latest release-1.14 branch.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Pull request merged**
