### PR TITLE
[1.20] Point to k8s release-1.20 branch for tests

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

#### What type of PR is this?

/kind other

#### What this PR does / why we need it:
Pinning the tests to k8s release-1.20 branch

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by umohnani8** [comment]
@mrunalp @haircommander PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM
/retest

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
