### PR TITLE
openshift e2e: bump ci image

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Which issue(s) this PR fixes:

/kind ci

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
```
task path: /go/src/github.com/cri-o/cri-o/contrib/test/integration/build/runc.yml:9
redirecting (type: modules) ansible.builtin.make to community.general.make
changed: [localhost] => {"changed": true, "chdir": "/go/src/github.com/opencontainers/runc", "file": null, "params": {"BUILDTAGS": "seccomp selinux"}, "stderr": "", "stderr_lines": [], "stdout": "go build -trimpath \"-mod=vendor\" \"-buildmode=pie\"  -tags \"seccomp selinux\" -ldflags \"-X main.gitCommit=\"06c1cd8896a910bc5cf4f86623dd85a9f9a558e0\" -X main.version=1.0.0-rc93+dev \" -o runc .", "stdout_lines": ["go build -trimpath \"-mod=vendor\" \"-buildmode=pie\"  -tags \"seccomp selinux\" -ldflags \"-X main.gitCommit=\"06c1cd8896a910bc5cf4f86623dd85a9f9a558e0\" -X main.version=1.0.0-rc93+dev \" -o runc ."], "target": null}
```

I guess HEAD didn't correspond to main? lets see if that helps

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
