### PR TITLE
Create PID file at startup

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Create a PID file at CRI-O's startup.

There are cases where it'd be useful to write a PID file when CRI-O starts up. Specifically, a PID file is a good way to for cadvisor to track usage in the crio cgroup in a way that's agnostic of systemd.

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
CRI-O now writes its PID to a file at startup. The location can be configured with config value pid_path, or CLI value --pid-path```

### CODE REVIEW

**Comment by haircommander** [comment]
PTAL @joelsmith

Would you be against using /var/run/crio/pid instead of /var/run/crio.pid? the former is more in line with how we format other files

**Comment by mrunalp** [comment]
Can you check if using systemd `PIDFile=` makes sense to use with this?

**Comment by haircommander** [comment]
> Can you check if using systemd `PIDFile=` makes sense to use with this?

I'd rather use a solution that doesn't rely on systemd if we don't have to

**Comment by joelsmith** [comment]
Looks good. I'm waiting for a review on https://github.com/kubernetes/kubernetes/pull/88823 so it's good that this is done. Thanks!

**Comment by haircommander** [comment]
closing as the kube PR is not needed

**Pull request closed without merging**
