### PR TITLE
Bumps github.com/containers/ocicrypt from 1.0.3 to 1.1.0.

### PR DESCRIPTION
**Pull request by pravinrajr9**
Bumps [github.com/containers/ocicrypt](https://github.com/containers/ocicrypt) from 1.0.3 to 1.1.0.

Release notes
_Sourced from [github.com/containers/ocicrypt's releases](https://github.com/containers/ocicrypt/releases)._
> ## ocicrypt 1.1.0
> # Ocicrypt Release 1.1.0
```release-note
This new release of ocicrypt contains new usable interfaces and thus is a new minor number. This issue details the notable features added as well as a checklist before making a new release that will be used by consuming projects. Target date for completion is 24th January.

Changes
There are several significant changes in release 1.1.0, this includes:
    * Experimental PKCS11 support enabled via ENV variable
    * Custom keyprovider support enabled via ENV variable
```
 Commits
 * [`059f6b1`](https://github.com/containers/ocicrypt/commit/059f6b1c0b8dc88d452fff7bcfa2adf323c26c3b) docs: Modify link to sample golang application
 * [`641905b`](https://github.com/containers/ocicrypt/commit/641905bdc4bf24e75a5fe3f6f5d0cbd58ee8f20a) docs: Fix link to example pkcs11 config file and show example at link
 * [`15699c8`](https://github.com/containers/ocicrypt/commit/15699c8b16dcafadc311319227848105462ddb8b) helpers: Modify parsing of private keys for key provider protocol
 * [`ca1ce75`](https://github.com/containers/ocicrypt/commit/ca1ce75ef801a2c74a918428567ba3faf4a4b97c) docs: Fix JSON path to executable
 * [`a8080c6`](https://github.com/containers/ocicrypt/commit/a8080c6c34bf48726416895fb42501231e4fea51) helpers: Fix bug skipping over pkcs11 public keys
 * [`6677ff6`](https://github.com/containers/ocicrypt/commit/6677ff674fff7fe27926871eba872e22d155db97) pkcs11: Move pkcs11 experimental stage to a print statement
 * [`206c356`](https://github.com/containers/ocicrypt/commit/206c3563d006a5f3d270df46b0d9a3d283851ccf) pkcs11: Write version identifier into JSON holding encrypted blobs
 * [`867e064`](https://github.com/containers/ocicrypt/commit/867e0648375e1490f30f41220a25b2e31e4a8710) modules: Update go modules to latest version
 * [`f19091c`](https://github.com/containers/ocicrypt/commit/f19091c230ae51cea3f0f5c7084c2de352ac1006) pkcs11: PCT-encode the keyid when displaying in error message
 * [`cabb320`](https://github.com/containers/ocicrypt/commit/cabb320230fabd790dd24c5ff66ce9bff5f6f87a) Implemented custom provider for keywrap through env config
 * Additional commits viewable in [compare view](https://github.com/containers/ocicrypt/compare/v1.0.3...v1.1.0)

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/ok-to-test
/release-note-none
LGTM

**Comment by saschagrunert** [comment]
@pravinrajr9 thank you for the PR! Can you please sign-off your commit via `git commit --amend --no-edit -s` and force-push again?

**Comment by lumjjb** [comment]
@saschagrunert the commits should be all updated now! I see a couple errors on some e2e tests, are these known issues? 

```
Already on 'master'
Your branch is up to date with 'origin/master'.
+ git branch -D target
error: branch 'target' not found.
+ true
+ git branch -D pr
error: branch 'pr' not found.
```

**Comment by pravinrajr9** [comment]
> @pravinrajr9: The following tests **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> ci/prow/e2e-agnostic	[b5b9b70](https://github.com/cri-o/cri-o/commit/b5b9b7002ac27da8e9ce9b769c50c3f645db4052)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/4537/pull-ci-cri-o-cri-o-master-e2e-agnostic/1361318747746340864)	`/test e2e-agnostic`
> ci/prow/e2e-gcp	[b5b9b70](https://github.com/cri-o/cri-o/commit/b5b9b7002ac27da8e9ce9b769c50c3f645db4052)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/4537/pull-ci-cri-o-cri-o-master-e2e-gcp/1361318747779895296)	`/test e2e-gcp`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=cri-o&repo=cri-o&pr=4537). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:pravinrajr9).
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

Are these known issues?

**Comment by lumjjb** [comment]
@haircommander Is it possible to merge this PR? Looks like the working CI tests are all good.

**Comment by haircommander** [comment]
/lgtm

thanks @lumjjb !

**Comment by lumjjb** [comment]
Thanks @haircommander ! :D

**Pull request merged**
