### PR TITLE
Bump kubernetes to v1.18.0-beta.0

### PR DESCRIPTION
**Pull request by saschagrunert**
This updates Kubernetes to the latest beta version.

### CODE REVIEW

**Comment by saschagrunert** [comment]
It does not build with go1.10 any more. I'm now investigating what we can do on our side.

**Comment by saschagrunert** [comment]
Fix is incoming in https://github.com/kubernetes-sigs/structured-merge-diff/pull/157

**Comment by rhatdan** [comment]
@saschagrunert Any update on this?

**Comment by saschagrunert** [comment]
> @saschagrunert Any update on this?

Unfortunately not. We could decide to drop support for go 1.10 (1.14 seems right around the corner). WDYT?

**Comment by rhatdan** [comment]
Yes drop support for go 1.10.  I would drop it up to 1.12.  Only issue would be on back ports.

**Comment by rhatdan** [comment]
@mrunalp Do you agree?

**Comment by mrunalp** [comment]
Yes, dropping 1.10 sounds good :+1:

**Comment by umohnani8** [comment]
#3312 merged, please rebase

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch and bumped k8s to v1.18.0-beta.0

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons

**Pull request merged**
