### PR TITLE
contrib/test/ci: fix SELinux permission issue on RHEL9

### PR DESCRIPTION
**Pull request by sohankunkerkar**
A few CI tests were failing on RHEL9 due to the SELinux permission issue where the boolean `container_manage_cgroup` variable was not populating the right value. Somehow that boolean variable is getting dropped and the value is always set to true. So avoid setting the value when the distribution is RHEL.

#### What type of PR is this?

/kind failing-test

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
```
STDOUT:

Downloading https://storage.googleapis.com/crio-ci/etcd-v3.5.6.tar.gz failed. 4 retries left.
Downloading https://storage.googleapis.com/crio-ci/etcd-v3.5.6.tar.gz failed. 3 retries left.
Downloading https://storage.googleapis.com/crio-ci/etcd-v3.5.6.tar.gz failed. 2 retries left.
Downloading https://storage.googleapis.com/crio-ci/etcd-v3.5.6.tar.gz failed. 1 retries left.
Downloading https://storage.googleapis.com/crio-ci/etcd-v3.5.6.tar.gz failed. 0 retries left.


STDERR:

curl: (22) The requested URL returned error: 404
curl: (22) The requested URL returned error: 404
curl: (22) The requested URL returned error: 404
curl: (22) The requested URL returned error: 404
curl: (22) The requested URL returned error: 404
!!! [1127 14:25:35] Call tree:
!!! [1127 14:25:35]  1: hack/install-etcd.sh:28 kube::etcd::install(...)
!!! [1127 14:25:35] Call tree:
!!! [1127 14:25:35]  1: hack/install-etcd.sh:28 kube::etcd::install(...)
```

**Comment by sohankunkerkar** [comment]
hmm... that tar file is missing from the `crio-ci` bucket

**Comment by sohankunkerkar** [comment]
gated on https://github.com/openshift/release/pull/34347

**Comment by sohankunkerkar** [comment]
This PR should get merged in tandem with https://github.com/openshift/release/pull/34425

**Comment by haircommander** [comment]
@sohankunkerkar are we able to merge this first and then that if the rehearsal passes?

**Pull request merged**
