### PR TITLE
[release-1.26] OCPBUGS-30656: Add exponential backoff to the container stop loop

### PR DESCRIPTION
**Pull request by kwilczynski**
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7854

/assign kwilczynski

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/hold 

for some soak time on newer versions

**Comment by kwilczynski** [comment]
@cri-o/cri-o-maintainers, this is good to go, I believe.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
