### PR TITLE
[1.17] vendor github.com/containers/image/v5@v5.3.0

### PR DESCRIPTION
**Pull request by vrothberg**
* Fixed registries.conf
* Add Code of Conduct
* Bubbling up errors returned by copyBlobFromStream
* Re-order the members of archiveReference to a more logical orde
* Add docker/archive.NewReference
* Remove tarballReference.transport
* Add tarball.NewReference
* Add storage.Transport.GetStoreIfSet
* Simplify ID value check
* Add validateImageID
* Add storage.Transport.NewStoreReference
* registries.conf.d: add stances for the registries.conf
* Add $HOME/.config/containers/registries.conf to config path
* sysregistriesv2: drop "rewrite" debug messages
* Add $HOME/.config/containers/certs.d to perHostCertDirPath
* Intial authfile man page
* Return error when acquire semaphore lock gets error
* feat(docker): support docker registry token
* containers-registries.conf.d: refine semantics
* Updated warning about short names.
* Make UpdatedImage update after conversion of MIME type
* Support IdentityToken in registry authn
* Deprecate SupportsEncryption call in manifest interface
* oci manifest: do not require whitelist of layer types
* Fix crash on missing RootFS in docker/tarfile configs
* copy: try list conversions on list push failures
* Support architecture variants for multi-arch images and runtime
  compatibility checks

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Update c/image to the latest release, mainly to pull in the registries.conf.d support for OpenShift.

#### Does this PR introduce a user-facing change?

```release-note
Added support for drop-in registries.conf configuration files. Please refer to the registries.conf.d documentation (https://github.com/containers/image/blob/master/docs/containers-registries.conf.d.5.md) for further details.
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM once the tests are happy.

**Comment by vrothberg** [comment]
@haircommander @saschagrunert, I need some guidance on the docs failure. Can you reproduce? I see two files changing locally:
```
 modified:   docs/crio-status.8.md
 modified:   docs/crio.8.md
```

**Comment by saschagrunert** [comment]
> @haircommander @saschagrunert, I need some guidance on the docs failure. Can you reproduce? I see two files changing locally:
> 
> ```
>  modified:   docs/crio-status.8.md
>  modified:   docs/crio.8.md
> ```

This has been introduced some PRs ago, I'm checking how to fix that.

**Comment by vrothberg** [comment]
> > @haircommander @saschagrunert, I need some guidance on the docs failure. Can you reproduce? I see two files changing locally:
> > ```
> >  modified:   docs/crio-status.8.md
> >  modified:   docs/crio.8.md
> > ```
> 
> This has been introduced some PRs ago, I'm checking how to fix that.

Awesome, thanks a ton, @saschagrunert !

**Comment by saschagrunert** [comment]
See https://github.com/cri-o/cri-o/pull/3448

**Comment by vrothberg** [comment]
Ready to merge, @haircommander :)

**Comment by haircommander** [comment]
I am tempted to wait until https://github.com/cri-o/cri-o/pull/3428#issuecomment-603214620 is resolved

**Pull request closed without merging**
