### PR TITLE
[1.20] Add support to drop ALL and add back few capabilities

### PR DESCRIPTION
**Pull request by haircommander**
The current implemention has an issue where we add the default
capabilties when the user does drop ALL and add few.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Fix drop ALL and add back few caps behavior to not include the default configured capabilities
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
1.20 is EOL

**Comment by saschagrunert** [comment]
> 1.20 is EOL

Any reason why we reopened this?

**Comment by haircommander** [comment]
> > 1.20 is EOL
> 
> Can we close it again?

no someone needs it downstream :disappointed:

**Review by saschagrunert — APPROVED** [review]
CI seems broken, rest in peace.

**Pull request merged**
