### PR TITLE
server: don't set memory swap when it's not enabled

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where memory swap values were specified even if the memory swap cgroup is not enabled
```

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by fgiudici — APPROVED** [review]

**Pull request merged**
