### PR TITLE
Use new containerd/release-tool path

### PR DESCRIPTION
**Pull request by saschagrunert**
The release tool is now part of its own project in
github.com/containerd/release-tool, which we should use instead of the
old path.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by saschagrunert** [comment]
Rebased on top of the latest master to get the CI fixes in.

**Comment by TomSweeneyRedHat** [comment]
Happy green test buttons on this one.

**Pull request merged**
