### PR TITLE
Fix static build DNS resolving with netgo

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This should prevent the net package to link against the host resolver.
#### Which issue(s) this PR fixes:
Fixes https://github.com/cri-o/cri-o/issues/3612

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
- Fixed glibc static binary bug to not resolve DNS correctly
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@lbogdan can you pelpleasese test if the binary provided in the bundle works for you:
https://storage.googleapis.com/k8s-conform-cri-o/artifacts/crio-f7896341f.tar.gz

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons

**Comment by lbogdan** [comment]
@saschagrunert I can confirm the static `crio` binary from https://storage.googleapis.com/k8s-conform-cri-o/artifacts/crio-f7896341f.tar.gz works out of the box in Ubuntu 18.04.

**Comment by lbogdan** [comment]
Also, now this is fixed, can you please cut a new official 1.18.0-rc2 release?

**Comment by saschagrunert** [comment]
@haircommander do we want to cut a rc2 or go for the final version in some time?

**Pull request merged**
