### PR TITLE
main.go: flag help message error fix

### PR DESCRIPTION
**Pull request by ethan-daocloud**
Signed-off-by: ethan <guangming.wang@daocloud.io>

**- What I did**
just fix message misspell error.

**- How I did it**

**- How to verify it**
dictionary know.

**- Description for the changelog**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
Thanks @ethan-daocloud !

**Comment by haircommander** [comment]
change LGTM. the test failures are well known flakes. I think we should force merge this, it definitely will not bother e2e* tests when they're fixed. WDYT @rhatdan @saschagrunert @umohnani8 @mrunalp

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
