### PR TITLE
Update kubeadm init instructions

### LINKED ISSUE #5862: Error when following "Running CRI-O with kubeadm" guide
### What happened?

I tried following the steps in the [Running CRI-O with kubeadm](https://github.com/cri-o/cri-o/blob/main/tutorials/kubeadm.md) guide, but the `kubeadm init --pod-network-cidr=$CIDR --config=$KUBEADM_CONFIG` resulted in an error.

```
# kubeadm init --pod-network-cidr=$CIDR --config=$KUBEADM_CONFIG --v=5
can not mix '--config' with arguments [pod-network-cidr]
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation.ValidateMixedArguments
	cmd/kubeadm/app/apis/kubeadm/validation/validation.go:552
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newInitData
	cmd/kubeadm/app/cmd/init.go:334
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func3
	cmd/kubeadm/app/cmd/init.go:197
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).InitData
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:183
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	cmd/kubeadm/app/cmd/init.go:145
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
	cmd/kubeadm/app/kubeadm.go:50
main.main
	cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1571

```

### What did you expect to happen?

`kubeadm` to create a single-node cluster using the CRI-O runtime.

### How can we reproduce it (as minimally and precisely as possible)?

Follow the steps in the [Running CRI-O with kubeadm](https://github.com/cri-o/cri-o/blob/main/tutorials/kubeadm.md) guide.

### Anything else we need to know?

I was able to create the cluster by running `kubeadm init --pod-network-cidr=$CIDR`, i.e. without the `--config` flag.

I'm assuming this is more an issue with `kubeadm`, but if that's the case the doc may need an update to the proper command.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.24.0
Version:          1.24.0
GitCommit:        0ba47c9b3e52eee95d898be84500c38c9fe032c9
GitTreeState:     dirty
BuildDate:        1980-01-01T00:00:00Z
GoVersion:        go1.18.1
Compiler:         gc
Platform:         linux/amd64
Linkmode:         static
BuildTags:        apparmor, exclude_graphdriver_devicemapper, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  true

```

```console
$ kubectl --version
ARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux paul 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Using a VM running via KVM
</details>

### PR DESCRIPTION
**Pull request by psschwei**
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Newer versions of `kubeadm` do not allow passing both the `pod-network-cidr` and `config` flags. This PR updates the install instructions to pass the crio socket via the `cri-socket` flag rather than in a config file.

#### Which issue(s) this PR fixes:

Fixes #5862 

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM :)

**Comment by psschwei** [comment]
This was just a docs change, so assuming the test failures are unrelated...
/retest

**Comment by haircommander** [comment]
much easier! thank you @psschwei 

/lgtm

**Pull request merged**
