### PR TITLE
test: bump log level

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
to debug this odd fedora issue where nodes fail to come up
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by haircommander** [comment]
[we caught one](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/3882/test_pull_request_crio_e2e_features_fedora/11382/)

**Comment by TomSweeneyRedHat** [comment]
LGTM, but not so much to lint apparently.

**Comment by umohnani8** [comment]
I was trying to get the e2e_features_fedora to fail so I can poke around a preserved instance, but it has been passing since :facepalm:

**Comment by haircommander** [comment]
> I was trying to get the e2e_features_fedora to fail so I can poke around a preserved instance, but it has been passing since facepalm

huzzah it's magically fixed :star_struck:

**Comment by umohnani8** [comment]
@haircommander we can close this right? The e2e issue is fixed by https://github.com/cri-o/cri-o/pull/3900

**Comment by haircommander** [comment]
yeah, I think so

**Pull request closed without merging**
