### PR TITLE
Add particule as adopters

### PR DESCRIPTION
**Pull request by ArchiFleKs**
#### What type of PR is this?

Just adding a company to adopters list

```release-note
Add Particule as adopters
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

Thank you @ArchiFleKs! :pray:

**Comment by haircommander** [comment]
yay! Thanks for this PR, I'm glad y'all are using CRI-O @ArchiFleKs

**Comment by TomSweeneyRedHat** [comment]
LGTM
thanks for the update!

**Pull request merged**
