### PR TITLE
Update awesome.md

### PR DESCRIPTION
**Pull request by rgherta**
#### What type of PR is this?

documentation

#### What this PR does / why we need it:

Updates the articles list

#### Which issue(s) this PR fixes:

Documents cri-o on fedora 39 with usernamespaces and selinux enabled

#### Special notes for your reviewer:

Feel free to review, edit and adapt

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by kwilczynski** [comment]
@rgherta, thank you for this fantastic article! Much appreciated.

**Comment by sohankunkerkar** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
