### PR TITLE
Switch to latest bats master

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
This should contain the fix for the parallel output issue we had in the
past.
#### Which issue(s) this PR fixes:

Refers to https://github.com/bats-core/bats-core/issues/290#event-3284364579
#### Special notes for your reviewer:
I first have to push the new test images, give me a couple of minutes.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
It does not seem to solve the issue: https://app.circleci.com/pipelines/github/openSUSE/cri-o/2717/workflows/43e23b44-425a-4522-82a2-f7bd22dd6a3e/jobs/45507/steps

**Comment by haircommander** [comment]
weird, ssh'ing into the box, and building the update from GH worked for me :confused:

**Comment by saschagrunert** [comment]
Closing since right now everything seems to work...

**Pull request closed without merging**
