### PR TITLE
Make storage unmount less strict

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
There are cases where the container storage unmount has been already (partially) done. This would cause `StopContainer()`  in `server/container_stop.go:76` fail and therefore make containers get stuck in recreation, making their pods stuck in `NotReady`.

We now double check the two c/stroage errors `ErrContainerUnknown` and `ErrLayerUnknown`

Somehow related to: https://github.com/containers/podman/issues/11207#issuecomment-920768804

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@haircommander PTAL, https://github.com/cri-o/cri-o/pull/6518 got verified via https://bugzilla.redhat.com/show_bug.cgi?id=2116461#c38

**Comment by haircommander** [comment]
/lgtm

makes sense to me!

**Comment by saschagrunert** [comment]
Prow merged the PR commit but did not close the PR, not sure what is going on here and closing manually. 

cc @haircommander

**Pull request closed without merging**
