### PR TITLE
broken link

### PR DESCRIPTION
**Pull request by lovebaby979**
#### What type of PR is this?

kind documentation

#### What this PR does / why we need it:
update wrong path to tutorials

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?
None

```release-note
update broken link to files in tutorial
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/ok-to-test
Thank you!
/lgtm

**Comment by saschagrunert** [comment]
Can you please ensure that your commit messages are signed with `git commit --amend -s --no-edit` (force push again)?

**Comment by lovebaby979** [comment]
test

**Comment by TomSweeneyRedHat** [comment]
LGTM
once signed

**Comment by umohnani8** [comment]
LGTM, but commit needs to be signed

**Pull request closed without merging**
