### PR TITLE
Fix test scope for e2e features

### PR DESCRIPTION
**Pull request by saschagrunert**
The current features e2e test does not do anything at all, which should be fixed with this PR.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Tada, the 26 selected tests are passing:
- https://prow.svc.ci.openshift.org/view/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/2977/test_pull_request_crio_e2e_features_fedora/6041/
- https://prow.svc.ci.openshift.org/view/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/2977/test_pull_request_crio_e2e_features_rhel/6101/

**Comment by umohnani8** [comment]
Nice!
/lgtm

**Pull request merged**
