### PR TITLE
[WIP] run the tests using the crun runtime

### PR DESCRIPTION
**Pull request by giuseppe**
this is just a test to see how crun performs with the Kubernetes e2e tests

### CODE REVIEW

**Comment by mrunalp** [comment]
Pretty awesome. It passes all the tests :)

**Comment by giuseppe** [comment]
how to enable crun also for e2e?

**Comment by giuseppe** [comment]
@runcom, just to make it sure, is contrib/test/integration/main.yml also used for e2e tests?

**Comment by giuseppe** [comment]
@mrunalp this time it is correct :-)

Please ignore RHEL for now, it is failing for a missing dependency

**Comment by rhatdan** [comment]
@giuseppe Still working on this?

**Comment by giuseppe** [comment]
> @giuseppe Still working on this?

I've used this PR only to test crun and let it pass the Kubernetes e2e tests.  I am going to close it now as I am not working on it right now.

@mrunalp there is a crun version for Fedora now.  Is it worth/useful to add a test for it?

**Pull request closed without merging**
