### PR TITLE
version: bump version (and cri-tools) to 1.27.0

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind documentation
/kind dependency-change
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by adrianreber** [comment]
> @adrianreber do you expect
> 
> ```
>       <string>: failed to read "spec.dump": open /tmp/checkpoint2354776543/spec.dump: no such file or directory
>   to contain substring
> ```
> 
> in [this](https://github.com/cri-o/cri-o/actions/runs/4729671163/jobs/8392441626?pr=6822) run? it doesn't look like a flake

No, it doesn't look like a flake. One error message just differs concerning quotes and the other failure is also only about a different error message. Let me rerun it locally to see if I can reproduce it.

**Comment by adrianreber** [comment]
> @adrianreber do you expect
> 
> ```
>       <string>: failed to read "spec.dump": open /tmp/checkpoint2354776543/spec.dump: no such file or directory
>   to contain substring
> ```
> 
> in [this](https://github.com/cri-o/cri-o/actions/runs/4729671163/jobs/8392441626?pr=6822) run? it doesn't look like a flake

I also see it locally. Strange. Anyway, I can provide a quick patch that can be included in this PR.

**Comment by haircommander** [comment]
/hold
for that patch

**Comment by adrianreber** [comment]
```patch
commit 1e49fdedcba6bd0a55f725eb9bf1482c2cb4ebd3 (HEAD -> main)
Author: Adrian Reber <areber@redhat.com>
Date:   Tue Apr 18 07:43:44 2023 +0000

    Fix restore tests
    
    Some restore tests were failing because the output of the expected error
    messages changed. The underlying checkpointctl go library didn't
    actually break API, but the error messages changed when going from
    unversioned to 0.1.0.
    
    Signed-off-by: Adrian Reber <areber@redhat.com>

diff --git a/server/container_restore_test.go b/server/container_restore_test.go
index 76d5e6792..a53b03547 100644
--- a/server/container_restore_test.go
+++ b/server/container_restore_test.go
@@ -94,7 +94,7 @@ var _ = t.Describe("ContainerRestore", func() {
                                "",
                        )
                        // Then
-                       Expect(err.Error()).To(ContainSubstring(`failed to read "spec.dump": failed to read`))
+                       Expect(err.Error()).To(ContainSubstring(`failed to read "spec.dump": `))
                })
        })
        t.Describe("ContainerRestore from archive into new pod", func() {
@@ -571,7 +571,7 @@ var _ = t.Describe("ContainerRestore", func() {
                        )
 
                        // Then
-                       Expect(err.Error()).To(ContainSubstring(`failed to read spec.dump: open spec.dump: no such file or directory`))
+                       Expect(err.Error()).To(ContainSubstring(`failed to read "spec.dump": open spec.dump: no such file or directory`))
                })
        })
 })
```

**Comment by adrianreber** [comment]
Please include that patch.

**Comment by haircommander** [comment]
:upside_down_face: 

```
Error: verifying blob [cri-o.amd64.120c549c6a7442d81d466e3855f7dbcc2f9a96ca.tar.gz]: expected GitHub Workflow Ref not found in certificate
```
@saschagrunert [your turn!](https://github.com/cri-o/cri-o/actions/runs/4729945907/jobs/8393035134?pr=6822) :sweat_smile:

**Comment by adrianreber** [comment]
There is also still an error around the restore unit test.

**Comment by adrianreber** [comment]
> There is also still an error around the restore unit test.

Ah, @haircommander, you changed the patch while applying it. This was confusing. For the second hunk you put the quotes around the wrong `spec.dump`. The first one comes from `%q` and probably therefore needs the quotes. The second time the file name appears is directly from `os.ReadFile()`.

**Comment by haircommander** [comment]
> > There is also still an error around the restore unit test.
> 
> Ah, @haircommander, you changed the patch while applying it. This was confusing. For the second hunk you put the quotes around the wrong `spec.dump`. The first one comes from `%q` and probably therefore needs the quotes. The second time the file name appears is directly from `os.ReadFile()`.


yeah sorry it didn't apply so I appied it manually

**Review by saschagrunert — APPROVED** [review]

**Comment by haircommander** [comment]
/unhold

we're going to go without the get script verification working. we can fix after we release if needed.

**Pull request merged**
