### PR TITLE
[1.15] e2e: clean kubernetes before making

### PR DESCRIPTION
**Pull request by haircommander**
to fix problem in update to etcd

as well as carry https://github.com/cri-o/cri-o/pull/2771 to fix grpc in kubelet

Signed-off-by: Peter Hunt <pehunt@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by haircommander** [comment]
e2e_features_rhel won't pass. plz merge this to unblock https://github.com/cri-o/cri-o/pull/2780

**Pull request merged**
