### PR TITLE
Automatically generate release notes and upload them to the bucket

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
We now automatically generate the release notes in CircleCI and upload them into our bucket.
#### Which issue(s) this PR fixes:

Needs https://github.com/cri-o/cri-o/pull/3331

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@saschagrunert Still a WIP?

**Comment by saschagrunert** [comment]
Rebased on the latest master.

**Comment by saschagrunert** [comment]
@haircommander @rhatdan @mrunalp I think we can get this in. I will follow-up with some auto-publishing when I found a web-server somewhere. Maybe hosted on packet.net...

**Comment by haircommander** [comment]
LGTM

**Pull request merged**
